## BertMorphTagger

#### Prerequisites

Import modules

To use `BertMorphTagger`, you need to import BertMorphTagger from [`bert_morph_tagger.py`](https://github.com/estnltk/estnltk-model-training/blob/main/morph_tagging/bert_morph_tagger.py).

In [24]:
import estnltk
from bert_morph_tagger import BertMorphTagger

#### Using BertMorphTagger

To initialize BertMorphTagger, call `BertMorphTagger` with preferred parameter values.

Important parameters are:
* `get_top_n_predictions`: Predict $n$ morphological tags for each word. Defaults to **1**;
* `token_level`: If True outputs morphological tags for each BERT token, otherwise for each word in EstNLTK's `words` layer. Defaults to **False**;
* `split_pos_form`: If True splits the predicted label into Vabamorf's tags `form` and `partofspeech`, otherwise outputs the label itself, which is a concatenation of previous Vabamorf's tags joined with `_`. Defaults to **True**

In [25]:
# morph_tagger = BertMorphTagger(get_top_n_predictions=1, token_level=False, split_pos_form=True) # With defined parameters
morph_tagger = BertMorphTagger() # Without defined parameters

Fetching 11 files: 100%|██████████| 11/11 [00:21<00:00,  1.94s/it]

`BertMorphTagger` relies on EstNLTK's `sentences` and `words` layer. Without them, tagger will not work.

In [26]:
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
# text_obj.tag_layer('sentences') # Without sentences and words layers
try:
    morph_tagger.tag(text_obj)
except ValueError as e:
    print(f"ValueError: {e}")

ValueError: missing input layer: 'sentences'

In [27]:
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layers
morph_tagger.tag(text_obj)

Text(text='A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija.')

Accessing `bert_morph_tagging` layer.

In [28]:
text_obj['bert_morph_tagging']

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('A. H. Tammsaare', [{'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'form': 'sg n', 'partofspeech': 'H', 'probability': 0.99541}]),
Span('oli', [{'bert_tokens': ['▁oli'], 'form': 's', 'partofspeech': 'V', 'probability': 0.99992}]),
Span('eesti', [{'bert_tokens': ['▁eesti'], 'form': '', 'partofspeech': 'G', 'probability': 0.99577}]),
Span('kirjanik', [{'bert_tokens': ['▁kirjanik'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9997}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}]),
Span('esseist', [{'bert_tokens': ['▁es', 'se', 'ist'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99956}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}]),
Span('kultuurifilosoof', [{'bert_tokens': ['▁kultuuri', 'filosoof'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99963}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'J', 'probability': 0.99988}]),
Span('tõlkija', [{'bert_tokens': ['▁tõlkija'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99926}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}])])

BertMorphTagger generates four tags:
* `bert_tokens`: List of BERT tokens that are in one Vabamorf's word;
* `form`: Noun or verb form;
* `partofspeech`: Word's part of speech;
* `probability`: BertMorphTagger's model prediction probability.

Below is an example of one Vabamorf's word and its related BertMorphTagger's tokens.

In [29]:
print(f"""Vabamorf's word: {text_obj['words'][0].text}
BertMorphTagger's tokens: {text_obj['bert_morph_tagging'][0]['bert_tokens'][0]}""")

Vabamorf's word: A. H. Tammsaare
BertMorphTagger's tokens: ['▁A', '.', '▁H', '.', '▁Tammsaare']

Changing `get_top_n_predictions` parameter to 2.

In [30]:
morph_tagger = BertMorphTagger(get_top_n_predictions=2)
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)
text_obj['bert_morph_tagging']

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('A. H. Tammsaare', [{'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'form': 'sg n', 'partofspeech': 'H', 'probability': 0.99541}, {'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.00244}]),
Span('oli', [{'bert_tokens': ['▁oli'], 'form': 's', 'partofspeech': 'V', 'probability': 0.99992}, {'bert_tokens': ['▁oli'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.0}]),
Span('eesti', [{'bert_tokens': ['▁eesti'], 'form': '', 'partofspeech': 'G', 'probability': 0.99577}, {'bert_tokens': ['▁eesti'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.00042}]),
Span('kirjanik', [{'bert_tokens': ['▁kirjanik'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9997}, {'bert_tokens': ['▁kirjanik'], 'form': 'sg n', 'partofspeech': 'A', 'probability': 3e-05}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}, {'bert_tokens': [','], 'form': '', 'partofspeech': 'J', 'probability': 1e-05}]),
Span('esseist', [{'bert_tokens': ['▁es', 'se', 'ist'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99956}, {'bert_tokens': ['▁es', 'se', 'ist'], 'form': 'sg n', 'partofspeech': 'A', 'probability': 9e-05}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}, {'bert_tokens': [','], 'form': '', 'partofspeech': 'J', 'probability': 0.0}]),
Span('kultuurifilosoof', [{'bert_tokens': ['▁kultuuri', 'filosoof'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99963}, {'bert_tokens': ['▁kultuuri', 'filosoof'], 'form': 'sg n', 'partofspeech': 'A', 'probability': 5e-05}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'J', 'probability': 0.99988}, {'bert_tokens': ['▁ja'], 'form': '', 'partofspeech': 'Z', 'probability': 1e-05}]),
Span('tõlkija', [{'bert_tokens': ['▁tõlkija'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99926}, {'bert_tokens': ['▁tõlkija'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.00013}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}, {'bert_tokens': ['.'], 'form': '', 'partofspeech': 'J', 'probability': 0.0}])])

Changing `token_level` parameter **True**.

In [31]:
morph_tagger = BertMorphTagger(token_level=True)
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)
text_obj['bert_morph_tagging']

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('A', [{'bert_tokens': '▁A', 'form': 'sg n', 'partofspeech': 'H', 'probability': 0.99541}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Z', 'probability': 0.99949}]),
Span(' H', [{'bert_tokens': '▁H', 'form': 'sg n', 'partofspeech': 'H', 'probability': 0.99685}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Z', 'probability': 0.99929}]),
Span(' Tammsaare', [{'bert_tokens': '▁Tammsaare', 'form': 'sg n', 'partofspeech': 'H', 'probability': 0.99937}]),
Span(' oli', [{'bert_tokens': '▁oli', 'form': 's', 'partofspeech': 'V', 'probability': 0.99992}]),
Span(' eesti', [{'bert_tokens': '▁eesti', 'form': '', 'partofspeech': 'G', 'probability': 0.99577}]),
Span(' kirjanik', [{'bert_tokens': '▁kirjanik', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9997}]),
Span(',', [{'bert_tokens': ',', 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}]),
Span(' es', [{'bert_tokens': '▁es', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99956}]),
Span('se', [{'bert_tokens': 'se', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99957}]),
Span('ist', [{'bert_tokens': 'ist', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99956}]),
Span(',', [{'bert_tokens': ',', 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}]),
Span(' kultuuri', [{'bert_tokens': '▁kultuuri', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99963}]),
Span('filosoof', [{'bert_tokens': 'filosoof', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99969}]),
Span(' ja', [{'bert_tokens': '▁ja', 'form': '', 'partofspeech': 'J', 'probability': 0.99988}]),
Span(' tõlkija', [{'bert_tokens': '▁tõlkija', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99926}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Z', 'probability': 0.99995}])])

Changing `split_pos_form` parameter **False**.

In [32]:
morph_tagger = BertMorphTagger(split_pos_form=False)
input_str = "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija."
text_obj = estnltk.Text(input_str)
text_obj.tag_layer('sentences') # With sentences and words layer
morph_tagger.tag(text_obj)
text_obj['bert_morph_tagging']

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'morph_label', 'probability'), spans=SL[Span('A. H. Tammsaare', [{'bert_tokens': ['▁A', '.', '▁H', '.', '▁Tammsaare'], 'morph_label': 'sg n_H', 'probability': 0.99541}]),
Span('oli', [{'bert_tokens': ['▁oli'], 'morph_label': 's_V', 'probability': 0.99992}]),
Span('eesti', [{'bert_tokens': ['▁eesti'], 'morph_label': 'G', 'probability': 0.99577}]),
Span('kirjanik', [{'bert_tokens': ['▁kirjanik'], 'morph_label': 'sg n_S', 'probability': 0.9997}]),
Span(',', [{'bert_tokens': [','], 'morph_label': 'Z', 'probability': 0.99995}]),
Span('esseist', [{'bert_tokens': ['▁es', 'se', 'ist'], 'morph_label': 'sg n_S', 'probability': 0.99956}]),
Span(',', [{'bert_tokens': [','], 'morph_label': 'Z', 'probability': 0.99995}]),
Span('kultuurifilosoof', [{'bert_tokens': ['▁kultuuri', 'filosoof'], 'morph_label': 'sg n_S', 'probability': 0.99963}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'morph_label': 'J', 'probability': 0.99988}]),
Span('tõlkija', [{'bert_tokens': ['▁tõlkija'], 'morph_label': 'sg n_S', 'probability': 0.99926}]),
Span('.', [{'bert_tokens': ['.'], 'morph_label': 'Z', 'probability': 0.99995}])])

As you can see above, tags `form` and `partofspeech` are concatenated into one tag `morph_label`.