In [1]:
print("Test")

Test

In [2]:
# Imports
import sys
import pathlib

# Add the project's root directory to the Python path
sys.path.append(pathlib.Path("../").resolve().as_posix())

# Configurations
seed = 42

# Paths
DATA_DIR = pathlib.Path("../data/")
ENC2017_ROOT = DATA_DIR / "enc2017"
UD_ET_EDT_ROOT = DATA_DIR / "ud_et_edt"
HOMONYMS_ROOT = DATA_DIR / "homonymous_word_forms"

ENC2017_DIRS = {
    "processed": ENC2017_ROOT / "processed",
    "raw": ENC2017_ROOT / "raw",
}

UD_ET_EDT_DIRS = {
    "processed": UD_ET_EDT_ROOT / "processed",
    "raw": UD_ET_EDT_ROOT / "raw",
}

HOMONYMS_DIRS = {
    "processed": HOMONYMS_ROOT / "processed",
    "annotations": HOMONYMS_ROOT / "annotations",
}

OUTPUT_DIR = pathlib.Path("../outputs/")

MODEL_DIR = pathlib.Path("../models/")

In [3]:
import os
import random
import time
import ast
import json
import tqdm
import pandas as pd
import numpy as np
import estnltk
from estnltk.default_resolver import make_resolver
from estnltk.taggers import VabamorfAnalyzer

import pandas as pd
from dotenv import load_dotenv
from google import genai
from google.genai import types

from typing import Any

import torch
from transformers import AutoModelForMaskedLM, AutoTokenizer, pipeline

from datasets import Dataset
from transformers.pipelines.pt_utils import KeyDataset

e:\Git_projects\EstNLTK\simpletransformers\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
from scripts.notebooks.NotebookFunctions import display_examples

In [5]:
"""
Google Gen AI setup for Estonian marked-word rewriting.

This cell configures the Gen AI client, reads the API key from the environment,
and prepares the model call for JSON output.
"""

load_dotenv(".env", verbose=True)

api_key = os.getenv("GOOGLE_API_KEY")
model = "gemini-3.1-flash-lite-preview"
client = genai.Client(api_key=api_key)

print(f"Using model: {model}")

Using model: gemini-3.1-flash-lite-preview

In [63]:
bert_mlm_candidates_filepath = (
    HOMONYMS_DIRS["processed"] / "homonyms_bert_mlm_candidate_details_100.jsonl"
)
with open(bert_mlm_candidates_filepath, "r", encoding="utf-8") as f:
    bert_mlm_candidates_data = [json.loads(line) for line in f]

bert_mlm_candidates_df = pd.DataFrame(bert_mlm_candidates_data)
display(bert_mlm_candidates_df.head(1))

llm_homonyms_predictions_filepath = (
    HOMONYMS_DIRS["processed"] / "homonyms_llm_mlm_predictions_v3_200.parquet"
)
llm_homonyms_predictions_df = pd.read_parquet(llm_homonyms_predictions_filepath)
display(llm_homonyms_predictions_df.head(1))

   row_index  inflection_type  \
0          0                1

                                                                                                                                                                                                              sentence  \
0  Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.

     word word_span true_label predicted_best_label  \
0  võitja  [74, 80]       sg n                 sg n

   predicted_best_label_score  \
0                     0.72215

                                                                                                                                                                                                                                      predicted_top_labels  \
0  [{'label': 'sg n', 'score': 0.7221502446191154}, {'label': 'sg g', 'score': 0.18655089150706772}, {'label': 'pl n', 'score': 0.031669486401369795}, {'label': 'nud', 'score': 0.03149387186567765}, {'label': 'sg tr', 'score': 0.0014702172484248877}]

                                                                                                                                                                                                    label_scores  \
0  {'sg n': 0.7221502446191154, 'sg g': 0.18655089150706772, 'nud': 0.03149387186567765, 'pl n': 0.031669486401369795, 'sg tr': 0.0014702172484248877, 'o': 0.00035745027707889676, 's': 0.00035488014691509306}


,id,candidates,pred_label,true_label,predicted_form_distribution,source_sentence,target_word,word_span
0,630,"[ilmselge, arusaadav, loomulik, mõistetav, aktsepteeritav, kindel, tõestatud, ilmne, uskumatu, tunduv]",sg n,sg n,"{'': 0.025, '?': None, 'adt': None, 'nud': None, 'pl ab': None, 'pl all': None, 'pl el': None, 'pl g': None, 'pl ill': None, 'pl in': None, 'pl kom': None, 'pl n': 0.025, 'pl p': None, 's': None, 'sg all': None, 'sg el': None, 'sg g': None, 'sg ill': None, 'sg in': None, 'sg kom': None, 'sg n': 0.9249999999999999, 'sg p': None, 'sg ter': None, 'sg tr': None, 'tud': 0.025}","Aga samas on ju täiesti selge, et kool peab olema koht, kus turvatunne oleks tagatud kõigile, nii õpilastele kui õpetajatele.",selge,"[24, 29]"

In [64]:
print("Keys in 'candidate_details' of the first row:")
print(bert_mlm_candidates_df["candidate_details"].iloc[0][0].keys())

# Extract tokens from candidate_details and replace the original column with a new one containing new details in a more structured format.
for index, row in bert_mlm_candidates_df.iterrows():
    candidate_details = row["candidate_details"]
    structured_details = []
    for candidate in candidate_details:
        structured_details.append(
            {
                "token": candidate["token"],
                "score": candidate["score"],
                "resolved_form": candidate["resolved_forms"],
            }
        )
    bert_mlm_candidates_df.at[index, "candidate_details"] = structured_details

# Rename columns for clarity
bert_mlm_candidates_df.rename(columns={"row_index": "index"}, inplace=True)

Keys in 'candidate_details' of the first row:
dict_keys(['rank', 'token', 'score', 'sequence', 'candidate_sentence', 'candidate_span', 'resolved_forms'])

In [65]:
display(bert_mlm_candidates_df.head(1))

   index  inflection_type  \
0      0                1

                                                                                                                                                                                                              sentence  \
0  Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.

     word word_span true_label predicted_best_label  \
0  võitja  [74, 80]       sg n                 sg n

   predicted_best_label_score  \
0                     0.72215

                                                                                                                                                                                                                                      predicted_top_labels  \
0  [{'label': 'sg n', 'score': 0.7221502446191154}, {'label': 'sg g', 'score': 0.18655089150706772}, {'label': 'pl n', 'score': 0.031669486401369795}, {'label': 'nud', 'score': 0.03149387186567765}, {'label': 'sg tr', 'score': 0.0014702172484248877}]

                                                                                                                                                                                                    label_scores  \
0  {'sg n': 0.7221502446191154, 'sg g': 0.18655089150706772, 'nud': 0.03149387186567765, 'pl n': 0.031669486401369795, 'sg tr': 0.0014702172484248877, 'o': 0.00035745027707889676, 's': 0.00035488014691509306}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             candidate_details  \
0  [{'token': 'võitja', 'score': 0.6679869294166565, 'resolved_form': ['sg n']}, {'token': 'omaniku', 'score': 0.05648179352283478, 'resolved_form': ['sg g']}, {'token': 'auhinna', 'score': 0.05616520345211029, 'resolved_form': ['sg g']}, {'token': 'võitnud', 'score': 0.05125705897808075, 'resolved_form': ['nud', 'pl n', 'sg n']}, {'token': 'saanud', 'score': 0.02686145156621933, 'resolved_form': ['nud', 'pl n', 'sg n']}, {'token': 'kandidaadi', 'score': 0.022922614589333534, 'resolved_form': ['sg g']}, {'token': 'pälvinud', 'score': 0.015388736501336098, 'resolved_form': ['nud', 'pl n', 'sg n']}, {'token': 'asutaja', 'score': 0.009527058340609074, 'resolved_form': ['sg n']}, {'token': 'saaja', 'score': 0.006725015118718147, 'resolved_form': ['sg g']}, {'token': 'autori', 'score': 0.0039146277122199535, 'resolved_form': ['sg g']}, {'token': 'parima', 'score': 0.003787625813856721, 'resolved_form': ['sg g']}, {'token': 'liikme', 'score': 0.0036989012733101845, 'resolved_form': ['sg g']}, {'token': 'preemia', 'score': 0.003675566054880619, 'resolved_form': ['sg g']}, {'token': 'presidendi', 'score': 0.002232660772278905, 'resolved_form': ['sg g']}, {'token': 'ja', 'score': 0.0022204129491001368, 'resolved_form': []}, {'token': 'laure', 'score': 0.002179876435548067, 'resolved_form': ['sg g']}, {'token': 'näitleja', 'score': 0.002168209757655859, 'resolved_form': ['sg g']}, {'token': 'isa', 'score': 0.0020003803074359894, 'resolved_form': ['sg n']}, {'token': 'meistri', 'score': 0.0017460546223446727, 'resolved_form': ['sg g']}, {'token': 'mehe', 'score': 0.0016435248544439673, 'resolved_form': ['sg g']}, {'token': 'omanik', 'score': 0.0016333964886143804, 'resolved_form': ['sg n']}, {'token': 'kandidaat', 'score': 0.0014800678472965956, 'resolved_form': ['sg n']}, {'token': 'kandidaadiks', 'score': 0.0014702172484248877, 'resolved_form': ['sg tr']}, {'token': 'tähe', 'score': 0.0012897186679765582, 'resolved_form': ['sg g']}, {'token': 'kirjaniku', 'score': 0.0011800117790699005, 'resolved_form': ['sg g']}, {'token': 'härra', 'score': 0.0010734554380178452, 'resolved_form': ['sg n']}, {'token': 'looja', 'score': 0.0010602290276437998, 'resolved_form': ['sg n']}, {'token': 'ema', 'score': 0.001014739740639925, 'resolved_form': ['sg n']}, {'token': 'esindaja', 'score': 0.0009600090561434627, 'resolved_form': ['sg n']}, {'token': 'staari', 'score': 0.0008699243771843612, 'resolved_form': ['sg g']}, {'token': 'sõbra', 'score': 0.0008439786033704877, 'resolved_form': ['sg g']}, {'token': 'lavastaja', 'score': 0.0008322214707732201, 'resolved_form': ['sg n']}, {'token': 'kuninga', 'score': 0.0008287334349006414, 'resolved_form': ['sg g']}, {'token': 'mängija', 'score': 0.0008017856744118035, 'resolved_form': ['sg n']}, {'token': 'kolleegi', 'score': 0.0007466874667443335, 'resolved_form': ['sg g']}, {'token': 'isanda', 'score': 0.0006973558920435607, 'resolved_form': ['sg g']}, {'token': 'vastase', 'score': 0.0006961811450310051, 'resolved_form': ['sg g']}, {'token': 'teeninud', 'score': 0.0006834609666839242, 'resolved_form': ['nud', 'pl n', 'sg n']}, {'token': 'kapteni', 'score': 0.0006308616721071303, 'resolved_form': ['sg g']}, {'token': 'ründaja', 'score': 0.0006217407062649727, 'resolved_form': ['sg g']}, {'token': 'juhendaja', 'score': 0.0006125213694758713, 'resolved_form': ['sg n']}, {'token': 'venna', 'score': 0.0006077964208088815, 'resolved_form': ['sg g']}, {'token': 'kaitsja', 'score': 0.0005989529308862984, 'resolved_form': ['sg g']}, {'token': 'juhi', 'score': 0.0005254283896647394, 'resolved_form': ['sg g']}, {'token': 'tegija', 'score': 0.000493158120661974, 'resolved_form': ['sg g']}, {'token': 'lemmiku', 'score': 0.0004714803653769195, 'resolved_form': ['sg g']}, {'token': 'võidu', 'score': 0.00045580408186651766, 'resolved_form': ['sg g']}, {'token': 'kodaniku', 'score': 0.0004379459423944354, 'resolved_form': ['sg g']}, {'token': 'esimehe', 'score': 0.0004118243232369423, 'resolved_form': ['sg g']}, {'token': 'kunstniku', 'score': 0.0004012177814729512, 'resolved_form': ['sg g']}, {'token': 'abikaasa', 'score': 0.000398065458284691, 'resolved_form': ['sg g']}, {'token': 'liidri', 'score': 0.00037775954115204513, 'resolved_form': ['sg g']}, {'token': 'dollari', 'score': 0.00037722382694482803, 'resolved_form': ['sg g']}, {'token': 'saa', 'score': 0.00035745027707889676, 'resolved_form': ['o']}, {'token': 'nomin', 'score': 0.0003493431431706995, 'resolved_form': ['sg n']}, {'token': 'raamatu', 'score': 0.00034856339334510267, 'resolved_form': ['sg g']}, {'token': 'briti', 'score': 0.0003380945126991719, 'resolved_form': []}, {'token': 'tiitli', 'score': 0.00033233329304493964, 'resolved_form': ['sg g']}, {'token': 'naise', 'score': 0.0003143508220091462, 'resolved_form': ['sg g']}, {'token': 'laulja', 'score': 0.00029885320691391826, 'resolved_form': ['sg n']}, {'token': '-', 'score': 0.00029321739566512406, 'resolved_form': []}, {'token': 'väärt', 'score': 0.0002856887294910848, 'resolved_form': []}, {'token': 'kana', 'score': 0.00024467636831104755, 'resolved_form': ['sg g']}, {'token': 'aasta', 'score': 0.00023115883232094347, 'resolved_form': ['sg g']}, {'token': 'printsi', 'score': 0.0002310191048309207, 'resolved_form': ['sg g']}, {'token': 'sepa', 'score': 0.00022591109154745936, 'resolved_form': ['sg g']}, {'token': 'saadiku', 'score': 0.00022341952717397362, 'resolved_form': ['sg g']}, {'token': 'treeneri', 'score': 0.00021901819854974747, 'resolved_form': ['sg g']}, {'token': 'kuld', 'score': 0.00021807423036079854, 'resolved_form': ['sg n']}, {'token': 'tegelase', 'score': 0.00021500229195225984, 'resolved_form': ['sg g']}, {'token': 'professori', 'score': 0.000204405325348489, 'resolved_form': ['sg g']}, {'token': 'ajakirjaniku', 'score': 0.00020393180602695793, 'resolved_form': ['sg g']}, {'token': 'noore', 'score': 0.00019151298329234123, 'resolved_form': ['sg g']}, {'token': 'loo', 'score': 0.0001848623505793512, 'resolved_form': ['sg g']}, {'token': 'partneri', 'score': 0.00018288470164407045, 'resolved_form': ['sg g']}, {'token': 'Tony', 'score': 0.0001788577064871788, 'resolved_form': ['sg n']}, {'token': 'pälvis', 'score': 0.00017851773009169847, 'resolved_form': ['s']}, {'token': 'toetaja', 'score': 0.0001784402847988531, 'resolved_form': ['sg g']}, {'token': 'sai', 'score': 0.0001763624168233946, 'resolved_form': ['s']}, {'token': 'võitjad', 'score': 0.0001756145356921479, 'resolved_form': ['pl n']}, {'token': 'peakorraldaja', 'score': 0.00017006427515298128, 'resolved_form': ['sg n']}, {'token': 'mees', 'score': 0.00016988143033813685, 'resolved_form': ['sg n']}, {'token': 'investori', 'score': 0.00016926559328567237, 'resolved_form': ['sg g']}, {'token': 'ka', 'score': 0.00016847631195560098, 'resolved_form': []}, {'token': 'ehk', 'score': 0.00016597034118603915, 'resolved_form': []}, {'token': 'kassi', 'score': 0.00016552348097320646, 'resolved_form': ['sg g']}, {'token': 'oma', 'score': 0.00016366528871003538, 'resolved_form': ['sg g']}, {'token': 'no', 'score': 0.00015471612277906388, 'resolved_form': []}, {'token': 'taotleja', 'score': 0.0001538139913463965, 'resolved_form': ['sg g']}, {'token': 'ning', 'score': 0.000151759828440845, 'resolved_form': []}, {'token': 'konkurendi', 'score': 0.00014740241749677807, 'resolved_form': ['sg g']}, {'token': 'saavutanud', 'score': 0.00014670303789898753, 'resolved_form': ['nud', 'pl n', 'sg n']}, {'token': 'au', 'score': 0.00014521890261676162, 'resolved_form': ['sg g']}, {'token': 'enda', 'score': 0.00014509154425468296, 'resolved_form': ['sg g']}, {'token': 'võitja', 'score': 0.00014480332902166992, 'resolved_form': ['sg n']}, {'token': 'korraldaja', 'score': 0.0001445740053895861, 'resolved_form': ['sg g']}, {'token': 'kaotanud', 'score': 0.00014420454681385309, 'resolved_form': ['nud', 'pl n', 'sg n']}, {'token': 'juhataja', 'score': 0.0001437012542737648, 'resolved_form': ['sg n']}, {'token': 'päritolu', 'score': 0.00014286403893493116, 'resolved_form': ['sg g']}, {'token': 'tütre', 'score': 0.0001384569623041898, 'resolved_form': ['sg g']}]

                                                             source
0  infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json

In [66]:
display_examples(
    bert_mlm_candidates_df.iloc[9:10],
    num_examples=1,
    display_or_print="print",
    list_of_columns_to_show=[
        c for c in bert_mlm_candidates_df.columns if c != "candidate_details"
    ],
)
print("Candidate details for the example:")
for candidate in bert_mlm_candidates_df["candidate_details"].iloc[9]:
    print(candidate)

Example 1 (index 9):
  index: 9
  inflection_type: 1
  sentence: Rahvusvaheline diplomaatia hoidis ära kahe naabri vahelise sõja.
  word: diplomaatia
  word_span: [15, 26]
  true_label: sg n
  predicted_best_label: sg n
  predicted_best_label_score: 0.87688607966993
  predicted_top_labels: [{'label': 'sg n', 'score': 0.87688607966993}, {'label': 'pl n', 'score': 0.003051594365388155}, {'label': 'sg g', 'score': 0.0023830299032852054}]
  label_scores: {'sg n': 0.87688607966993, 'pl n': 0.003051594365388155, 'sg g': 0.0023830299032852054}
  source: infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json
----------------------------------------
Candidate details for the example:
{'token': 'kohus', 'score': 0.24282342195510864, 'resolved_form': ['sg n']}
{'token': 'kogukond', 'score': 0.11585666984319687, 'resolved_form': ['sg n']}
{'token': 'õigus', 'score': 0.10598563402891159, 'resolved_form': ['sg n']}
{'token': 'Kohus', 'score': 0.07946448028087616, 'resolved_form': ['sg n']}
{'token': 'rahu', 'score': 0.02973697893321514, 'resolved_form': ['sg n']}
{'token': 'õiglus', 'score': 0.02540486492216587, 'resolved_form': ['sg n']}
{'token': 'sõda', 'score': 0.02247893251478672, 'resolved_form': ['sg n']}
{'token': 'koostöö', 'score': 0.020630070939660072, 'resolved_form': ['sg n']}
{'token': 'valitsus', 'score': 0.009934665635228157, 'resolved_form': ['sg n']}
{'token': 'Rahu', 'score': 0.00925903208553791, 'resolved_form': ['sg n']}
{'token': 'abi', 'score': 0.009237299673259258, 'resolved_form': ['sg n']}
{'token': 'kriis', 'score': 0.00915871188044548, 'resolved_form': ['sg n']}
{'token': 'komisjon', 'score': 0.009113362058997154, 'resolved_form': ['sg n']}
{'token': 'kokkulepe', 'score': 0.008625988848507404, 'resolved_form': ['sg n']}
{'token': 'Olümpiakomitee', 'score': 0.008360723033547401, 'resolved_form': ['sg n']}
{'token': 'olukord', 'score': 0.00799632165580988, 'resolved_form': ['sg n']}
{'token': 'poliitika', 'score': 0.007941859774291515, 'resolved_form': ['sg n']}
{'token': 'organisatsioon', 'score': 0.007616089656949043, 'resolved_form': ['sg n']}
{'token': 'õnnetus', 'score': 0.006216485984623432, 'resolved_form': ['sg n']}
{'token': 'tegevus', 'score': 0.005645086523145437, 'resolved_form': ['sg n']}
{'token': 'julgeolek', 'score': 0.005532612558454275, 'resolved_form': ['sg n']}
{'token': 'politsei', 'score': 0.0052654133178293705, 'resolved_form': ['sg n']}
{'token': 'ja', 'score': 0.004962018225342035, 'resolved_form': []}
{'token': 'arvamus', 'score': 0.004816389176994562, 'resolved_form': ['sg n']}
{'token': 'sündmus', 'score': 0.004448497202247381, 'resolved_form': ['sg n']}
{'token': 'jõud', 'score': 0.004146798979490995, 'resolved_form': ['pl n', 'sg n']}
{'token': 'maailm', 'score': 0.0041030943393707275, 'resolved_form': ['sg n']}
{'token': 'katastroof', 'score': 0.003796609817072749, 'resolved_form': ['sg n']}
{'token': 'tava', 'score': 0.003586223814636469, 'resolved_form': ['sg n']}
{'token': 'Rist', 'score': 0.0034894715063273907, 'resolved_form': ['sg n']}
{'token': 'otsus', 'score': 0.003373144194483757, 'resolved_form': ['sg n']}
{'token': 'Sõda', 'score': 0.0032125492580235004, 'resolved_form': ['sg n']}
{'token': 'vandenõu', 'score': 0.0031428569927811623, 'resolved_form': ['sg n']}
{'token': 'tegutsemine', 'score': 0.003032289445400238, 'resolved_form': ['sg n']}
{'token': 'kuritegu', 'score': 0.0027681575156748295, 'resolved_form': ['sg n']}
{'token': 'Liit', 'score': 0.0026965858414769173, 'resolved_form': ['sg n']}
{'token': 'Politsei', 'score': 0.0026932882610708475, 'resolved_form': ['sg n']}
{'token': 'kohustus', 'score': 0.0026569166220724583, 'resolved_form': ['sg n']}
{'token': 'rikkus', 'score': 0.00263125984929502, 'resolved_form': ['sg n']}
{'token': 'Venemaa', 'score': 0.002551313955336809, 'resolved_form': ['sg n']}
{'token': 'menetlus', 'score': 0.0024073829408735037, 'resolved_form': ['sg n']}
{'token': 'konverents', 'score': 0.0023284873459488153, 'resolved_form': ['sg n']}
{'token': 'uurimine', 'score': 0.0023210446815937757, 'resolved_form': ['sg n']}
{'token': 'kohtunik', 'score': 0.002278996864333749, 'resolved_form': ['sg n']}
{'token': 'ühendus', 'score': 0.002271595411002636, 'resolved_form': ['sg n']}
{'token': 'majandus', 'score': 0.002118571661412716, 'resolved_form': ['sg n']}
{'token': 'majanduskriis', 'score': 0.0020686564967036247, 'resolved_form': ['sg n']}
{'token': 'Jõud', 'score': 0.0019563897512853146, 'resolved_form': ['pl n', 'sg n']}
{'token': 'kuritegevus', 'score': 0.0019502181094139814, 'resolved_form': ['sg n']}
{'token': 'Kriminaal', 'score': 0.0017182915471494198, 'resolved_form': ['sg n']}
{'token': 'sekkumine', 'score': 0.0016665436560288072, 'resolved_form': ['sg n']}
{'token': 'lahendus', 'score': 0.00166649604216218, 'resolved_form': ['sg n']}
{'token': 'käitumine', 'score': 0.0015784298302605748, 'resolved_form': ['sg n']}
{'token': 'konflikt', 'score': 0.001575827831402421, 'resolved_form': ['sg n']}
{'token': 'koalitsioon', 'score': 0.0015712898457422853, 'resolved_form': ['sg n']}
{'token': 'Õigus', 'score': 0.0015426701866090298, 'resolved_form': ['sg n']}
{'token': 'Föderatsioon', 'score': 0.0014008753933012486, 'resolved_form': ['sg n']}
{'token': 'Vabariik', 'score': 0.0013583371182903647, 'resolved_form': ['sg n']}
{'token': 'kindlustus', 'score': 0.0013539528008550406, 'resolved_form': ['sg n']}
{'token': 'tragöödia', 'score': 0.0013489931588992476, 'resolved_form': ['sg n']}
{'token': 'võim', 'score': 0.0013236949453130364, 'resolved_form': ['sg n']}
{'token': 'seisukord', 'score': 0.0012966300128027797, 'resolved_form': ['sg n']}
{'token': 'sõprus', 'score': 0.0012841542484238744, 'resolved_form': ['sg n']}
{'token': 'avalikkus', 'score': 0.0012769928434863687, 'resolved_form': ['sg n']}
{'token': 'vaen', 'score': 0.0012313592014834285, 'resolved_form': ['sg n']}
{'token': 'Komisjon', 'score': 0.0011638434370979667, 'resolved_form': ['sg n']}
{'token': 'huvi', 'score': 0.0011576665565371513, 'resolved_form': ['sg n']}
{'token': 'kohtumine', 'score': 0.001141972839832306, 'resolved_form': ['sg n']}
{'token': 'revolutsioon', 'score': 0.001109353150241077, 'resolved_form': ['sg n']}
{'token': 'riik', 'score': 0.0010685540037229657, 'resolved_form': ['sg n']}
{'token': 'Maailm', 'score': 0.0010591479949653149, 'resolved_form': ['sg n']}
{'token': 'kaubandus', 'score': 0.0010217773960903287, 'resolved_form': ['sg n']}
{'token': 'seisukoht', 'score': 0.001002554432488978, 'resolved_form': ['sg n']}
{'token': 'toetus', 'score': 0.000984745449386537, 'resolved_form': ['sg n']}
{'token': 'kord', 'score': 0.0009746530558913946, 'resolved_form': ['sg n']}
{'token': 'vastutus', 'score': 0.0009645987884141505, 'resolved_form': ['sg n']}
{'token': 'kokkuleppe', 'score': 0.0009372530039399862, 'resolved_form': ['sg g']}
{'token': 'turvalisus', 'score': 0.0009193615987896919, 'resolved_form': ['sg n']}
{'token': 'ajalugu', 'score': 0.0009114053100347519, 'resolved_form': ['sg n']}
{'token': 'missioon', 'score': 0.0009056340786628425, 'resolved_form': ['sg n']}
{'token': 'protsess', 'score': 0.000904892454855144, 'resolved_form': ['sg n']}
{'token': 'juhtum', 'score': 0.0008737824973650277, 'resolved_form': ['sg n']}
{'token': 'seadus', 'score': 0.0008660274324938655, 'resolved_form': ['sg n']}
{'token': 'asi', 'score': 0.0008539060945622623, 'resolved_form': ['sg n']}
{'token': 'pääste', 'score': 0.0008372415322810411, 'resolved_form': ['sg n']}
{'token': 'skandaal', 'score': 0.0008338406914845109, 'resolved_form': ['sg n']}
{'token': 'kaitse', 'score': 0.0008214472327381372, 'resolved_form': ['sg n']}
{'token': 'leping', 'score': 0.0008155126706697047, 'resolved_form': ['sg n']}
{'token': 'Valitsus', 'score': 0.0008062776760198176, 'resolved_form': ['sg n']}
{'token': 'liit', 'score': 0.0007711206562817097, 'resolved_form': ['sg n']}
{'token': 'õiguse', 'score': 0.0007399469031952322, 'resolved_form': ['sg g']}
{'token': 'Pank', 'score': 0.0007386960787698627, 'resolved_form': ['sg n']}
{'token': 'elu', 'score': 0.0007154282066039741, 'resolved_form': ['sg n']}
{'token': 'inimene', 'score': 0.0007102615782059729, 'resolved_form': ['sg n']}
{'token': 'tulekahju', 'score': 0.000705829996149987, 'resolved_form': ['sg g']}
{'token': 'tõde', 'score': 0.0006923364126123488, 'resolved_form': ['sg n']}
{'token': '–', 'score': 0.0006873863749206066, 'resolved_form': []}
{'token': 'operatsioon', 'score': 0.0006766919977962971, 'resolved_form': ['sg n']}
{'token': 'praktika', 'score': 0.0006601949571631849, 'resolved_form': ['sg n']}
{'token': 'maailmasõda', 'score': 0.0006487129721790552, 'resolved_form': ['sg n']}

In [82]:
# Create a new dataset of BERT MLM candidates containing only the relevant rows of LLM dataset
bert_mlm_candidates_subset_df = bert_mlm_candidates_df[
    bert_mlm_candidates_df["index"].isin(llm_homonyms_predictions_df["id"])
].reset_index(drop=True)
print(
    f"Number of rows in the BERT MLM candidates subset: {len(bert_mlm_candidates_subset_df)}"
)
print(
    f"Number of rows in the LLM homonyms predictions dataset: {len(llm_homonyms_predictions_df)}"
)
display(bert_mlm_candidates_subset_df.head(1))

Number of rows in the BERT MLM candidates subset: 200
Number of rows in the LLM homonyms predictions dataset: 200

   index  inflection_type  \
0    160                1

                                                             sentence  \
0  Harju politseiprefektuur algatas juhtunu uurimiseks kriminaalasja.

      word word_span true_label predicted_best_label  \
0  juhtunu  [33, 40]       sg g                 sg g

   predicted_best_label_score  \
0                    0.700327

                                                                                                                                                                                                                                        predicted_top_labels  \
0  [{'label': 'sg g', 'score': 0.7003272122237831}, {'label': 'pl g', 'score': 0.20161150055355392}, {'label': 'sg n', 'score': 0.02562290756031871}, {'label': 'sg in', 'score': 0.0016581377130933106}, {'label': 'pl n', 'score': 0.0006457525305449963}]

                                                                                                                                                                                                                                                                       label_scores  \
0  {'sg g': 0.7003272122237831, 'pl g': 0.20161150055355392, 'sg n': 0.02562290756031871, 'pl n': 0.0006457525305449963, 'tud': 0.0006457525305449963, 'sg in': 0.0016581377130933106, 'sg ad': 0.0006257191416807473, 'sg tr': 0.0004245820455253124, '?': 0.00036423635901883245}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             candidate_details  \
0  [{'token': 'juhtunu', 'score': 0.24518722295761108, 'resolved_form': ['sg g']}, {'token': 'asjaolude', 'score': 0.13490526378154755, 'resolved_form': ['pl g']}, {'token': 'juhtumi', 'score': 0.1036483496427536, 'resolved_form': ['sg g'], 'normalised_score': 0.6206560604136335}, {'token': 'selle', 'score': 0.09421201795339584, 'resolved_form': ['sg g']}, {'token': 'sündmuse', 'score': 0.060792475938797, 'resolved_form': ['sg g'], 'normalised_score': 0.3640310603016173}, {'token': 'kuriteo', 'score': 0.04071388021111488, 'resolved_form': ['sg g']}, {'token': 'asja', 'score': 0.03698594123125076, 'resolved_form': ['sg g']}, {'token': 'toimunu', 'score': 0.024977155029773712, 'resolved_form': ['sg n']}, {'token': 'õnnetuse', 'score': 0.017669614404439926, 'resolved_form': ['sg g']}, {'token': 'tulekahju', 'score': 0.01649288646876812, 'resolved_form': ['sg g']}, {'token': 'kuritegude', 'score': 0.015974223613739014, 'resolved_form': ['pl g']}, {'token': 'liiklusõnnetuse', 'score': 0.013116450048983097, 'resolved_form': ['sg g']}, {'token': 'sündmuste', 'score': 0.012618201784789562, 'resolved_form': ['pl g']}, {'token': 'nende', 'score': 0.0073024858720600605, 'resolved_form': ['pl g']}, {'token': 'mõrva', 'score': 0.007100264076143503, 'resolved_form': ['sg g']}, {'token': 'varguse', 'score': 0.006384691223502159, 'resolved_form': ['sg g']}, {'token': 'olukorra', 'score': 0.0059357862919569016, 'resolved_form': ['sg g']}, {'token': 'põlengu', 'score': 0.005803085397928953, 'resolved_form': ['sg g']}, {'token': 'juhtumite', 'score': 0.004808688536286354, 'resolved_form': ['pl g']}, {'token': 'röövi', 'score': 0.003571360604837537, 'resolved_form': ['sg g']}, {'token': 'asjade', 'score': 0.003569855587556958, 'resolved_form': ['pl g']}, {'token': 'süüteo', 'score': 0.003070624079555273, 'resolved_form': ['sg g']}, {'token': 'faktide', 'score': 0.0026769896503537893, 'resolved_form': ['pl g']}, {'token': 'varguste', 'score': 0.00266515975818038, 'resolved_form': ['pl g']}, {'token': 'rikkumise', 'score': 0.002173707587644458, 'resolved_form': ['sg g']}, {'token': 'avarii', 'score': 0.0021672432776540518, 'resolved_form': ['sg g']}, {'token': 'väärteo', 'score': 0.0020157741382718086, 'resolved_form': ['sg g']}, {'token': 'tegevuse', 'score': 0.001965251751244068, 'resolved_form': ['sg g']}, {'token': 'rahapesu', 'score': 0.0019554293248802423, 'resolved_form': ['sg g']}, {'token': 'antud', 'score': 0.0019372575916349888, 'resolved_form': ['pl n', 'sg n', 'tud']}, {'token': 'rikkumiste', 'score': 0.0018479886930435896, 'resolved_form': ['pl g']}, {'token': 'tõendite', 'score': 0.0017974822549149394, 'resolved_form': ['pl g']}, {'token': 'kriminaalasja', 'score': 0.0017378716729581356, 'resolved_form': ['sg g']}, {'token': 'surma', 'score': 0.0016041662311181426, 'resolved_form': ['sg g']}, {'token': 'loo', 'score': 0.0015982382465153933, 'resolved_form': ['sg g']}, {'token': 'tema', 'score': 0.0015922714956104755, 'resolved_form': ['sg g']}, {'token': 'korruptsiooni', 'score': 0.0015875347889959812, 'resolved_form': ['sg g']}, {'token': 'avalduse', 'score': 0.0014611937804147601, 'resolved_form': ['sg g']}, {'token': 'vigastuste', 'score': 0.0013305068714544177, 'resolved_form': ['pl g']}, {'token': 'pettuse', 'score': 0.001320238341577351, 'resolved_form': ['sg g']}, {'token': 'kahju', 'score': 0.0012703015236184, 'resolved_form': ['sg g']}, {'token': 'tapmise', 'score': 0.0012569144601002336, 'resolved_form': ['sg g']}, {'token': 'teo', 'score': 0.0011329705594107509, 'resolved_form': ['sg g'], 'normalised_score': 0.006784334206884973}, {'token': 'andmete', 'score': 0.0011290853144600987, 'resolved_form': ['pl g']}, {'token': 'süütegude', 'score': 0.0011086637387052178, 'resolved_form': ['pl g']}, {'token': 'fotode', 'score': 0.0010419979225844145, 'resolved_form': ['pl g']}, {'token': 'selles', 'score': 0.001021365518681705, 'resolved_form': ['sg in']}, {'token': 'altkäemaksu', 'score': 0.0009761825203895569, 'resolved_form': ['sg g']}, {'token': 'röövimise', 'score': 0.0009721653186716139, 'resolved_form': ['sg g']}, {'token': 'kadumise', 'score': 0.0009405948803760111, 'resolved_form': ['sg g']}, {'token': 'kahjude', 'score': 0.0009308422449976206, 'resolved_form': ['pl g']}, {'token': 'põhjuste', 'score': 0.0009224592940881848, 'resolved_form': ['pl g']}, {'token': 'väärtegude', 'score': 0.0009169581462629139, 'resolved_form': ['pl g']}, {'token': 'õnnetuste', 'score': 0.0008545335149392486, 'resolved_form': ['pl g']}, {'token': 'video', 'score': 0.0008305923547595739, 'resolved_form': ['sg g']}, {'token': 'tõe', 'score': 0.000773383944761008, 'resolved_form': ['sg g']}, {'token': 'asjaolu', 'score': 0.0007661793497391045, 'resolved_form': ['sg g'], 'normalised_score': 0.004587953965677042}, {'token': 'süü', 'score': 0.0007119496585801244, 'resolved_form': ['sg g']}, {'token': 'asitõendite', 'score': 0.0006706843851134181, 'resolved_form': ['pl g']}, {'token': 'sündmuskoha', 'score': 0.0006681969971396029, 'resolved_form': ['sg g']}, {'token': 'vägivalla', 'score': 0.0006649093120358884, 'resolved_form': ['sg g']}, {'token': 'fakti', 'score': 0.0006580710178241134, 'resolved_form': ['sg g'], 'normalised_score': 0.003940591112187181}, {'token': 'kuriteos', 'score': 0.0006367721944116056, 'resolved_form': ['sg in']}, {'token': 'kõigi', 'score': 0.0006354654906317592, 'resolved_form': ['pl g']}, {'token': 'dokumentide', 'score': 0.0006272127502597868, 'resolved_form': ['pl g']}, {'token': 'sel', 'score': 0.0006257191416807473, 'resolved_form': ['sg ad']}, {'token': 'materjalide', 'score': 0.0005717944004572928, 'resolved_form': ['pl g']}, {'token': 'kohapeal', 'score': 0.0005632312968373299, 'resolved_form': []}, {'token': 'asukoha', 'score': 0.0005568595370277762, 'resolved_form': ['sg g']}, {'token': 'surnu', 'score': 0.0005460555548779666, 'resolved_form': ['sg g']}, {'token': 'politsei', 'score': 0.0005341117503121495, 'resolved_form': ['sg g']}, {'token': 'katastroofi', 'score': 0.00047290624934248626, 'resolved_form': ['sg g']}, {'token': 'toimuva', 'score': 0.00044728838838636875, 'resolved_form': ['sg g']}, {'token': 'tegude', 'score': 0.0004428414686117321, 'resolved_form': ['pl g']}, {'token': 'skeemi', 'score': 0.00043934036511927843, 'resolved_form': ['sg g']}, {'token': 'minu', 'score': 0.0004275327082723379, 'resolved_form': ['sg g']}, {'token': 'võimalikuks', 'score': 0.0004245820455253124, 'resolved_form': ['sg tr']}, {'token': 'narkootikumide', 'score': 0.0004184649733360857, 'resolved_form': ['pl g']}, {'token': 'katse', 'score': 0.00040893166442401707, 'resolved_form': ['sg g']}, {'token': '</s>NOTUSED', 'score': 0.00039983936585485935, 'resolved_form': []}, {'token': 'isiku', 'score': 0.0003950737009290606, 'resolved_form': ['sg g']}, {'token': 'ka', 'score': 0.00039029112667776644, 'resolved_form': []}, {'token': 'isikute', 'score': 0.00038377256714738905, 'resolved_form': ['pl g']}, {'token': 'reisijate', 'score': 0.00037512011476792395, 'resolved_form': ['pl g']}, {'token': 'tulemuste', 'score': 0.0003681434609461576, 'resolved_form': ['pl g']}, {'token': 'tehingute', 'score': 0.0003645977994892746, 'resolved_form': ['pl g']}, {'token': 'SIA', 'score': 0.00036423635901883245, 'resolved_form': ['?']}, {'token': 'tüli', 'score': 0.0003549180692061782, 'resolved_form': ['sg g']}, {'token': 'probleemide', 'score': 0.0003520165628287941, 'resolved_form': ['pl g']}, {'token': 'info', 'score': 0.00035083567490801215, 'resolved_form': ['sg g']}, {'token': 'hiljem', 'score': 0.00035071372985839844, 'resolved_form': []}, {'token': 'siin', 'score': 0.00034678581869229674, 'resolved_form': []}, {'token': 'materjali', 'score': 0.0003426255425438285, 'resolved_form': ['sg g']}, {'token': 'väärteoasja', 'score': 0.0003384728915989399, 'resolved_form': ['sg g']}, {'token': 'eelnevalt', 'score': 0.00033558867289684713, 'resolved_form': []}, {'token': 'seal', 'score': 0.00032716343412175775, 'resolved_form': []}, {'token': 'terrorismi', 'score': 0.0003136777086183429, 'resolved_form': ['sg g']}, {'token': 'vea', 'score': 0.00031002561445347965, 'resolved_form': ['sg g']}, {'token': 'müra', 'score': 0.0003020060539711267, 'resolved_form': ['sg g']}, {'token': 'pommi', 'score': 0.000300567684462294, 'resolved_form': ['sg g']}]

                                                             source
0  infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json

### Testing on a single sentence

In [68]:
# System prompt: enforce Estonian rewriting behaviour, case conditioning, and JSON output
system_prompt = """You are an Estonian sentence rewriting assistant.
Your task is to select the best 5 candidates from a provided list of 100 BERT-generated candidate replacements for exactly one marked token in angle brackets <...>, using the full sentence context.

Follow this procedure internally:

1. Analyse the sentence context and the marked word.
2. Evaluate the 100 provided candidates only.
3. Reject candidates that do not fit the sentence grammatically or semantically.
4. Keep only candidates that are natural Estonian word forms in the correct context.
5. Rank the surviving candidates by suitability for the sentence.

Rules:
- Use only the provided BERT candidates. Do not invent new candidates.
- Preserve tense, number, case, agreement, punctuation, and capitalisation.
- The chosen candidates must fit the sentence context naturally and grammatically.
- The chosen candidates must be in one of the allowed morphological cases only: nominative, genitive, partitive, or illative.
- Prefer candidates whose morphological form best matches the masked word’s role in the sentence.
- If the marked token is a proper name, keep only proper-name candidates that fit the same grammatical context.
- If fewer than 5 valid candidates exist, return as many valid candidates as possible.
- Order the returned candidates from best to worst.
- Do not repeat the original marked word unless it is the only valid option.
- Return strict JSON only. Do not add explanations, markdown, or extra text.

JSON schema:
{
  "id": string,
  "candidates": array of 5 strings
}
"""

# Few-shot example to anchor the output format
few_shot_user = """Sentence ID: 2
Sentence: "Ehk oleks mõttekas ka mõni selleteemaline hoiatav <kampaania> korraldada," lisab punase autoga preili.
Candidates: ['aktsioon', 'üritus', 'kampaania', 'sündmus', 'saade', 'koosolek', 'kõne', 'päev', 'postitus', 'artikkel', 'video', 'näitus', 'asi', 'lugu', 'teade', 'lugemine', 'leht', 'liiklus', 'hoiatus', 'uudis', 'post', 'teavitus', 'loeng', 'komm', 'akt', 'õnnetus', 'sari', 'teema', 'tund', 'ettevõtmine', 'plakat', 'lõik', 'film', 'kirjutis', 'kirjandus', 'tekst', 'kontsert', 'seminar', 'märk', 'sõnum', 'konverents', 'üleskutse', 'foorum', 'festival', 'paraad', 'tegevus', 'sõit', 'reklaam', 'vms', 'eksperiment', 'paik', 'foto', 'kiri', 'nädal', 'ralli', 'juhtum', 'pilt', 'õppetund', 'ring', 'raamat', 'lehekülg', 'marss', 'jalutuskäik', 'pidu', 'koht', 'liik', 'küsitlus', 'mäng', 'traditsioon', 'kirjand', 'päeva', 'foor', 'avarii', 'õhtu', 'liikumine', 'kohtumine', 'arutelu', 'koolitus', 'võistlus', 'nali', 'liiklusõnnetus', 'ilm', 'tseremoonia', 'ajaleht', 'väljaanne', 'reis', 'näit', 'tee', 'materjal', 'test', 'püha', 'minut', 'kommentaarium', 'värk', 'näidis', 'katse', 'algatus', 'seeria', 'pühapäev', 'blogi']
"""

few_shot_assistant = json.dumps(
    {
        "id": "2",
        "candidates": [
            "aktsioon",
            "üritus",
            "sündmus",
            "näitus",
            "seminar",
        ],
    },
    ensure_ascii=False,
    indent=2,
)

In [38]:
# Real input sentence
user_prompt = """Sentence ID: 9
Sentence: Rahvusvaheline <diplomaatia> hoidis ära kahe naabri vahelise sõja.
Candidates: ['kohus', 'kogukond', 'õigus', 'Kohus', 'rahu', 'õiglus', 'sõda', 'koostöö', 'valitsus', 'Rahu', 'abi', 'kriis', 'komisjon', 'kokkulepe', 'Olümpiakomitee', 'olukord', 'poliitika', 'organisatsioon', 'õnnetus', 'tegevus', 'julgeolek', 'politsei', 'ja', 'arvamus', 'sündmus', 'jõud', 'maailm', 'katastroof', 'tava', 'Rist', 'otsus', 'Sõda', 'vandenõu', 'tegutsemine', 'kuritegu', 'Liit', 'Politsei', 'kohustus', 'rikkus', 'Venemaa', 'menetlus', 'konverents', 'uurimine', 'kohtunik', 'ühendus', 'majandus', 'majanduskriis', 'Jõud', 'kuritegevus', 'Kriminaal', 'sekkumine', 'lahendus', 'käitumine', 'konflikt', 'koalitsioon', 'Õigus', 'Föderatsioon', 'Vabariik', 'kindlustus', 'tragöödia', 'võim', 'seisukord', 'sõprus', 'avalikkus', 'vaen', 'Komisjon', 'huvi', 'kohtumine', 'revolutsioon', 'riik', 'Maailm', 'kaubandus', 'seisukoht', 'toetus', 'kord', 'vastutus', 'kokkuleppe', 'turvalisus', 'ajalugu', 'missioon', 'protsess', 'juhtum', 'seadus', 'asi', 'pääste', 'skandaal', 'kaitse', 'leping', 'Valitsus', 'liit', 'õiguse', 'Pank', 'elu', 'inimene', 'tulekahju', 'tõde', '–', 'operatsioon', 'praktika', 'maailmasõda']
"""

contents = [
    types.Content(role="user", parts=[types.Part.from_text(text=few_shot_user)]),
    types.Content(role="model", parts=[types.Part.from_text(text=few_shot_assistant)]),
    types.Content(role="user", parts=[types.Part.from_text(text=user_prompt)]),
]

In [39]:
# Request a JSON response from Gemini / Google Gen AI
response = client.models.generate_content(
    model=model,
    contents=contents,
    config=types.GenerateContentConfig(
        system_instruction=system_prompt,
        # temperature=0.3,
        top_p=0.95,
        # top_k=40,
        max_output_tokens=100000,
        response_mime_type="application/json",
    ),
)

INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"

In [40]:
content = response.text
result = json.loads(content)

print("Raw JSON response:")
print(json.dumps(result, ensure_ascii=False, indent=2))

Raw JSON response:
{
  "id": "9",
  "selected_candidates": [
    "koostöö",
    "sekkumine",
    "poliitika",
    "abi",
    "kaitse"
  ]
}

In [27]:
# Extract the selected candidates from the response
selected_id = "9"
selected_candidates = ["koostöö", "sekkumine", "poliitika", "abi", "kaitse"]

# Extract the selected candidates from the dataframe for comparison
original_candidates = bert_mlm_candidates_df.loc[int(selected_id), "candidate_details"]
selected_original_candidates = [
    c for c in original_candidates if c["token"] in selected_candidates
]
display(selected_original_candidates)

# Normalise the scores of the selected candidates for better comparison
scores = [c["score"] for c in selected_original_candidates]
total_score = sum(scores)
for candidate in selected_original_candidates:
    candidate["normalised_score"] = (
        candidate["score"] / total_score if total_score > 0 else 0
    )

display(selected_original_candidates)

# Sum up the normalised scores of the selected candidates per label
predictions = {}
for candidate in selected_original_candidates:
    label = candidate["resolved_form"][0]
    normalised_score = candidate["normalised_score"]
    predictions[label] = predictions.get(label, 0) + normalised_score
display(predictions)

# Print the final predicted label based on the highest summed normalised score
predicted_label = max(predictions, key=predictions.get)
print(f"Predicted label for sentence ID {selected_id}: {predicted_label}")

[{'token': 'koostöö',
  'score': 0.020630070939660072,
  'resolved_form': ['sg n'],
  'normalised_score': 0.5119477295561863},
 {'token': 'abi',
  'score': 0.009237299673259258,
  'resolved_form': ['sg n'],
  'normalised_score': 0.22922919697110355},
 {'token': 'poliitika',
  'score': 0.007941859774291515,
  'resolved_form': ['sg n'],
  'normalised_score': 0.19708206975119305},
 {'token': 'sekkumine',
  'score': 0.0016665436560288072,
  'resolved_form': ['sg n'],
  'normalised_score': 0.04135629215263725},
 {'token': 'kaitse',
  'score': 0.0008214472327381372,
  'resolved_form': ['sg n'],
  'normalised_score': 0.020384711568879887}]

[{'token': 'koostöö',
  'score': 0.020630070939660072,
  'resolved_form': ['sg n'],
  'normalised_score': 0.5119477295561863},
 {'token': 'abi',
  'score': 0.009237299673259258,
  'resolved_form': ['sg n'],
  'normalised_score': 0.22922919697110355},
 {'token': 'poliitika',
  'score': 0.007941859774291515,
  'resolved_form': ['sg n'],
  'normalised_score': 0.19708206975119305},
 {'token': 'sekkumine',
  'score': 0.0016665436560288072,
  'resolved_form': ['sg n'],
  'normalised_score': 0.04135629215263725},
 {'token': 'kaitse',
  'score': 0.0008214472327381372,
  'resolved_form': ['sg n'],
  'normalised_score': 0.020384711568879887}]

{'sg n': 1.0}

Predicted label for sentence ID 9: sg n

### Testing on a sample of sentences with batch processing and error handling

In [69]:
# System prompt: enforce Estonian rewriting behaviour, case conditioning, and JSON output
system_prompt = """You are an Estonian sentence rewriting assistant.
Your task is to select the best 5 candidates from a provided list of 100 BERT-generated candidate replacements for exactly one marked token in angle brackets <...>, using the full sentence context.

Follow this procedure internally:

1. Analyse the sentence context and the marked word.
2. Evaluate the 100 provided candidates only.
3. Reject candidates that do not fit the sentence grammatically or semantically.
4. Keep only candidates that are natural Estonian word forms in the correct context.
5. Rank the surviving candidates by suitability for the sentence.

Rules:
- Use only the provided BERT candidates. Do not invent new candidates.
- Preserve tense, number, case, agreement, punctuation, and capitalisation.
- The chosen candidates must fit the sentence context naturally and grammatically.
- The chosen candidates must be in one of the allowed morphological cases only: nominative, genitive, partitive, or illative.
- Prefer candidates whose morphological form best matches the masked word’s role in the sentence.
- If the marked token is a proper name, keep only proper-name candidates that fit the same grammatical context.
- If fewer than 5 valid candidates exist, return as many valid candidates as possible.
- Order the returned candidates from best to worst.
- Do not repeat the original marked word unless it is the only valid option.
- Return strict JSON only. Do not add explanations, markdown, or extra text.

JSON schema:
{
  "id": string,
  "candidates": array of 5 strings
}
"""

# Few-shot example to anchor the output format
few_shot_user = """Sentence ID: 2
Sentence: "Ehk oleks mõttekas ka mõni selleteemaline hoiatav <kampaania> korraldada," lisab punase autoga preili.
Candidates: ['aktsioon', 'üritus', 'kampaania', 'sündmus', 'saade', 'koosolek', 'kõne', 'päev', 'postitus', 'artikkel', 'video', 'näitus', 'asi', 'lugu', 'teade', 'lugemine', 'leht', 'liiklus', 'hoiatus', 'uudis', 'post', 'teavitus', 'loeng', 'komm', 'akt', 'õnnetus', 'sari', 'teema', 'tund', 'ettevõtmine', 'plakat', 'lõik', 'film', 'kirjutis', 'kirjandus', 'tekst', 'kontsert', 'seminar', 'märk', 'sõnum', 'konverents', 'üleskutse', 'foorum', 'festival', 'paraad', 'tegevus', 'sõit', 'reklaam', 'vms', 'eksperiment', 'paik', 'foto', 'kiri', 'nädal', 'ralli', 'juhtum', 'pilt', 'õppetund', 'ring', 'raamat', 'lehekülg', 'marss', 'jalutuskäik', 'pidu', 'koht', 'liik', 'küsitlus', 'mäng', 'traditsioon', 'kirjand', 'päeva', 'foor', 'avarii', 'õhtu', 'liikumine', 'kohtumine', 'arutelu', 'koolitus', 'võistlus', 'nali', 'liiklusõnnetus', 'ilm', 'tseremoonia', 'ajaleht', 'väljaanne', 'reis', 'näit', 'tee', 'materjal', 'test', 'püha', 'minut', 'kommentaarium', 'värk', 'näidis', 'katse', 'algatus', 'seeria', 'pühapäev', 'blogi']
"""

few_shot_assistant = json.dumps(
    {
        "id": "2",
        "candidates": [
            "aktsioon",
            "üritus",
            "sündmus",
            "näitus",
            "seminar",
        ],
    },
    ensure_ascii=False,
    indent=2,
)

In [88]:
# Create a user prompt template for the real sentences, using the same format as the few-shot example
def create_user_prompt(sentence_id, sentence, word_span):
    # Mark the target word with angle brackets
    start, end = word_span
    marked_sentence = (
        sentence[:start] + "<" + sentence[start:end] + ">" + sentence[end:]
    )
    return f"""Sentence ID: {sentence_id}
Sentence: {marked_sentence}
"""


def append_result_to_json(file_path, record, id=None):
    """Append one record to a JSON array stored in file_path."""
    file_path.parent.mkdir(parents=True, exist_ok=True)
    # If the file exists and is non-empty, load the existing data; otherwise start with an empty list
    if file_path.exists() and file_path.stat().st_size > 0:
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError:
                data = []
    else:
        data = []

    if not isinstance(data, list):
        data = []
    if id:
        # If ID is provided, check if a record with the same ID already exists and update it; otherwise append the new record
        existing_record = next((r for r in data if int(r.get("id")) == int(id)), None)
        if existing_record:
            existing_record.update(record)
            # Remove error field if it exists, since we have a successful rewrite now
            existing_record.pop("error", None)
        else:
            data.append(
                record
            )  # Append the new record if no existing record with the same ID is found
    else:
        # If no ID is provided, put the record at the end of the list
        data.append(record)
    # Write the updated list back to the file with pretty formatting
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def rewrite_sentence_with_genai(
    sentence_id, sentence, word_span, candidate_details, metadata
):
    """Rewrite one sentence by selecting candidates and deriving the predicted label from BERT candidate scores."""
    user_prompt = create_user_prompt(
        sentence_id=sentence_id, sentence=sentence, word_span=word_span
    )
    # The few-shot example is included in every call to ensure the model understands the expected JSON format and the task.
    local_contents = [
        types.Content(role="user", parts=[types.Part.from_text(text=few_shot_user)]),
        types.Content(
            role="model", parts=[types.Part.from_text(text=few_shot_assistant)]
        ),
        types.Content(role="user", parts=[types.Part.from_text(text=user_prompt)]),
    ]
    # Request a JSON response from Gemini / Google Gen AI
    response = client.models.generate_content(
        model=model,
        contents=local_contents,
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
            # temperature=0.3,
            top_p=0.95,
            max_output_tokens=100000,
            response_mime_type="application/json",
        ),
    )
    # Parse the JSON response and enrich it with metadata for later analysis
    content = response.text or "{}"
    parsed = json.loads(content)

    selected_candidates = parsed.get("candidates", [])
    if not isinstance(selected_candidates, list):
        selected_candidates = []

    selected_candidate_details = [
        candidate
        for candidate in candidate_details
        if candidate.get("token") in selected_candidates
    ]

    selected_score_total = sum(
        candidate.get("score", 0.0) for candidate in selected_candidate_details
    )
    for candidate in selected_candidate_details:
        candidate_score = candidate.get("score", 0.0)
        candidate["normalised_score"] = (
            candidate_score / selected_score_total if selected_score_total > 0 else 0.0
        )

    predictions = {}
    for candidate in selected_candidate_details:
        resolved_form = candidate.get("resolved_form", [])
        if not resolved_form:
            continue
        label = resolved_form[0]
        predictions[label] = predictions.get(label, 0.0) + candidate["normalised_score"]

    predicted_label = max(predictions, key=predictions.get) if predictions else None

    parsed["candidate_details"] = selected_candidate_details
    parsed["predictions"] = predictions
    parsed["pred_label"] = predicted_label

    parsed["source_sentence"] = sentence
    parsed["target_word"] = metadata.get("target_word", "")
    if isinstance(word_span, list):
        parsed["word_span"] = word_span
    else:
        parsed["word_span"] = word_span.astype(
            int
        ).tolist()  # Convert numpy array to list for JSON serialization
    parsed["label"] = metadata.get("label", [])

    return parsed


def get_latest_processed_id(output_file):
    """Get the highest sentence ID that has already been processed and saved in the output file."""
    if output_file.exists() and output_file.stat().st_size > 0:
        with open(output_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            if isinstance(data, list) and len(data) > 0:
                return max(int(record["id"]) for record in data if "id" in record)
    return -1  # No valid records found, start from the beginning


def get_unprocessed_dataset(dataset, output_file):
    """Filter the dataset to include only records that have errors or have not been processed yet, based on the output file."""
    if output_file.exists() and output_file.stat().st_size > 0:
        unprocessed_records = []
        processed_records = []
        # First, get the list of sentences that have errors in the output file
        with open(output_file, "r", encoding="utf-8") as f:
            processed_data = json.load(f)
            for record in processed_data:
                if "error" in record:
                    unprocessed_records.append(record["source_sentence"])
                else:
                    processed_records.append(record["source_sentence"])
        # Now filter the original dataset to include only records that are either unprocessed or have errors
        filtered_dataset = dataset[
            dataset["sentence"].isin(unprocessed_records)
            | ~dataset["sentence"].isin(processed_records)
        ]
        return filtered_dataset
    return dataset  # If no output file exists, return the entire dataset for processing


def is_transient_error(exc: Exception) -> bool:
    """Heuristically detect retryable errors such as rate limit and network hiccups."""
    message = str(exc).lower()
    transient_markers = [
        "429",
        "rate",
        "quota",
        "too many requests",
        "timeout",
        "timed out",
        "connection",
        "temporar",
        "unavailable",
        "503",
        "502",
        "504",
        "internal",
    ]
    return any(marker in message for marker in transient_markers)


def rewrite_with_retry(
    sentence_id, sentence, word_span, candidate_details, metadata, config
):
    """Call rewrite function with exponential backoff on transient errors."""
    for attempt in range(1, config["max_attempts"] + 1):
        try:
            return rewrite_sentence_with_genai(
                sentence_id=sentence_id,
                sentence=sentence,
                word_span=word_span,
                candidate_details=candidate_details,
                metadata=metadata,
            )
        except Exception as exc:
            # should_retry = is_transient_error(exc) and attempt < config["max_attempts"]
            should_retry = (
                attempt < config["max_attempts"]
            )  # Retry on all exceptions for robustness, but still limit the number of attempts
            if not should_retry:
                raise
            backoff = min(
                config["max_backoff_seconds"],
                config["initial_backoff_seconds"] * (2 ** (attempt - 1)),
            )
            sleep_s = backoff + random.uniform(0.0, config["jitter_seconds"])
            print(
                f"Retry {attempt}/{config['max_attempts'] - 1} for sentence_id={sentence_id} "
                f"after transient error: {exc}. Sleeping {sleep_s:.2f}s..."
            )
            time.sleep(sleep_s)

In [89]:
##### Create a small sample of sentences from homonym_df for testing the batch processing and error handling
max_rows = 200  # Change or remove this limit for larger runs
working_df = bert_mlm_candidates_subset_df

### Calculate the number of groups based on inflection type and form label
# First check the number of unique inflection types
num_inflection_types = working_df["inflection_type"].nunique()
# Find the number of unique form labels for each inflection type
form_labels_per_inflection = working_df.groupby("inflection_type")[
    "true_label"
].nunique()
print("Number of unique form labels per inflection type:")
print(form_labels_per_inflection)
print(
    f"Number of unique inflection types: {num_inflection_types}"
)  # 4 inflection types in total (1, 16, 17, 19)
print(
    f"Number of inflection types and form label groups: {form_labels_per_inflection.sum()}"  # 10 inflection type + form label groups in total
)
print()

### Extract n sentences from each inflection type (1, 16, 17, 19) and from each form label (sg n, sg g, sg p, adt) to have a balanced test set across both dimensions
if max_rows >= form_labels_per_inflection.sum():
    cols = [c for c in working_df.columns if c not in ["inflection_type", "true_label"]]
    sample_df = (
        working_df.groupby(["inflection_type", "true_label"])[cols]
        .apply(
            lambda group: group.sample(
                n=int(max_rows / form_labels_per_inflection.sum()),
                random_state=seed,
            )
        )
        .reset_index(level=[0, 1])  # bring group keys
        .reset_index(
            drop=True
        )  # reset the final index to be sequential and drop the old one
    )
    # Display inflection type + form label distribution in the sample to verify balance
    print("Inflection type and form label distribution in the sample:")
    print(sample_df.groupby(["inflection_type", "true_label"]).size())

# If the sample is too small to be balanced, just take the first n rows and warn about the imbalance.
else:
    print(
        f"Warning: max_rows={max_rows} is too small to have a balanced sample across inflection types and form labels. The sample will be imbalanced."
    )
    sample_df = working_df.head(max_rows)

# Check few sample sentences and their metadata
display(sample_df.head())

Number of unique form labels per inflection type:
inflection_type
1     2
16    2
17    3
19    3
Name: true_label, dtype: int64
Number of unique inflection types: 4
Number of inflection types and form label groups: 10

Inflection type and form label distribution in the sample:
inflection_type  true_label
1                sg g          20
                 sg n          20
16               sg g          20
                 sg n          20
17               sg g          20
                 sg n          20
                 sg p          20
19               adt           20
                 sg g          20
                 sg p          20
dtype: int64

   inflection_type true_label  index  \
0                1       sg g    160
1                1       sg g   4623
2                1       sg g   4502
3                1       sg g    200
4                1       sg g    833

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sentence  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Harju politseiprefektuur algatas juhtunu uurimiseks kriminaalasja.
1  Väitekirja struktuur Tulenevalt väitekirja ülesehitusest õpik-monograafiana on töö eesmärkide saavutamiseks 1) uuritud maksukorralduse ja tarbimismaksude teoreetilisi aluseid ; 2) käsitletud käibemaksu rakendamise ajalugu ning põhjusi, mis mõjutasid selle rakendamist Euroopa Liidus või rakendamise edasilükkamist Ameerika Ühendriikides ; 3) analüüsitud käibemaksu puhul kasutatavat terminoloogiat ja käibemaksu rakendamise praktilisi probleeme ning selgitatud nende võimalikke lehendusi autori poolt väljatöötatud praktiliste näidetega ; 4) analüüsitud toiduainete käibemaksumäära alandamise mõju leibkondade elujärjele võrrelduna tulumaksuvaba miinimumi tõstmisega kaasneva mõjuga.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Teisipäeval, 10. veebruaril teatas Indoneesia esindajatekoja asespiiker Abdul Gafur, et riigi parlament toetab valitsuse ettepanekut rakendada Indoneesia valuuta, ruupia stabiliseerimiseks valuutakomitee põhimõtet.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      26. veebruar, esmaspäev Kell 18.15-18.35 kadus Tihniku 5 Maksimarketi eest helebeezh VAZ 21063 numbriga 903 ABL, 1985. aasta väljalase.
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Valitsuse pöördumine : "Ühinemine Euroopa Liidu ja NATO-ga oli iseseisvuse taastanud Eesti jaoks kõige olulisem välispoliitiline eesmärk.

       word   word_span predicted_best_label  predicted_best_label_score  \
0   juhtunu    [33, 40]                 sg g                    0.700327
1  Ameerika  [314, 322]                 sg g                    0.998324
2    ruupia  [163, 169]                 sg g                    0.892514
3     aasta  [119, 124]                 sg g                    0.939417
4   Euroopa    [34, 41]                 sg g                    0.996955

                                                                                                                                                                                                                                            predicted_top_labels  \
0      [{'label': 'sg g', 'score': 0.7003272122237831}, {'label': 'pl g', 'score': 0.20161150055355392}, {'label': 'sg n', 'score': 0.02562290756031871}, {'label': 'sg in', 'score': 0.0016581377130933106}, {'label': 'pl n', 'score': 0.0006457525305449963}]
1  [{'label': 'sg g', 'score': 0.9983236787059013}, {'label': '?', 'score': 0.0005688135765353763}, {'label': 'sg tr', 'score': 0.0004460761185782758}, {'label': 'sg in', 'score': 0.00010913026267189707}, {'label': 'pl in', 'score': 8.276284279418178e-05}]
2          [{'label': 'sg g', 'score': 0.8925140607752837}, {'label': 'pl g', 'score': 0.017751883307937533}, {'label': '?', 'score': 0.009548590081976727}, {'label': 'sg tr', 'score': 0.006863836228149012}, {'label': 'sg n', 'score': 0.00507515835245916}]
3      [{'label': 'sg g', 'score': 0.9394167860272091}, {'label': '?', 'score': 0.059073759690136285}, {'label': 'sg ad', 'score': 0.000536415327587747}, {'label': 'pl g', 'score': 0.0003689920616807285}, {'label': 'sg n', 'score': 0.00012026514843910263}]
4      [{'label': 'sg g', 'score': 0.996954773767289}, {'label': '?', 'score': 0.002269228288209746}, {'label': 'pl g', 'score': 0.0007118540549768682}, {'label': 'sg n', 'score': 4.463536883747565e-05}, {'label': 'sg in', 'score': 5.6655771913938224e-06}]

                                                                                                                                                                                                                                                                                                                                                                                                                                      label_scores  \
0                                                                                                                                                                 {'sg g': 0.7003272122237831, 'pl g': 0.20161150055355392, 'sg n': 0.02562290756031871, 'pl n': 0.0006457525305449963, 'tud': 0.0006457525305449963, 'sg in': 0.0016581377130933106, 'sg ad': 0.0006257191416807473, 'sg tr': 0.0004245820455253124, '?': 0.00036423635901883245}
1  {'sg g': 0.9983236787059013, 'sg tr': 0.0004460761185782758, '?': 0.0005688135765353763, 'sg in': 0.00010913026267189707, 'pl in': 8.276284279418178e-05, 'sg n': 3.23257115345162e-05, 'pl g': 2.3818553927412722e-05, 'sg ad': 6.837851287855301e-06, 'nud': 1.1108941938194525e-06, 'pl n': 1.707609915987026e-06, 'b': 7.088337952154689e-07, 'vad': 7.088337952154689e-07, 'pl p': 9.049549589690287e-07, 'pl all': 8.493744871884701e-07}
2                                                                                                                                  {'sg g': 0.8925140607752837, 'pl g': 0.017751883307937533, 'sg tr': 0.006863836228149012, '?': 0.009548590081976727, 'sg n': 0.00507515835245916, 'sg p': 0.0023222011514008045, 'pl n': 0.0003874472216314947, 'tud': 0.00014573087294896445, 'sg all': 0.0003669287543743849, 'sg in': 0.0003321576805319637}
3                                                                                                                                                                                           {'sg g': 0.9394167860272091, '?': 0.059073759690136285, 'sg ad': 0.000536415327587747, 'pl g': 0.0003689920616807285, 'sg el': 5.8902653108816594e-05, 'sg n': 0.00012026514843910263, 'sg p': 7.061139513098169e-06, 'sg ter': 2.987970674439566e-06}
4                                 {'sg g': 0.996954773767289, '?': 0.002269228288209746, 'pl g': 0.0007118540549768682, 'sg n': 4.463536883747565e-05, 'sg in': 5.6655771913938224e-06, 'sg ill': 1.3123964208716643e-06, 'sg all': 5.745636144638411e-07, 'sg el': 2.761849202670419e-07, 'sg p': 1.125593982465034e-07, 'pl n': 3.846468388246649e-08, 'tud': 3.846468388246649e-08, 'b': 1.9682913077190278e-08, 'vad': 1.9682913077190278e-08}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             candidate_details  \

In [90]:
output_file = (
    OUTPUT_DIR / f"genai_annotations_bert_mlm_{max_rows}.json"
)  # Output file for results

# gemini-3.1-flash-lite-preview has strict request limits, so we throttle and retry safely.
config = {
    # Pacing configuration to avoid hitting rate limits
    "base_delay_seconds": round(
        60 / 15, 2
    ),  # RPM is 15 for gemini-3.1-flash-lite-preview
    "jitter_seconds": 1.0,
    # Retry configuration for transient failures
    "max_attempts": 6,
    "initial_backoff_seconds": 2.0,
    "max_backoff_seconds": 60.0,
}

# Start from the next unprocessed sentence based on the output file contents

# latest_id = get_latest_processed_id(output_file)
# unprocessed_df = sample_df[sample_df.index > latest_id]
# print(
#     f"Starting processing from sentence ID > {latest_id + 1}. Total unprocessed sentences: {len(unprocessed_df)}"
# )
unprocessed_df = get_unprocessed_dataset(sample_df, output_file)
if len(unprocessed_df) == 0:
    print("No unprocessed sentences found. All done!")
else:
    print(f"Total unprocessed sentences to process: {len(unprocessed_df)}")
    print("Next sentence to process:")
    display(unprocessed_df.head(1))

Total unprocessed sentences to process: 200
Next sentence to process:

   inflection_type true_label  index  \
0                1       sg g    160

                                                             sentence  \
0  Harju politseiprefektuur algatas juhtunu uurimiseks kriminaalasja.

      word word_span predicted_best_label  predicted_best_label_score  \
0  juhtunu  [33, 40]                 sg g                    0.700327

                                                                                                                                                                                                                                        predicted_top_labels  \
0  [{'label': 'sg g', 'score': 0.7003272122237831}, {'label': 'pl g', 'score': 0.20161150055355392}, {'label': 'sg n', 'score': 0.02562290756031871}, {'label': 'sg in', 'score': 0.0016581377130933106}, {'label': 'pl n', 'score': 0.0006457525305449963}]

                                                                                                                                                                                                                                                                       label_scores  \
0  {'sg g': 0.7003272122237831, 'pl g': 0.20161150055355392, 'sg n': 0.02562290756031871, 'pl n': 0.0006457525305449963, 'tud': 0.0006457525305449963, 'sg in': 0.0016581377130933106, 'sg ad': 0.0006257191416807473, 'sg tr': 0.0004245820455253124, '?': 0.00036423635901883245}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             candidate_details  \
0  [{'token': 'juhtunu', 'score': 0.24518722295761108, 'resolved_form': ['sg g']}, {'token': 'asjaolude', 'score': 0.13490526378154755, 'resolved_form': ['pl g']}, {'token': 'juhtumi', 'score': 0.1036483496427536, 'resolved_form': ['sg g'], 'normalised_score': 0.6206560604136335}, {'token': 'selle', 'score': 0.09421201795339584, 'resolved_form': ['sg g']}, {'token': 'sündmuse', 'score': 0.060792475938797, 'resolved_form': ['sg g'], 'normalised_score': 0.3640310603016173}, {'token': 'kuriteo', 'score': 0.04071388021111488, 'resolved_form': ['sg g']}, {'token': 'asja', 'score': 0.03698594123125076, 'resolved_form': ['sg g']}, {'token': 'toimunu', 'score': 0.024977155029773712, 'resolved_form': ['sg n']}, {'token': 'õnnetuse', 'score': 0.017669614404439926, 'resolved_form': ['sg g']}, {'token': 'tulekahju', 'score': 0.01649288646876812, 'resolved_form': ['sg g']}, {'token': 'kuritegude', 'score': 0.015974223613739014, 'resolved_form': ['pl g']}, {'token': 'liiklusõnnetuse', 'score': 0.013116450048983097, 'resolved_form': ['sg g']}, {'token': 'sündmuste', 'score': 0.012618201784789562, 'resolved_form': ['pl g']}, {'token': 'nende', 'score': 0.0073024858720600605, 'resolved_form': ['pl g']}, {'token': 'mõrva', 'score': 0.007100264076143503, 'resolved_form': ['sg g']}, {'token': 'varguse', 'score': 0.006384691223502159, 'resolved_form': ['sg g']}, {'token': 'olukorra', 'score': 0.0059357862919569016, 'resolved_form': ['sg g']}, {'token': 'põlengu', 'score': 0.005803085397928953, 'resolved_form': ['sg g']}, {'token': 'juhtumite', 'score': 0.004808688536286354, 'resolved_form': ['pl g']}, {'token': 'röövi', 'score': 0.003571360604837537, 'resolved_form': ['sg g']}, {'token': 'asjade', 'score': 0.003569855587556958, 'resolved_form': ['pl g']}, {'token': 'süüteo', 'score': 0.003070624079555273, 'resolved_form': ['sg g']}, {'token': 'faktide', 'score': 0.0026769896503537893, 'resolved_form': ['pl g']}, {'token': 'varguste', 'score': 0.00266515975818038, 'resolved_form': ['pl g']}, {'token': 'rikkumise', 'score': 0.002173707587644458, 'resolved_form': ['sg g']}, {'token': 'avarii', 'score': 0.0021672432776540518, 'resolved_form': ['sg g']}, {'token': 'väärteo', 'score': 0.0020157741382718086, 'resolved_form': ['sg g']}, {'token': 'tegevuse', 'score': 0.001965251751244068, 'resolved_form': ['sg g']}, {'token': 'rahapesu', 'score': 0.0019554293248802423, 'resolved_form': ['sg g']}, {'token': 'antud', 'score': 0.0019372575916349888, 'resolved_form': ['pl n', 'sg n', 'tud']}, {'token': 'rikkumiste', 'score': 0.0018479886930435896, 'resolved_form': ['pl g']}, {'token': 'tõendite', 'score': 0.0017974822549149394, 'resolved_form': ['pl g']}, {'token': 'kriminaalasja', 'score': 0.0017378716729581356, 'resolved_form': ['sg g']}, {'token': 'surma', 'score': 0.0016041662311181426, 'resolved_form': ['sg g']}, {'token': 'loo', 'score': 0.0015982382465153933, 'resolved_form': ['sg g']}, {'token': 'tema', 'score': 0.0015922714956104755, 'resolved_form': ['sg g']}, {'token': 'korruptsiooni', 'score': 0.0015875347889959812, 'resolved_form': ['sg g']}, {'token': 'avalduse', 'score': 0.0014611937804147601, 'resolved_form': ['sg g']}, {'token': 'vigastuste', 'score': 0.0013305068714544177, 'resolved_form': ['pl g']}, {'token': 'pettuse', 'score': 0.001320238341577351, 'resolved_form': ['sg g']}, {'token': 'kahju', 'score': 0.0012703015236184, 'resolved_form': ['sg g']}, {'token': 'tapmise', 'score': 0.0012569144601002336, 'resolved_form': ['sg g']}, {'token': 'teo', 'score': 0.0011329705594107509, 'resolved_form': ['sg g'], 'normalised_score': 0.006784334206884973}, {'token': 'andmete', 'score': 0.0011290853144600987, 'resolved_form': ['pl g']}, {'token': 'süütegude', 'score': 0.0011086637387052178, 'resolved_form': ['pl g']}, {'token': 'fotode', 'score': 0.0010419979225844145, 'resolved_form': ['pl g']}, {'token': 'selles', 'score': 0.001021365518681705, 'resolved_form': ['sg in']}, {'token': 'altkäemaksu', 'score': 0.0009761825203895569, 'resolved_form': ['sg g']}, {'token': 'röövimise', 'score': 0.0009721653186716139, 'resolved_form': ['sg g']}, {'token': 'kadumise', 'score': 0.0009405948803760111, 'resolved_form': ['sg g']}, {'token': 'kahjude', 'score': 0.0009308422449976206, 'resolved_form': ['pl g']}, {'token': 'põhjuste', 'score': 0.0009224592940881848, 'resolved_form': ['pl g']}, {'token': 'väärtegude', 'score': 0.0009169581462629139, 'resolved_form': ['pl g']}, {'token': 'õnnetuste', 'score': 0.0008545335149392486, 'resolved_form': ['pl g']}, {'token': 'video', 'score': 0.0008305923547595739, 'resolved_form': ['sg g']}, {'token': 'tõe', 'score': 0.000773383944761008, 'resolved_form': ['sg g']}, {'token': 'asjaolu', 'score': 0.0007661793497391045, 'resolved_form': ['sg g'], 'normalised_score': 0.004587953965677042}, {'token': 'süü', 'score': 0.0007119496585801244, 'resolved_form': ['sg g']}, {'token': 'asitõendite', 'score': 0.0006706843851134181, 'resolved_form': ['pl g']}, {'token': 'sündmuskoha', 'score': 0.0006681969971396029, 'resolved_form': ['sg g']}, {'token': 'vägivalla', 'score': 0.0006649093120358884, 'resolved_form': ['sg g']}, {'token': 'fakti', 'score': 0.0006580710178241134, 'resolved_form': ['sg g'], 'normalised_score': 0.003940591112187181}, {'token': 'kuriteos', 'score': 0.0006367721944116056, 'resolved_form': ['sg in']}, {'token': 'kõigi', 'score': 0.0006354654906317592, 'resolved_form': ['pl g']}, {'token': 'dokumentide', 'score': 0.0006272127502597868, 'resolved_form': ['pl g']}, {'token': 'sel', 'score': 0.0006257191416807473, 'resolved_form': ['sg ad']}, {'token': 'materjalide', 'score': 0.0005717944004572928, 'resolved_form': ['pl g']}, {'token': 'kohapeal', 'score': 0.0005632312968373299, 'resolved_form': []}, {'token': 'asukoha', 'score': 0.0005568595370277762, 'resolved_form': ['sg g']}, {'token': 'surnu', 'score': 0.0005460555548779666, 'resolved_form': ['sg g']}, {'token': 'politsei', 'score': 0.0005341117503121495, 'resolved_form': ['sg g']}, {'token': 'katastroofi', 'score': 0.00047290624934248626, 'resolved_form': ['sg g']}, {'token': 'toimuva', 'score': 0.00044728838838636875, 'resolved_form': ['sg g']}, {'token': 'tegude', 'score': 0.0004428414686117321, 'resolved_form': ['pl g']}, {'token': 'skeemi', 'score': 0.00043934036511927843, 'resolved_form': ['sg g']}, {'token': 'minu', 'score': 0.0004275327082723379, 'resolved_form': ['sg g']}, {'token': 'võimalikuks', 'score': 0.0004245820455253124, 'resolved_form': ['sg tr']}, {'token': 'narkootikumide', 'score': 0.0004184649733360857, 'resolved_form': ['pl g']}, {'token': 'katse', 'score': 0.00040893166442401707, 'resolved_form': ['sg g']}, {'token': '</s>NOTUSED', 'score': 0.00039983936585485935, 'resolved_form': []}, {'token': 'isiku', 'score': 0.0003950737009290606, 'resolved_form': ['sg g']}, {'token': 'ka', 'score': 0.00039029112667776644, 'resolved_form': []}, {'token': 'isikute', 'score': 0.00038377256714738905, 'resolved_form': ['pl g']}, {'token': 'reisijate', 'score': 0.00037512011476792395, 'resolved_form': ['pl g']}, {'token': 'tulemuste', 'score': 0.0003681434609461576, 'resolved_form': ['pl g']}, {'token': 'tehingute', 'score': 0.0003645977994892746, 'resolved_form': ['pl g']}, {'token': 'SIA', 'score': 0.00036423635901883245, 'resolved_form': ['?']}, {'token': 'tüli', 'score': 0.0003549180692061782, 'resolved_form': ['sg g']}, {'token': 'probleemide', 'score': 0.0003520165628287941, 'resolved_form': ['pl g']}, {'token': 'info', 'score': 0.00035083567490801215, 'resolved_form': ['sg g']}, {'token': 'hiljem', 'score': 0.00035071372985839844, 'resolved_form': []}, {'token': 'siin', 'score': 0.00034678581869229674, 'resolved_form': []}, {'token': 'materjali', 'score': 0.0003426255425438285, 'resolved_form': ['sg g']}, {'token': 'väärteoasja', 'score': 0.0003384728915989399, 'resolved_form': ['sg g']}, {'token': 'eelnevalt', 'score': 0.00033558867289684713, 'resolved_form': []}, {'token': 'seal', 'score': 0.00032716343412175775, 'resolved_form': []}, {'token': 'terrorismi', 'score': 0.0003136777086183429, 'resolved_form': ['sg g']}, {'token': 'vea', 'score': 0.00031002561445347965, 'resolved_form': ['sg g']}, {'token': 'müra', 'score': 0.0003020060539711267, 'resolved_form': ['sg g']}, {'token': 'pommi', 'score': 0.000300567684462294, 'resolved_form': ['sg g']}]

                                                             source
0  infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json

In [91]:
# Find processed records that are in the sample_df
if output_file.exists() and output_file.stat().st_size > 0:
    with open(output_file, "r", encoding="utf-8") as f:
        processed_data = json.load(f)
        processed_ids = [
            int(record["id"]) for record in processed_data if "id" in record
        ]
        processed_sentences = sample_df[sample_df["index"].isin(processed_ids)]
        print(
            f"Number of sentences in sample_df that have already been processed: {len(processed_sentences)}"
        )
        print("Sample of processed sentences:")
        display(sample_df[sample_df["index"].isin(processed_ids)].head(10))

# Now remove all the already processed sentences from the output file that are not in the sample_df
if output_file.exists() and output_file.stat().st_size > 0:
    with open(output_file, "r", encoding="utf-8") as f:
        processed_data = json.load(f)
        processed_ids = [
            int(record["id"]) for record in processed_data if "id" in record
        ]
        filtered_data = [
            record
            for record in processed_data
            if int(record.get("id", -1)) in sample_df["index"].values
        ]
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(filtered_data, f, ensure_ascii=False, indent=2)

else:
    print("No output file found, so no sentences have been processed yet.")

No output file found, so no sentences have been processed yet.

In [92]:
# Batch rewrite loop: call Gen AI and append each result to a JSON file
processed = 0
for i, (sentence_id, sentence, word_span, word, label, candidate_details) in enumerate(
    zip(
        unprocessed_df["index"],
        unprocessed_df["sentence"],
        unprocessed_df["word_span"],
        unprocessed_df["word"],
        unprocessed_df["true_label"],
        unprocessed_df["candidate_details"],
    )
):
    try:
        metadata = {
            "target_word": word,
            "label": label.tolist() if isinstance(label, np.ndarray) else label,
        }
        result = rewrite_with_retry(
            sentence_id=sentence_id,
            sentence=sentence,
            word_span=word_span,
            candidate_details=candidate_details,
            config=config,
            metadata=metadata,
        )
        append_result_to_json(output_file, result, id=sentence_id)
        print(f"[{processed + 1}] Saved sentence_id={sentence_id}")
    except Exception as exc:
        error_record = {
            "id": str(sentence_id),
            "source_sentence": sentence,
            "target_word": word,
            "word_span": word_span.astype(int).tolist(),
            "true_label": label.tolist(),
            "pred_label": None,
            "error": str(exc),
        }
        append_result_to_json(output_file, error_record, id=sentence_id)
        print(f"[{processed + 1}] Error on sentence_id={sentence_id}: {exc}")

    processed += 1

    # Additional pacing between successful/failed items to avoid bursty traffic.
    if i < max_rows:
        sleep_s = config["base_delay_seconds"] + random.uniform(
            0.0, config["jitter_seconds"]
        )
        print(f"Sleeping {sleep_s:.2f}s before next request...")
        time.sleep(sleep_s)

print(f"Finished. Processed {processed} rows. Results appended to: {output_file}")

INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[1] Saved sentence_id=160
Sleeping 4.75s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[2] Saved sentence_id=4623
Sleeping 4.75s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[3] Saved sentence_id=4502
Sleeping 4.79s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[4] Saved sentence_id=200
Sleeping 4.77s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[5] Saved sentence_id=833
Sleeping 4.22s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[6] Saved sentence_id=584
Sleeping 4.49s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[7] Saved sentence_id=4009
Sleeping 4.99s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[8] Saved sentence_id=387
Sleeping 4.40s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[9] Saved sentence_id=4625
Sleeping 4.81s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[10] Saved sentence_id=4506
Sleeping 4.41s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[11] Saved sentence_id=4379
Sleeping 4.30s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[12] Saved sentence_id=330
Sleeping 4.19s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[13] Saved sentence_id=878
Sleeping 4.12s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 1/5 for sentence_id=4805 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 2.86s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[14] Saved sentence_id=4805
Sleeping 4.63s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[15] Saved sentence_id=519
Sleeping 4.41s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[16] Saved sentence_id=4120
Sleeping 4.34s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[17] Saved sentence_id=673
Sleeping 4.19s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[18] Saved sentence_id=884
Sleeping 4.02s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[19] Saved sentence_id=4392
Sleeping 4.72s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[20] Saved sentence_id=667
Sleeping 4.20s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[21] Saved sentence_id=185
Sleeping 4.82s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[22] Saved sentence_id=4501
Sleeping 4.18s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[23] Saved sentence_id=4380
Sleeping 4.62s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[24] Saved sentence_id=192
Sleeping 4.73s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[25] Saved sentence_id=689
Sleeping 4.69s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[26] Saved sentence_id=560
Sleeping 4.95s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[27] Saved sentence_id=958
Sleeping 4.95s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[28] Saved sentence_id=524
Sleeping 4.12s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[29] Saved sentence_id=4898
Sleeping 4.38s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[30] Saved sentence_id=4468
Sleeping 4.01s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[31] Saved sentence_id=4073
Sleeping 4.13s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[32] Saved sentence_id=375
Sleeping 4.10s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 1/5 for sentence_id=876 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 2.74s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 2/5 for sentence_id=876 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 4.60s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 3/5 for sentence_id=876 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 8.44s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[33] Saved sentence_id=876
Sleeping 4.52s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[34] Saved sentence_id=4919
Sleeping 5.00s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[35] Saved sentence_id=534
Sleeping 4.44s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 1/5 for sentence_id=3986 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 2.82s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[36] Saved sentence_id=3986
Sleeping 4.45s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[37] Saved sentence_id=630
Sleeping 4.31s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 1/5 for sentence_id=893 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 2.01s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[38] Saved sentence_id=893
Sleeping 4.90s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 1/5 for sentence_id=4278 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 2.93s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[39] Saved sentence_id=4278
Sleeping 4.73s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[40] Saved sentence_id=590
Sleeping 4.79s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[41] Saved sentence_id=1272
Sleeping 4.88s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[42] Saved sentence_id=5868
Sleeping 4.55s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[43] Saved sentence_id=5750
Sleeping 4.49s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[44] Saved sentence_id=1595
Sleeping 4.11s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[45] Saved sentence_id=4980
Sleeping 4.39s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[46] Saved sentence_id=1867
Sleeping 4.25s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[47] Saved sentence_id=5255
Sleeping 4.16s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"
Retry 1/5 for sentence_id=1747 after transient error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}. Sleeping 2.22s...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[48] Saved sentence_id=1747
Sleeping 4.93s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[49] Saved sentence_id=5872
Sleeping 4.39s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[50] Saved sentence_id=5752
Sleeping 4.59s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[51] Saved sentence_id=5587
Sleeping 4.67s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[52] Saved sentence_id=1644
Sleeping 4.97s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[53] Saved sentence_id=5022
Sleeping 4.35s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
[54] Saved sentence_id=5901
Sleeping 4.91s before next request...
INFO:models.py:6013: AFC is enabled with max remote calls: 10.
INFO:_client.py:1025: HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 503 Service Unavailable"

In [ ]:
# Open LLM sample annotation data
llm_samples_df = pd.read_json(output_file, orient="records")

new_records = []

# For each record, iterate over the candidates, construct the candidate sentence, and perform morphological analysis to extract the case and other features of the candidate replacement word. Assume each candidate has uniform probability and sum up the probabilities for candidates that match each form label to get a distribution of form labels for the candidates.
for index, row in tqdm.tqdm(llm_samples_df.iterrows(), total=llm_samples_df.shape[0]):
    id = row["id"]
    candidates = row.get("candidates", [])
    chosen = row.get("chosen", "")
    rewritten = row.get("rewritten", "")
    new_word_span = row.get("new_word_span", None)
    source_sentence = row["source_sentence"]
    target_word = row["target_word"]
    word_span = row["word_span"]
    label = row.get("label", [])[
        0
    ]  # Assuming label is a list and we take the first element as the form label
    # print(f"Source sentence: {source_sentence}")
    # print(f"Target word span: {word_span}")
    candidate_form_weight = (
        1 / len(candidates) if candidates else 0
    )  # Uniform weight for each candidate
    form_probabilities = {}
    for candidate in candidates:
        # Construct sentence with the candidate replacement
        candidate_sentence = (
            source_sentence[: word_span[0]]
            + candidate
            + source_sentence[word_span[1] :]
        )
        # print(f"Candidate sentence: {candidate_sentence}")
        # Create EstNLTK Text object and perform morphological analysis
        estnltk_text = estnltk.Text(candidate_sentence)
        estnltk_text.tag_layer("morph_analysis")
        # Extract the morphological tags for the candidate word
        morph_layer = estnltk_text.morph_analysis
        # Find the token in the morph layer that corresponds to the candidate replacement
        candidate_token = None
        for token in morph_layer:
            if (
                token.start <= word_span[0] < token.end
            ):  # Check if the token covers the start of the original word span
                candidate_token = token
                break
        if candidate_token:
            # Count up the form labels for the candidate
            number_of_labels = len(candidate_token.form) if candidate_token.form else 0
            if number_of_labels > 0:
                weight_per_label = candidate_form_weight / number_of_labels
                for candidate_label in candidate_token.form:
                    form_probabilities[candidate_label] = (
                        form_probabilities.get(candidate_label, 0) + weight_per_label
                    )
            else:
                form_probabilities["unknown"] = (
                    form_probabilities.get("unknown", 0) + candidate_form_weight
                )

    best_form_label = (
        max(form_probabilities, key=form_probabilities.get)
        if form_probabilities
        else "unknown"
    )
    # Create a record for the chosen candidate and its features
    candidate_record = {
        "id": id,
        "candidates": candidates,
        "pred_label": best_form_label,
        "true_label": label,
        "predicted_form_distribution": form_probabilities,
        "source_sentence": source_sentence,
        "target_word": target_word,
        "word_span": word_span,
    }
    new_records.append(candidate_record)

100%|██████████| 100/100 [00:06<00:00, 14.64it/s]

In [ ]:
# Create a new DataFrame from the predicted form labels and their distributions and save to JSON
homonym_results_df = pd.DataFrame(new_records)
homonym_results_df_path = (
    HOMONYMS_DIRS["processed"] / f"homonyms_llm_mlm_predictions_v2_{max_rows}.parquet"
)
homonym_results_df.to_parquet(homonym_results_df_path, index=False)