In [1]:
print("Test")

Test

In [2]:
import os
import json
import random
import time
import pandas as pd
import estnltk
import tqdm
import pathlib
import logging
import re

logging.getLogger().setLevel(logging.WARNING)

from scripts.config import (
    SEED,
    ROOT,
    DATA_DIR,
    ENC2017_ROOT,
    UD_ET_EDT_ROOT,
    HOMONYMS_ROOT,
    ENC2017_DIRS,
    UD_ET_EDT_DIRS,
    HOMONYMS_DIRS,
    OUTPUT_DIR,
    PLOTS_DIR,
    HOMONYMS_PLOTS_DIR,
    MODEL_DIR,
)

# from pydantic import BaseModel
import tiktoken
import tempfile
from dotenv import load_dotenv
from openai import AzureOpenAI
from openai_cost_calculator import estimate_cost_typed
from typing import Any

load_dotenv(".env", verbose=True)
api_version = "2024-12-01-preview"
model_name = "gpt-4o"
deployment_name = "EstNLTK-gpt-4o"
endpoint = str(os.getenv("AZURE_ENDPOINT"))
api_key = str(os.getenv("OPENAI_API_KEY"))

### Testing

In [3]:
client = AzureOpenAI(
    api_version=api_version,
    azure_endpoint=endpoint,
    api_key=api_key,
)

In [ ]:
# Estimate the cost of a request
max_tokens = 128
costs = {
    "gpt-4o": {
        "input": 2.50 / 1_000_000,  # $2.50 per 1M tokens
        "cached_input": 1.25 / 1_000_000,  # $1.25 per 1M tokens
        "output": 10.00 / 1_000_000,  # $10.00 per 1M tokens
    }
}

# 1) build messages
# System prompt: enforce Estonian rewriting behaviour, case conditioning, and JSON output
system_prompt = """You are an Estonian sentence rewriting assistant.

Replace exactly one marked token in angle brackets <...> with a context-appropriate alternative.

Rules:
- Preserve tense, number, case, agreement, capitalisation, punctuation, and word order as much as possible.
- Infer the token’s grammatical role and morphology from the sentence context.
- Generate 10 alternatives that fit the context and use only these cases: nominative, genitive, partitive, or additive/illative (both fit the same role in this task).
- If the token is a proper name, replace it with another plausible proper name that still fits the required case.
- Do not repeat the original token unless it is the only valid option.
"""

# Structured output format for Azure OpenAI chat completions.
# Structured Outputs require a top-level object, so the list is wrapped in a candidates field.
response_format = {
    "type": "json_schema",
    "json_schema": {
        "name": "candidates",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 10,
                    "maxItems": 10,
                }
            },
            "required": ["candidates"],
            "additionalProperties": False,
        },
    },
}

# One-shot example to anchor the output format
one_shot_user = """Sentence: Ma näen <maja>."""

one_shot_assistant = json.dumps(
    {
        "candidates": [
            "ehitist",
            "hoonet",
            "elamut",
            "rajatist",
            "korterit",
            "kodu",
            "eluaset",
            "hoonestust",
            "majapidamist",
            "häärberit",
        ],
    },
    ensure_ascii=False,
    indent=2,
)


# User prompt example for the real sentence
# user_prompt = """Sentence: Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots."""
# user_prompt = """Provide 10 alternatives for the marked token in the following sentence: KOMISJONI MÄÄRUS (EMÜ) nr 344/86, millega muudetakse tagatiste osas määrusi (EMÜ) nr 626/85 ja (EMÜ) 2077/85 17. veebruar 1986 EUROOPA ÜHENDUSTE KOMISJON, võttes arvesse Euroopa Majandusühenduse asutamislepingut, võttes arvesse nõukogu 14. märtsi 1977. aasta määrust (EMÜ) nr 516/77 puu- ja köögiviljatooteturu ühise korralduse kohta, 1 viimati muudetud määrusega (EMÜ) nr 3768/85, 2 eriti selle artikli 4 lõiget 8, võttes arvesse nõukogu 14. märtsi 1977. aasta määrust (EMÜ) nr 525/77, millega kehtestatakse ananassikonservide tootmistoetuste süsteem, 3 viimati muudetud määrusega (EMÜ) nr 1699/85, 4 eriti selle artiklit 8, ning arvestades, et : komisjoni 22. juuli 1985. aasta määruse (EMÜ) nr 2220/85 (millega sätestatakse põllumajandustoodete tagatissüsteemi ühised üksikasjalikud rakenduseeskirjad) 5 III jaotises sätestatakse tagatiste andmise vormid ; sama määruse artikli 19 lõikes 1 sätestatakse seoses ettemaksetega esitatud tagatiste vabastamine ; sellest tulenevalt tuleks tunnistada kehtetuks komisjoni 12. märtsi 1985. aasta määruse (EMÜ) nr 626/85 (töötlemata kuivatatud viinamarjade ja viigimarjade ostmise, müümise ja ladustamise kohta ladustusasutuste poolt) 6 ja komisjoni 25. juuli 1985. aasta määruse (EMÜ) nr 2077/85 (milles sätestatakse ananassikonservide tootmistoetuse üksikasjalikud rakenduseeskirjad) 7 vastavad sätted ; käesoleva määrusega ettenähtud meetmed on kooskõlas puu- ja köögiviljatooteturu korralduskomitee arvamusega, ON VASTU VÕTNUD KÄESOLEVA MÄÄRUSE.""",
# user_prompt = """Väljakutsete ja abisaanute analüüsi alusel otsustatakse jaanuaris-veebruaris, kas Elvas hakkavad sõitma ka kogemustega Tartu kiirabi arstid-velskrid."""
user_prompt = """Sentence: Normi-aktiveerimise teooria (Schwartz, 1970) on algselt mõeldud moraalse otsustamisprotsessi analüüsimiseks abistava käitumise näitel."""

output_content = """{\"candidates\":[\"hüpoteesi\",\"mudeli\",\"käsitluse\",\"lähenemise\",\"kontseptsiooni\",\"idee\",\"doktriini\",\"teooriate\",\"kontseptsioonide\",\"vaatenurga\"]}"""


messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": one_shot_user},
    {"role": "assistant", "content": one_shot_assistant},
    {"role": "user", "content": user_prompt},
]

# 2) token count (use model encoding)
enc = tiktoken.encoding_for_model(model_name)  # pick same model you'll use
prompt_text = "".join(m["content"] for m in messages)
prompt_tokens = (
    len(enc.encode(prompt_text)) + 32
)  # +32 for the tokens are added (316 was the actual prompt tokens)
output_tokens = (
    len(enc.encode(output_content)) + 1
)  # +1 for the assistant's role token in the response
print(f"Prompt tokens: {prompt_tokens}")
print(f"Output tokens: {output_tokens}")
print(f"Total tokens: {prompt_tokens + output_tokens}")

# 3) estimate cost
# Assuming all prompt tokens are input and cached input tokens, and max_tokens are output tokens
input_costs = costs[model_name]["input"] * prompt_tokens
print(f"Estimated input cost: ${input_costs:.6f}")
cached_input_costs = (
    costs[model_name]["cached_input"] * 0
)  # There has not been any cached input in experiments.
print(f"Estimated cached input cost: ${cached_input_costs:.6f}")
output_costs = costs[model_name]["output"] * output_tokens
print(f"Estimated output cost: ${output_costs:.6f}")
print(f"Total estimated cost: ${input_costs + cached_input_costs + output_costs:.6f}")

Prompt tokens: 299
Output tokens: 49
Total tokens: 348
Estimated input cost: $0.000748
Estimated cached input cost: $0.000000
Estimated output cost: $0.000490
Total estimated cost: $0.001238

In [28]:
response = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Hello!",
        }
    ],
    max_completion_tokens=512,
    top_p=0.95,
    model=deployment_name,
)

In [29]:
print(response)

ChatCompletion(id='chatcmpl-DZehCb459dk5GzgEFxCdrXJ5jYmje', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! 😊 How can I assist you today?', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None), content_filter_results={'protected_material_code': {'filtered': False, 'detected': False}, 'protected_material_text': {'filtered': False, 'detected': False}})], created=1777390286, model='gpt-4o-2024-11-20', object='chat.completion', service_tier='default', system_fingerprint='fp_af7f7349a4', usage=CompletionUsage(completion_tokens=11, prompt_tokens=9, total_tokens=20, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0)), prompt_filter_results=[{'prompt_index': 0, 'content_filter_results': {'jailbreak': {'filtered': False, 'detected': False}}}])

In [30]:
print(response.to_dict())

{'id': 'chatcmpl-DZehCb459dk5GzgEFxCdrXJ5jYmje', 'choices': [{'finish_reason': 'stop', 'index': 0, 'logprobs': None, 'message': {'content': 'Hello! 😊 How can I assist you today?', 'refusal': None, 'role': 'assistant', 'annotations': []}, 'content_filter_results': {'protected_material_code': {'filtered': False, 'detected': False}, 'protected_material_text': {'filtered': False, 'detected': False}}}], 'created': 1777390286, 'model': 'gpt-4o-2024-11-20', 'object': 'chat.completion', 'service_tier': 'default', 'system_fingerprint': 'fp_af7f7349a4', 'usage': {'completion_tokens': 11, 'prompt_tokens': 9, 'total_tokens': 20, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'jailbreak': {'filtered': False, 'detected': False}}}]}

```
ChatCompletion(id='chatcmpl-DZZFQtM00dyhVqTaXZ2XqHnOdRB1r', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! 😊 How can I assist you today?', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None), content_filter_results={'protected_material_code': {'filtered': False, 'detected': False}, 'protected_material_text': {'filtered': False, 'detected': False}})], created=1777369344, model='gpt-4o-2024-11-20', object='chat.completion', service_tier='default', system_fingerprint='fp_af7f7349a4', usage=CompletionUsage(completion_tokens=11, prompt_tokens=9, total_tokens=20, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0)), prompt_filter_results=[{'prompt_index': 0, 'content_filter_results': {'jailbreak': {'filtered': False, 'detected': False}}}])
```

In [31]:
estimate_cost_typed(response).as_dict()

{'prompt_cost_uncached': '0.00002250',
 'prompt_cost_cached': '0.00000000',
 'completion_cost': '0.00011000',
 'total_cost': '0.00013250'}

In [40]:
rd = response.to_dict()
rd["cost"] = estimate_cost_typed(response).as_dict()
print(rd)

{'id': 'chatcmpl-DZehCb459dk5GzgEFxCdrXJ5jYmje', 'choices': [{'finish_reason': 'stop', 'index': 0, 'logprobs': None, 'message': {'content': 'Hello! 😊 How can I assist you today?', 'refusal': None, 'role': 'assistant', 'annotations': []}, 'content_filter_results': {'protected_material_code': {'filtered': False, 'detected': False}, 'protected_material_text': {'filtered': False, 'detected': False}}}], 'created': 1777390286, 'model': 'gpt-4o-2024-11-20', 'object': 'chat.completion', 'service_tier': 'default', 'system_fingerprint': 'fp_af7f7349a4', 'usage': {'completion_tokens': 11, 'prompt_tokens': 9, 'total_tokens': 20, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'jailbreak': {'filtered': False, 'detected': False}}}], 'cost': {'prompt_cost_uncached': '0.00002250', 'prompt_cost_cached': '0.00000000', 'completion_cost': '0.00011000', 'total_cost': '0.00013250'}}

In [42]:
# Extract used tokens from response
# Structure of the response is:
# usage=CompletionUsage(completion_tokens=11, prompt_tokens=9, total_tokens=20, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0))
print(f"Actual prompt tokens used: {response.usage.prompt_tokens}")
print(
    f"Actual cached input tokens used: {response.usage.prompt_tokens_details.cached_tokens}"
)
print(f"Actual completion tokens used: {response.usage.completion_tokens}")
print(f"Actual total tokens used: {response.usage.total_tokens}")
# Calculate actual cost based on usage
actual_input_cost = costs[model_name]["input"] * response.usage.prompt_tokens
actual_cached_input_cost = (
    costs[model_name]["cached_input"]
    * response.usage.prompt_tokens_details.cached_tokens
)
actual_output_cost = costs[model_name]["output"] * response.usage.completion_tokens
print(f"Input cost: ${actual_input_cost:.7f}")
print(f"Cached input cost: ${actual_cached_input_cost:.7f}")
print(f"Output cost: ${actual_output_cost:.7f}")
print(
    f"Total actual cost: ${actual_input_cost + actual_cached_input_cost + actual_output_cost:.7f}"
)

Actual prompt tokens used: 9
Actual cached input tokens used: 0
Actual completion tokens used: 11
Actual total tokens used: 20
Input cost: $0.0000225
Cached input cost: $0.0000000
Output cost: $0.0001100
Total actual cost: $0.0001325

In [33]:
client.close()

### LLM Batch request

In [19]:
client = AzureOpenAI(
    api_version=api_version,
    azure_endpoint=endpoint,
    api_key=api_key,
)

In [16]:
# System prompt: enforce Estonian rewriting behaviour, case conditioning, and JSON output
system_prompt = """You are an Estonian sentence rewriting assistant.

Replace exactly one marked token in angle brackets <...> with a context-appropriate alternative.

Rules:
- Preserve tense, number, case, agreement, capitalisation, punctuation, and word order as much as possible.
- Infer the token’s grammatical role and morphology from the sentence context.
- Generate 10 alternatives that fit the context and use only these cases: nominative, genitive, partitive, or additive/illative (both fit the same role in this task).
- If the token is a proper name, replace it with another plausible proper name that still fits the required case.
- Do not repeat the original token unless it is the only valid option.
"""

# Structured output format for Azure OpenAI chat completions.
# Structured Outputs require a top-level object, so the list is wrapped in a candidates field.
response_format = {
    "type": "json_schema",
    "json_schema": {
        "name": "candidates",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 10,
                    "maxItems": 10,
                }
            },
            "required": ["candidates"],
            "additionalProperties": False,
        },
    },
}

# One-shot example to anchor the output format
one_shot_user = """Sentence: Ma näen <maja>."""

one_shot_assistant = json.dumps(
    {
        "candidates": [
            "ehitist",
            "hoonet",
            "elamut",
            "rajatist",
            "korterit",
            "kodu",
            "eluaset",
            "hoonestust",
            "majapidamist",
            "häärberit",
        ],
    },
    ensure_ascii=False,
    indent=2,
)

# Example real input sentence
# user_prompt = """Sentence: Samas on kõik uue kodu lähistel asuvad koolid sellised, mis võtavad <gümnaasiumi> vastu katsetega."""


# Create a user prompt template for the real sentences, using the same format as the few-shot example
def create_user_prompt(sentence, word_span):
    # Mark the target word with angle brackets
    start, end = word_span
    marked_sentence = (
        sentence[:start] + "<" + sentence[start:end] + ">" + sentence[end:]
    )
    return f"""Sentence: {marked_sentence}"""


def build_messages(user_prompt: str) -> list[dict[str, str]]:
    """Build the chat-completions message list for one rewrite request."""
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": one_shot_user},
        {"role": "assistant", "content": one_shot_assistant},
        {"role": "user", "content": user_prompt},
    ]


def parse_response_content(content: str) -> dict[str, Any]:
    """Parse and validate the JSON payload returned by Azure OpenAI."""
    parsed = json.loads(content or "{}")
    if not isinstance(parsed, dict):
        raise ValueError("Expected a JSON object from the model response.")
    if "candidates" not in parsed or not isinstance(parsed["candidates"], list):
        raise ValueError("Model response did not contain a candidates list.")
    return parsed


def _atomic_write_json(file_path: pathlib.Path, data: list[dict[str, Any]]) -> None:
    """Write JSON atomically to avoid partial files on crash/interruption."""
    file_path.parent.mkdir(parents=True, exist_ok=True)
    temp_file_path: pathlib.Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=file_path.parent,
            prefix=f"{file_path.stem}.",
            suffix=".tmp",
            delete=False,
        ) as temp_file:
            json.dump(data, temp_file, ensure_ascii=False, indent=2)
            temp_file.flush()
            os.fsync(temp_file.fileno())
            temp_file_path = pathlib.Path(temp_file.name)

        # Atomic replace: after a crash you see either the old or the new file, never a partial one.
        os.replace(temp_file_path, file_path)
    finally:
        if temp_file_path is not None and temp_file_path.exists():
            temp_file_path.unlink(missing_ok=True)


def _load_results_json(file_path: pathlib.Path) -> list[dict[str, Any]]:
    """Load results JSON safely and fail closed on corruption to prevent silent data loss."""
    if not file_path.exists() or file_path.stat().st_size == 0:
        return []

    with open(file_path, "r", encoding="utf-8") as file_handle:
        try:
            loaded = json.load(file_handle)
        except json.JSONDecodeError as error:
            raise RuntimeError(
                f"Failed to parse existing output file {file_path}. "
                "Refusing to overwrite it to avoid data loss."
            ) from error

    if not isinstance(loaded, list):
        raise RuntimeError(
            f"Expected a JSON list in {file_path}, got {type(loaded).__name__}. "
            "Refusing to overwrite it to avoid data loss."
        )
    return loaded


def append_result_to_json(file_path, record, id=None, search_id="sentence_id"):
    """Append or update one record in a JSON array using crash-safe atomic writes."""
    resolved_path = pathlib.Path(file_path)
    data = _load_results_json(resolved_path)

    if id is not None and search_id is not None:
        # If ID is provided, update matching record; otherwise append.
        existing_record = next(
            (
                r
                for r in data
                if isinstance(r, dict)
                and r.get(search_id) is not None
                and str(r.get(search_id)) == str(id)
            ),
            None,
        )
        if existing_record:
            existing_record.update(record)
            # Remove stale error after a successful rewrite.
            existing_record.pop("error", None)
        else:
            data.append(record)
    else:
        data.append(record)

    _atomic_write_json(resolved_path, data)


def write_total_cost(file_path, total_cost):
    """Write the total cost to a separate txt file."""
    resolved_path = pathlib.Path(file_path)
    with open(resolved_path, "w", encoding="utf-8") as f:
        f.write(str(total_cost))


def rewrite_sentence_with_azure_openai(sentence_id, sentence, word_span, metadata):
    """Rewrite one sentence by replacing the marked target word via Azure OpenAI."""
    user_prompt = create_user_prompt(sentence=sentence, word_span=word_span)
    messages = build_messages(user_prompt)

    # Request a structured JSON response from Azure OpenAI chat completions.
    response = client.chat.completions.create(
        model=deployment_name,
        messages=messages,
        response_format=response_format,
        max_completion_tokens=512,
        top_p=0.95,
    )
    # Estimate cost for this response (best-effort). The estimator expects the full response object.
    try:
        cost_result = estimate_cost_typed(response)
        cost_info = cost_result.as_dict()  # Convert to dict for JSON serialization
    except Exception as _err:
        # Don't fail the rewrite on estimator errors; keep a surfacable error message.
        cost_info = {"error": str(_err)}
    message = response.choices[0].message
    refusal = getattr(message, "refusal", None)
    if refusal:
        raise RuntimeError(f"Model refused the request: {refusal}")

    # Parse the JSON response and enrich it with metadata for later analysis.
    parsed = parse_response_content(message.content or "{}")
    response_dict = response.to_dict()

    # Keep useful metadata for later analysis/debugging.
    parsed["sentence_id"] = str(sentence_id)
    parsed["source_sentence"] = sentence
    parsed["target_word"] = metadata.get("target_word", "")
    if isinstance(word_span, list):
        parsed["word_span"] = word_span
    else:
        parsed["word_span"] = word_span.astype(
            int
        ).tolist()  # Convert numpy array to list for JSON serialization
    parsed["label"] = metadata.get("label", [])
    # Attach cost estimation metadata (not part of the structured schema)
    response_dict["cost"] = cost_info

    return parsed, response_dict


# Backwards-compatible alias for any existing callers.
rewrite_sentence_with_genai = rewrite_sentence_with_azure_openai


def get_latest_processed_id(output_file):
    """Get the highest sentence ID that has already been processed and saved in the output file."""
    if output_file.exists() and output_file.stat().st_size > 0:
        with open(output_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            if isinstance(data, list) and len(data) > 0:
                return max(int(record["id"]) for record in data if "id" in record)
    return -1  # No valid records found, start from the beginning


def get_unprocessed_dataset(dataset, output_file):
    """Filter the dataset to include only records that have errors or have not been processed yet, based on the output file."""
    if output_file.exists() and output_file.stat().st_size > 0:
        unprocessed_records = []
        processed_records = []
        # First, get the list of sentences that have errors in the output file
        with open(output_file, "r", encoding="utf-8") as f:
            processed_data = json.load(f)
            for record in processed_data:
                if "error" in record:
                    unprocessed_records.append(record["source_sentence"])
                else:
                    processed_records.append(record["source_sentence"])
        # Now filter the original dataset to include only records that are either unprocessed or have errors
        filtered_dataset = dataset[
            dataset["sentence"].isin(unprocessed_records)
            | ~dataset["sentence"].isin(processed_records)
        ]
        return filtered_dataset
    else:
        return dataset  # If no output file exists, return the entire dataset as unprocessed


def is_transient_error(exc: Exception) -> bool:
    """Heuristically detect retryable errors such as rate limit and network hiccups."""
    message = str(exc).lower()
    transient_markers = [
        "429",
        "rate",
        "quota",
        "too many requests",
        "timeout",
        "timed out",
        "connection",
        "temporar",
        "unavailable",
        "503",
        "502",
        "504",
        "internal",
    ]
    return any(marker in message for marker in transient_markers)


def rewrite_with_retry(sentence_id, sentence, word_span, metadata, config):
    """Call rewrite function with exponential backoff on transient errors."""
    for attempt in range(1, config["max_attempts"] + 1):
        try:
            return rewrite_sentence_with_azure_openai(
                sentence_id=sentence_id,
                sentence=sentence,
                word_span=word_span,
                metadata=metadata,
            )
        except Exception as exc:
            # should_retry = is_transient_error(exc) and attempt < config["max_attempts"]
            should_retry = (
                attempt < config["max_attempts"]
            )  # Retry on all exceptions for robustness, but still limit the number of attempts
            if not should_retry:
                raise

            backoff = min(
                config["max_backoff_seconds"],
                config["initial_backoff_seconds"] * (2 ** (attempt - 1)),
            )
            sleep_s = backoff + random.uniform(0.0, config["jitter_seconds"])
            print(
                f"Retry {attempt}/{config['max_attempts'] - 1} for sentence_id={sentence_id} "
                f"after transient error: {exc}. Sleeping {sleep_s:.2f}s..."
            )
            time.sleep(sleep_s)

In [20]:
# Load the homonyms dataset to get the sentences we want to rewrite with Gen AI
homonyms_df = pd.read_parquet(
    HOMONYMS_DIRS["processed"] / "homonyms_overall_updated_sentences.parquet"
)
display(homonyms_df.head())
display(homonyms_df.shape)

,num,inflection_type,sentence,word,word_span,label,source
0,1,1,"Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.",võitja,"[74, 80]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json
1,1,1,"Normi-aktiveerimise teooria (Schwartz, 1970) on algselt mõeldud moraalse otsustamisprotsessi analüüsimiseks abistava käitumise näitel.",teooria,"[20, 27]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json
2,1,1,"""Ehk oleks mõttekas ka mõni selleteemaline hoiatav kampaania korraldada,"" lisab punase autoga preili.",kampaania,"[51, 60]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json
3,1,1,"""Minu otsus oli õige ning teeksin kõik sama moodi, kui saaksin uuesti teha,"" kommenteerib kolm aastat tagasi eriliste teenete eest Eesti passi saanud Primakov.",õige,"[16, 20]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json
4,1,1,"Itaalia president ütles Venemaa riigipea auks korraldatud suurejoonelisel banketil, et kahe riigi ühisavaldus Iraagi kohta oli kahe riigipea ""suur tarkuseavaldus"".",Itaalia,"[0, 7]",[sg g],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json

(7886, 7)

In [ ]:
output_file = OUTPUT_DIR / "gpt-4o-homonyms_LLM_MLM.json"  # Output file for results
# output_file_log = (
#     OUTPUT_DIR / "gpt-4o-homonyms_LLM_MLM_log.json"
# )  # More detailed log file for debugging and analysis
total_cost_txt = (
    OUTPUT_DIR / "gpt-4o-homonyms_LLM_MLM_total_cost.txt"
)  # File to store the total cost information
sample_df = homonyms_df.iloc[:].copy()  # Use N for testing
sample_df["index"] = sample_df.index.astype(
    int
)  # Ensure index is an integer for ID purposes

# gpt-4o has following rate limits:
# - 180 000 tokens per minute (TPM)
# - 1080 requests per minute (RPM)
config = {
    # Pacing configuration to avoid hitting rate limits
    "base_delay_seconds": round(60 / 1080, 2),  # RPM is 1080 for gpt-4o
    "jitter_seconds": 0.1,  # Add a small random jitter to avoid thundering herd issues
    # Retry configuration for transient failures
    "max_attempts": 6,
    "initial_backoff_seconds": 2.0,
    "max_backoff_seconds": 60.0,
}

# Start from the next unprocessed sentence based on the output file contents
unprocessed_df = get_unprocessed_dataset(sample_df, output_file)
if len(unprocessed_df) == 0:
    print("No unprocessed sentences found. All done!")
else:
    print(f"Total unprocessed sentences to process: {len(unprocessed_df)}")
    print("Next sentence to process:")
    display(unprocessed_df.head(1))

# Find processed records that are in the sample_df
if output_file.exists() and output_file.stat().st_size > 0:
    with open(output_file, "r", encoding="utf-8") as f:
        processed_data = json.load(f)
        processed_ids = [
            int(record["sentence_id"])
            for record in processed_data
            if "sentence_id" in record
        ]
        processed_sentences = sample_df[sample_df["index"].isin(processed_ids)]
        print(
            f"Number of sentences in sample_df that have already been processed: {len(processed_sentences)}"
        )
        print("Sample of processed sentences:")
        display(sample_df[sample_df["index"].isin(processed_ids)].head(10))
else:
    print("No output file found, so no sentences have been processed yet.")

# Now remove all the already processed sentences from the output file that are not in the sample_df
# if output_file.exists() and output_file.stat().st_size > 0:
#     with open(output_file, "r", encoding="utf-8") as f:
#         processed_data = json.load(f)
#         processed_ids = [
#             int(record["sentence_id"])
#             for record in processed_data
#             if "sentence_id" in record
#         ]
#         filtered_data = [
#             record
#             for record in processed_data
#             if int(record.get("sentence_id", -1)) in sample_df["index"].values
#         ]
#     with open(output_file, "w", encoding="utf-8") as f:
#         json.dump(filtered_data, f, ensure_ascii=False, indent=2)

# Find cumulative total cost from the output file
total_cost = 0.0
if total_cost_txt.exists() and total_cost_txt.stat().st_size > 0:
    with open(total_cost_txt, "r", encoding="utf-8") as f:
        total_cost = float(f.read().strip())
        print(f"Cumulative total cost from log file: ${total_cost:.6f}")
else:
    print("No log file found, so cumulative cost is $0.00.")

Total unprocessed sentences to process: 1523
Next sentence to process:

,num,inflection_type,sentence,word,word_span,label,source,index
6363,2,17,"Ei saa hästi aru, miks oli vaja Tallinnas osatada Hansapanka või Briti nõukogu.",aru,"[13, 16]",[sg p],infl_type_17_1000_v2.json,6363

Number of sentences in sample_df that have already been processed: 6363
Sample of processed sentences:

,num,inflection_type,sentence,word,word_span,label,source,index
0,1,1,"Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.",võitja,"[74, 80]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,0
1,1,1,"Normi-aktiveerimise teooria (Schwartz, 1970) on algselt mõeldud moraalse otsustamisprotsessi analüüsimiseks abistava käitumise näitel.",teooria,"[20, 27]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,1
2,1,1,"""Ehk oleks mõttekas ka mõni selleteemaline hoiatav kampaania korraldada,"" lisab punase autoga preili.",kampaania,"[51, 60]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,2
3,1,1,"""Minu otsus oli õige ning teeksin kõik sama moodi, kui saaksin uuesti teha,"" kommenteerib kolm aastat tagasi eriliste teenete eest Eesti passi saanud Primakov.",õige,"[16, 20]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,3
4,1,1,"Itaalia president ütles Venemaa riigipea auks korraldatud suurejoonelisel banketil, et kahe riigi ühisavaldus Iraagi kohta oli kahe riigipea ""suur tarkuseavaldus"".",Itaalia,"[0, 7]",[sg g],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,4
5,1,1,"Žüriis olid Ave Needo (Ruut FM), Aivo Tammela (Jüri noortemaja), Thea Tekkel (politsei esindaja), Margus Sõna (DJ School) ja Mario Liimann (OÜ Audiomeedia).",Mario,"[125, 130]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,5
6,1,1,"Samas teeb aga murelikuks asjaolu, et paljudes Araabia riikides kasvab rahva seas pahameel oma nn liiga Läänemeelse valitsuse vastu.",Araabia,"[47, 54]",[sg g],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,6
7,1,1,"Meri kinnitas eile Hamburgi linnapeale, et Eesti on valmis viisata suhtluseks kümmet Euroopa Liidu riiki ühendava Schengeni ühisviisaruumiga, sest Eesti piirikaitse on eeskujulik ja üks tänapäevasemaid Euroopas.",Euroopa,"[85, 92]",[sg g],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,7
8,1,1,"Siiditee John W. Orrison, endine CSX Transportationi presidendi abi, on rääkinud Wall Street Journalile, et kaupade eksportimine Hiinast ja Koreast Euroopa Liitu on piiramatu potentsiaaliga äri, kus liigub aastas kümneid miljardeid eurosid.",piiramatu,"[165, 174]",[sg g],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,8
9,1,1,Rahvusvaheline diplomaatia hoidis ära kahe naabri vahelise sõja.,diplomaatia,"[15, 26]",[sg n],infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json,9

Cumulative total cost from log file: $7.598968

In [22]:
# Batch rewrite loop: call OpenAI and append each result to a JSON file
processed = len(processed_sentences)
max_cost = 20.0  # Set a maximum total cost threshold for the entire batch to avoid unexpected high costs during testing
with tqdm.tqdm(
    total=len(sample_df), desc="Processing sentences", initial=processed
) as pbar:
    for i, row in enumerate(
        zip(
            unprocessed_df["index"],
            unprocessed_df["sentence"],
            unprocessed_df["word_span"],
            unprocessed_df["word"],
            unprocessed_df["label"],
        )
    ):
        sentence_id, sentence, word_span, word, label = row
        try:
            metadata = {
                "target_word": word,
                "label": label.tolist(),  # Convert numpy array to list for JSON serialization
            }
            result, response = rewrite_with_retry(
                sentence_id=sentence_id,
                sentence=sentence,
                word_span=word_span,
                config=config,
                metadata=metadata,
            )
            append_result_to_json(output_file, result, id=sentence_id)
            # append_result_to_json(output_file_log, response, id=sentence_id) # Log the full response for debugging and analysis
            # Get the cost info from the result for logging
            cost_info = response.get("cost", {})
            if "error" in cost_info:
                tqdm.tqdm.write(
                    f"[{processed + 1}] Saved sentence_id={sentence_id} with cost estimation error: {cost_info['error']}"
                )
            else:
                total_cost_info = cost_info.get("total_cost", 0.0)
                total_cost += float(total_cost_info)
                write_total_cost(total_cost_txt, total_cost)
                # tqdm.tqdm.write(
                #     f"[{processed + 1}] Saved sentence_id={sentence_id} cost: {total_cost_info} total: {total_cost:.6f}"
                # )
        except Exception as exc:
            error_record = {
                "sentence_id": str(sentence_id),
                "source_sentence": sentence,
                "target_word": word,
                "word_span": word_span.astype(int).tolist(),
                "label": label.tolist(),
                "error": str(exc),
            }
            append_result_to_json(output_file, error_record, id=sentence_id)
            # append_result_to_json(
            #     output_file_log, {"error": str(exc)}, id=sentence_id
            # )  # Log the error details in the log file as well
            tqdm.tqdm.write(
                f"[{processed + 1}] Error on sentence_id={sentence_id}: {exc}"
            )
            print("Traceback:", exc.__traceback__)

        processed += 1
        # update postfix shown to the right of the bar
        pbar.set_postfix({"total_cost": f"${total_cost:.6f}", "processed": processed})
        pbar.update(1)

        if (
            total_cost > max_cost
        ):  # Stop the loop if total cost exceeds $20 to avoid unexpected high costs during testing
            print(
                f"Total cost exceeded ${max_cost}. Stopping the loop to avoid unexpected high costs during testing."
            )
            break

        # Additional pacing between successful/failed items to avoid bursty traffic.
        if i < len(unprocessed_df) - 1:  # Don't sleep after the last item
            sleep_s = config["base_delay_seconds"] + random.uniform(
                0.0, config["jitter_seconds"]
            )
            pbar.set_description_str(f"Sleeping {sleep_s:.2f}s")
            time.sleep(sleep_s)

print(f"Batch processing completed. Total cost: ${total_cost:.6f}")
print(f"Finished. Processed {processed} rows. Results appended to: {output_file}")

Processing sentences:  81%|████████  | 6363/7886 [00:01<?, ?it/s]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████  | 6364/7886 [00:02<34:00,  1.34s/it, total_cost=$7.600146, processed=6364]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6365/7886 [00:03<29:53,  1.18s/it, total_cost=$7.601343, processed=6365]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  81%|████████  | 6366/7886 [00:04<28:43,  1.13s/it, total_cost=$7.602623, processed=6366]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  81%|████████  | 6367/7886 [00:05<28:54,  1.14s/it, total_cost=$7.603803, processed=6367]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6368/7886 [00:06<30:02,  1.19s/it, total_cost=$7.605021, processed=6368]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████  | 6369/7886 [00:07<29:20,  1.16s/it, total_cost=$7.606206, processed=6369]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  81%|████████  | 6370/7886 [00:09<29:35,  1.17s/it, total_cost=$7.607413, processed=6370]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6371/7886 [00:10<29:40,  1.18s/it, total_cost=$7.608521, processed=6371]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6372/7886 [00:12<31:09,  1.23s/it, total_cost=$7.609591, processed=6372]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████  | 6373/7886 [00:13<36:02,  1.43s/it, total_cost=$7.610778, processed=6373]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  81%|████████  | 6374/7886 [00:14<33:20,  1.32s/it, total_cost=$7.611828, processed=6374]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6375/7886 [00:15<34:43,  1.38s/it, total_cost=$7.613033, processed=6375]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  81%|████████  | 6376/7886 [00:17<32:29,  1.29s/it, total_cost=$7.614088, processed=6376]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6377/7886 [00:18<31:27,  1.25s/it, total_cost=$7.615178, processed=6377]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6378/7886 [00:19<31:25,  1.25s/it, total_cost=$7.616313, processed=6378]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  81%|████████  | 6379/7886 [00:21<31:49,  1.27s/it, total_cost=$7.617628, processed=6379]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████  | 6380/7886 [00:22<32:22,  1.29s/it, total_cost=$7.618828, processed=6380]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6381/7886 [00:23<31:10,  1.24s/it, total_cost=$7.620063, processed=6381]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  81%|████████  | 6382/7886 [00:24<30:49,  1.23s/it, total_cost=$7.621261, processed=6382]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  81%|████████  | 6383/7886 [00:26<33:25,  1.33s/it, total_cost=$7.622351, processed=6383]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6384/7886 [00:27<35:27,  1.42s/it, total_cost=$7.623541, processed=6384]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6385/7886 [00:29<33:07,  1.32s/it, total_cost=$7.624693, processed=6385]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  81%|████████  | 6386/7886 [00:30<33:50,  1.35s/it, total_cost=$7.625848, processed=6386]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6387/7886 [00:31<31:26,  1.26s/it, total_cost=$7.626966, processed=6387]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  81%|████████  | 6388/7886 [00:33<35:25,  1.42s/it, total_cost=$7.628098, processed=6388]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  81%|████████  | 6389/7886 [00:34<33:41,  1.35s/it, total_cost=$7.629246, processed=6389]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████  | 6390/7886 [00:35<32:21,  1.30s/it, total_cost=$7.630573, processed=6390]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6391/7886 [00:36<31:58,  1.28s/it, total_cost=$7.631781, processed=6391]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████  | 6392/7886 [00:37<31:26,  1.26s/it, total_cost=$7.632963, processed=6392]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  81%|████████  | 6393/7886 [00:39<30:15,  1.22s/it, total_cost=$7.634068, processed=6393]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████  | 6394/7886 [00:40<30:43,  1.24s/it, total_cost=$7.635121, processed=6394]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████  | 6395/7886 [00:41<28:59,  1.17s/it, total_cost=$7.636268, processed=6395]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████  | 6396/7886 [00:42<28:23,  1.14s/it, total_cost=$7.637425, processed=6396]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6397/7886 [00:43<28:07,  1.13s/it, total_cost=$7.638630, processed=6397]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████  | 6398/7886 [00:45<28:49,  1.16s/it, total_cost=$7.639750, processed=6398]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  81%|████████  | 6399/7886 [00:46<35:40,  1.44s/it, total_cost=$7.640955, processed=6399]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  81%|████████  | 6400/7886 [00:48<35:12,  1.42s/it, total_cost=$7.642098, processed=6400]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  81%|████████  | 6401/7886 [00:49<34:25,  1.39s/it, total_cost=$7.643298, processed=6401]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  81%|████████  | 6402/7886 [00:51<33:12,  1.34s/it, total_cost=$7.644443, processed=6402]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  81%|████████  | 6403/7886 [00:52<34:44,  1.41s/it, total_cost=$7.645860, processed=6403]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  81%|████████  | 6404/7886 [00:53<33:15,  1.35s/it, total_cost=$7.647035, processed=6404]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████  | 6405/7886 [00:54<32:59,  1.34s/it, total_cost=$7.648145, processed=6405]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6406/7886 [00:56<32:20,  1.31s/it, total_cost=$7.649270, processed=6406]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████  | 6407/7886 [00:57<32:00,  1.30s/it, total_cost=$7.650463, processed=6407]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  81%|████████▏ | 6408/7886 [00:58<32:21,  1.31s/it, total_cost=$7.651700, processed=6408]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  81%|████████▏ | 6409/7886 [01:00<31:18,  1.27s/it, total_cost=$7.652905, processed=6409]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  81%|████████▏ | 6410/7886 [01:01<32:43,  1.33s/it, total_cost=$7.654028, processed=6410]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  81%|████████▏ | 6411/7886 [01:02<34:57,  1.42s/it, total_cost=$7.655093, processed=6411]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████▏ | 6412/7886 [01:04<32:59,  1.34s/it, total_cost=$7.656245, processed=6412]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  81%|████████▏ | 6413/7886 [01:05<32:17,  1.32s/it, total_cost=$7.657450, processed=6413]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  81%|████████▏ | 6414/7886 [01:06<31:41,  1.29s/it, total_cost=$7.658648, processed=6414]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  81%|████████▏ | 6415/7886 [01:07<31:06,  1.27s/it, total_cost=$7.659810, processed=6415]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  81%|████████▏ | 6416/7886 [01:09<31:12,  1.27s/it, total_cost=$7.661005, processed=6416]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  81%|████████▏ | 6417/7886 [01:10<29:55,  1.22s/it, total_cost=$7.662118, processed=6417]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  81%|████████▏ | 6418/7886 [01:11<28:34,  1.17s/it, total_cost=$7.663418, processed=6418]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████▏ | 6419/7886 [01:12<27:35,  1.13s/it, total_cost=$7.664580, processed=6419]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  81%|████████▏ | 6420/7886 [01:13<28:44,  1.18s/it, total_cost=$7.665740, processed=6420]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████▏ | 6421/7886 [01:14<28:29,  1.17s/it, total_cost=$7.666938, processed=6421]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████▏ | 6422/7886 [01:15<28:29,  1.17s/it, total_cost=$7.668083, processed=6422]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  81%|████████▏ | 6423/7886 [01:17<28:11,  1.16s/it, total_cost=$7.669253, processed=6423]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  81%|████████▏ | 6424/7886 [01:18<28:06,  1.15s/it, total_cost=$7.670343, processed=6424]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  81%|████████▏ | 6425/7886 [01:19<29:16,  1.20s/it, total_cost=$7.671640, processed=6425]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  81%|████████▏ | 6426/7886 [01:20<28:56,  1.19s/it, total_cost=$7.672775, processed=6426]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  81%|████████▏ | 6427/7886 [01:21<28:20,  1.17s/it, total_cost=$7.673975, processed=6427]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  82%|████████▏ | 6428/7886 [01:23<27:03,  1.11s/it, total_cost=$7.675050, processed=6428]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6429/7886 [01:24<29:41,  1.22s/it, total_cost=$7.676188, processed=6429]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6430/7886 [01:25<30:22,  1.25s/it, total_cost=$7.677423, processed=6430]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6431/7886 [01:26<29:02,  1.20s/it, total_cost=$7.678683, processed=6431]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6432/7886 [01:27<28:16,  1.17s/it, total_cost=$7.679833, processed=6432]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  82%|████████▏ | 6433/7886 [01:28<27:53,  1.15s/it, total_cost=$7.681078, processed=6433]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6434/7886 [01:29<27:47,  1.15s/it, total_cost=$7.682120, processed=6434]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6435/7886 [01:31<27:52,  1.15s/it, total_cost=$7.683198, processed=6435]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  82%|████████▏ | 6436/7886 [01:32<27:10,  1.12s/it, total_cost=$7.684365, processed=6436]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6437/7886 [01:33<27:14,  1.13s/it, total_cost=$7.685475, processed=6437]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6438/7886 [01:34<27:13,  1.13s/it, total_cost=$7.686640, processed=6438]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  82%|████████▏ | 6439/7886 [01:35<27:55,  1.16s/it, total_cost=$7.687933, processed=6439]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6440/7886 [01:36<27:26,  1.14s/it, total_cost=$7.689090, processed=6440]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6441/7886 [01:38<27:45,  1.15s/it, total_cost=$7.690585, processed=6441]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6442/7886 [01:40<37:07,  1.54s/it, total_cost=$7.691708, processed=6442]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6443/7886 [01:41<34:44,  1.44s/it, total_cost=$7.692990, processed=6443]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6444/7886 [01:42<32:27,  1.35s/it, total_cost=$7.694053, processed=6444]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6445/7886 [01:43<31:21,  1.31s/it, total_cost=$7.695208, processed=6445]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  82%|████████▏ | 6446/7886 [01:45<30:18,  1.26s/it, total_cost=$7.696370, processed=6446]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6447/7886 [01:46<30:20,  1.27s/it, total_cost=$7.697535, processed=6447]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6448/7886 [01:47<29:45,  1.24s/it, total_cost=$7.698613, processed=6448]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6449/7886 [01:48<29:40,  1.24s/it, total_cost=$7.699948, processed=6449]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6450/7886 [01:49<29:05,  1.22s/it, total_cost=$7.701160, processed=6450]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6451/7886 [01:51<28:17,  1.18s/it, total_cost=$7.702230, processed=6451]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6452/7886 [01:52<29:12,  1.22s/it, total_cost=$7.703370, processed=6452]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6453/7886 [01:53<28:41,  1.20s/it, total_cost=$7.704623, processed=6453]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6454/7886 [01:55<28:11,  1.18s/it, total_cost=$7.706005, processed=6454]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6455/7886 [01:56<29:51,  1.25s/it, total_cost=$7.707155, processed=6455]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  82%|████████▏ | 6456/7886 [01:57<28:52,  1.21s/it, total_cost=$7.708238, processed=6456]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  82%|████████▏ | 6457/7886 [01:58<27:45,  1.17s/it, total_cost=$7.709418, processed=6457]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6458/7886 [01:59<27:43,  1.17s/it, total_cost=$7.710550, processed=6458]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6459/7886 [02:01<28:07,  1.18s/it, total_cost=$7.712025, processed=6459]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  82%|████████▏ | 6460/7886 [02:03<42:00,  1.77s/it, total_cost=$7.713253, processed=6460]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6461/7886 [02:05<37:30,  1.58s/it, total_cost=$7.714363, processed=6461]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  82%|████████▏ | 6462/7886 [02:07<36:02,  1.52s/it, total_cost=$7.715560, processed=6462]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  82%|████████▏ | 6463/7886 [02:08<40:28,  1.71s/it, total_cost=$7.716785, processed=6463]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6464/7886 [02:10<39:51,  1.68s/it, total_cost=$7.717853, processed=6464]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  82%|████████▏ | 6465/7886 [02:11<35:25,  1.50s/it, total_cost=$7.718940, processed=6465]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6466/7886 [02:12<32:58,  1.39s/it, total_cost=$7.720080, processed=6466]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6467/7886 [02:13<33:37,  1.42s/it, total_cost=$7.721270, processed=6467]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6468/7886 [02:16<42:29,  1.80s/it, total_cost=$7.722508, processed=6468]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  82%|████████▏ | 6469/7886 [02:17<38:15,  1.62s/it, total_cost=$7.723745, processed=6469]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6470/7886 [02:18<35:17,  1.50s/it, total_cost=$7.724920, processed=6470]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6471/7886 [02:20<33:19,  1.41s/it, total_cost=$7.726053, processed=6471]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6472/7886 [02:21<31:05,  1.32s/it, total_cost=$7.727305, processed=6472]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6473/7886 [02:23<37:33,  1.60s/it, total_cost=$7.728445, processed=6473]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6474/7886 [02:24<35:17,  1.50s/it, total_cost=$7.729583, processed=6474]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  82%|████████▏ | 6475/7886 [02:26<32:42,  1.39s/it, total_cost=$7.730755, processed=6475]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  82%|████████▏ | 6476/7886 [02:27<32:14,  1.37s/it, total_cost=$7.732043, processed=6476]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6477/7886 [02:28<30:37,  1.30s/it, total_cost=$7.733148, processed=6477]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6478/7886 [02:29<29:41,  1.27s/it, total_cost=$7.734360, processed=6478]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6479/7886 [02:30<28:19,  1.21s/it, total_cost=$7.735500, processed=6479]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6480/7886 [02:31<28:26,  1.21s/it, total_cost=$7.736825, processed=6480]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  82%|████████▏ | 6481/7886 [02:32<27:43,  1.18s/it, total_cost=$7.737970, processed=6481]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6482/7886 [02:34<27:27,  1.17s/it, total_cost=$7.739093, processed=6482]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6483/7886 [02:35<27:49,  1.19s/it, total_cost=$7.740290, processed=6483]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  82%|████████▏ | 6484/7886 [02:36<26:54,  1.15s/it, total_cost=$7.741483, processed=6484]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6485/7886 [02:38<30:58,  1.33s/it, total_cost=$7.742843, processed=6485]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6486/7886 [02:39<31:01,  1.33s/it, total_cost=$7.743998, processed=6486]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6487/7886 [02:41<29:36,  1.27s/it, total_cost=$7.745150, processed=6487]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6488/7886 [02:42<33:16,  1.43s/it, total_cost=$7.746403, processed=6488]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6489/7886 [02:43<31:10,  1.34s/it, total_cost=$7.747618, processed=6489]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6490/7886 [02:44<30:17,  1.30s/it, total_cost=$7.748698, processed=6490]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6491/7886 [02:46<30:09,  1.30s/it, total_cost=$7.749880, processed=6491]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  82%|████████▏ | 6492/7886 [02:47<29:17,  1.26s/it, total_cost=$7.751063, processed=6492]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  82%|████████▏ | 6493/7886 [02:48<28:23,  1.22s/it, total_cost=$7.752268, processed=6493]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6494/7886 [02:49<26:53,  1.16s/it, total_cost=$7.753385, processed=6494]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  82%|████████▏ | 6495/7886 [02:50<26:34,  1.15s/it, total_cost=$7.754580, processed=6495]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6496/7886 [02:51<25:59,  1.12s/it, total_cost=$7.755678, processed=6496]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  82%|████████▏ | 6497/7886 [02:52<27:00,  1.17s/it, total_cost=$7.756808, processed=6497]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6498/7886 [02:54<27:09,  1.17s/it, total_cost=$7.758175, processed=6498]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  82%|████████▏ | 6499/7886 [02:55<27:11,  1.18s/it, total_cost=$7.759380, processed=6499]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6500/7886 [02:56<30:22,  1.31s/it, total_cost=$7.760565, processed=6500]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6501/7886 [02:57<29:31,  1.28s/it, total_cost=$7.761735, processed=6501]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  82%|████████▏ | 6502/7886 [02:59<28:02,  1.22s/it, total_cost=$7.762810, processed=6502]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  82%|████████▏ | 6503/7886 [03:00<27:43,  1.20s/it, total_cost=$7.764020, processed=6503]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  82%|████████▏ | 6504/7886 [03:01<26:55,  1.17s/it, total_cost=$7.765175, processed=6504]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  82%|████████▏ | 6505/7886 [03:02<26:34,  1.15s/it, total_cost=$7.766270, processed=6505]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6506/7886 [03:03<26:53,  1.17s/it, total_cost=$7.767448, processed=6506]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  83%|████████▎ | 6507/7886 [03:04<26:30,  1.15s/it, total_cost=$7.768710, processed=6507]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  83%|████████▎ | 6508/7886 [03:05<24:42,  1.08s/it, total_cost=$7.769723, processed=6508]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6509/7886 [03:06<26:02,  1.13s/it, total_cost=$7.770853, processed=6509]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6510/7886 [03:08<26:26,  1.15s/it, total_cost=$7.772060, processed=6510]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  83%|████████▎ | 6511/7886 [03:09<26:48,  1.17s/it, total_cost=$7.773275, processed=6511]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  83%|████████▎ | 6512/7886 [03:10<26:18,  1.15s/it, total_cost=$7.774375, processed=6512]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6513/7886 [03:11<26:17,  1.15s/it, total_cost=$7.775458, processed=6513]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  83%|████████▎ | 6514/7886 [03:12<26:35,  1.16s/it, total_cost=$7.776635, processed=6514]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  83%|████████▎ | 6515/7886 [03:13<26:23,  1.16s/it, total_cost=$7.777785, processed=6515]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6516/7886 [03:15<25:57,  1.14s/it, total_cost=$7.778843, processed=6516]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  83%|████████▎ | 6517/7886 [03:16<26:47,  1.17s/it, total_cost=$7.780013, processed=6517]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6518/7886 [03:17<26:58,  1.18s/it, total_cost=$7.781123, processed=6518]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6519/7886 [03:18<27:01,  1.19s/it, total_cost=$7.782305, processed=6519]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  83%|████████▎ | 6520/7886 [03:20<26:31,  1.17s/it, total_cost=$7.783505, processed=6520]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  83%|████████▎ | 6521/7886 [03:22<36:04,  1.59s/it, total_cost=$7.784568, processed=6521]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  83%|████████▎ | 6522/7886 [03:23<32:54,  1.45s/it, total_cost=$7.785638, processed=6522]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6523/7886 [03:24<30:46,  1.36s/it, total_cost=$7.786740, processed=6523]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6524/7886 [03:25<29:30,  1.30s/it, total_cost=$7.787893, processed=6524]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6525/7886 [03:27<29:05,  1.28s/it, total_cost=$7.788978, processed=6525]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6526/7886 [03:29<35:26,  1.56s/it, total_cost=$7.790293, processed=6526]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6527/7886 [03:31<37:36,  1.66s/it, total_cost=$7.791543, processed=6527]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6528/7886 [03:32<33:49,  1.49s/it, total_cost=$7.792680, processed=6528]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6529/7886 [03:33<31:14,  1.38s/it, total_cost=$7.793893, processed=6529]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  83%|████████▎ | 6530/7886 [03:34<30:19,  1.34s/it, total_cost=$7.795123, processed=6530]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6531/7886 [03:35<29:26,  1.30s/it, total_cost=$7.796315, processed=6531]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6532/7886 [03:37<28:32,  1.26s/it, total_cost=$7.797523, processed=6532]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6533/7886 [03:38<28:18,  1.26s/it, total_cost=$7.798733, processed=6533]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6534/7886 [03:39<27:31,  1.22s/it, total_cost=$7.799870, processed=6534]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6535/7886 [03:40<27:09,  1.21s/it, total_cost=$7.800970, processed=6535]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  83%|████████▎ | 6536/7886 [03:41<26:54,  1.20s/it, total_cost=$7.802078, processed=6536]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  83%|████████▎ | 6537/7886 [03:42<26:12,  1.17s/it, total_cost=$7.803200, processed=6537]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6538/7886 [03:43<26:36,  1.18s/it, total_cost=$7.804370, processed=6538]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  83%|████████▎ | 6539/7886 [03:45<25:49,  1.15s/it, total_cost=$7.805575, processed=6539]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6540/7886 [03:46<26:15,  1.17s/it, total_cost=$7.806793, processed=6540]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6541/7886 [03:47<29:04,  1.30s/it, total_cost=$7.807940, processed=6541]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  83%|████████▎ | 6542/7886 [03:49<27:50,  1.24s/it, total_cost=$7.809123, processed=6542]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  83%|████████▎ | 6543/7886 [03:50<27:16,  1.22s/it, total_cost=$7.811215, processed=6543]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6544/7886 [03:51<26:46,  1.20s/it, total_cost=$7.812330, processed=6544]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6545/7886 [03:52<27:36,  1.24s/it, total_cost=$7.813650, processed=6545]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  83%|████████▎ | 6546/7886 [03:53<26:55,  1.21s/it, total_cost=$7.814800, processed=6546]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6547/7886 [03:54<26:46,  1.20s/it, total_cost=$7.815970, processed=6547]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6548/7886 [03:56<26:07,  1.17s/it, total_cost=$7.817063, processed=6548]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6549/7886 [03:57<25:32,  1.15s/it, total_cost=$7.818148, processed=6549]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  83%|████████▎ | 6550/7886 [03:58<24:26,  1.10s/it, total_cost=$7.819278, processed=6550]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  83%|████████▎ | 6551/7886 [03:59<24:40,  1.11s/it, total_cost=$7.820340, processed=6551]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6552/7886 [04:00<25:05,  1.13s/it, total_cost=$7.821460, processed=6552]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  83%|████████▎ | 6553/7886 [04:01<25:02,  1.13s/it, total_cost=$7.822598, processed=6553]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6554/7886 [04:02<25:07,  1.13s/it, total_cost=$7.823763, processed=6554]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6555/7886 [04:03<24:58,  1.13s/it, total_cost=$7.824878, processed=6555]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6556/7886 [04:05<24:40,  1.11s/it, total_cost=$7.826030, processed=6556]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6557/7886 [04:06<26:16,  1.19s/it, total_cost=$7.827248, processed=6557]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6558/7886 [04:07<25:50,  1.17s/it, total_cost=$7.828425, processed=6558]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6559/7886 [04:08<26:46,  1.21s/it, total_cost=$7.829598, processed=6559]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6560/7886 [04:09<26:34,  1.20s/it, total_cost=$7.830763, processed=6560]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  83%|████████▎ | 6561/7886 [04:11<27:04,  1.23s/it, total_cost=$7.831838, processed=6561]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6562/7886 [04:12<26:17,  1.19s/it, total_cost=$7.832985, processed=6562]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  83%|████████▎ | 6563/7886 [04:13<25:24,  1.15s/it, total_cost=$7.834063, processed=6563]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  83%|████████▎ | 6564/7886 [04:14<24:39,  1.12s/it, total_cost=$7.835163, processed=6564]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6565/7886 [04:15<24:34,  1.12s/it, total_cost=$7.836280, processed=6565]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  83%|████████▎ | 6566/7886 [04:16<26:34,  1.21s/it, total_cost=$7.837525, processed=6566]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6567/7886 [04:17<25:39,  1.17s/it, total_cost=$7.838733, processed=6567]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6568/7886 [04:19<24:46,  1.13s/it, total_cost=$7.839888, processed=6568]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6569/7886 [04:22<36:05,  1.64s/it, total_cost=$7.840915, processed=6569]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6570/7886 [04:23<37:39,  1.72s/it, total_cost=$7.842035, processed=6570]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  83%|████████▎ | 6571/7886 [04:24<34:42,  1.58s/it, total_cost=$7.843308, processed=6571]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  83%|████████▎ | 6572/7886 [04:27<31:15,  1.43s/it, total_cost=$7.844378, processed=6572]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6573/7886 [04:28<36:39,  1.68s/it, total_cost=$7.845673, processed=6573]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6574/7886 [04:31<37:09,  1.70s/it, total_cost=$7.846825, processed=6574]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  83%|████████▎ | 6575/7886 [04:33<43:10,  1.98s/it, total_cost=$7.848050, processed=6575]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6576/7886 [04:34<41:55,  1.92s/it, total_cost=$7.849125, processed=6576]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6577/7886 [04:35<37:17,  1.71s/it, total_cost=$7.850338, processed=6577]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6578/7886 [04:37<34:06,  1.56s/it, total_cost=$7.851560, processed=6578]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6579/7886 [04:38<31:31,  1.45s/it, total_cost=$7.852830, processed=6579]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6580/7886 [04:39<29:37,  1.36s/it, total_cost=$7.854035, processed=6580]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  83%|████████▎ | 6581/7886 [04:40<29:00,  1.33s/it, total_cost=$7.855150, processed=6581]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  83%|████████▎ | 6582/7886 [04:41<27:55,  1.29s/it, total_cost=$7.856335, processed=6582]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  83%|████████▎ | 6583/7886 [04:42<26:31,  1.22s/it, total_cost=$7.857410, processed=6583]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  83%|████████▎ | 6584/7886 [04:44<25:44,  1.19s/it, total_cost=$7.858490, processed=6584]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  84%|████████▎ | 6585/7886 [04:45<26:16,  1.21s/it, total_cost=$7.859628, processed=6585]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▎ | 6586/7886 [04:46<25:25,  1.17s/it, total_cost=$7.860823, processed=6586]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▎ | 6587/7886 [04:47<26:46,  1.24s/it, total_cost=$7.861990, processed=6587]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▎ | 6588/7886 [04:48<26:11,  1.21s/it, total_cost=$7.863435, processed=6588]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▎ | 6589/7886 [04:49<25:31,  1.18s/it, total_cost=$7.864603, processed=6589]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▎ | 6590/7886 [04:51<25:35,  1.19s/it, total_cost=$7.865790, processed=6590]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▎ | 6591/7886 [04:52<25:16,  1.17s/it, total_cost=$7.866893, processed=6591]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▎ | 6592/7886 [04:53<25:41,  1.19s/it, total_cost=$7.868140, processed=6592]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▎ | 6593/7886 [04:54<26:00,  1.21s/it, total_cost=$7.869298, processed=6593]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▎ | 6594/7886 [04:55<25:47,  1.20s/it, total_cost=$7.870388, processed=6594]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▎ | 6595/7886 [04:57<25:45,  1.20s/it, total_cost=$7.871558, processed=6595]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▎ | 6596/7886 [04:58<25:46,  1.20s/it, total_cost=$7.872705, processed=6596]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▎ | 6597/7886 [04:59<25:34,  1.19s/it, total_cost=$7.873958, processed=6597]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▎ | 6598/7886 [05:00<25:35,  1.19s/it, total_cost=$7.875130, processed=6598]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▎ | 6599/7886 [05:01<25:17,  1.18s/it, total_cost=$7.876300, processed=6599]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  84%|████████▎ | 6600/7886 [05:02<24:44,  1.15s/it, total_cost=$7.877498, processed=6600]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▎ | 6601/7886 [05:04<24:23,  1.14s/it, total_cost=$7.878525, processed=6601]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  84%|████████▎ | 6602/7886 [05:05<24:19,  1.14s/it, total_cost=$7.879635, processed=6602]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▎ | 6603/7886 [05:06<24:04,  1.13s/it, total_cost=$7.880820, processed=6603]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▎ | 6604/7886 [05:07<24:41,  1.16s/it, total_cost=$7.882120, processed=6604]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▍ | 6605/7886 [05:08<25:04,  1.17s/it, total_cost=$7.883353, processed=6605]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6606/7886 [05:10<26:23,  1.24s/it, total_cost=$7.884543, processed=6606]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6607/7886 [05:11<25:54,  1.22s/it, total_cost=$7.885753, processed=6607]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▍ | 6608/7886 [05:12<25:32,  1.20s/it, total_cost=$7.886803, processed=6608]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6609/7886 [05:13<25:10,  1.18s/it, total_cost=$7.887898, processed=6609]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6610/7886 [05:14<25:21,  1.19s/it, total_cost=$7.889003, processed=6610]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▍ | 6611/7886 [05:16<25:33,  1.20s/it, total_cost=$7.890068, processed=6611]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6612/7886 [05:17<25:11,  1.19s/it, total_cost=$7.891310, processed=6612]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6613/7886 [05:18<24:14,  1.14s/it, total_cost=$7.892455, processed=6613]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▍ | 6614/7886 [05:19<24:03,  1.13s/it, total_cost=$7.893598, processed=6614]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6615/7886 [05:20<23:42,  1.12s/it, total_cost=$7.894700, processed=6615]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6616/7886 [05:21<24:34,  1.16s/it, total_cost=$7.895940, processed=6616]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▍ | 6617/7886 [05:22<24:34,  1.16s/it, total_cost=$7.897060, processed=6617]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6618/7886 [05:23<24:14,  1.15s/it, total_cost=$7.898440, processed=6618]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6619/7886 [05:24<24:19,  1.15s/it, total_cost=$7.899533, processed=6619]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6620/7886 [05:26<23:33,  1.12s/it, total_cost=$7.900605, processed=6620]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6621/7886 [05:27<24:41,  1.17s/it, total_cost=$7.901740, processed=6621]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▍ | 6622/7886 [05:28<23:58,  1.14s/it, total_cost=$7.902875, processed=6622]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6623/7886 [05:29<23:49,  1.13s/it, total_cost=$7.904033, processed=6623]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6624/7886 [05:30<23:59,  1.14s/it, total_cost=$7.905125, processed=6624]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6625/7886 [05:31<23:40,  1.13s/it, total_cost=$7.906283, processed=6625]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6626/7886 [05:33<24:05,  1.15s/it, total_cost=$7.907475, processed=6626]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6627/7886 [05:34<25:03,  1.19s/it, total_cost=$7.908720, processed=6627]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6628/7886 [05:35<23:55,  1.14s/it, total_cost=$7.909818, processed=6628]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6629/7886 [05:36<24:29,  1.17s/it, total_cost=$7.910913, processed=6629]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  84%|████████▍ | 6630/7886 [05:37<24:56,  1.19s/it, total_cost=$7.912023, processed=6630]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  84%|████████▍ | 6631/7886 [05:38<24:17,  1.16s/it, total_cost=$7.913330, processed=6631]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6632/7886 [05:40<23:59,  1.15s/it, total_cost=$7.914508, processed=6632]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6633/7886 [05:41<24:07,  1.16s/it, total_cost=$7.915670, processed=6633]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6634/7886 [05:42<24:08,  1.16s/it, total_cost=$7.916818, processed=6634]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6635/7886 [05:43<23:23,  1.12s/it, total_cost=$7.918018, processed=6635]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6636/7886 [05:44<23:31,  1.13s/it, total_cost=$7.919080, processed=6636]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  84%|████████▍ | 6637/7886 [05:45<24:39,  1.18s/it, total_cost=$7.920245, processed=6637]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6638/7886 [05:47<24:26,  1.18s/it, total_cost=$7.921485, processed=6638]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6639/7886 [05:48<24:24,  1.17s/it, total_cost=$7.922610, processed=6639]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  84%|████████▍ | 6640/7886 [05:50<23:48,  1.15s/it, total_cost=$7.923755, processed=6640]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  84%|████████▍ | 6641/7886 [05:51<31:02,  1.50s/it, total_cost=$7.924875, processed=6641]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6642/7886 [05:53<30:43,  1.48s/it, total_cost=$7.925915, processed=6642]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6643/7886 [05:55<33:58,  1.64s/it, total_cost=$7.926998, processed=6643]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6644/7886 [05:56<33:14,  1.61s/it, total_cost=$7.928183, processed=6644]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6645/7886 [05:58<30:02,  1.45s/it, total_cost=$7.929378, processed=6645]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  84%|████████▍ | 6646/7886 [05:59<30:37,  1.48s/it, total_cost=$7.930500, processed=6646]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▍ | 6647/7886 [06:00<27:50,  1.35s/it, total_cost=$7.931596, processed=6647]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  84%|████████▍ | 6648/7886 [06:01<27:01,  1.31s/it, total_cost=$7.932708, processed=6648]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  84%|████████▍ | 6649/7886 [06:02<27:04,  1.31s/it, total_cost=$7.934348, processed=6649]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6650/7886 [06:03<26:01,  1.26s/it, total_cost=$7.935548, processed=6650]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▍ | 6651/7886 [06:05<25:28,  1.24s/it, total_cost=$7.936658, processed=6651]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6652/7886 [06:06<24:49,  1.21s/it, total_cost=$7.937940, processed=6652]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6653/7886 [06:07<24:20,  1.18s/it, total_cost=$7.939123, processed=6653]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6654/7886 [06:08<23:46,  1.16s/it, total_cost=$7.940403, processed=6654]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▍ | 6655/7886 [06:09<23:32,  1.15s/it, total_cost=$7.941566, processed=6655]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  84%|████████▍ | 6656/7886 [06:10<23:39,  1.15s/it, total_cost=$7.942768, processed=6656]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  84%|████████▍ | 6657/7886 [06:12<24:03,  1.17s/it, total_cost=$7.943936, processed=6657]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  84%|████████▍ | 6658/7886 [06:13<23:34,  1.15s/it, total_cost=$7.945115, processed=6658]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6659/7886 [06:14<23:22,  1.14s/it, total_cost=$7.946195, processed=6659]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  84%|████████▍ | 6660/7886 [06:15<23:21,  1.14s/it, total_cost=$7.947278, processed=6660]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  84%|████████▍ | 6661/7886 [06:16<24:06,  1.18s/it, total_cost=$7.948475, processed=6661]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  84%|████████▍ | 6662/7886 [06:17<24:03,  1.18s/it, total_cost=$7.949708, processed=6662]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  84%|████████▍ | 6663/7886 [06:18<23:05,  1.13s/it, total_cost=$7.950823, processed=6663]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  85%|████████▍ | 6664/7886 [06:20<23:52,  1.17s/it, total_cost=$7.952141, processed=6664]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▍ | 6665/7886 [06:21<23:04,  1.13s/it, total_cost=$7.953198, processed=6665]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6666/7886 [06:23<27:49,  1.37s/it, total_cost=$7.954313, processed=6666]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6667/7886 [06:24<27:21,  1.35s/it, total_cost=$7.955526, processed=6667]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▍ | 6668/7886 [06:25<26:11,  1.29s/it, total_cost=$7.956816, processed=6668]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6669/7886 [06:26<24:38,  1.21s/it, total_cost=$7.957923, processed=6669]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  85%|████████▍ | 6670/7886 [06:27<24:53,  1.23s/it, total_cost=$7.959083, processed=6670]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▍ | 6671/7886 [06:29<24:19,  1.20s/it, total_cost=$7.960366, processed=6671]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▍ | 6672/7886 [06:30<24:32,  1.21s/it, total_cost=$7.961586, processed=6672]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▍ | 6673/7886 [06:31<26:52,  1.33s/it, total_cost=$7.962776, processed=6673]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6674/7886 [06:33<26:10,  1.30s/it, total_cost=$7.963878, processed=6674]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▍ | 6675/7886 [06:34<25:27,  1.26s/it, total_cost=$7.965138, processed=6675]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6676/7886 [06:35<25:37,  1.27s/it, total_cost=$7.966208, processed=6676]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▍ | 6677/7886 [06:36<27:16,  1.35s/it, total_cost=$7.967351, processed=6677]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  85%|████████▍ | 6678/7886 [06:38<25:46,  1.28s/it, total_cost=$7.968433, processed=6678]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▍ | 6679/7886 [06:39<25:49,  1.28s/it, total_cost=$7.969541, processed=6679]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▍ | 6680/7886 [06:40<25:47,  1.28s/it, total_cost=$7.970708, processed=6680]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▍ | 6681/7886 [06:41<24:39,  1.23s/it, total_cost=$7.971808, processed=6681]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▍ | 6682/7886 [06:43<25:39,  1.28s/it, total_cost=$7.972956, processed=6682]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▍ | 6683/7886 [06:44<24:52,  1.24s/it, total_cost=$7.974058, processed=6683]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▍ | 6684/7886 [06:45<24:29,  1.22s/it, total_cost=$7.976063, processed=6684]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▍ | 6685/7886 [06:46<24:26,  1.22s/it, total_cost=$7.977321, processed=6685]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▍ | 6686/7886 [06:47<23:43,  1.19s/it, total_cost=$7.978426, processed=6686]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▍ | 6687/7886 [06:49<24:08,  1.21s/it, total_cost=$7.979731, processed=6687]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▍ | 6688/7886 [06:50<23:28,  1.18s/it, total_cost=$7.980851, processed=6688]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▍ | 6689/7886 [06:51<23:27,  1.18s/it, total_cost=$7.982028, processed=6689]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  85%|████████▍ | 6690/7886 [06:52<24:10,  1.21s/it, total_cost=$7.983303, processed=6690]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  85%|████████▍ | 6691/7886 [06:53<23:49,  1.20s/it, total_cost=$7.984433, processed=6691]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6692/7886 [06:55<23:50,  1.20s/it, total_cost=$7.985613, processed=6692]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  85%|████████▍ | 6693/7886 [06:56<23:16,  1.17s/it, total_cost=$7.986693, processed=6693]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▍ | 6694/7886 [06:57<23:35,  1.19s/it, total_cost=$7.987871, processed=6694]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  85%|████████▍ | 6695/7886 [06:58<23:28,  1.18s/it, total_cost=$7.989101, processed=6695]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  85%|████████▍ | 6696/7886 [06:59<24:00,  1.21s/it, total_cost=$7.990268, processed=6696]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6697/7886 [07:01<24:17,  1.23s/it, total_cost=$7.991393, processed=6697]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▍ | 6698/7886 [07:02<23:55,  1.21s/it, total_cost=$7.992586, processed=6698]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  85%|████████▍ | 6699/7886 [07:03<24:11,  1.22s/it, total_cost=$7.993671, processed=6699]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6700/7886 [07:04<23:28,  1.19s/it, total_cost=$7.994851, processed=6700]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▍ | 6701/7886 [07:05<23:17,  1.18s/it, total_cost=$7.996018, processed=6701]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  85%|████████▍ | 6702/7886 [07:07<24:08,  1.22s/it, total_cost=$7.997221, processed=6702]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▍ | 6703/7886 [07:08<24:04,  1.22s/it, total_cost=$7.998526, processed=6703]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▌ | 6704/7886 [07:09<24:21,  1.24s/it, total_cost=$7.999738, processed=6704]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▌ | 6705/7886 [07:10<23:53,  1.21s/it, total_cost=$8.000926, processed=6705]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▌ | 6706/7886 [07:12<24:04,  1.22s/it, total_cost=$8.002093, processed=6706]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▌ | 6707/7886 [07:13<24:00,  1.22s/it, total_cost=$8.003258, processed=6707]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  85%|████████▌ | 6708/7886 [07:14<23:11,  1.18s/it, total_cost=$8.004498, processed=6708]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  85%|████████▌ | 6709/7886 [07:15<23:56,  1.22s/it, total_cost=$8.005723, processed=6709]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▌ | 6710/7886 [07:16<22:35,  1.15s/it, total_cost=$8.006783, processed=6710]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▌ | 6711/7886 [07:17<23:04,  1.18s/it, total_cost=$8.007908, processed=6711]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▌ | 6712/7886 [07:19<22:49,  1.17s/it, total_cost=$8.009058, processed=6712]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  85%|████████▌ | 6713/7886 [07:20<22:46,  1.16s/it, total_cost=$8.010173, processed=6713]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▌ | 6714/7886 [07:21<23:19,  1.19s/it, total_cost=$8.011398, processed=6714]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  85%|████████▌ | 6715/7886 [07:22<24:39,  1.26s/it, total_cost=$8.012773, processed=6715]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▌ | 6716/7886 [07:24<24:58,  1.28s/it, total_cost=$8.013958, processed=6716]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▌ | 6717/7886 [07:25<23:45,  1.22s/it, total_cost=$8.015098, processed=6717]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▌ | 6718/7886 [07:26<27:01,  1.39s/it, total_cost=$8.016201, processed=6718]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▌ | 6719/7886 [07:28<25:35,  1.32s/it, total_cost=$8.017313, processed=6719]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  85%|████████▌ | 6720/7886 [07:29<24:30,  1.26s/it, total_cost=$8.018435, processed=6720]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  85%|████████▌ | 6721/7886 [07:30<26:16,  1.35s/it, total_cost=$8.019575, processed=6721]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  85%|████████▌ | 6722/7886 [07:32<25:48,  1.33s/it, total_cost=$8.020680, processed=6722]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▌ | 6723/7886 [07:33<28:08,  1.45s/it, total_cost=$8.021930, processed=6723]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  85%|████████▌ | 6724/7886 [07:35<26:25,  1.36s/it, total_cost=$8.023231, processed=6724]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▌ | 6725/7886 [07:36<25:17,  1.31s/it, total_cost=$8.024406, processed=6725]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▌ | 6726/7886 [07:37<24:13,  1.25s/it, total_cost=$8.025553, processed=6726]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▌ | 6727/7886 [07:38<23:59,  1.24s/it, total_cost=$8.026625, processed=6727]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▌ | 6728/7886 [07:39<23:41,  1.23s/it, total_cost=$8.027763, processed=6728]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▌ | 6729/7886 [07:40<23:05,  1.20s/it, total_cost=$8.028863, processed=6729]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  85%|████████▌ | 6730/7886 [07:42<22:17,  1.16s/it, total_cost=$8.029868, processed=6730]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  85%|████████▌ | 6731/7886 [07:43<22:41,  1.18s/it, total_cost=$8.031048, processed=6731]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▌ | 6732/7886 [07:44<22:59,  1.20s/it, total_cost=$8.032195, processed=6732]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  85%|████████▌ | 6733/7886 [07:45<22:07,  1.15s/it, total_cost=$8.033288, processed=6733]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  85%|████████▌ | 6734/7886 [07:46<21:44,  1.13s/it, total_cost=$8.034365, processed=6734]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  85%|████████▌ | 6735/7886 [07:47<21:44,  1.13s/it, total_cost=$8.035498, processed=6735]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  85%|████████▌ | 6736/7886 [07:49<23:09,  1.21s/it, total_cost=$8.036735, processed=6736]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▌ | 6737/7886 [07:50<23:14,  1.21s/it, total_cost=$8.037955, processed=6737]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  85%|████████▌ | 6738/7886 [07:51<23:11,  1.21s/it, total_cost=$8.039123, processed=6738]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▌ | 6739/7886 [07:52<22:24,  1.17s/it, total_cost=$8.040260, processed=6739]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▌ | 6740/7886 [07:53<22:08,  1.16s/it, total_cost=$8.041470, processed=6740]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  85%|████████▌ | 6741/7886 [07:54<22:01,  1.15s/it, total_cost=$8.042590, processed=6741]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  85%|████████▌ | 6742/7886 [07:56<22:19,  1.17s/it, total_cost=$8.043785, processed=6742]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6743/7886 [07:57<22:37,  1.19s/it, total_cost=$8.044945, processed=6743]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6744/7886 [07:58<22:08,  1.16s/it, total_cost=$8.046073, processed=6744]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6745/7886 [08:00<22:49,  1.20s/it, total_cost=$8.047313, processed=6745]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▌ | 6746/7886 [08:01<24:29,  1.29s/it, total_cost=$8.048653, processed=6746]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6747/7886 [08:02<24:01,  1.27s/it, total_cost=$8.049853, processed=6747]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6748/7886 [08:03<23:50,  1.26s/it, total_cost=$8.051111, processed=6748]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  86%|████████▌ | 6749/7886 [08:05<24:58,  1.32s/it, total_cost=$8.052461, processed=6749]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▌ | 6750/7886 [08:06<24:57,  1.32s/it, total_cost=$8.053716, processed=6750]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6751/7886 [08:07<22:59,  1.22s/it, total_cost=$8.054838, processed=6751]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6752/7886 [08:09<23:28,  1.24s/it, total_cost=$8.055995, processed=6752]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6753/7886 [08:10<26:18,  1.39s/it, total_cost=$8.057308, processed=6753]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6754/7886 [08:11<24:24,  1.29s/it, total_cost=$8.058535, processed=6754]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6755/7886 [08:12<23:22,  1.24s/it, total_cost=$8.059725, processed=6755]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  86%|████████▌ | 6756/7886 [08:14<23:28,  1.25s/it, total_cost=$8.060945, processed=6756]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6757/7886 [08:15<23:47,  1.26s/it, total_cost=$8.062343, processed=6757]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  86%|████████▌ | 6758/7886 [08:16<23:25,  1.25s/it, total_cost=$8.063510, processed=6758]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6759/7886 [08:17<22:48,  1.21s/it, total_cost=$8.064705, processed=6759]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6760/7886 [08:18<22:23,  1.19s/it, total_cost=$8.065765, processed=6760]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▌ | 6761/7886 [08:20<22:46,  1.21s/it, total_cost=$8.066913, processed=6761]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6762/7886 [08:21<24:11,  1.29s/it, total_cost=$8.068098, processed=6762]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  86%|████████▌ | 6763/7886 [08:22<23:15,  1.24s/it, total_cost=$8.069235, processed=6763]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  86%|████████▌ | 6764/7886 [08:23<22:35,  1.21s/it, total_cost=$8.070480, processed=6764]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  86%|████████▌ | 6765/7886 [08:24<21:52,  1.17s/it, total_cost=$8.071638, processed=6765]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6766/7886 [08:25<21:43,  1.16s/it, total_cost=$8.072908, processed=6766]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6767/7886 [08:27<22:22,  1.20s/it, total_cost=$8.074480, processed=6767]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6768/7886 [08:28<22:05,  1.19s/it, total_cost=$8.075570, processed=6768]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▌ | 6769/7886 [08:29<22:16,  1.20s/it, total_cost=$8.076800, processed=6769]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6770/7886 [08:30<21:38,  1.16s/it, total_cost=$8.077993, processed=6770]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  86%|████████▌ | 6771/7886 [08:31<21:39,  1.17s/it, total_cost=$8.079128, processed=6771]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  86%|████████▌ | 6772/7886 [08:33<22:13,  1.20s/it, total_cost=$8.080445, processed=6772]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  86%|████████▌ | 6773/7886 [08:34<22:00,  1.19s/it, total_cost=$8.081605, processed=6773]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6774/7886 [08:35<21:14,  1.15s/it, total_cost=$8.082710, processed=6774]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▌ | 6775/7886 [08:38<27:34,  1.49s/it, total_cost=$8.083845, processed=6775]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  86%|████████▌ | 6776/7886 [08:39<30:29,  1.65s/it, total_cost=$8.084933, processed=6776]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6777/7886 [08:40<27:30,  1.49s/it, total_cost=$8.086025, processed=6777]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  86%|████████▌ | 6778/7886 [08:41<25:40,  1.39s/it, total_cost=$8.087103, processed=6778]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▌ | 6779/7886 [08:43<24:11,  1.31s/it, total_cost=$8.088328, processed=6779]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6780/7886 [08:44<23:10,  1.26s/it, total_cost=$8.089468, processed=6780]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6781/7886 [08:45<22:17,  1.21s/it, total_cost=$8.090610, processed=6781]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  86%|████████▌ | 6782/7886 [08:46<22:26,  1.22s/it, total_cost=$8.091843, processed=6782]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6783/7886 [08:47<22:05,  1.20s/it, total_cost=$8.092968, processed=6783]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▌ | 6784/7886 [08:48<21:29,  1.17s/it, total_cost=$8.094160, processed=6784]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▌ | 6785/7886 [08:49<21:09,  1.15s/it, total_cost=$8.095311, processed=6785]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6786/7886 [08:50<20:45,  1.13s/it, total_cost=$8.096445, processed=6786]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▌ | 6787/7886 [08:52<21:12,  1.16s/it, total_cost=$8.097691, processed=6787]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▌ | 6788/7886 [08:53<21:15,  1.16s/it, total_cost=$8.098943, processed=6788]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  86%|████████▌ | 6789/7886 [08:54<20:48,  1.14s/it, total_cost=$8.100133, processed=6789]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6790/7886 [08:55<20:56,  1.15s/it, total_cost=$8.101250, processed=6790]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  86%|████████▌ | 6791/7886 [08:56<21:12,  1.16s/it, total_cost=$8.102438, processed=6791]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  86%|████████▌ | 6792/7886 [08:58<21:48,  1.20s/it, total_cost=$8.103553, processed=6792]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▌ | 6793/7886 [08:59<21:41,  1.19s/it, total_cost=$8.104698, processed=6793]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6794/7886 [09:00<21:19,  1.17s/it, total_cost=$8.105800, processed=6794]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▌ | 6795/7886 [09:01<21:07,  1.16s/it, total_cost=$8.106935, processed=6795]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▌ | 6796/7886 [09:03<21:09,  1.16s/it, total_cost=$8.108075, processed=6796]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6797/7886 [09:04<22:55,  1.26s/it, total_cost=$8.109223, processed=6797]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▌ | 6798/7886 [09:05<22:24,  1.24s/it, total_cost=$8.110340, processed=6798]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▌ | 6799/7886 [09:06<22:00,  1.21s/it, total_cost=$8.111560, processed=6799]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▌ | 6800/7886 [09:07<22:18,  1.23s/it, total_cost=$8.112795, processed=6800]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▌ | 6801/7886 [09:09<22:34,  1.25s/it, total_cost=$8.114010, processed=6801]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  86%|████████▋ | 6802/7886 [09:10<23:14,  1.29s/it, total_cost=$8.115440, processed=6802]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▋ | 6803/7886 [09:11<22:48,  1.26s/it, total_cost=$8.116683, processed=6803]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▋ | 6804/7886 [09:12<22:13,  1.23s/it, total_cost=$8.117700, processed=6804]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▋ | 6805/7886 [09:13<20:55,  1.16s/it, total_cost=$8.118785, processed=6805]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▋ | 6806/7886 [09:15<21:43,  1.21s/it, total_cost=$8.119960, processed=6806]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▋ | 6807/7886 [09:16<21:42,  1.21s/it, total_cost=$8.121035, processed=6807]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  86%|████████▋ | 6808/7886 [09:17<21:23,  1.19s/it, total_cost=$8.122180, processed=6808]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▋ | 6809/7886 [09:18<21:19,  1.19s/it, total_cost=$8.123365, processed=6809]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  86%|████████▋ | 6810/7886 [09:19<21:27,  1.20s/it, total_cost=$8.124450, processed=6810]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  86%|████████▋ | 6811/7886 [09:21<21:16,  1.19s/it, total_cost=$8.125580, processed=6811]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▋ | 6812/7886 [09:22<21:23,  1.19s/it, total_cost=$8.126690, processed=6812]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▋ | 6813/7886 [09:23<20:56,  1.17s/it, total_cost=$8.127948, processed=6813]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▋ | 6814/7886 [09:24<20:18,  1.14s/it, total_cost=$8.129090, processed=6814]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  86%|████████▋ | 6815/7886 [09:25<20:43,  1.16s/it, total_cost=$8.130358, processed=6815]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▋ | 6816/7886 [09:27<21:34,  1.21s/it, total_cost=$8.131585, processed=6816]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  86%|████████▋ | 6817/7886 [09:28<21:29,  1.21s/it, total_cost=$8.132760, processed=6817]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  86%|████████▋ | 6818/7886 [09:29<21:37,  1.21s/it, total_cost=$8.133953, processed=6818]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  86%|████████▋ | 6819/7886 [09:30<21:00,  1.18s/it, total_cost=$8.135080, processed=6819]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  86%|████████▋ | 6820/7886 [09:31<20:46,  1.17s/it, total_cost=$8.136220, processed=6820]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  86%|████████▋ | 6821/7886 [09:32<20:35,  1.16s/it, total_cost=$8.137295, processed=6821]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6822/7886 [09:33<20:09,  1.14s/it, total_cost=$8.138448, processed=6822]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  87%|████████▋ | 6823/7886 [09:35<21:00,  1.19s/it, total_cost=$8.139645, processed=6823]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  87%|████████▋ | 6824/7886 [09:36<20:44,  1.17s/it, total_cost=$8.140770, processed=6824]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  87%|████████▋ | 6825/7886 [09:37<20:40,  1.17s/it, total_cost=$8.141933, processed=6825]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6826/7886 [09:38<20:12,  1.14s/it, total_cost=$8.143030, processed=6826]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  87%|████████▋ | 6827/7886 [09:39<20:59,  1.19s/it, total_cost=$8.144155, processed=6827]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6828/7886 [09:40<20:41,  1.17s/it, total_cost=$8.145238, processed=6828]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  87%|████████▋ | 6829/7886 [09:42<20:21,  1.16s/it, total_cost=$8.146303, processed=6829]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6830/7886 [09:44<24:31,  1.39s/it, total_cost=$8.147430, processed=6830]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6831/7886 [09:46<32:26,  1.84s/it, total_cost=$8.148655, processed=6831]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6832/7886 [09:48<28:30,  1.62s/it, total_cost=$8.149725, processed=6832]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6833/7886 [09:49<25:48,  1.47s/it, total_cost=$8.150883, processed=6833]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6834/7886 [09:50<24:02,  1.37s/it, total_cost=$8.152028, processed=6834]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6835/7886 [09:51<22:48,  1.30s/it, total_cost=$8.153150, processed=6835]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6836/7886 [09:52<23:11,  1.32s/it, total_cost=$8.154300, processed=6836]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6837/7886 [09:53<22:24,  1.28s/it, total_cost=$8.155533, processed=6837]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6838/7886 [09:55<21:20,  1.22s/it, total_cost=$8.156660, processed=6838]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6839/7886 [09:56<20:56,  1.20s/it, total_cost=$8.157828, processed=6839]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6840/7886 [09:57<20:41,  1.19s/it, total_cost=$8.158955, processed=6840]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6841/7886 [09:58<20:41,  1.19s/it, total_cost=$8.160123, processed=6841]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6842/7886 [09:59<20:08,  1.16s/it, total_cost=$8.161225, processed=6842]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  87%|████████▋ | 6843/7886 [10:00<20:21,  1.17s/it, total_cost=$8.162435, processed=6843]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6844/7886 [10:01<19:56,  1.15s/it, total_cost=$8.163685, processed=6844]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  87%|████████▋ | 6845/7886 [10:03<20:18,  1.17s/it, total_cost=$8.164753, processed=6845]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6846/7886 [10:04<19:46,  1.14s/it, total_cost=$8.165875, processed=6846]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6847/7886 [10:05<19:41,  1.14s/it, total_cost=$8.167000, processed=6847]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  87%|████████▋ | 6848/7886 [10:06<19:27,  1.12s/it, total_cost=$8.168355, processed=6848]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6849/7886 [10:07<19:45,  1.14s/it, total_cost=$8.169575, processed=6849]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6850/7886 [10:08<19:47,  1.15s/it, total_cost=$8.170660, processed=6850]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6851/7886 [10:10<19:38,  1.14s/it, total_cost=$8.171740, processed=6851]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6852/7886 [10:11<19:57,  1.16s/it, total_cost=$8.172945, processed=6852]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6853/7886 [10:12<19:41,  1.14s/it, total_cost=$8.174038, processed=6853]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6854/7886 [10:13<19:33,  1.14s/it, total_cost=$8.175163, processed=6854]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6855/7886 [10:14<20:13,  1.18s/it, total_cost=$8.176305, processed=6855]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6856/7886 [10:15<19:50,  1.16s/it, total_cost=$8.177456, processed=6856]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6857/7886 [10:17<20:34,  1.20s/it, total_cost=$8.178691, processed=6857]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6858/7886 [10:18<20:26,  1.19s/it, total_cost=$8.179761, processed=6858]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  87%|████████▋ | 6859/7886 [10:19<20:14,  1.18s/it, total_cost=$8.180886, processed=6859]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6860/7886 [10:20<20:13,  1.18s/it, total_cost=$8.181940, processed=6860]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  87%|████████▋ | 6861/7886 [10:21<19:34,  1.15s/it, total_cost=$8.183105, processed=6861]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6862/7886 [10:22<19:13,  1.13s/it, total_cost=$8.184266, processed=6862]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6863/7886 [10:23<19:02,  1.12s/it, total_cost=$8.185443, processed=6863]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6864/7886 [10:24<19:14,  1.13s/it, total_cost=$8.186691, processed=6864]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  87%|████████▋ | 6865/7886 [10:26<19:06,  1.12s/it, total_cost=$8.187723, processed=6865]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  87%|████████▋ | 6866/7886 [10:27<19:00,  1.12s/it, total_cost=$8.188931, processed=6866]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6867/7886 [10:28<19:15,  1.13s/it, total_cost=$8.190026, processed=6867]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  87%|████████▋ | 6868/7886 [10:29<19:30,  1.15s/it, total_cost=$8.191236, processed=6868]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  87%|████████▋ | 6869/7886 [10:30<19:04,  1.13s/it, total_cost=$8.192291, processed=6869]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6870/7886 [10:31<19:17,  1.14s/it, total_cost=$8.193443, processed=6870]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6871/7886 [10:33<19:19,  1.14s/it, total_cost=$8.194555, processed=6871]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6872/7886 [10:34<19:54,  1.18s/it, total_cost=$8.195778, processed=6872]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6873/7886 [10:35<19:51,  1.18s/it, total_cost=$8.196881, processed=6873]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6874/7886 [10:36<19:35,  1.16s/it, total_cost=$8.198116, processed=6874]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6875/7886 [10:37<19:50,  1.18s/it, total_cost=$8.199345, processed=6875]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  87%|████████▋ | 6876/7886 [10:38<19:48,  1.18s/it, total_cost=$8.200630, processed=6876]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6877/7886 [10:39<18:38,  1.11s/it, total_cost=$8.201690, processed=6877]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6878/7886 [10:41<19:20,  1.15s/it, total_cost=$8.202958, processed=6878]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6879/7886 [10:42<19:14,  1.15s/it, total_cost=$8.204101, processed=6879]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6880/7886 [10:43<20:24,  1.22s/it, total_cost=$8.205321, processed=6880]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  87%|████████▋ | 6881/7886 [10:44<20:12,  1.21s/it, total_cost=$8.206628, processed=6881]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6882/7886 [10:45<19:50,  1.19s/it, total_cost=$8.207790, processed=6882]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6883/7886 [10:47<19:25,  1.16s/it, total_cost=$8.208873, processed=6883]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6884/7886 [10:48<19:31,  1.17s/it, total_cost=$8.210071, processed=6884]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6885/7886 [10:49<20:04,  1.20s/it, total_cost=$8.211310, processed=6885]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6886/7886 [10:50<19:49,  1.19s/it, total_cost=$8.212606, processed=6886]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  87%|████████▋ | 6887/7886 [10:51<19:42,  1.18s/it, total_cost=$8.213768, processed=6887]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  87%|████████▋ | 6888/7886 [10:52<19:31,  1.17s/it, total_cost=$8.214861, processed=6888]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6889/7886 [10:54<19:22,  1.17s/it, total_cost=$8.216041, processed=6889]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  87%|████████▋ | 6890/7886 [10:55<20:12,  1.22s/it, total_cost=$8.217196, processed=6890]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6891/7886 [10:56<20:57,  1.26s/it, total_cost=$8.218521, processed=6891]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  87%|████████▋ | 6892/7886 [10:58<21:27,  1.30s/it, total_cost=$8.219798, processed=6892]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  87%|████████▋ | 6893/7886 [11:01<20:26,  1.24s/it, total_cost=$8.220991, processed=6893]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6894/7886 [11:02<31:28,  1.90s/it, total_cost=$8.222291, processed=6894]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6895/7886 [11:03<27:24,  1.66s/it, total_cost=$8.223398, processed=6895]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  87%|████████▋ | 6896/7886 [11:04<24:28,  1.48s/it, total_cost=$8.224521, processed=6896]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  87%|████████▋ | 6897/7886 [11:07<29:18,  1.78s/it, total_cost=$8.225726, processed=6897]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6898/7886 [11:08<25:57,  1.58s/it, total_cost=$8.227441, processed=6898]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  87%|████████▋ | 6899/7886 [11:09<24:25,  1.48s/it, total_cost=$8.228663, processed=6899]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  87%|████████▋ | 6900/7886 [11:10<22:38,  1.38s/it, total_cost=$8.229831, processed=6900]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6901/7886 [11:12<21:00,  1.28s/it, total_cost=$8.230963, processed=6901]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6902/7886 [11:13<20:59,  1.28s/it, total_cost=$8.232163, processed=6902]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6903/7886 [11:14<20:47,  1.27s/it, total_cost=$8.233448, processed=6903]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  88%|████████▊ | 6904/7886 [11:15<21:15,  1.30s/it, total_cost=$8.234686, processed=6904]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  88%|████████▊ | 6905/7886 [11:16<20:22,  1.25s/it, total_cost=$8.235876, processed=6905]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6906/7886 [11:18<19:59,  1.22s/it, total_cost=$8.237046, processed=6906]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6907/7886 [11:19<19:42,  1.21s/it, total_cost=$8.238253, processed=6907]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6908/7886 [11:20<21:41,  1.33s/it, total_cost=$8.239418, processed=6908]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6909/7886 [11:22<21:15,  1.31s/it, total_cost=$8.240638, processed=6909]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6910/7886 [11:23<20:51,  1.28s/it, total_cost=$8.241801, processed=6910]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  88%|████████▊ | 6911/7886 [11:24<20:40,  1.27s/it, total_cost=$8.243008, processed=6911]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6912/7886 [11:25<20:03,  1.24s/it, total_cost=$8.244306, processed=6912]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  88%|████████▊ | 6913/7886 [11:26<19:37,  1.21s/it, total_cost=$8.245458, processed=6913]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6914/7886 [11:28<20:03,  1.24s/it, total_cost=$8.246788, processed=6914]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6915/7886 [11:29<20:40,  1.28s/it, total_cost=$8.248098, processed=6915]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6916/7886 [11:30<20:59,  1.30s/it, total_cost=$8.249398, processed=6916]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6917/7886 [11:32<19:53,  1.23s/it, total_cost=$8.250581, processed=6917]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6918/7886 [11:33<19:57,  1.24s/it, total_cost=$8.251821, processed=6918]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6919/7886 [11:34<20:08,  1.25s/it, total_cost=$8.253001, processed=6919]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6920/7886 [11:35<20:29,  1.27s/it, total_cost=$8.254501, processed=6920]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6921/7886 [11:37<20:05,  1.25s/it, total_cost=$8.255828, processed=6921]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6922/7886 [11:38<19:22,  1.21s/it, total_cost=$8.256948, processed=6922]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6923/7886 [11:39<19:46,  1.23s/it, total_cost=$8.258121, processed=6923]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  88%|████████▊ | 6924/7886 [11:40<20:02,  1.25s/it, total_cost=$8.259386, processed=6924]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6925/7886 [11:42<20:05,  1.25s/it, total_cost=$8.260558, processed=6925]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  88%|████████▊ | 6926/7886 [11:43<19:45,  1.24s/it, total_cost=$8.261828, processed=6926]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6927/7886 [11:44<19:10,  1.20s/it, total_cost=$8.263068, processed=6927]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6928/7886 [11:45<20:15,  1.27s/it, total_cost=$8.264300, processed=6928]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6929/7886 [11:46<19:33,  1.23s/it, total_cost=$8.265538, processed=6929]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6930/7886 [11:47<18:46,  1.18s/it, total_cost=$8.266768, processed=6930]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  88%|████████▊ | 6931/7886 [11:49<18:37,  1.17s/it, total_cost=$8.267880, processed=6931]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6932/7886 [11:50<18:24,  1.16s/it, total_cost=$8.269053, processed=6932]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6933/7886 [11:51<20:14,  1.27s/it, total_cost=$8.270425, processed=6933]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6934/7886 [11:53<19:41,  1.24s/it, total_cost=$8.271673, processed=6934]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6935/7886 [11:54<20:25,  1.29s/it, total_cost=$8.273058, processed=6935]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6936/7886 [11:55<19:49,  1.25s/it, total_cost=$8.274200, processed=6936]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6937/7886 [11:56<19:42,  1.25s/it, total_cost=$8.275440, processed=6937]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  88%|████████▊ | 6938/7886 [11:58<19:27,  1.23s/it, total_cost=$8.276628, processed=6938]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6939/7886 [11:59<19:55,  1.26s/it, total_cost=$8.277820, processed=6939]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6940/7886 [12:00<19:59,  1.27s/it, total_cost=$8.279018, processed=6940]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6941/7886 [12:01<19:34,  1.24s/it, total_cost=$8.280343, processed=6941]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6942/7886 [12:03<19:19,  1.23s/it, total_cost=$8.281513, processed=6942]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6943/7886 [12:04<20:38,  1.31s/it, total_cost=$8.282743, processed=6943]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6944/7886 [12:06<20:54,  1.33s/it, total_cost=$8.283988, processed=6944]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  88%|████████▊ | 6945/7886 [12:07<21:41,  1.38s/it, total_cost=$8.285143, processed=6945]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6946/7886 [12:09<22:53,  1.46s/it, total_cost=$8.286328, processed=6946]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6947/7886 [12:10<22:37,  1.45s/it, total_cost=$8.287708, processed=6947]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6948/7886 [12:12<23:35,  1.51s/it, total_cost=$8.288838, processed=6948]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6949/7886 [12:14<22:29,  1.44s/it, total_cost=$8.290150, processed=6949]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  88%|████████▊ | 6950/7886 [12:15<25:18,  1.62s/it, total_cost=$8.291415, processed=6950]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6951/7886 [12:16<23:16,  1.49s/it, total_cost=$8.292703, processed=6951]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6952/7886 [12:18<23:08,  1.49s/it, total_cost=$8.293985, processed=6952]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6953/7886 [12:19<22:12,  1.43s/it, total_cost=$8.295473, processed=6953]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6954/7886 [12:20<21:33,  1.39s/it, total_cost=$8.296598, processed=6954]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  88%|████████▊ | 6955/7886 [12:21<20:07,  1.30s/it, total_cost=$8.297773, processed=6955]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6956/7886 [12:22<19:03,  1.23s/it, total_cost=$8.298933, processed=6956]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6957/7886 [12:23<18:53,  1.22s/it, total_cost=$8.300135, processed=6957]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6958/7886 [12:25<18:43,  1.21s/it, total_cost=$8.301288, processed=6958]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6959/7886 [12:26<18:43,  1.21s/it, total_cost=$8.302498, processed=6959]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6960/7886 [12:27<18:34,  1.20s/it, total_cost=$8.303715, processed=6960]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6961/7886 [12:28<18:18,  1.19s/it, total_cost=$8.304923, processed=6961]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6962/7886 [12:29<18:00,  1.17s/it, total_cost=$8.306075, processed=6962]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6963/7886 [12:31<18:37,  1.21s/it, total_cost=$8.307228, processed=6963]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6964/7886 [12:32<18:29,  1.20s/it, total_cost=$8.308463, processed=6964]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  88%|████████▊ | 6965/7886 [12:34<24:07,  1.57s/it, total_cost=$8.309765, processed=6965]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6966/7886 [12:36<23:23,  1.53s/it, total_cost=$8.311088, processed=6966]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6967/7886 [12:37<24:26,  1.60s/it, total_cost=$8.312453, processed=6967]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6968/7886 [12:39<22:52,  1.50s/it, total_cost=$8.313695, processed=6968]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6969/7886 [12:40<21:19,  1.40s/it, total_cost=$8.314930, processed=6969]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  88%|████████▊ | 6970/7886 [12:41<19:43,  1.29s/it, total_cost=$8.316053, processed=6970]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  88%|████████▊ | 6971/7886 [12:42<19:36,  1.29s/it, total_cost=$8.317343, processed=6971]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  88%|████████▊ | 6972/7886 [12:44<19:55,  1.31s/it, total_cost=$8.318530, processed=6972]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  88%|████████▊ | 6973/7886 [12:45<19:07,  1.26s/it, total_cost=$8.319683, processed=6973]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  88%|████████▊ | 6974/7886 [12:46<18:42,  1.23s/it, total_cost=$8.320980, processed=6974]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6975/7886 [12:47<18:13,  1.20s/it, total_cost=$8.322238, processed=6975]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  88%|████████▊ | 6976/7886 [12:48<17:49,  1.17s/it, total_cost=$8.323328, processed=6976]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  88%|████████▊ | 6977/7886 [12:50<22:42,  1.50s/it, total_cost=$8.324625, processed=6977]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  88%|████████▊ | 6978/7886 [12:51<20:42,  1.37s/it, total_cost=$8.325888, processed=6978]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  88%|████████▊ | 6979/7886 [12:53<19:52,  1.32s/it, total_cost=$8.327118, processed=6979]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▊ | 6980/7886 [12:54<19:09,  1.27s/it, total_cost=$8.328408, processed=6980]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  89%|████████▊ | 6981/7886 [12:55<19:44,  1.31s/it, total_cost=$8.329973, processed=6981]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  89%|████████▊ | 6982/7886 [12:56<19:34,  1.30s/it, total_cost=$8.331118, processed=6982]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  89%|████████▊ | 6983/7886 [12:58<18:47,  1.25s/it, total_cost=$8.332288, processed=6983]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▊ | 6984/7886 [13:00<22:28,  1.49s/it, total_cost=$8.333525, processed=6984]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  89%|████████▊ | 6985/7886 [13:01<21:32,  1.43s/it, total_cost=$8.334813, processed=6985]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  89%|████████▊ | 6986/7886 [13:02<20:13,  1.35s/it, total_cost=$8.335920, processed=6986]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▊ | 6987/7886 [13:03<20:07,  1.34s/it, total_cost=$8.337160, processed=6987]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▊ | 6988/7886 [13:05<19:22,  1.29s/it, total_cost=$8.338365, processed=6988]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▊ | 6989/7886 [13:06<18:21,  1.23s/it, total_cost=$8.339438, processed=6989]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▊ | 6990/7886 [13:07<18:27,  1.24s/it, total_cost=$8.340585, processed=6990]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▊ | 6991/7886 [13:08<17:52,  1.20s/it, total_cost=$8.341733, processed=6991]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  89%|████████▊ | 6992/7886 [13:09<18:13,  1.22s/it, total_cost=$8.342983, processed=6992]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  89%|████████▊ | 6993/7886 [13:11<17:58,  1.21s/it, total_cost=$8.344278, processed=6993]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▊ | 6994/7886 [13:12<17:56,  1.21s/it, total_cost=$8.345578, processed=6994]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  89%|████████▊ | 6995/7886 [13:13<17:22,  1.17s/it, total_cost=$8.346773, processed=6995]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▊ | 6996/7886 [13:14<17:48,  1.20s/it, total_cost=$8.347955, processed=6996]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  89%|████████▊ | 6997/7886 [13:17<22:48,  1.54s/it, total_cost=$8.349135, processed=6997]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▊ | 6998/7886 [13:18<23:00,  1.55s/it, total_cost=$8.350380, processed=6998]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 6999/7886 [13:19<20:48,  1.41s/it, total_cost=$8.351513, processed=6999]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  89%|████████▉ | 7000/7886 [13:20<19:47,  1.34s/it, total_cost=$8.352658, processed=7000]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7001/7886 [13:22<19:36,  1.33s/it, total_cost=$8.353823, processed=7001]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  89%|████████▉ | 7002/7886 [13:23<18:47,  1.28s/it, total_cost=$8.355025, processed=7002]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7003/7886 [13:24<18:56,  1.29s/it, total_cost=$8.356385, processed=7003]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7004/7886 [13:25<18:01,  1.23s/it, total_cost=$8.357598, processed=7004]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7005/7886 [13:26<17:59,  1.23s/it, total_cost=$8.358823, processed=7005]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  89%|████████▉ | 7006/7886 [13:28<21:28,  1.46s/it, total_cost=$8.359955, processed=7006]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7007/7886 [13:29<20:08,  1.37s/it, total_cost=$8.361155, processed=7007]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7008/7886 [13:31<18:55,  1.29s/it, total_cost=$8.362253, processed=7008]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7009/7886 [13:32<18:28,  1.26s/it, total_cost=$8.363495, processed=7009]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  89%|████████▉ | 7010/7886 [13:33<17:37,  1.21s/it, total_cost=$8.364665, processed=7010]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7011/7886 [13:35<22:28,  1.54s/it, total_cost=$8.365778, processed=7011]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7012/7886 [13:36<20:43,  1.42s/it, total_cost=$8.367095, processed=7012]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▉ | 7013/7886 [13:38<19:36,  1.35s/it, total_cost=$8.368273, processed=7013]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7014/7886 [13:39<20:18,  1.40s/it, total_cost=$8.369470, processed=7014]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  89%|████████▉ | 7015/7886 [13:40<19:33,  1.35s/it, total_cost=$8.370718, processed=7015]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▉ | 7016/7886 [13:42<18:35,  1.28s/it, total_cost=$8.371848, processed=7016]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7017/7886 [13:43<21:08,  1.46s/it, total_cost=$8.373145, processed=7017]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7018/7886 [13:44<19:34,  1.35s/it, total_cost=$8.374288, processed=7018]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▉ | 7019/7886 [13:48<18:48,  1.30s/it, total_cost=$8.375505, processed=7019]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  89%|████████▉ | 7020/7886 [13:50<30:06,  2.09s/it, total_cost=$8.376750, processed=7020]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7021/7886 [13:52<32:08,  2.23s/it, total_cost=$8.377983, processed=7021]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▉ | 7022/7886 [13:54<28:32,  1.98s/it, total_cost=$8.379253, processed=7022]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7023/7886 [13:55<25:41,  1.79s/it, total_cost=$8.380520, processed=7023]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7024/7886 [13:56<23:29,  1.63s/it, total_cost=$8.381720, processed=7024]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7025/7886 [13:58<24:10,  1.68s/it, total_cost=$8.382930, processed=7025]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7026/7886 [13:59<22:23,  1.56s/it, total_cost=$8.384113, processed=7026]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7027/7886 [14:01<24:42,  1.73s/it, total_cost=$8.385298, processed=7027]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7028/7886 [14:02<22:16,  1.56s/it, total_cost=$8.386530, processed=7028]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7029/7886 [14:03<20:38,  1.45s/it, total_cost=$8.387750, processed=7029]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7030/7886 [14:05<19:27,  1.36s/it, total_cost=$8.388955, processed=7030]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7031/7886 [14:06<19:19,  1.36s/it, total_cost=$8.390288, processed=7031]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7032/7886 [14:07<18:30,  1.30s/it, total_cost=$8.391413, processed=7032]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7033/7886 [14:10<23:06,  1.63s/it, total_cost=$8.392753, processed=7033]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7034/7886 [14:12<24:43,  1.74s/it, total_cost=$8.393963, processed=7034]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7035/7886 [14:13<22:31,  1.59s/it, total_cost=$8.395215, processed=7035]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  89%|████████▉ | 7036/7886 [14:14<20:49,  1.47s/it, total_cost=$8.396445, processed=7036]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7037/7886 [14:16<22:18,  1.58s/it, total_cost=$8.397650, processed=7037]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7038/7886 [14:17<20:52,  1.48s/it, total_cost=$8.398953, processed=7038]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  89%|████████▉ | 7039/7886 [14:18<19:44,  1.40s/it, total_cost=$8.400138, processed=7039]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  89%|████████▉ | 7040/7886 [14:20<18:59,  1.35s/it, total_cost=$8.401340, processed=7040]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7041/7886 [14:21<18:43,  1.33s/it, total_cost=$8.402505, processed=7041]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▉ | 7042/7886 [14:22<17:38,  1.25s/it, total_cost=$8.403953, processed=7042]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7043/7886 [14:24<19:10,  1.36s/it, total_cost=$8.405128, processed=7043]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  89%|████████▉ | 7044/7886 [14:25<20:17,  1.45s/it, total_cost=$8.406323, processed=7044]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7045/7886 [14:26<18:55,  1.35s/it, total_cost=$8.407458, processed=7045]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7046/7886 [14:28<21:16,  1.52s/it, total_cost=$8.408638, processed=7046]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7047/7886 [14:30<20:06,  1.44s/it, total_cost=$8.409908, processed=7047]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7048/7886 [14:31<19:12,  1.38s/it, total_cost=$8.411105, processed=7048]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  89%|████████▉ | 7049/7886 [14:32<18:22,  1.32s/it, total_cost=$8.412258, processed=7049]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  89%|████████▉ | 7050/7886 [14:33<18:04,  1.30s/it, total_cost=$8.413418, processed=7050]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  89%|████████▉ | 7051/7886 [14:34<16:58,  1.22s/it, total_cost=$8.414540, processed=7051]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  89%|████████▉ | 7052/7886 [14:36<21:43,  1.56s/it, total_cost=$8.415825, processed=7052]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  89%|████████▉ | 7053/7886 [14:38<20:10,  1.45s/it, total_cost=$8.416993, processed=7053]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7054/7886 [14:39<18:39,  1.35s/it, total_cost=$8.418118, processed=7054]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7055/7886 [14:40<18:13,  1.32s/it, total_cost=$8.419268, processed=7055]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  89%|████████▉ | 7056/7886 [14:41<18:00,  1.30s/it, total_cost=$8.420483, processed=7056]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  89%|████████▉ | 7057/7886 [14:44<22:38,  1.64s/it, total_cost=$8.421648, processed=7057]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  90%|████████▉ | 7058/7886 [14:45<21:55,  1.59s/it, total_cost=$8.422868, processed=7058]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  90%|████████▉ | 7059/7886 [14:47<24:09,  1.75s/it, total_cost=$8.424115, processed=7059]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|████████▉ | 7060/7886 [14:49<21:34,  1.57s/it, total_cost=$8.425285, processed=7060]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  90%|████████▉ | 7061/7886 [14:50<20:17,  1.48s/it, total_cost=$8.426550, processed=7061]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  90%|████████▉ | 7062/7886 [14:51<19:08,  1.39s/it, total_cost=$8.427745, processed=7062]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|████████▉ | 7063/7886 [14:52<18:01,  1.31s/it, total_cost=$8.429365, processed=7063]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  90%|████████▉ | 7064/7886 [14:53<17:00,  1.24s/it, total_cost=$8.430638, processed=7064]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  90%|████████▉ | 7065/7886 [14:54<16:36,  1.21s/it, total_cost=$8.431768, processed=7065]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  90%|████████▉ | 7066/7886 [14:56<16:58,  1.24s/it, total_cost=$8.432985, processed=7066]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|████████▉ | 7067/7886 [14:57<16:31,  1.21s/it, total_cost=$8.434118, processed=7067]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|████████▉ | 7068/7886 [14:58<17:15,  1.27s/it, total_cost=$8.435345, processed=7068]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|████████▉ | 7069/7886 [14:59<16:44,  1.23s/it, total_cost=$8.436505, processed=7069]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  90%|████████▉ | 7070/7886 [15:01<17:05,  1.26s/it, total_cost=$8.437693, processed=7070]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|████████▉ | 7071/7886 [15:02<16:46,  1.24s/it, total_cost=$8.438815, processed=7071]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|████████▉ | 7072/7886 [15:03<16:50,  1.24s/it, total_cost=$8.439983, processed=7072]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|████████▉ | 7073/7886 [15:04<16:24,  1.21s/it, total_cost=$8.441158, processed=7073]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  90%|████████▉ | 7074/7886 [15:06<16:58,  1.25s/it, total_cost=$8.442458, processed=7074]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  90%|████████▉ | 7075/7886 [15:07<17:24,  1.29s/it, total_cost=$8.443868, processed=7075]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|████████▉ | 7076/7886 [15:08<16:52,  1.25s/it, total_cost=$8.445025, processed=7076]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  90%|████████▉ | 7077/7886 [15:09<16:25,  1.22s/it, total_cost=$8.446225, processed=7077]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|████████▉ | 7078/7886 [15:10<16:01,  1.19s/it, total_cost=$8.447393, processed=7078]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|████████▉ | 7079/7886 [15:12<16:14,  1.21s/it, total_cost=$8.448565, processed=7079]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|████████▉ | 7080/7886 [15:13<15:57,  1.19s/it, total_cost=$8.449703, processed=7080]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  90%|████████▉ | 7081/7886 [15:14<16:44,  1.25s/it, total_cost=$8.450955, processed=7081]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|████████▉ | 7082/7886 [15:16<16:56,  1.26s/it, total_cost=$8.452145, processed=7082]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|████████▉ | 7083/7886 [15:17<16:41,  1.25s/it, total_cost=$8.453410, processed=7083]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|████████▉ | 7084/7886 [15:18<16:58,  1.27s/it, total_cost=$8.454615, processed=7084]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|████████▉ | 7085/7886 [15:19<16:53,  1.26s/it, total_cost=$8.455903, processed=7085]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|████████▉ | 7086/7886 [15:20<16:16,  1.22s/it, total_cost=$8.457080, processed=7086]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|████████▉ | 7087/7886 [15:22<16:01,  1.20s/it, total_cost=$8.458293, processed=7087]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  90%|████████▉ | 7088/7886 [15:23<15:54,  1.20s/it, total_cost=$8.459543, processed=7088]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|████████▉ | 7089/7886 [15:24<16:12,  1.22s/it, total_cost=$8.460723, processed=7089]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|████████▉ | 7090/7886 [15:25<16:30,  1.24s/it, total_cost=$8.461940, processed=7090]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|████████▉ | 7091/7886 [15:27<16:19,  1.23s/it, total_cost=$8.463090, processed=7091]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|████████▉ | 7092/7886 [15:28<16:09,  1.22s/it, total_cost=$8.464378, processed=7092]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|████████▉ | 7093/7886 [15:29<16:07,  1.22s/it, total_cost=$8.465555, processed=7093]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|████████▉ | 7094/7886 [15:30<15:35,  1.18s/it, total_cost=$8.466738, processed=7094]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|████████▉ | 7095/7886 [15:31<15:55,  1.21s/it, total_cost=$8.468050, processed=7095]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|████████▉ | 7096/7886 [15:33<16:14,  1.23s/it, total_cost=$8.469270, processed=7096]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  90%|████████▉ | 7097/7886 [15:34<16:04,  1.22s/it, total_cost=$8.470545, processed=7097]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  90%|█████████ | 7098/7886 [15:35<15:56,  1.21s/it, total_cost=$8.471755, processed=7098]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|█████████ | 7099/7886 [15:36<16:18,  1.24s/it, total_cost=$8.472898, processed=7099]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  90%|█████████ | 7100/7886 [15:38<16:27,  1.26s/it, total_cost=$8.474200, processed=7100]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|█████████ | 7101/7886 [15:39<16:44,  1.28s/it, total_cost=$8.475378, processed=7101]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|█████████ | 7102/7886 [15:40<16:48,  1.29s/it, total_cost=$8.476550, processed=7102]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  90%|█████████ | 7103/7886 [15:42<17:34,  1.35s/it, total_cost=$8.477865, processed=7103]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  90%|█████████ | 7104/7886 [15:43<17:19,  1.33s/it, total_cost=$8.478983, processed=7104]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|█████████ | 7105/7886 [15:44<17:07,  1.32s/it, total_cost=$8.480293, processed=7105]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|█████████ | 7106/7886 [15:45<16:27,  1.27s/it, total_cost=$8.481430, processed=7106]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  90%|█████████ | 7107/7886 [15:47<16:08,  1.24s/it, total_cost=$8.482625, processed=7107]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|█████████ | 7108/7886 [15:48<15:48,  1.22s/it, total_cost=$8.483808, processed=7108]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|█████████ | 7109/7886 [15:49<17:21,  1.34s/it, total_cost=$8.485023, processed=7109]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|█████████ | 7110/7886 [15:51<17:06,  1.32s/it, total_cost=$8.486160, processed=7110]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  90%|█████████ | 7111/7886 [15:52<17:24,  1.35s/it, total_cost=$8.487285, processed=7111]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|█████████ | 7112/7886 [15:53<17:15,  1.34s/it, total_cost=$8.488525, processed=7112]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|█████████ | 7113/7886 [15:55<17:34,  1.36s/it, total_cost=$8.489728, processed=7113]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|█████████ | 7114/7886 [15:56<17:40,  1.37s/it, total_cost=$8.490913, processed=7114]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  90%|█████████ | 7115/7886 [15:58<16:54,  1.32s/it, total_cost=$8.492125, processed=7115]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|█████████ | 7116/7886 [16:00<19:58,  1.56s/it, total_cost=$8.493613, processed=7116]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|█████████ | 7117/7886 [16:02<21:09,  1.65s/it, total_cost=$8.494873, processed=7117]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|█████████ | 7118/7886 [16:03<20:23,  1.59s/it, total_cost=$8.496095, processed=7118]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  90%|█████████ | 7119/7886 [16:04<20:41,  1.62s/it, total_cost=$8.497463, processed=7119]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|█████████ | 7120/7886 [16:06<19:12,  1.51s/it, total_cost=$8.498720, processed=7120]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|█████████ | 7121/7886 [16:07<17:49,  1.40s/it, total_cost=$8.499878, processed=7121]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|█████████ | 7122/7886 [16:08<17:14,  1.35s/it, total_cost=$8.501000, processed=7122]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  90%|█████████ | 7123/7886 [16:09<16:54,  1.33s/it, total_cost=$8.502173, processed=7123]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|█████████ | 7124/7886 [16:11<16:03,  1.26s/it, total_cost=$8.503338, processed=7124]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  90%|█████████ | 7125/7886 [16:16<16:14,  1.28s/it, total_cost=$8.504518, processed=7125]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|█████████ | 7126/7886 [16:18<33:13,  2.62s/it, total_cost=$8.505730, processed=7126]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  90%|█████████ | 7127/7886 [16:19<27:41,  2.19s/it, total_cost=$8.506918, processed=7127]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  90%|█████████ | 7128/7886 [16:20<24:19,  1.93s/it, total_cost=$8.508140, processed=7128]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|█████████ | 7129/7886 [16:22<21:34,  1.71s/it, total_cost=$8.509360, processed=7129]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|█████████ | 7130/7886 [16:23<20:28,  1.63s/it, total_cost=$8.510588, processed=7130]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  90%|█████████ | 7131/7886 [16:24<18:46,  1.49s/it, total_cost=$8.511700, processed=7131]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  90%|█████████ | 7132/7886 [16:25<18:37,  1.48s/it, total_cost=$8.512913, processed=7132]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|█████████ | 7133/7886 [16:27<17:51,  1.42s/it, total_cost=$8.514093, processed=7133]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  90%|█████████ | 7134/7886 [16:28<16:35,  1.32s/it, total_cost=$8.515278, processed=7134]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  90%|█████████ | 7135/7886 [16:29<16:00,  1.28s/it, total_cost=$8.516533, processed=7135]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  90%|█████████ | 7136/7886 [16:30<15:14,  1.22s/it, total_cost=$8.517643, processed=7136]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████ | 7137/7886 [16:31<15:14,  1.22s/it, total_cost=$8.518860, processed=7137]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7138/7886 [16:33<15:57,  1.28s/it, total_cost=$8.520295, processed=7138]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7139/7886 [16:34<15:49,  1.27s/it, total_cost=$8.521428, processed=7139]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7140/7886 [16:36<16:02,  1.29s/it, total_cost=$8.522770, processed=7140]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  91%|█████████ | 7141/7886 [16:38<19:44,  1.59s/it, total_cost=$8.524030, processed=7141]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7142/7886 [16:39<18:23,  1.48s/it, total_cost=$8.525135, processed=7142]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7143/7886 [16:40<17:29,  1.41s/it, total_cost=$8.526310, processed=7143]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████ | 7144/7886 [16:41<16:50,  1.36s/it, total_cost=$8.527453, processed=7144]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████ | 7145/7886 [16:43<16:51,  1.37s/it, total_cost=$8.528775, processed=7145]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7146/7886 [16:44<16:44,  1.36s/it, total_cost=$8.530090, processed=7146]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████ | 7147/7886 [16:45<16:57,  1.38s/it, total_cost=$8.531285, processed=7147]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7148/7886 [16:47<16:18,  1.33s/it, total_cost=$8.532650, processed=7148]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████ | 7149/7886 [16:48<15:52,  1.29s/it, total_cost=$8.534670, processed=7149]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  91%|█████████ | 7150/7886 [16:49<15:05,  1.23s/it, total_cost=$8.535818, processed=7150]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7151/7886 [16:50<14:26,  1.18s/it, total_cost=$8.537013, processed=7151]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7152/7886 [16:57<15:25,  1.26s/it, total_cost=$8.538195, processed=7152]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████ | 7153/7886 [16:58<34:20,  2.81s/it, total_cost=$8.539338, processed=7153]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████ | 7154/7886 [17:01<30:38,  2.51s/it, total_cost=$8.540525, processed=7154]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7155/7886 [17:02<29:49,  2.45s/it, total_cost=$8.541993, processed=7155]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7156/7886 [17:03<25:31,  2.10s/it, total_cost=$8.543448, processed=7156]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████ | 7157/7886 [17:05<22:41,  1.87s/it, total_cost=$8.544588, processed=7157]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7158/7886 [17:06<20:19,  1.68s/it, total_cost=$8.545748, processed=7158]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  91%|█████████ | 7159/7886 [17:07<19:20,  1.60s/it, total_cost=$8.547008, processed=7159]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7160/7886 [17:08<17:35,  1.45s/it, total_cost=$8.548250, processed=7160]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7161/7886 [17:10<16:34,  1.37s/it, total_cost=$8.549365, processed=7161]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7162/7886 [17:12<16:13,  1.34s/it, total_cost=$8.550725, processed=7162]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  91%|█████████ | 7163/7886 [17:13<18:10,  1.51s/it, total_cost=$8.552003, processed=7163]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7164/7886 [17:14<17:19,  1.44s/it, total_cost=$8.553283, processed=7164]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████ | 7165/7886 [17:15<16:52,  1.40s/it, total_cost=$8.554600, processed=7165]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  91%|█████████ | 7166/7886 [17:17<16:52,  1.41s/it, total_cost=$8.555883, processed=7166]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7167/7886 [17:19<18:06,  1.51s/it, total_cost=$8.557125, processed=7167]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  91%|█████████ | 7168/7886 [17:20<17:15,  1.44s/it, total_cost=$8.558353, processed=7168]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7169/7886 [17:21<18:22,  1.54s/it, total_cost=$8.559640, processed=7169]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7170/7886 [17:23<16:44,  1.40s/it, total_cost=$8.560765, processed=7170]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████ | 7171/7886 [17:24<16:23,  1.38s/it, total_cost=$8.561873, processed=7171]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████ | 7172/7886 [17:25<15:47,  1.33s/it, total_cost=$8.563173, processed=7172]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  91%|█████████ | 7173/7886 [17:26<15:08,  1.27s/it, total_cost=$8.564378, processed=7173]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7174/7886 [17:27<14:30,  1.22s/it, total_cost=$8.565553, processed=7174]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████ | 7175/7886 [17:29<14:09,  1.20s/it, total_cost=$8.566985, processed=7175]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████ | 7176/7886 [17:30<14:48,  1.25s/it, total_cost=$8.568215, processed=7176]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████ | 7177/7886 [17:31<14:43,  1.25s/it, total_cost=$8.569450, processed=7177]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7178/7886 [17:32<14:00,  1.19s/it, total_cost=$8.570580, processed=7178]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████ | 7179/7886 [17:33<13:54,  1.18s/it, total_cost=$8.571738, processed=7179]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7180/7886 [17:34<13:42,  1.16s/it, total_cost=$8.573018, processed=7180]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  91%|█████████ | 7181/7886 [17:36<13:59,  1.19s/it, total_cost=$8.574225, processed=7181]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████ | 7182/7886 [17:37<13:55,  1.19s/it, total_cost=$8.575470, processed=7182]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  91%|█████████ | 7183/7886 [17:38<13:42,  1.17s/it, total_cost=$8.576800, processed=7183]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7184/7886 [17:39<13:48,  1.18s/it, total_cost=$8.578025, processed=7184]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7185/7886 [17:40<14:03,  1.20s/it, total_cost=$8.579153, processed=7185]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7186/7886 [17:42<13:39,  1.17s/it, total_cost=$8.580308, processed=7186]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  91%|█████████ | 7187/7886 [17:43<13:58,  1.20s/it, total_cost=$8.581363, processed=7187]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7188/7886 [17:44<14:01,  1.21s/it, total_cost=$8.582493, processed=7188]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████ | 7189/7886 [17:45<14:18,  1.23s/it, total_cost=$8.583645, processed=7189]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7190/7886 [17:47<16:33,  1.43s/it, total_cost=$8.584930, processed=7190]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████ | 7191/7886 [17:49<16:03,  1.39s/it, total_cost=$8.586198, processed=7191]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████ | 7192/7886 [17:50<16:05,  1.39s/it, total_cost=$8.587575, processed=7192]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████ | 7193/7886 [17:51<15:41,  1.36s/it, total_cost=$8.588780, processed=7193]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████ | 7194/7886 [17:53<16:47,  1.46s/it, total_cost=$8.589915, processed=7194]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████ | 7195/7886 [17:54<16:15,  1.41s/it, total_cost=$8.591148, processed=7195]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  91%|█████████▏| 7196/7886 [17:55<15:23,  1.34s/it, total_cost=$8.592465, processed=7196]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████▏| 7197/7886 [17:56<14:42,  1.28s/it, total_cost=$8.593605, processed=7197]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████▏| 7198/7886 [17:58<14:21,  1.25s/it, total_cost=$8.594870, processed=7198]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████▏| 7199/7886 [17:59<16:34,  1.45s/it, total_cost=$8.596030, processed=7199]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  91%|█████████▏| 7200/7886 [18:01<15:08,  1.32s/it, total_cost=$8.597175, processed=7200]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  91%|█████████▏| 7201/7886 [18:02<14:28,  1.27s/it, total_cost=$8.598388, processed=7201]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████▏| 7202/7886 [18:04<18:52,  1.66s/it, total_cost=$8.599580, processed=7202]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████▏| 7203/7886 [18:05<17:04,  1.50s/it, total_cost=$8.600743, processed=7203]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████▏| 7204/7886 [18:07<16:09,  1.42s/it, total_cost=$8.601963, processed=7204]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████▏| 7205/7886 [18:08<15:33,  1.37s/it, total_cost=$8.603213, processed=7205]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████▏| 7206/7886 [18:09<14:45,  1.30s/it, total_cost=$8.604448, processed=7206]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  91%|█████████▏| 7207/7886 [18:10<14:05,  1.24s/it, total_cost=$8.605538, processed=7207]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████▏| 7208/7886 [18:12<13:55,  1.23s/it, total_cost=$8.606703, processed=7208]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  91%|█████████▏| 7209/7886 [18:13<15:25,  1.37s/it, total_cost=$8.607995, processed=7209]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████▏| 7210/7886 [18:14<15:05,  1.34s/it, total_cost=$8.609153, processed=7210]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  91%|█████████▏| 7211/7886 [18:16<14:58,  1.33s/it, total_cost=$8.610360, processed=7211]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  91%|█████████▏| 7212/7886 [18:17<14:03,  1.25s/it, total_cost=$8.611543, processed=7212]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  91%|█████████▏| 7213/7886 [18:18<14:13,  1.27s/it, total_cost=$8.612738, processed=7213]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  91%|█████████▏| 7214/7886 [18:19<14:09,  1.26s/it, total_cost=$8.613965, processed=7214]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  91%|█████████▏| 7215/7886 [18:21<14:18,  1.28s/it, total_cost=$8.615263, processed=7215]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  92%|█████████▏| 7216/7886 [18:22<14:20,  1.28s/it, total_cost=$8.616563, processed=7216]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7217/7886 [18:23<13:41,  1.23s/it, total_cost=$8.617783, processed=7217]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  92%|█████████▏| 7218/7886 [18:24<13:42,  1.23s/it, total_cost=$8.618965, processed=7218]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7219/7886 [18:26<13:44,  1.24s/it, total_cost=$8.620155, processed=7219]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7220/7886 [18:27<13:43,  1.24s/it, total_cost=$8.621445, processed=7220]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7221/7886 [18:28<13:45,  1.24s/it, total_cost=$8.622733, processed=7221]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  92%|█████████▏| 7222/7886 [18:30<15:30,  1.40s/it, total_cost=$8.623943, processed=7222]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  92%|█████████▏| 7223/7886 [18:31<14:48,  1.34s/it, total_cost=$8.625190, processed=7223]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  92%|█████████▏| 7224/7886 [18:32<14:13,  1.29s/it, total_cost=$8.626388, processed=7224]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7225/7886 [18:33<13:48,  1.25s/it, total_cost=$8.627538, processed=7225]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7226/7886 [18:34<13:36,  1.24s/it, total_cost=$8.628695, processed=7226]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7227/7886 [18:37<17:02,  1.55s/it, total_cost=$8.629775, processed=7227]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7228/7886 [18:38<17:11,  1.57s/it, total_cost=$8.630990, processed=7228]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7229/7886 [18:40<16:36,  1.52s/it, total_cost=$8.632303, processed=7229]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  92%|█████████▏| 7230/7886 [18:42<17:58,  1.64s/it, total_cost=$8.633385, processed=7230]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7231/7886 [18:43<17:24,  1.59s/it, total_cost=$8.634480, processed=7231]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7232/7886 [18:45<16:12,  1.49s/it, total_cost=$8.635643, processed=7232]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7233/7886 [18:46<15:33,  1.43s/it, total_cost=$8.636988, processed=7233]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7234/7886 [18:47<15:15,  1.40s/it, total_cost=$8.638205, processed=7234]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7235/7886 [18:48<14:33,  1.34s/it, total_cost=$8.639425, processed=7235]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  92%|█████████▏| 7236/7886 [18:49<14:20,  1.32s/it, total_cost=$8.640563, processed=7236]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  92%|█████████▏| 7237/7886 [18:51<13:36,  1.26s/it, total_cost=$8.641705, processed=7237]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  92%|█████████▏| 7238/7886 [18:53<17:10,  1.59s/it, total_cost=$8.642953, processed=7238]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7239/7886 [18:55<17:35,  1.63s/it, total_cost=$8.644158, processed=7239]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  92%|█████████▏| 7240/7886 [18:57<18:04,  1.68s/it, total_cost=$8.645328, processed=7240]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7241/7886 [18:58<16:28,  1.53s/it, total_cost=$8.646498, processed=7241]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7242/7886 [18:59<15:43,  1.47s/it, total_cost=$8.647845, processed=7242]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  92%|█████████▏| 7243/7886 [19:00<14:58,  1.40s/it, total_cost=$8.649085, processed=7243]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7244/7886 [19:02<13:51,  1.30s/it, total_cost=$8.650305, processed=7244]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7245/7886 [19:04<17:02,  1.60s/it, total_cost=$8.651580, processed=7245]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7246/7886 [19:05<15:22,  1.44s/it, total_cost=$8.652693, processed=7246]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7247/7886 [19:06<15:26,  1.45s/it, total_cost=$8.654013, processed=7247]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7248/7886 [19:08<15:28,  1.46s/it, total_cost=$8.655188, processed=7248]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7249/7886 [19:09<15:07,  1.43s/it, total_cost=$8.656405, processed=7249]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  92%|█████████▏| 7250/7886 [19:11<14:48,  1.40s/it, total_cost=$8.658455, processed=7250]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7251/7886 [19:13<20:02,  1.89s/it, total_cost=$8.659610, processed=7251]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7252/7886 [19:15<17:27,  1.65s/it, total_cost=$8.660758, processed=7252]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  92%|█████████▏| 7253/7886 [19:16<16:07,  1.53s/it, total_cost=$8.662065, processed=7253]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7254/7886 [19:17<15:06,  1.43s/it, total_cost=$8.663285, processed=7254]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7255/7886 [19:18<14:12,  1.35s/it, total_cost=$8.664485, processed=7255]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7256/7886 [19:21<17:42,  1.69s/it, total_cost=$8.665733, processed=7256]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7257/7886 [19:23<19:47,  1.89s/it, total_cost=$8.666888, processed=7257]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7258/7886 [19:24<17:35,  1.68s/it, total_cost=$8.668073, processed=7258]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7259/7886 [19:26<16:12,  1.55s/it, total_cost=$8.669230, processed=7259]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  92%|█████████▏| 7260/7886 [19:27<17:26,  1.67s/it, total_cost=$8.670590, processed=7260]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7261/7886 [19:29<16:39,  1.60s/it, total_cost=$8.671830, processed=7261]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7262/7886 [19:30<16:34,  1.59s/it, total_cost=$8.673025, processed=7262]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  92%|█████████▏| 7263/7886 [19:32<16:34,  1.60s/it, total_cost=$8.674158, processed=7263]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7264/7886 [19:33<16:11,  1.56s/it, total_cost=$8.675335, processed=7264]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  92%|█████████▏| 7265/7886 [19:35<14:42,  1.42s/it, total_cost=$8.676575, processed=7265]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7266/7886 [19:36<14:44,  1.43s/it, total_cost=$8.677753, processed=7266]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  92%|█████████▏| 7267/7886 [19:37<14:01,  1.36s/it, total_cost=$8.678988, processed=7267]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7268/7886 [19:40<17:02,  1.65s/it, total_cost=$8.680145, processed=7268]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7269/7886 [19:41<16:16,  1.58s/it, total_cost=$8.681438, processed=7269]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7270/7886 [19:43<18:41,  1.82s/it, total_cost=$8.682663, processed=7270]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7271/7886 [19:45<16:48,  1.64s/it, total_cost=$8.683915, processed=7271]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7272/7886 [19:46<15:16,  1.49s/it, total_cost=$8.685078, processed=7272]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7273/7886 [19:47<14:41,  1.44s/it, total_cost=$8.686215, processed=7273]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7274/7886 [19:48<13:45,  1.35s/it, total_cost=$8.687453, processed=7274]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7275/7886 [19:51<17:31,  1.72s/it, total_cost=$8.688640, processed=7275]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7276/7886 [19:52<15:16,  1.50s/it, total_cost=$8.689825, processed=7276]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7277/7886 [19:53<14:29,  1.43s/it, total_cost=$8.690998, processed=7277]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7278/7886 [19:54<13:48,  1.36s/it, total_cost=$8.692228, processed=7278]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  92%|█████████▏| 7279/7886 [19:55<13:06,  1.30s/it, total_cost=$8.693443, processed=7279]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  92%|█████████▏| 7280/7886 [19:57<13:04,  1.30s/it, total_cost=$8.694778, processed=7280]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7281/7886 [19:58<12:35,  1.25s/it, total_cost=$8.695958, processed=7281]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  92%|█████████▏| 7282/7886 [19:59<12:40,  1.26s/it, total_cost=$8.697143, processed=7282]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7283/7886 [20:02<16:29,  1.64s/it, total_cost=$8.698463, processed=7283]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  92%|█████████▏| 7284/7886 [20:04<18:45,  1.87s/it, total_cost=$8.699635, processed=7284]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  92%|█████████▏| 7285/7886 [20:05<16:30,  1.65s/it, total_cost=$8.700833, processed=7285]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  92%|█████████▏| 7286/7886 [20:06<15:20,  1.53s/it, total_cost=$8.701993, processed=7286]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  92%|█████████▏| 7287/7886 [20:07<14:07,  1.42s/it, total_cost=$8.703203, processed=7287]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7288/7886 [20:09<13:04,  1.31s/it, total_cost=$8.704408, processed=7288]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  92%|█████████▏| 7289/7886 [20:11<16:25,  1.65s/it, total_cost=$8.705550, processed=7289]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  92%|█████████▏| 7290/7886 [20:13<17:50,  1.80s/it, total_cost=$8.706698, processed=7290]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  92%|█████████▏| 7291/7886 [20:14<16:15,  1.64s/it, total_cost=$8.707888, processed=7291]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7292/7886 [20:16<14:59,  1.51s/it, total_cost=$8.709070, processed=7292]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  92%|█████████▏| 7293/7886 [20:17<13:57,  1.41s/it, total_cost=$8.710290, processed=7293]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  92%|█████████▏| 7294/7886 [20:19<17:22,  1.76s/it, total_cost=$8.711608, processed=7294]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7295/7886 [20:22<18:36,  1.89s/it, total_cost=$8.712865, processed=7295]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7296/7886 [20:23<16:42,  1.70s/it, total_cost=$8.714083, processed=7296]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7297/7886 [20:25<16:42,  1.70s/it, total_cost=$8.715393, processed=7297]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7298/7886 [20:26<16:01,  1.64s/it, total_cost=$8.716565, processed=7298]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7299/7886 [20:28<15:24,  1.58s/it, total_cost=$8.717743, processed=7299]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7300/7886 [20:30<18:01,  1.84s/it, total_cost=$8.719058, processed=7300]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7301/7886 [20:31<17:14,  1.77s/it, total_cost=$8.720298, processed=7301]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7302/7886 [20:34<19:05,  1.96s/it, total_cost=$8.721488, processed=7302]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7303/7886 [20:35<16:26,  1.69s/it, total_cost=$8.722645, processed=7303]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7304/7886 [20:36<14:49,  1.53s/it, total_cost=$8.723810, processed=7304]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  93%|█████████▎| 7305/7886 [20:37<14:03,  1.45s/it, total_cost=$8.725120, processed=7305]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7306/7886 [20:38<12:53,  1.33s/it, total_cost=$8.726355, processed=7306]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7307/7886 [20:40<13:26,  1.39s/it, total_cost=$8.727518, processed=7307]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  93%|█████████▎| 7308/7886 [20:42<15:57,  1.66s/it, total_cost=$8.728783, processed=7308]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7309/7886 [20:44<16:01,  1.67s/it, total_cost=$8.729978, processed=7309]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  93%|█████████▎| 7310/7886 [20:45<14:15,  1.49s/it, total_cost=$8.731150, processed=7310]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7311/7886 [20:47<14:41,  1.53s/it, total_cost=$8.732295, processed=7311]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7312/7886 [20:48<14:33,  1.52s/it, total_cost=$8.733570, processed=7312]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  93%|█████████▎| 7313/7886 [20:49<13:48,  1.45s/it, total_cost=$8.734823, processed=7313]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7314/7886 [20:52<17:12,  1.81s/it, total_cost=$8.735965, processed=7314]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7315/7886 [20:53<15:08,  1.59s/it, total_cost=$8.737103, processed=7315]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7316/7886 [20:55<16:27,  1.73s/it, total_cost=$8.738218, processed=7316]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  93%|█████████▎| 7317/7886 [20:57<15:17,  1.61s/it, total_cost=$8.739485, processed=7317]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7318/7886 [20:58<14:46,  1.56s/it, total_cost=$8.740688, processed=7318]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7319/7886 [20:59<13:40,  1.45s/it, total_cost=$8.741835, processed=7319]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7320/7886 [21:00<12:46,  1.35s/it, total_cost=$8.743070, processed=7320]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7321/7886 [21:02<15:01,  1.60s/it, total_cost=$8.744245, processed=7321]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7322/7886 [21:04<13:40,  1.45s/it, total_cost=$8.745423, processed=7322]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7323/7886 [21:05<13:24,  1.43s/it, total_cost=$8.746620, processed=7323]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7324/7886 [21:06<12:49,  1.37s/it, total_cost=$8.747798, processed=7324]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7325/7886 [21:07<12:05,  1.29s/it, total_cost=$8.749085, processed=7325]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7326/7886 [21:08<11:32,  1.24s/it, total_cost=$8.750255, processed=7326]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7327/7886 [21:11<14:03,  1.51s/it, total_cost=$8.751443, processed=7327]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7328/7886 [21:12<13:30,  1.45s/it, total_cost=$8.752685, processed=7328]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7329/7886 [21:13<12:26,  1.34s/it, total_cost=$8.753828, processed=7329]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7330/7886 [21:14<11:40,  1.26s/it, total_cost=$8.754960, processed=7330]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  93%|█████████▎| 7331/7886 [21:15<11:30,  1.24s/it, total_cost=$8.756108, processed=7331]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7332/7886 [21:17<13:09,  1.43s/it, total_cost=$8.757293, processed=7332]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7333/7886 [21:19<12:54,  1.40s/it, total_cost=$8.758548, processed=7333]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7334/7886 [21:20<12:52,  1.40s/it, total_cost=$8.759748, processed=7334]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7335/7886 [21:21<12:04,  1.31s/it, total_cost=$8.760845, processed=7335]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7336/7886 [21:22<11:50,  1.29s/it, total_cost=$8.761975, processed=7336]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  93%|█████████▎| 7337/7886 [21:24<12:03,  1.32s/it, total_cost=$8.763138, processed=7337]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7338/7886 [21:25<12:08,  1.33s/it, total_cost=$8.764185, processed=7338]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7339/7886 [21:26<12:31,  1.37s/it, total_cost=$8.765310, processed=7339]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  93%|█████████▎| 7340/7886 [21:28<12:05,  1.33s/it, total_cost=$8.766518, processed=7340]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7341/7886 [21:30<13:25,  1.48s/it, total_cost=$8.767783, processed=7341]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7342/7886 [21:31<12:58,  1.43s/it, total_cost=$8.768960, processed=7342]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7343/7886 [21:33<13:11,  1.46s/it, total_cost=$8.770183, processed=7343]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7344/7886 [21:35<16:11,  1.79s/it, total_cost=$8.771348, processed=7344]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7345/7886 [21:36<14:41,  1.63s/it, total_cost=$8.772445, processed=7345]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  93%|█████████▎| 7346/7886 [21:38<13:36,  1.51s/it, total_cost=$8.773575, processed=7346]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7347/7886 [21:39<14:00,  1.56s/it, total_cost=$8.774783, processed=7347]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7348/7886 [21:40<12:45,  1.42s/it, total_cost=$8.775990, processed=7348]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7349/7886 [21:41<12:03,  1.35s/it, total_cost=$8.777273, processed=7349]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7350/7886 [21:42<11:35,  1.30s/it, total_cost=$8.778448, processed=7350]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7351/7886 [21:44<12:05,  1.36s/it, total_cost=$8.779780, processed=7351]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7352/7886 [21:45<11:54,  1.34s/it, total_cost=$8.781005, processed=7352]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7353/7886 [21:48<14:34,  1.64s/it, total_cost=$8.782093, processed=7353]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7354/7886 [21:49<14:29,  1.64s/it, total_cost=$8.783373, processed=7354]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7355/7886 [21:51<15:05,  1.71s/it, total_cost=$8.784553, processed=7355]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7356/7886 [21:52<13:57,  1.58s/it, total_cost=$8.785800, processed=7356]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7357/7886 [21:55<15:07,  1.72s/it, total_cost=$8.787045, processed=7357]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7358/7886 [21:57<15:50,  1.80s/it, total_cost=$8.788340, processed=7358]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7359/7886 [21:58<14:20,  1.63s/it, total_cost=$8.789560, processed=7359]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  93%|█████████▎| 7360/7886 [21:59<13:35,  1.55s/it, total_cost=$8.790813, processed=7360]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7361/7886 [22:00<12:31,  1.43s/it, total_cost=$8.791950, processed=7361]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  93%|█████████▎| 7362/7886 [22:02<14:08,  1.62s/it, total_cost=$8.793213, processed=7362]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7363/7886 [22:03<13:10,  1.51s/it, total_cost=$8.794463, processed=7363]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7364/7886 [22:05<12:35,  1.45s/it, total_cost=$8.795610, processed=7364]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  93%|█████████▎| 7365/7886 [22:06<12:22,  1.43s/it, total_cost=$8.796848, processed=7365]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7366/7886 [22:08<11:55,  1.38s/it, total_cost=$8.798138, processed=7366]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  93%|█████████▎| 7367/7886 [22:09<11:42,  1.35s/it, total_cost=$8.799368, processed=7367]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  93%|█████████▎| 7368/7886 [22:10<11:08,  1.29s/it, total_cost=$8.800463, processed=7368]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  93%|█████████▎| 7369/7886 [22:12<13:33,  1.57s/it, total_cost=$8.801755, processed=7369]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7370/7886 [22:14<13:30,  1.57s/it, total_cost=$8.803043, processed=7370]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  93%|█████████▎| 7371/7886 [22:17<15:47,  1.84s/it, total_cost=$8.804305, processed=7371]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  93%|█████████▎| 7372/7886 [22:18<16:54,  1.97s/it, total_cost=$8.805548, processed=7372]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  93%|█████████▎| 7373/7886 [22:20<15:02,  1.76s/it, total_cost=$8.806863, processed=7373]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▎| 7374/7886 [22:22<14:06,  1.65s/it, total_cost=$8.808145, processed=7374]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  94%|█████████▎| 7375/7886 [22:24<17:23,  2.04s/it, total_cost=$8.809308, processed=7375]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▎| 7376/7886 [22:25<15:30,  1.82s/it, total_cost=$8.810443, processed=7376]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▎| 7377/7886 [22:27<13:45,  1.62s/it, total_cost=$8.811625, processed=7377]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▎| 7378/7886 [22:29<15:27,  1.83s/it, total_cost=$8.812833, processed=7378]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▎| 7379/7886 [22:30<14:08,  1.67s/it, total_cost=$8.814028, processed=7379]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▎| 7380/7886 [22:32<14:33,  1.73s/it, total_cost=$8.815353, processed=7380]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▎| 7381/7886 [22:33<13:13,  1.57s/it, total_cost=$8.816580, processed=7381]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▎| 7382/7886 [22:34<12:25,  1.48s/it, total_cost=$8.817810, processed=7382]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▎| 7383/7886 [22:36<11:37,  1.39s/it, total_cost=$8.818963, processed=7383]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  94%|█████████▎| 7384/7886 [22:37<11:52,  1.42s/it, total_cost=$8.820560, processed=7384]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▎| 7385/7886 [22:39<12:13,  1.46s/it, total_cost=$8.821790, processed=7385]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  94%|█████████▎| 7386/7886 [22:40<12:32,  1.51s/it, total_cost=$8.823053, processed=7386]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▎| 7387/7886 [22:42<12:16,  1.48s/it, total_cost=$8.824405, processed=7387]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▎| 7388/7886 [22:43<12:02,  1.45s/it, total_cost=$8.825670, processed=7388]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▎| 7389/7886 [22:44<11:29,  1.39s/it, total_cost=$8.826903, processed=7389]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  94%|█████████▎| 7390/7886 [22:46<11:10,  1.35s/it, total_cost=$8.828125, processed=7390]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▎| 7391/7886 [22:47<10:48,  1.31s/it, total_cost=$8.829313, processed=7391]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▎| 7392/7886 [22:48<10:58,  1.33s/it, total_cost=$8.830510, processed=7392]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▎| 7393/7886 [22:49<10:33,  1.28s/it, total_cost=$8.831760, processed=7393]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▍| 7394/7886 [22:51<11:12,  1.37s/it, total_cost=$8.833055, processed=7394]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7395/7886 [22:52<10:18,  1.26s/it, total_cost=$8.834180, processed=7395]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7396/7886 [22:53<10:50,  1.33s/it, total_cost=$8.835540, processed=7396]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  94%|█████████▍| 7397/7886 [22:56<13:51,  1.70s/it, total_cost=$8.836865, processed=7397]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7398/7886 [22:57<12:29,  1.54s/it, total_cost=$8.837988, processed=7398]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  94%|█████████▍| 7399/7886 [23:00<14:49,  1.83s/it, total_cost=$8.839245, processed=7399]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  94%|█████████▍| 7400/7886 [23:01<13:21,  1.65s/it, total_cost=$8.840418, processed=7400]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  94%|█████████▍| 7401/7886 [23:02<12:09,  1.51s/it, total_cost=$8.841648, processed=7401]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▍| 7402/7886 [23:03<11:25,  1.42s/it, total_cost=$8.842895, processed=7402]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▍| 7403/7886 [23:05<10:54,  1.36s/it, total_cost=$8.844170, processed=7403]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▍| 7404/7886 [23:06<10:43,  1.34s/it, total_cost=$8.845378, processed=7404]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▍| 7405/7886 [23:07<10:33,  1.32s/it, total_cost=$8.846613, processed=7405]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▍| 7406/7886 [23:09<13:14,  1.65s/it, total_cost=$8.847778, processed=7406]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  94%|█████████▍| 7407/7886 [23:12<11:58,  1.50s/it, total_cost=$8.848933, processed=7407]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7408/7886 [23:13<13:48,  1.73s/it, total_cost=$8.850175, processed=7408]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▍| 7409/7886 [23:14<12:40,  1.59s/it, total_cost=$8.851323, processed=7409]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7410/7886 [23:16<11:37,  1.46s/it, total_cost=$8.852490, processed=7410]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  94%|█████████▍| 7411/7886 [23:17<11:24,  1.44s/it, total_cost=$8.853773, processed=7411]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▍| 7412/7886 [23:18<12:18,  1.56s/it, total_cost=$8.854913, processed=7412]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7413/7886 [23:20<11:14,  1.43s/it, total_cost=$8.856095, processed=7413]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  94%|█████████▍| 7414/7886 [23:22<13:18,  1.69s/it, total_cost=$8.857305, processed=7414]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7415/7886 [23:24<12:02,  1.53s/it, total_cost=$8.858518, processed=7415]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  94%|█████████▍| 7416/7886 [23:25<12:41,  1.62s/it, total_cost=$8.859750, processed=7416]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7417/7886 [23:26<11:32,  1.48s/it, total_cost=$8.860958, processed=7417]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7418/7886 [23:29<14:09,  1.82s/it, total_cost=$8.862153, processed=7418]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▍| 7419/7886 [23:31<14:15,  1.83s/it, total_cost=$8.863450, processed=7419]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7420/7886 [23:32<12:36,  1.62s/it, total_cost=$8.864768, processed=7420]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7421/7886 [23:33<11:42,  1.51s/it, total_cost=$8.866078, processed=7421]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7422/7886 [23:34<11:12,  1.45s/it, total_cost=$8.867200, processed=7422]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7423/7886 [23:36<12:50,  1.66s/it, total_cost=$8.868493, processed=7423]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  94%|█████████▍| 7424/7886 [23:38<11:49,  1.53s/it, total_cost=$8.869630, processed=7424]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7425/7886 [23:39<10:55,  1.42s/it, total_cost=$8.870728, processed=7425]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▍| 7426/7886 [23:41<10:32,  1.38s/it, total_cost=$8.871875, processed=7426]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  94%|█████████▍| 7427/7886 [23:43<13:06,  1.71s/it, total_cost=$8.873138, processed=7427]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7428/7886 [23:44<12:05,  1.58s/it, total_cost=$8.874330, processed=7428]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  94%|█████████▍| 7429/7886 [23:45<11:29,  1.51s/it, total_cost=$8.875548, processed=7429]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▍| 7430/7886 [23:47<11:32,  1.52s/it, total_cost=$8.876718, processed=7430]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7431/7886 [23:48<10:53,  1.44s/it, total_cost=$8.877818, processed=7431]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7432/7886 [23:50<13:01,  1.72s/it, total_cost=$8.879013, processed=7432]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7433/7886 [23:52<13:17,  1.76s/it, total_cost=$8.880275, processed=7433]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  94%|█████████▍| 7434/7886 [23:53<11:52,  1.58s/it, total_cost=$8.881355, processed=7434]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  94%|█████████▍| 7435/7886 [23:55<12:58,  1.73s/it, total_cost=$8.882618, processed=7435]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  94%|█████████▍| 7436/7886 [23:57<11:51,  1.58s/it, total_cost=$8.883745, processed=7436]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7437/7886 [23:58<10:54,  1.46s/it, total_cost=$8.884903, processed=7437]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  94%|█████████▍| 7438/7886 [23:59<10:38,  1.43s/it, total_cost=$8.886363, processed=7438]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  94%|█████████▍| 7439/7886 [24:01<10:31,  1.41s/it, total_cost=$8.887643, processed=7439]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▍| 7440/7886 [24:03<13:04,  1.76s/it, total_cost=$8.888755, processed=7440]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  94%|█████████▍| 7441/7886 [24:04<11:47,  1.59s/it, total_cost=$8.889950, processed=7441]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▍| 7442/7886 [24:06<12:38,  1.71s/it, total_cost=$8.891120, processed=7442]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  94%|█████████▍| 7443/7886 [24:08<11:25,  1.55s/it, total_cost=$8.892370, processed=7443]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  94%|█████████▍| 7444/7886 [24:09<10:49,  1.47s/it, total_cost=$8.893525, processed=7444]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  94%|█████████▍| 7445/7886 [24:10<10:17,  1.40s/it, total_cost=$8.894843, processed=7445]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  94%|█████████▍| 7446/7886 [24:11<09:49,  1.34s/it, total_cost=$8.896075, processed=7446]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  94%|█████████▍| 7447/7886 [24:12<09:18,  1.27s/it, total_cost=$8.897170, processed=7447]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  94%|█████████▍| 7448/7886 [24:14<10:25,  1.43s/it, total_cost=$8.898370, processed=7448]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▍| 7449/7886 [24:16<10:09,  1.39s/it, total_cost=$8.899528, processed=7449]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  94%|█████████▍| 7450/7886 [24:17<10:00,  1.38s/it, total_cost=$8.900870, processed=7450]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  94%|█████████▍| 7451/7886 [24:18<09:41,  1.34s/it, total_cost=$8.901978, processed=7451]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  94%|█████████▍| 7452/7886 [24:19<09:19,  1.29s/it, total_cost=$8.903123, processed=7452]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▍| 7453/7886 [24:21<10:54,  1.51s/it, total_cost=$8.904360, processed=7453]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  95%|█████████▍| 7454/7886 [24:22<10:34,  1.47s/it, total_cost=$8.905580, processed=7454]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▍| 7455/7886 [24:24<09:38,  1.34s/it, total_cost=$8.906760, processed=7455]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  95%|█████████▍| 7456/7886 [24:25<09:07,  1.27s/it, total_cost=$8.907898, processed=7456]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  95%|█████████▍| 7457/7886 [24:27<10:28,  1.46s/it, total_cost=$8.909010, processed=7457]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▍| 7458/7886 [24:28<09:53,  1.39s/it, total_cost=$8.910135, processed=7458]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▍| 7459/7886 [24:29<10:26,  1.47s/it, total_cost=$8.911295, processed=7459]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▍| 7460/7886 [24:31<09:32,  1.34s/it, total_cost=$8.912453, processed=7460]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▍| 7461/7886 [24:32<09:07,  1.29s/it, total_cost=$8.913635, processed=7461]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▍| 7462/7886 [24:33<09:25,  1.33s/it, total_cost=$8.915075, processed=7462]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  95%|█████████▍| 7463/7886 [24:35<09:29,  1.35s/it, total_cost=$8.916268, processed=7463]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▍| 7464/7886 [24:36<09:22,  1.33s/it, total_cost=$8.917430, processed=7464]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▍| 7465/7886 [24:37<09:25,  1.34s/it, total_cost=$8.918658, processed=7465]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▍| 7466/7886 [24:38<09:04,  1.30s/it, total_cost=$8.919853, processed=7466]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  95%|█████████▍| 7467/7886 [24:40<09:42,  1.39s/it, total_cost=$8.921040, processed=7467]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▍| 7468/7886 [24:42<09:58,  1.43s/it, total_cost=$8.922250, processed=7468]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▍| 7469/7886 [24:43<09:22,  1.35s/it, total_cost=$8.923420, processed=7469]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▍| 7470/7886 [24:44<09:27,  1.36s/it, total_cost=$8.924705, processed=7470]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  95%|█████████▍| 7471/7886 [24:45<09:09,  1.32s/it, total_cost=$8.925905, processed=7471]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▍| 7472/7886 [24:47<08:59,  1.30s/it, total_cost=$8.927155, processed=7472]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▍| 7473/7886 [24:48<09:43,  1.41s/it, total_cost=$8.928240, processed=7473]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▍| 7474/7886 [24:50<09:27,  1.38s/it, total_cost=$8.929425, processed=7474]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▍| 7475/7886 [24:51<09:01,  1.32s/it, total_cost=$8.930675, processed=7475]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  95%|█████████▍| 7476/7886 [24:52<09:01,  1.32s/it, total_cost=$8.931815, processed=7476]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▍| 7477/7886 [24:54<09:40,  1.42s/it, total_cost=$8.932918, processed=7477]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▍| 7478/7886 [24:55<08:51,  1.30s/it, total_cost=$8.934118, processed=7478]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▍| 7479/7886 [24:56<09:35,  1.41s/it, total_cost=$8.935295, processed=7479]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  95%|█████████▍| 7480/7886 [24:58<08:51,  1.31s/it, total_cost=$8.936543, processed=7480]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  95%|█████████▍| 7481/7886 [24:59<09:39,  1.43s/it, total_cost=$8.937793, processed=7481]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  95%|█████████▍| 7482/7886 [25:01<09:32,  1.42s/it, total_cost=$8.939058, processed=7482]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▍| 7483/7886 [25:02<09:04,  1.35s/it, total_cost=$8.940180, processed=7483]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▍| 7484/7886 [25:03<08:49,  1.32s/it, total_cost=$8.941393, processed=7484]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▍| 7485/7886 [25:04<08:44,  1.31s/it, total_cost=$8.942563, processed=7485]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▍| 7486/7886 [25:06<08:31,  1.28s/it, total_cost=$8.943818, processed=7486]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▍| 7487/7886 [25:08<10:16,  1.54s/it, total_cost=$8.945060, processed=7487]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▍| 7488/7886 [25:09<09:41,  1.46s/it, total_cost=$8.946398, processed=7488]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▍| 7489/7886 [25:10<09:06,  1.38s/it, total_cost=$8.947680, processed=7489]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▍| 7490/7886 [25:11<09:03,  1.37s/it, total_cost=$8.949013, processed=7490]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▍| 7491/7886 [25:13<08:34,  1.30s/it, total_cost=$8.950165, processed=7491]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▌| 7492/7886 [25:14<08:29,  1.29s/it, total_cost=$8.951420, processed=7492]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▌| 7493/7886 [25:15<08:22,  1.28s/it, total_cost=$8.952638, processed=7493]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  95%|█████████▌| 7494/7886 [25:18<10:22,  1.59s/it, total_cost=$8.953723, processed=7494]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▌| 7495/7886 [25:20<11:53,  1.82s/it, total_cost=$8.954980, processed=7495]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▌| 7496/7886 [25:21<10:43,  1.65s/it, total_cost=$8.956195, processed=7496]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  95%|█████████▌| 7497/7886 [25:22<10:02,  1.55s/it, total_cost=$8.957525, processed=7497]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▌| 7498/7886 [25:24<09:12,  1.42s/it, total_cost=$8.958830, processed=7498]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▌| 7499/7886 [25:26<10:24,  1.61s/it, total_cost=$8.960008, processed=7499]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  95%|█████████▌| 7500/7886 [25:27<09:28,  1.47s/it, total_cost=$8.961150, processed=7500]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7501/7886 [25:28<08:59,  1.40s/it, total_cost=$8.962270, processed=7501]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7502/7886 [25:29<08:42,  1.36s/it, total_cost=$8.963540, processed=7502]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7503/7886 [25:31<08:43,  1.37s/it, total_cost=$8.964750, processed=7503]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  95%|█████████▌| 7504/7886 [25:32<08:34,  1.35s/it, total_cost=$8.966033, processed=7504]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▌| 7505/7886 [25:33<08:07,  1.28s/it, total_cost=$8.967208, processed=7505]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  95%|█████████▌| 7506/7886 [25:34<07:49,  1.23s/it, total_cost=$8.968505, processed=7506]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7507/7886 [25:37<10:33,  1.67s/it, total_cost=$8.969628, processed=7507]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7508/7886 [25:39<11:20,  1.80s/it, total_cost=$8.970780, processed=7508]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▌| 7509/7886 [25:40<10:21,  1.65s/it, total_cost=$8.971978, processed=7509]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▌| 7510/7886 [25:41<09:27,  1.51s/it, total_cost=$8.973265, processed=7510]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7511/7886 [25:43<08:36,  1.38s/it, total_cost=$8.974600, processed=7511]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  95%|█████████▌| 7512/7886 [25:45<10:48,  1.73s/it, total_cost=$8.975678, processed=7512]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▌| 7513/7886 [25:47<11:35,  1.86s/it, total_cost=$8.976880, processed=7513]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▌| 7514/7886 [25:48<10:15,  1.66s/it, total_cost=$8.978040, processed=7514]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  95%|█████████▌| 7515/7886 [25:50<09:20,  1.51s/it, total_cost=$8.979308, processed=7515]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7516/7886 [25:51<08:37,  1.40s/it, total_cost=$8.980588, processed=7516]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  95%|█████████▌| 7517/7886 [25:52<08:34,  1.39s/it, total_cost=$8.982723, processed=7517]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  95%|█████████▌| 7518/7886 [25:53<08:20,  1.36s/it, total_cost=$8.984030, processed=7518]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7519/7886 [25:55<09:21,  1.53s/it, total_cost=$8.985138, processed=7519]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  95%|█████████▌| 7520/7886 [25:56<08:36,  1.41s/it, total_cost=$8.986308, processed=7520]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  95%|█████████▌| 7521/7886 [25:58<08:13,  1.35s/it, total_cost=$8.987548, processed=7521]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  95%|█████████▌| 7522/7886 [25:59<08:53,  1.46s/it, total_cost=$8.988685, processed=7522]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  95%|█████████▌| 7523/7886 [26:01<08:24,  1.39s/it, total_cost=$8.989855, processed=7523]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▌| 7524/7886 [26:02<08:19,  1.38s/it, total_cost=$8.991048, processed=7524]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▌| 7525/7886 [26:03<07:51,  1.30s/it, total_cost=$8.992303, processed=7525]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  95%|█████████▌| 7526/7886 [26:04<07:59,  1.33s/it, total_cost=$8.993483, processed=7526]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  95%|█████████▌| 7527/7886 [26:06<07:39,  1.28s/it, total_cost=$8.994705, processed=7527]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  95%|█████████▌| 7528/7886 [26:07<08:22,  1.40s/it, total_cost=$8.995975, processed=7528]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▌| 7529/7886 [26:09<07:59,  1.34s/it, total_cost=$8.997203, processed=7529]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  95%|█████████▌| 7530/7886 [26:10<07:44,  1.31s/it, total_cost=$8.998525, processed=7530]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  95%|█████████▌| 7531/7886 [26:11<08:17,  1.40s/it, total_cost=$8.999838, processed=7531]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7532/7886 [26:13<07:59,  1.35s/it, total_cost=$9.001090, processed=7532]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▌| 7533/7886 [26:14<07:54,  1.34s/it, total_cost=$9.002413, processed=7533]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7534/7886 [26:15<07:43,  1.32s/it, total_cost=$9.003580, processed=7534]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▌| 7535/7886 [26:16<07:11,  1.23s/it, total_cost=$9.004753, processed=7535]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  96%|█████████▌| 7536/7886 [26:19<09:10,  1.57s/it, total_cost=$9.005988, processed=7536]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7537/7886 [26:20<08:28,  1.46s/it, total_cost=$9.007238, processed=7537]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7538/7886 [26:21<07:59,  1.38s/it, total_cost=$9.008408, processed=7538]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  96%|█████████▌| 7539/7886 [26:22<07:39,  1.33s/it, total_cost=$9.009660, processed=7539]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7540/7886 [26:24<07:52,  1.37s/it, total_cost=$9.010925, processed=7540]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7541/7886 [26:25<07:42,  1.34s/it, total_cost=$9.012203, processed=7541]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  96%|█████████▌| 7542/7886 [26:26<07:29,  1.31s/it, total_cost=$9.013448, processed=7542]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  96%|█████████▌| 7543/7886 [26:27<07:30,  1.31s/it, total_cost=$9.014723, processed=7543]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▌| 7544/7886 [26:29<07:06,  1.25s/it, total_cost=$9.015848, processed=7544]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  96%|█████████▌| 7545/7886 [26:30<07:24,  1.30s/it, total_cost=$9.017135, processed=7545]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  96%|█████████▌| 7546/7886 [26:33<09:00,  1.59s/it, total_cost=$9.018303, processed=7546]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▌| 7547/7886 [26:35<10:11,  1.81s/it, total_cost=$9.019555, processed=7547]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  96%|█████████▌| 7548/7886 [26:37<09:13,  1.64s/it, total_cost=$9.020785, processed=7548]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7549/7886 [26:38<09:39,  1.72s/it, total_cost=$9.022035, processed=7549]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  96%|█████████▌| 7550/7886 [26:40<09:50,  1.76s/it, total_cost=$9.023230, processed=7550]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7551/7886 [26:41<08:53,  1.59s/it, total_cost=$9.024460, processed=7551]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7552/7886 [26:42<08:44,  1.57s/it, total_cost=$9.025835, processed=7552]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7553/7886 [26:44<09:01,  1.62s/it, total_cost=$9.026963, processed=7553]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  96%|█████████▌| 7554/7886 [26:45<08:25,  1.52s/it, total_cost=$9.028193, processed=7554]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▌| 7555/7886 [26:47<07:58,  1.45s/it, total_cost=$9.029410, processed=7555]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7556/7886 [26:48<07:58,  1.45s/it, total_cost=$9.030540, processed=7556]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7557/7886 [26:50<07:39,  1.40s/it, total_cost=$9.031898, processed=7557]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7558/7886 [26:51<08:21,  1.53s/it, total_cost=$9.033093, processed=7558]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7559/7886 [26:52<07:41,  1.41s/it, total_cost=$9.034273, processed=7559]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  96%|█████████▌| 7560/7886 [26:54<07:12,  1.33s/it, total_cost=$9.035440, processed=7560]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7561/7886 [26:55<07:53,  1.46s/it, total_cost=$9.036635, processed=7561]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  96%|█████████▌| 7562/7886 [26:57<07:42,  1.43s/it, total_cost=$9.037928, processed=7562]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▌| 7563/7886 [26:59<09:00,  1.67s/it, total_cost=$9.039143, processed=7563]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7564/7886 [27:01<08:54,  1.66s/it, total_cost=$9.040320, processed=7564]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7565/7886 [27:03<08:45,  1.64s/it, total_cost=$9.041535, processed=7565]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7566/7886 [27:05<10:34,  1.98s/it, total_cost=$9.042745, processed=7566]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7567/7886 [27:06<09:30,  1.79s/it, total_cost=$9.043943, processed=7567]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7568/7886 [27:07<08:28,  1.60s/it, total_cost=$9.045143, processed=7568]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7569/7886 [27:08<07:43,  1.46s/it, total_cost=$9.046368, processed=7569]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▌| 7570/7886 [27:10<07:21,  1.40s/it, total_cost=$9.047555, processed=7570]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  96%|█████████▌| 7571/7886 [27:12<08:46,  1.67s/it, total_cost=$9.048785, processed=7571]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7572/7886 [27:13<07:51,  1.50s/it, total_cost=$9.049960, processed=7572]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7573/7886 [27:14<07:34,  1.45s/it, total_cost=$9.051333, processed=7573]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  96%|█████████▌| 7574/7886 [27:16<07:05,  1.36s/it, total_cost=$9.052438, processed=7574]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7575/7886 [27:17<06:56,  1.34s/it, total_cost=$9.053703, processed=7575]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7576/7886 [27:18<06:37,  1.28s/it, total_cost=$9.054895, processed=7576]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  96%|█████████▌| 7577/7886 [27:19<06:17,  1.22s/it, total_cost=$9.056013, processed=7577]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7578/7886 [27:21<07:07,  1.39s/it, total_cost=$9.057280, processed=7578]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▌| 7579/7886 [27:22<06:48,  1.33s/it, total_cost=$9.058528, processed=7579]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7580/7886 [27:23<06:41,  1.31s/it, total_cost=$9.059703, processed=7580]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  96%|█████████▌| 7581/7886 [27:25<07:48,  1.53s/it, total_cost=$9.060925, processed=7581]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▌| 7582/7886 [27:27<07:14,  1.43s/it, total_cost=$9.062255, processed=7582]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  96%|█████████▌| 7583/7886 [27:28<06:59,  1.38s/it, total_cost=$9.063420, processed=7583]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7584/7886 [27:29<06:48,  1.35s/it, total_cost=$9.064588, processed=7584]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▌| 7585/7886 [27:31<06:49,  1.36s/it, total_cost=$9.065810, processed=7585]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  96%|█████████▌| 7586/7886 [27:32<06:29,  1.30s/it, total_cost=$9.066948, processed=7586]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▌| 7587/7886 [27:33<06:49,  1.37s/it, total_cost=$9.068263, processed=7587]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▌| 7588/7886 [27:35<06:54,  1.39s/it, total_cost=$9.069688, processed=7588]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  96%|█████████▌| 7589/7886 [27:36<06:38,  1.34s/it, total_cost=$9.071720, processed=7589]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▌| 7590/7886 [27:38<06:19,  1.28s/it, total_cost=$9.072888, processed=7590]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▋| 7591/7886 [27:39<07:31,  1.53s/it, total_cost=$9.074068, processed=7591]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▋| 7592/7886 [27:40<06:56,  1.42s/it, total_cost=$9.075305, processed=7592]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  96%|█████████▋| 7593/7886 [27:42<06:38,  1.36s/it, total_cost=$9.076465, processed=7593]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7594/7886 [27:43<06:54,  1.42s/it, total_cost=$9.077668, processed=7594]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  96%|█████████▋| 7595/7886 [27:45<06:32,  1.35s/it, total_cost=$9.078968, processed=7595]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  96%|█████████▋| 7596/7886 [27:48<08:46,  1.82s/it, total_cost=$9.080238, processed=7596]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7597/7886 [27:51<10:14,  2.13s/it, total_cost=$9.081378, processed=7597]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7598/7886 [27:52<10:10,  2.12s/it, total_cost=$9.082673, processed=7598]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  96%|█████████▋| 7599/7886 [27:54<09:14,  1.93s/it, total_cost=$9.083940, processed=7599]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7600/7886 [27:55<08:02,  1.69s/it, total_cost=$9.085295, processed=7600]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▋| 7601/7886 [27:57<07:30,  1.58s/it, total_cost=$9.086488, processed=7601]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  96%|█████████▋| 7602/7886 [27:58<08:02,  1.70s/it, total_cost=$9.087880, processed=7602]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  96%|█████████▋| 7603/7886 [27:59<07:18,  1.55s/it, total_cost=$9.088993, processed=7603]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  96%|█████████▋| 7604/7886 [28:00<06:46,  1.44s/it, total_cost=$9.090175, processed=7604]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7605/7886 [28:02<06:27,  1.38s/it, total_cost=$9.091425, processed=7605]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▋| 7606/7886 [28:03<06:22,  1.37s/it, total_cost=$9.092580, processed=7606]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7607/7886 [28:05<06:51,  1.48s/it, total_cost=$9.093908, processed=7607]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  96%|█████████▋| 7608/7886 [28:06<06:36,  1.42s/it, total_cost=$9.095185, processed=7608]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  96%|█████████▋| 7609/7886 [28:07<06:22,  1.38s/it, total_cost=$9.096340, processed=7609]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  97%|█████████▋| 7610/7886 [28:09<06:15,  1.36s/it, total_cost=$9.097918, processed=7610]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7611/7886 [28:10<06:37,  1.44s/it, total_cost=$9.099245, processed=7611]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7612/7886 [28:11<06:14,  1.37s/it, total_cost=$9.100468, processed=7612]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7613/7886 [28:13<05:50,  1.28s/it, total_cost=$9.101720, processed=7613]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7614/7886 [28:14<05:47,  1.28s/it, total_cost=$9.102958, processed=7614]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7615/7886 [28:15<05:50,  1.29s/it, total_cost=$9.104178, processed=7615]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7616/7886 [28:16<05:42,  1.27s/it, total_cost=$9.105443, processed=7616]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  97%|█████████▋| 7617/7886 [28:18<05:26,  1.21s/it, total_cost=$9.106605, processed=7617]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7618/7886 [28:19<05:59,  1.34s/it, total_cost=$9.107835, processed=7618]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  97%|█████████▋| 7619/7886 [28:21<07:14,  1.63s/it, total_cost=$9.109015, processed=7619]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7620/7886 [28:22<06:36,  1.49s/it, total_cost=$9.110258, processed=7620]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7621/7886 [28:24<06:02,  1.37s/it, total_cost=$9.111478, processed=7621]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7622/7886 [28:25<05:53,  1.34s/it, total_cost=$9.112840, processed=7622]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7623/7886 [28:26<05:29,  1.25s/it, total_cost=$9.113965, processed=7623]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  97%|█████████▋| 7624/7886 [28:27<05:33,  1.27s/it, total_cost=$9.115130, processed=7624]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7625/7886 [28:30<06:52,  1.58s/it, total_cost=$9.116258, processed=7625]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  97%|█████████▋| 7626/7886 [28:31<06:20,  1.46s/it, total_cost=$9.117423, processed=7626]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7627/7886 [28:33<06:57,  1.61s/it, total_cost=$9.118630, processed=7627]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7628/7886 [28:35<07:13,  1.68s/it, total_cost=$9.119960, processed=7628]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7629/7886 [28:36<06:33,  1.53s/it, total_cost=$9.121130, processed=7629]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7630/7886 [28:38<06:25,  1.51s/it, total_cost=$9.122365, processed=7630]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  97%|█████████▋| 7631/7886 [28:40<07:34,  1.78s/it, total_cost=$9.123493, processed=7631]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7632/7886 [28:42<08:17,  1.96s/it, total_cost=$9.124523, processed=7632]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  97%|█████████▋| 7633/7886 [28:43<07:31,  1.79s/it, total_cost=$9.125873, processed=7633]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7634/7886 [28:44<06:34,  1.57s/it, total_cost=$9.126983, processed=7634]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7635/7886 [28:46<05:54,  1.41s/it, total_cost=$9.128215, processed=7635]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  97%|█████████▋| 7636/7886 [28:47<05:43,  1.38s/it, total_cost=$9.129480, processed=7636]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7637/7886 [28:48<05:32,  1.34s/it, total_cost=$9.130675, processed=7637]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7638/7886 [28:49<05:25,  1.31s/it, total_cost=$9.131823, processed=7638]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  97%|█████████▋| 7639/7886 [28:52<06:48,  1.65s/it, total_cost=$9.133043, processed=7639]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  97%|█████████▋| 7640/7886 [28:53<06:12,  1.51s/it, total_cost=$9.134320, processed=7640]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  97%|█████████▋| 7641/7886 [28:54<05:53,  1.44s/it, total_cost=$9.136325, processed=7641]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7642/7886 [28:55<05:45,  1.42s/it, total_cost=$9.137498, processed=7642]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  97%|█████████▋| 7643/7886 [28:57<05:18,  1.31s/it, total_cost=$9.138753, processed=7643]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7644/7886 [28:58<05:12,  1.29s/it, total_cost=$9.139928, processed=7644]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  97%|█████████▋| 7645/7886 [28:59<05:03,  1.26s/it, total_cost=$9.141063, processed=7645]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7646/7886 [29:00<04:58,  1.24s/it, total_cost=$9.142358, processed=7646]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7647/7886 [29:01<04:55,  1.24s/it, total_cost=$9.144668, processed=7647]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7648/7886 [29:04<06:19,  1.60s/it, total_cost=$9.145795, processed=7648]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  97%|█████████▋| 7649/7886 [29:06<06:57,  1.76s/it, total_cost=$9.146973, processed=7649]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7650/7886 [29:07<06:21,  1.62s/it, total_cost=$9.148168, processed=7650]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  97%|█████████▋| 7651/7886 [29:08<05:52,  1.50s/it, total_cost=$9.149443, processed=7651]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7652/7886 [29:10<05:24,  1.39s/it, total_cost=$9.150568, processed=7652]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  97%|█████████▋| 7653/7886 [29:12<06:21,  1.64s/it, total_cost=$9.151998, processed=7653]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7654/7886 [29:13<05:53,  1.52s/it, total_cost=$9.153145, processed=7654]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7655/7886 [29:14<05:26,  1.41s/it, total_cost=$9.154403, processed=7655]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  97%|█████████▋| 7656/7886 [29:15<05:05,  1.33s/it, total_cost=$9.155685, processed=7656]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7657/7886 [29:17<04:54,  1.29s/it, total_cost=$9.156910, processed=7657]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7658/7886 [29:18<05:01,  1.32s/it, total_cost=$9.158133, processed=7658]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  97%|█████████▋| 7659/7886 [29:19<04:52,  1.29s/it, total_cost=$9.159233, processed=7659]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  97%|█████████▋| 7660/7886 [29:20<04:39,  1.24s/it, total_cost=$9.160465, processed=7660]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7661/7886 [29:23<05:51,  1.56s/it, total_cost=$9.161658, processed=7661]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7662/7886 [29:24<05:23,  1.44s/it, total_cost=$9.162880, processed=7662]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7663/7886 [29:25<05:09,  1.39s/it, total_cost=$9.164100, processed=7663]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7664/7886 [29:26<04:47,  1.29s/it, total_cost=$9.165945, processed=7664]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7665/7886 [29:27<04:37,  1.26s/it, total_cost=$9.167140, processed=7665]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7666/7886 [29:30<05:47,  1.58s/it, total_cost=$9.168413, processed=7666]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7667/7886 [29:31<05:21,  1.47s/it, total_cost=$9.169610, processed=7667]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  97%|█████████▋| 7668/7886 [29:32<05:07,  1.41s/it, total_cost=$9.170838, processed=7668]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  97%|█████████▋| 7669/7886 [29:33<04:42,  1.30s/it, total_cost=$9.172035, processed=7669]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7670/7886 [29:35<04:38,  1.29s/it, total_cost=$9.173308, processed=7670]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7671/7886 [29:36<04:47,  1.34s/it, total_cost=$9.174700, processed=7671]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  97%|█████████▋| 7672/7886 [29:37<04:43,  1.33s/it, total_cost=$9.175980, processed=7672]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7673/7886 [29:38<04:32,  1.28s/it, total_cost=$9.177190, processed=7673]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7674/7886 [29:40<04:26,  1.26s/it, total_cost=$9.178470, processed=7674]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7675/7886 [29:41<04:17,  1.22s/it, total_cost=$9.179675, processed=7675]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7676/7886 [29:43<04:57,  1.42s/it, total_cost=$9.180873, processed=7676]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  97%|█████████▋| 7677/7886 [29:44<04:39,  1.34s/it, total_cost=$9.182075, processed=7677]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7678/7886 [29:45<04:15,  1.23s/it, total_cost=$9.183148, processed=7678]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  97%|█████████▋| 7679/7886 [29:46<04:04,  1.18s/it, total_cost=$9.184293, processed=7679]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  97%|█████████▋| 7680/7886 [29:47<04:01,  1.17s/it, total_cost=$9.185800, processed=7680]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7681/7886 [29:48<04:00,  1.18s/it, total_cost=$9.186973, processed=7681]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7682/7886 [29:49<04:02,  1.19s/it, total_cost=$9.188213, processed=7682]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  97%|█████████▋| 7683/7886 [29:51<04:01,  1.19s/it, total_cost=$9.190473, processed=7683]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  97%|█████████▋| 7684/7886 [29:52<04:14,  1.26s/it, total_cost=$9.191765, processed=7684]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7685/7886 [29:54<04:56,  1.47s/it, total_cost=$9.192950, processed=7685]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  97%|█████████▋| 7686/7886 [29:56<04:32,  1.36s/it, total_cost=$9.194230, processed=7686]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  97%|█████████▋| 7687/7886 [29:57<05:00,  1.51s/it, total_cost=$9.195480, processed=7687]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  97%|█████████▋| 7688/7886 [29:59<05:09,  1.56s/it, total_cost=$9.196918, processed=7688]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7689/7886 [30:01<05:37,  1.71s/it, total_cost=$9.198020, processed=7689]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7690/7886 [30:03<06:33,  2.01s/it, total_cost=$9.199128, processed=7690]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7691/7886 [30:05<05:41,  1.75s/it, total_cost=$9.200393, processed=7691]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7692/7886 [30:06<05:20,  1.65s/it, total_cost=$9.201703, processed=7692]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7693/7886 [30:09<06:25,  2.00s/it, total_cost=$9.202840, processed=7693]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7694/7886 [30:11<05:49,  1.82s/it, total_cost=$9.204063, processed=7694]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  98%|█████████▊| 7695/7886 [30:12<06:08,  1.93s/it, total_cost=$9.205220, processed=7695]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  98%|█████████▊| 7696/7886 [30:14<06:12,  1.96s/it, total_cost=$9.206425, processed=7696]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7697/7886 [30:17<06:06,  1.94s/it, total_cost=$9.207780, processed=7697]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7698/7886 [30:19<06:23,  2.04s/it, total_cost=$9.208913, processed=7698]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7699/7886 [30:20<05:34,  1.79s/it, total_cost=$9.210185, processed=7699]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7700/7886 [30:21<04:56,  1.59s/it, total_cost=$9.211345, processed=7700]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7701/7886 [30:22<04:41,  1.52s/it, total_cost=$9.212515, processed=7701]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7702/7886 [30:23<04:20,  1.42s/it, total_cost=$9.213575, processed=7702]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7703/7886 [30:24<04:05,  1.34s/it, total_cost=$9.214828, processed=7703]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7704/7886 [30:27<04:44,  1.56s/it, total_cost=$9.215975, processed=7704]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7705/7886 [30:28<04:30,  1.50s/it, total_cost=$9.217260, processed=7705]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7706/7886 [30:30<04:43,  1.57s/it, total_cost=$9.218460, processed=7706]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7707/7886 [30:31<04:19,  1.45s/it, total_cost=$9.219713, processed=7707]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7708/7886 [30:32<04:03,  1.37s/it, total_cost=$9.220843, processed=7708]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7709/7886 [30:34<03:57,  1.34s/it, total_cost=$9.222045, processed=7709]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  98%|█████████▊| 7710/7886 [30:36<05:27,  1.86s/it, total_cost=$9.223338, processed=7710]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7711/7886 [30:38<04:48,  1.65s/it, total_cost=$9.224630, processed=7711]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7712/7886 [30:39<04:21,  1.50s/it, total_cost=$9.225840, processed=7712]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  98%|█████████▊| 7713/7886 [30:40<04:13,  1.46s/it, total_cost=$9.227033, processed=7713]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7714/7886 [30:42<04:14,  1.48s/it, total_cost=$9.228338, processed=7714]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  98%|█████████▊| 7715/7886 [30:44<03:57,  1.39s/it, total_cost=$9.229460, processed=7715]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7716/7886 [30:46<05:05,  1.80s/it, total_cost=$9.230708, processed=7716]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7717/7886 [30:47<04:55,  1.75s/it, total_cost=$9.231890, processed=7717]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7718/7886 [30:48<04:29,  1.60s/it, total_cost=$9.233563, processed=7718]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7719/7886 [30:50<04:10,  1.50s/it, total_cost=$9.234818, processed=7719]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7720/7886 [30:51<04:03,  1.47s/it, total_cost=$9.236053, processed=7720]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7721/7886 [30:52<03:51,  1.40s/it, total_cost=$9.237325, processed=7721]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7722/7886 [30:54<03:36,  1.32s/it, total_cost=$9.238523, processed=7722]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  98%|█████████▊| 7723/7886 [30:55<03:35,  1.32s/it, total_cost=$9.239735, processed=7723]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7724/7886 [30:56<03:30,  1.30s/it, total_cost=$9.241095, processed=7724]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7725/7886 [30:57<03:27,  1.29s/it, total_cost=$9.242328, processed=7725]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7726/7886 [30:59<03:24,  1.28s/it, total_cost=$9.243605, processed=7726]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7727/7886 [31:01<04:07,  1.56s/it, total_cost=$9.244863, processed=7727]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  98%|█████████▊| 7728/7886 [31:02<03:47,  1.44s/it, total_cost=$9.245928, processed=7728]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7729/7886 [31:03<03:38,  1.39s/it, total_cost=$9.247228, processed=7729]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  98%|█████████▊| 7730/7886 [31:05<03:27,  1.33s/it, total_cost=$9.248345, processed=7730]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7731/7886 [31:06<03:29,  1.35s/it, total_cost=$9.249733, processed=7731]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7732/7886 [31:07<03:19,  1.29s/it, total_cost=$9.250868, processed=7732]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7733/7886 [31:09<04:08,  1.62s/it, total_cost=$9.252005, processed=7733]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7734/7886 [31:11<03:48,  1.50s/it, total_cost=$9.253170, processed=7734]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7735/7886 [31:12<03:45,  1.50s/it, total_cost=$9.254428, processed=7735]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7736/7886 [31:14<04:04,  1.63s/it, total_cost=$9.255553, processed=7736]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7737/7886 [31:15<03:45,  1.52s/it, total_cost=$9.256778, processed=7737]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  98%|█████████▊| 7738/7886 [31:16<03:27,  1.40s/it, total_cost=$9.257888, processed=7738]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7739/7886 [31:17<03:11,  1.30s/it, total_cost=$9.259013, processed=7739]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7740/7886 [31:19<03:05,  1.27s/it, total_cost=$9.260153, processed=7740]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7741/7886 [31:20<03:00,  1.25s/it, total_cost=$9.261305, processed=7741]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7742/7886 [31:21<02:52,  1.20s/it, total_cost=$9.262448, processed=7742]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7743/7886 [31:22<02:57,  1.24s/it, total_cost=$9.263730, processed=7743]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  98%|█████████▊| 7744/7886 [31:24<02:57,  1.25s/it, total_cost=$9.264840, processed=7744]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7745/7886 [31:25<02:59,  1.27s/it, total_cost=$9.266058, processed=7745]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  98%|█████████▊| 7746/7886 [31:26<02:56,  1.26s/it, total_cost=$9.267285, processed=7746]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7747/7886 [31:27<02:58,  1.29s/it, total_cost=$9.268730, processed=7747]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7748/7886 [31:29<02:59,  1.30s/it, total_cost=$9.269960, processed=7748]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7749/7886 [31:30<02:53,  1.26s/it, total_cost=$9.271098, processed=7749]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7750/7886 [31:31<02:44,  1.21s/it, total_cost=$9.272310, processed=7750]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  98%|█████████▊| 7751/7886 [31:32<02:42,  1.21s/it, total_cost=$9.273590, processed=7751]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7752/7886 [31:34<02:46,  1.24s/it, total_cost=$9.274848, processed=7752]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  98%|█████████▊| 7753/7886 [31:35<02:46,  1.25s/it, total_cost=$9.275995, processed=7753]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  98%|█████████▊| 7754/7886 [31:36<02:56,  1.34s/it, total_cost=$9.277145, processed=7754]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  98%|█████████▊| 7755/7886 [31:38<02:48,  1.28s/it, total_cost=$9.278418, processed=7755]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7756/7886 [31:39<02:48,  1.30s/it, total_cost=$9.279750, processed=7756]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7757/7886 [31:40<03:00,  1.40s/it, total_cost=$9.280868, processed=7757]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  98%|█████████▊| 7758/7886 [31:42<02:50,  1.33s/it, total_cost=$9.282070, processed=7758]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  98%|█████████▊| 7759/7886 [31:43<02:46,  1.31s/it, total_cost=$9.283193, processed=7759]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7760/7886 [31:44<02:43,  1.30s/it, total_cost=$9.284375, processed=7760]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  98%|█████████▊| 7761/7886 [31:45<02:38,  1.27s/it, total_cost=$9.285585, processed=7761]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  98%|█████████▊| 7762/7886 [31:47<02:31,  1.22s/it, total_cost=$9.286790, processed=7762]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7763/7886 [31:48<02:32,  1.24s/it, total_cost=$9.287965, processed=7763]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  98%|█████████▊| 7764/7886 [31:49<02:23,  1.18s/it, total_cost=$9.289080, processed=7764]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  98%|█████████▊| 7765/7886 [31:51<02:48,  1.39s/it, total_cost=$9.290143, processed=7765]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  98%|█████████▊| 7766/7886 [31:52<02:40,  1.33s/it, total_cost=$9.291298, processed=7766]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  98%|█████████▊| 7767/7886 [31:54<03:06,  1.57s/it, total_cost=$9.292585, processed=7767]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▊| 7768/7886 [31:55<02:57,  1.50s/it, total_cost=$9.293903, processed=7768]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▊| 7769/7886 [31:56<02:48,  1.44s/it, total_cost=$9.295213, processed=7769]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▊| 7770/7886 [31:58<02:35,  1.34s/it, total_cost=$9.296358, processed=7770]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▊| 7771/7886 [31:59<02:42,  1.42s/it, total_cost=$9.297668, processed=7771]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  99%|█████████▊| 7772/7886 [32:00<02:30,  1.32s/it, total_cost=$9.298963, processed=7772]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▊| 7773/7886 [32:02<02:23,  1.27s/it, total_cost=$9.300075, processed=7773]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▊| 7774/7886 [32:03<02:20,  1.26s/it, total_cost=$9.301268, processed=7774]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▊| 7775/7886 [32:04<02:24,  1.30s/it, total_cost=$9.302460, processed=7775]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▊| 7776/7886 [32:06<02:20,  1.27s/it, total_cost=$9.303690, processed=7776]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  99%|█████████▊| 7777/7886 [32:07<02:30,  1.38s/it, total_cost=$9.304933, processed=7777]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  99%|█████████▊| 7778/7886 [32:08<02:23,  1.33s/it, total_cost=$9.306343, processed=7778]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▊| 7779/7886 [32:10<02:22,  1.34s/it, total_cost=$9.307628, processed=7779]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▊| 7780/7886 [32:12<02:44,  1.56s/it, total_cost=$9.308758, processed=7780]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▊| 7781/7886 [32:13<02:29,  1.42s/it, total_cost=$9.309950, processed=7781]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▊| 7782/7886 [32:15<02:41,  1.56s/it, total_cost=$9.311128, processed=7782]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▊| 7783/7886 [32:16<02:43,  1.59s/it, total_cost=$9.312335, processed=7783]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  99%|█████████▊| 7784/7886 [32:18<02:30,  1.47s/it, total_cost=$9.313573, processed=7784]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  99%|█████████▊| 7785/7886 [32:20<02:49,  1.67s/it, total_cost=$9.314860, processed=7785]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  99%|█████████▊| 7786/7886 [32:21<02:37,  1.58s/it, total_cost=$9.316140, processed=7786]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▊| 7787/7886 [32:22<02:30,  1.52s/it, total_cost=$9.317293, processed=7787]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7788/7886 [32:25<02:17,  1.40s/it, total_cost=$9.318398, processed=7788]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7789/7886 [32:27<03:04,  1.90s/it, total_cost=$9.319800, processed=7789]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▉| 7790/7886 [32:30<03:24,  2.13s/it, total_cost=$9.321035, processed=7790]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7791/7886 [32:31<03:24,  2.15s/it, total_cost=$9.322313, processed=7791]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▉| 7792/7886 [32:33<02:56,  1.88s/it, total_cost=$9.323655, processed=7792]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7793/7886 [32:35<03:09,  2.03s/it, total_cost=$9.324915, processed=7793]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7794/7886 [32:36<02:39,  1.74s/it, total_cost=$9.326038, processed=7794]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7795/7886 [32:37<02:24,  1.59s/it, total_cost=$9.327245, processed=7795]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7796/7886 [32:39<02:11,  1.47s/it, total_cost=$9.328448, processed=7796]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7797/7886 [32:40<02:02,  1.37s/it, total_cost=$9.329605, processed=7797]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s:  99%|█████████▉| 7798/7886 [32:41<02:01,  1.38s/it, total_cost=$9.330793, processed=7798]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▉| 7799/7886 [32:42<01:56,  1.34s/it, total_cost=$9.332020, processed=7799]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  99%|█████████▉| 7800/7886 [32:44<02:05,  1.46s/it, total_cost=$9.333240, processed=7800]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7801/7886 [32:45<02:00,  1.41s/it, total_cost=$9.334590, processed=7801]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7802/7886 [32:47<01:53,  1.35s/it, total_cost=$9.335745, processed=7802]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7803/7886 [32:48<01:50,  1.33s/it, total_cost=$9.336938, processed=7803]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  99%|█████████▉| 7804/7886 [32:49<01:48,  1.32s/it, total_cost=$9.338133, processed=7804]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▉| 7805/7886 [32:50<01:44,  1.29s/it, total_cost=$9.339388, processed=7805]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7806/7886 [32:53<02:02,  1.53s/it, total_cost=$9.340690, processed=7806]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  99%|█████████▉| 7807/7886 [32:54<01:54,  1.45s/it, total_cost=$9.341878, processed=7807]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7808/7886 [32:55<01:49,  1.40s/it, total_cost=$9.343058, processed=7808]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▉| 7809/7886 [32:56<01:41,  1.32s/it, total_cost=$9.344275, processed=7809]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7810/7886 [32:58<01:36,  1.27s/it, total_cost=$9.345480, processed=7810]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  99%|█████████▉| 7811/7886 [32:59<01:40,  1.34s/it, total_cost=$9.346883, processed=7811]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7812/7886 [33:00<01:39,  1.34s/it, total_cost=$9.348085, processed=7812]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7813/7886 [33:01<01:32,  1.27s/it, total_cost=$9.349215, processed=7813]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  99%|█████████▉| 7814/7886 [33:03<01:45,  1.46s/it, total_cost=$9.350358, processed=7814]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7815/7886 [33:05<01:39,  1.40s/it, total_cost=$9.351565, processed=7815]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▉| 7816/7886 [33:06<01:46,  1.53s/it, total_cost=$9.352800, processed=7816]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  99%|█████████▉| 7817/7886 [33:08<01:42,  1.48s/it, total_cost=$9.353908, processed=7817]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▉| 7818/7886 [33:09<01:34,  1.39s/it, total_cost=$9.355080, processed=7818]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  99%|█████████▉| 7819/7886 [33:10<01:28,  1.32s/it, total_cost=$9.356198, processed=7819]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  99%|█████████▉| 7820/7886 [33:12<01:31,  1.38s/it, total_cost=$9.357360, processed=7820]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7821/7886 [33:13<01:28,  1.36s/it, total_cost=$9.358523, processed=7821]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7822/7886 [33:14<01:23,  1.31s/it, total_cost=$9.359718, processed=7822]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7823/7886 [33:16<01:22,  1.31s/it, total_cost=$9.362045, processed=7823]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▉| 7824/7886 [33:17<01:34,  1.53s/it, total_cost=$9.363218, processed=7824]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7825/7886 [33:19<01:42,  1.69s/it, total_cost=$9.364385, processed=7825]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  99%|█████████▉| 7826/7886 [33:21<01:31,  1.53s/it, total_cost=$9.365625, processed=7826]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7827/7886 [33:22<01:26,  1.46s/it, total_cost=$9.366938, processed=7827]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7828/7886 [33:24<01:32,  1.59s/it, total_cost=$9.368215, processed=7828]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7829/7886 [33:25<01:24,  1.47s/it, total_cost=$9.369288, processed=7829]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  99%|█████████▉| 7830/7886 [33:27<01:22,  1.48s/it, total_cost=$9.370500, processed=7830]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▉| 7831/7886 [33:28<01:26,  1.58s/it, total_cost=$9.371640, processed=7831]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▉| 7832/7886 [33:30<01:22,  1.53s/it, total_cost=$9.372888, processed=7832]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s:  99%|█████████▉| 7833/7886 [33:32<01:23,  1.58s/it, total_cost=$9.374070, processed=7833]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s:  99%|█████████▉| 7834/7886 [33:33<01:21,  1.56s/it, total_cost=$9.375270, processed=7834]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7835/7886 [33:35<01:21,  1.60s/it, total_cost=$9.376613, processed=7835]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7836/7886 [33:36<01:15,  1.51s/it, total_cost=$9.377828, processed=7836]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  99%|█████████▉| 7837/7886 [33:37<01:15,  1.55s/it, total_cost=$9.379055, processed=7837]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s:  99%|█████████▉| 7838/7886 [33:39<01:14,  1.55s/it, total_cost=$9.380385, processed=7838]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  99%|█████████▉| 7839/7886 [33:41<01:17,  1.65s/it, total_cost=$9.381575, processed=7839]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s:  99%|█████████▉| 7840/7886 [33:42<01:12,  1.57s/it, total_cost=$9.382793, processed=7840]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s:  99%|█████████▉| 7841/7886 [33:45<01:15,  1.68s/it, total_cost=$9.384003, processed=7841]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s:  99%|█████████▉| 7842/7886 [33:47<01:21,  1.86s/it, total_cost=$9.385343, processed=7842]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s:  99%|█████████▉| 7843/7886 [33:49<01:21,  1.89s/it, total_cost=$9.386600, processed=7843]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s:  99%|█████████▉| 7844/7886 [33:51<01:23,  1.99s/it, total_cost=$9.387720, processed=7844]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s:  99%|█████████▉| 7845/7886 [33:52<01:13,  1.79s/it, total_cost=$9.388883, processed=7845]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s:  99%|█████████▉| 7846/7886 [33:54<01:11,  1.79s/it, total_cost=$9.390138, processed=7846]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s: 100%|█████████▉| 7847/7886 [33:55<01:05,  1.68s/it, total_cost=$9.391253, processed=7847]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s: 100%|█████████▉| 7848/7886 [33:57<01:10,  1.85s/it, total_cost=$9.392623, processed=7848]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s: 100%|█████████▉| 7849/7886 [33:59<01:01,  1.67s/it, total_cost=$9.393768, processed=7849]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s: 100%|█████████▉| 7850/7886 [34:01<01:04,  1.79s/it, total_cost=$9.395018, processed=7850]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s: 100%|█████████▉| 7851/7886 [34:03<01:02,  1.79s/it, total_cost=$9.396270, processed=7851]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s: 100%|█████████▉| 7852/7886 [34:05<01:03,  1.86s/it, total_cost=$9.397548, processed=7852]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7853/7886 [34:07<01:05,  1.98s/it, total_cost=$9.398793, processed=7853]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s: 100%|█████████▉| 7854/7886 [34:09<01:05,  2.05s/it, total_cost=$9.400180, processed=7854]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s: 100%|█████████▉| 7855/7886 [34:11<01:04,  2.09s/it, total_cost=$9.401393, processed=7855]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7856/7886 [34:13<01:01,  2.04s/it, total_cost=$9.402668, processed=7856]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s: 100%|█████████▉| 7857/7886 [34:15<01:00,  2.07s/it, total_cost=$9.403895, processed=7857]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s: 100%|█████████▉| 7858/7886 [34:17<00:56,  2.03s/it, total_cost=$9.405125, processed=7858]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s: 100%|█████████▉| 7859/7886 [34:19<00:55,  2.05s/it, total_cost=$9.406293, processed=7859]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s: 100%|█████████▉| 7860/7886 [34:21<00:46,  1.78s/it, total_cost=$9.407475, processed=7860]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s: 100%|█████████▉| 7861/7886 [34:23<00:49,  1.97s/it, total_cost=$9.408798, processed=7861]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s: 100%|█████████▉| 7862/7886 [34:25<00:47,  1.98s/it, total_cost=$9.410208, processed=7862]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.08s: 100%|█████████▉| 7863/7886 [34:27<00:44,  1.95s/it, total_cost=$9.411438, processed=7863]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.10s: 100%|█████████▉| 7864/7886 [34:29<00:43,  1.99s/it, total_cost=$9.412638, processed=7864]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7865/7886 [34:31<00:41,  1.98s/it, total_cost=$9.413790, processed=7865]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s: 100%|█████████▉| 7866/7886 [34:33<00:39,  1.97s/it, total_cost=$9.414885, processed=7866]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7867/7886 [34:35<00:36,  1.95s/it, total_cost=$9.416460, processed=7867]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.16s: 100%|█████████▉| 7868/7886 [34:37<00:35,  1.98s/it, total_cost=$9.417618, processed=7868]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7869/7886 [34:38<00:32,  1.90s/it, total_cost=$9.418848, processed=7869]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s: 100%|█████████▉| 7870/7886 [34:41<00:30,  1.92s/it, total_cost=$9.420098, processed=7870]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s: 100%|█████████▉| 7871/7886 [34:43<00:30,  2.06s/it, total_cost=$9.421358, processed=7871]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s: 100%|█████████▉| 7872/7886 [34:45<00:29,  2.12s/it, total_cost=$9.422680, processed=7872]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s: 100%|█████████▉| 7873/7886 [34:47<00:25,  1.95s/it, total_cost=$9.423848, processed=7873]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s: 100%|█████████▉| 7874/7886 [34:49<00:23,  1.98s/it, total_cost=$9.424985, processed=7874]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s: 100%|█████████▉| 7875/7886 [34:51<00:21,  1.99s/it, total_cost=$9.426293, processed=7875]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.12s: 100%|█████████▉| 7876/7886 [34:53<00:19,  1.92s/it, total_cost=$9.427513, processed=7876]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.15s: 100%|█████████▉| 7877/7886 [34:54<00:16,  1.87s/it, total_cost=$9.428708, processed=7877]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7878/7886 [34:56<00:15,  1.93s/it, total_cost=$9.430275, processed=7878]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7879/7886 [34:58<00:12,  1.78s/it, total_cost=$9.431538, processed=7879]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.07s: 100%|█████████▉| 7880/7886 [35:00<00:11,  1.89s/it, total_cost=$9.432710, processed=7880]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.11s: 100%|█████████▉| 7881/7886 [35:02<00:09,  1.87s/it, total_cost=$9.433850, processed=7881]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.09s: 100%|█████████▉| 7882/7886 [35:04<00:07,  1.88s/it, total_cost=$9.434953, processed=7882]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.06s: 100%|█████████▉| 7883/7886 [35:05<00:05,  1.85s/it, total_cost=$9.436178, processed=7883]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.14s: 100%|█████████▉| 7884/7886 [35:07<00:03,  1.86s/it, total_cost=$9.437500, processed=7884]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s: 100%|█████████▉| 7885/7886 [35:09<00:01,  1.90s/it, total_cost=$9.438723, processed=7885]

INFO:_client.py:1025: HTTP Request: POST https://tu-openai-api-management.azure-api.net/ltat-tartunlp/openai/deployments/EstNLTK-gpt-4o/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"

Sleeping 0.13s: 100%|██████████| 7886/7886 [35:10<00:00,  1.39s/it, total_cost=$9.439898, processed=7886]

Batch processing completed. Total cost: $9.439898
Finished. Processed 7886 rows. Results appended to: ..\outputs\gpt-4o-homonyms_LLM_MLM.json

In [23]:
# Open LLM sample annotation data
llm_samples_df = pd.read_json(output_file, orient="records")

new_records = []

# For each record, iterate over the candidates, construct the candidate sentence, and perform morphological analysis to extract the case and other features of the candidate replacement word. Assume each candidate has uniform probability and sum up the probabilities for candidates that match each form label to get a distribution of form labels for the candidates.
for index, row in tqdm.tqdm(llm_samples_df.iterrows(), total=llm_samples_df.shape[0]):
    id = row["sentence_id"]
    candidates = row.get("candidates", [])
    source_sentence = row["source_sentence"]
    target_word = row["target_word"]
    word_span = row["word_span"]
    label = row.get("label", [])[
        0
    ]  # Assuming label is a list and we take the first element as the form label
    # print(f"Source sentence: {source_sentence}")
    # print(f"Target word span: {word_span}")
    candidate_form_weight = (
        1 / len(candidates) if candidates else 0
    )  # Uniform weight for each candidate
    form_probabilities = {}
    for candidate in candidates:
        # Construct sentence with the candidate replacement
        candidate_sentence = (
            source_sentence[: word_span[0]]
            + candidate
            + source_sentence[word_span[1] :]
        )
        # print(f"Candidate sentence: {candidate_sentence}")
        # Create EstNLTK Text object and perform morphological analysis
        estnltk_text = estnltk.Text(candidate_sentence)
        estnltk_text.tag_layer("morph_analysis")
        # Extract the morphological tags for the candidate word
        morph_layer = estnltk_text.morph_analysis
        # Find the token in the morph layer that corresponds to the candidate replacement
        candidate_token = None
        for token in morph_layer:
            if (
                token.start <= word_span[0] < token.end
            ):  # Check if the token covers the start of the original word span
                candidate_token = token
                break
        if candidate_token:
            # Count up the form labels for the candidate
            number_of_labels = len(candidate_token.form) if candidate_token.form else 0
            if number_of_labels > 0:
                weight_per_label = candidate_form_weight / number_of_labels
                for candidate_label in candidate_token.form:
                    form_probabilities[candidate_label] = (
                        form_probabilities.get(candidate_label, 0) + weight_per_label
                    )
            else:
                form_probabilities["unknown"] = (
                    form_probabilities.get("unknown", 0) + candidate_form_weight
                )

    best_form_label = (
        max(form_probabilities, key=form_probabilities.get)
        if form_probabilities
        else "unknown"
    )
    # Create a record for the chosen candidate and its features
    candidate_record = {
        "id": id,
        "candidates": candidates,
        "pred_label": best_form_label,
        "true_label": label,
        "predicted_form_distribution": form_probabilities,
        "source_sentence": source_sentence,
        "target_word": target_word,
        "word_span": word_span,
    }
    new_records.append(candidate_record)

100%|██████████| 7886/7886 [07:52<00:00, 16.67it/s]

In [24]:
# Create a new DataFrame from the predicted form labels and their distributions and save to JSON
homonym_results_df = pd.DataFrame(new_records)
homonym_results_df_path = (
    HOMONYMS_DIRS["processed"] / "homonyms_llm_mlm_predictions_full.parquet"
)
homonym_results_df.to_parquet(homonym_results_df_path, index=False)

In [25]:
client.close()

In [ ]:
# previous_created = -1
# if output_file_log.exists() and output_file.exists():
#     with open(output_file_log, "r", encoding="utf-8") as f:
#         with open(output_file, "r", encoding="utf-8") as f2:
#             # Check if each record in output has logs
#             # Check via candidate list
#             output_data = json.load(f2)
#             log_data = json.load(f)
#             output_candidates = {}
#             log_candidates = {}
#             for record in output_data:
#                 sentence_id = int(record.get("sentence_id", -1))
#                 candidates = record.get("candidates", [])
#                 output_candidates[sentence_id] = candidates
#             for i, log_record in enumerate(log_data):
#                 candidates = log_record.get("choices")[0].get("message").get("content")
#                 # Parse the candidates from the log content
#                 candidate_data = json.loads(candidates)
#                 parsed_candidates = candidate_data.get("candidates")
#                 log_candidates[i] = parsed_candidates
#             for i in range(max(len(output_candidates), len(log_candidates))):
#                 output_cands = output_candidates.get(i)
#                 log_cands = log_candidates.get(i)
#                 if output_cands != log_cands:
#                     print(f"Mismatch in candidates for sentence_id={i}:")
#                     print(f"Output file candidates: {output_cands}")
#                     print(f"Log file candidates: {log_cands}")
#                     break

Mismatch in candidates for sentence_id=3710:
Output file candidates: ['Wiesenthali', 'Schindleri', 'Goldbergi', 'Edelsteini', 'Kaufmani', 'Liebmanni', 'Rosenbergi', 'Mendelsohni', 'Schwarzbergi', 'Leibovitsi']
Log file candidates: ['toimet', 'tagajärge', 'mõjust', 'tulemit', 'mõjuvõimu', 'tagasilööki', 'efekti', 'mõjujõudu', 'koormust', 'kõrvalnähtu']

In [ ]:
# # Estimate the total cost of the already processed sentences
# total_cost = 0.0  # Reset total cost for testing purposes
# enc = tiktoken.encoding_for_model(model_name)  # pick same model you'll use
# if output_file.exists() and output_file.stat().st_size > 0:
#     with open(output_file, "r", encoding="utf-8") as f:
#         data = json.load(f)
#         for row in data:
#             source_sentence = row.get("source_sentence", "")
#             word_span = row.get("word_span", [0, 0])
#             user_prompt = create_user_prompt(
#                 sentence=source_sentence, word_span=word_span
#             )
#             messages = build_messages(user_prompt)
#             # Calculate prompt tokens
#             # input cost
#             prompt_text = "".join(m["content"] for m in messages)
#             prompt_tokens = len(enc.encode(prompt_text)) + 30
#             input_cost = costs[model_name]["input"] * prompt_tokens
#             # cached input cost (not applicable in this case, but included for completeness)
#             cached_input_cost = 0.0
#             # output cost
#             prompt_text = '{"candidates":' + str(row.get("candidates", [])) + "}"
#             output_tokens = len(enc.encode(prompt_text)) - 8
#             output_cost = costs[model_name]["output"] * output_tokens
#             total_cost += input_cost + cached_input_cost + output_cost
#             # print(
#             #     f"Token counts for sentence_id={row.get('sentence_id', 'N/A')}: prompt_tokens={prompt_tokens}, output_tokens={output_tokens}"
#             # )
#             # print(
#             #     f"Costs for sentence_id={row.get('sentence_id', 'N/A')}: input_cost=${input_cost:.6f}, cached_input_cost=${cached_input_cost:.6f}, output_cost=${output_cost:.6f}"
#             # )
#             # print(
#             #     f"Estimated cost for sentence_id={row.get('sentence_id', 'N/A')}: ${input_cost + cached_input_cost + output_cost:.6f}"
#             # )
# print(f"Total estimated cost for already processed sentences: ${total_cost:.6f}")

Total estimated cost for already processed sentences: $7.299983

### BERT-LLM-morph Batch request

In [3]:
client = AzureOpenAI(
    api_version=api_version,
    azure_endpoint=endpoint,
    api_key=api_key,
)

In [4]:
system_prompt = """You are an Estonian sentence rewriting assistant.
Your task is to select the best 5 candidates from the provided 25 BERT candidates to replace the marked word <...> in the sentence.

Rules:
- Do not invent new candidates.
- Preserve the word's tense, number, case agreement, punctuation, and capitalisation.
- Return candidates that fit naturally and grammatically in one of these cases: nominative, genitive, partitive, or additive/illative.
- For proper names, keep only proper-name candidates that fit the same grammatical context.
- If fewer than 5 valid candidates exist, return as many as possible.
- Order candidates from best to worst fit.
- Do not repeat the original word unless it is the only valid option.
"""

# Structured output format for Azure OpenAI chat completions.
# Structured Outputs require a top-level object.
response_format = {
    "type": "json_schema",
    "json_schema": {
        "name": "bert_llm_selection",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "maxItems": 5,
                },
            },
            "required": ["candidates"],
            "additionalProperties": False,
        },
    },
}

# Few-shot example to anchor the output format
few_shot_user = """Sentence: "Ehk oleks mõttekas ka mõni selleteemaline hoiatav <kampaania> korraldada," lisab punase autoga preili.
Candidates: ['aktsioon', 'üritus', 'kampaania', 'sündmus', 'saade', 'koosolek', 'kõne', 'päev', 'postitus', 'artikkel', 'video', 'näitus', 'asi', 'lugu', 'teade', 'lugemine', 'leht', 'liiklus', 'hoiatus', 'uudis', 'post', 'teavitus', 'loeng', 'komm', 'akt']
"""

few_shot_assistant = json.dumps(
    {
        "candidates": [
            "aktsioon",
            "üritus",
            "sündmus",
            "näitus",
            "teade",
        ],
    },
    ensure_ascii=False,
    indent=2,
)


def filter_candidates(candidates: list[str]) -> list[str]:
    """Filter out candidates that are likely to be jailbreaks or otherwise invalid based on simple heuristics."""
    filtered = []
    for candidate in candidates:
        if not isinstance(candidate, str):
            continue  # Skip non-string candidates
        candidate_lower = candidate.lower()
        if any(
            marker in candidate_lower
            for marker in [
                "<s>",
                "</s>",
                "<pad>",
                "<unk>",
                "NOTUSED",
                "INVALID",
                "JAILBREAK",
                "HACK",
                "EXPLOIT",
            ]
        ):
            continue  # Skip candidates with suspicious markers
        if re.search(r"[<>/\\{}]", candidate):
            # Skip candidates containing special characters that could indicate an attempt to break the format or inject content
            continue
        if not any(ch.isalpha() for ch in candidate):
            # Skip candidates that don't contain any alphabetic characters, as they are unlikely to be valid word replacements
            continue
        filtered.append(candidate)
    return filtered


# Create a user prompt template for the real sentences, including candidates list.
def create_user_prompt(sentence: str, word_span: tuple, candidates: list[str]) -> str:
    """Create a user prompt with marked sentence and candidate list."""
    # Mark the target word with angle brackets
    start, end = word_span
    marked_sentence = (
        sentence[:start] + "<" + sentence[start:end] + ">" + sentence[end:]
    )
    # Filter jailbreak candidates
    candidates = filter_candidates(candidates)
    candidates_str = str(candidates)  # Simple list representation
    return f"""Sentence: {marked_sentence}
Candidates: {candidates_str}
"""


def build_messages(user_prompt: str) -> list[dict[str, str]]:
    """Build the chat-completions message list for one rewrite request."""
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": few_shot_user},
        {"role": "assistant", "content": few_shot_assistant},
        {"role": "user", "content": user_prompt},
    ]


def parse_response_content(content: str) -> dict[str, Any]:
    """Parse and validate the JSON payload returned by Azure OpenAI."""
    parsed = json.loads(content or "{}")
    if not isinstance(parsed, dict):
        raise ValueError("Expected a JSON object from the model response.")
    if "candidates" not in parsed or not isinstance(parsed["candidates"], list):
        raise ValueError("Model response did not contain a candidates list.")
    return parsed


def _atomic_write_json(file_path: pathlib.Path, data: list[dict[str, Any]]) -> None:
    """Write JSON atomically to avoid partial files on crash/interruption."""
    file_path.parent.mkdir(parents=True, exist_ok=True)
    temp_file_path: pathlib.Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=file_path.parent,
            prefix=f"{file_path.stem}.",
            suffix=".tmp",
            delete=False,
        ) as temp_file:
            json.dump(data, temp_file, ensure_ascii=False, indent=2)
            temp_file.flush()
            os.fsync(temp_file.fileno())
            temp_file_path = pathlib.Path(temp_file.name)

        # Atomic replace: after a crash you see either the old or the new file, never a partial one.
        os.replace(temp_file_path, file_path)
    finally:
        if temp_file_path is not None and temp_file_path.exists():
            temp_file_path.unlink(missing_ok=True)


def _load_results_json(file_path: pathlib.Path) -> list[dict[str, Any]]:
    """Load results JSON safely and fail closed on corruption to prevent silent data loss."""
    if not file_path.exists() or file_path.stat().st_size == 0:
        return []

    with open(file_path, "r", encoding="utf-8") as file_handle:
        try:
            loaded = json.load(file_handle)
        except json.JSONDecodeError as error:
            raise RuntimeError(
                f"Failed to parse existing output file {file_path}. "
                "Refusing to overwrite it to avoid data loss."
            ) from error

    if not isinstance(loaded, list):
        raise RuntimeError(
            f"Expected a JSON list in {file_path}, got {type(loaded).__name__}. "
            "Refusing to overwrite it to avoid data loss."
        )
    return loaded


def append_result_to_json(
    file_path: pathlib.Path, record: dict[str, Any], id: str | None = None
) -> None:
    """Append or update one record in a JSON array using crash-safe atomic writes."""
    resolved_path = pathlib.Path(file_path)
    data = _load_results_json(resolved_path)

    if id is not None:
        # If ID is provided, update matching record; otherwise append.
        existing_record = next(
            (
                r
                for r in data
                if isinstance(r, dict)
                and r.get("id") is not None
                and str(r.get("id")) == str(id)
            ),
            None,
        )
        if existing_record:
            existing_record.update(record)
            # Remove stale error after a successful rewrite.
            existing_record.pop("error", None)
        else:
            data.append(record)
    else:
        data.append(record)

    _atomic_write_json(resolved_path, data)


def write_total_cost(file_path: pathlib.Path, total_cost: float) -> None:
    """Write the total cost to a separate txt file."""
    resolved_path = pathlib.Path(file_path)
    resolved_path.parent.mkdir(parents=True, exist_ok=True)
    with open(resolved_path, "w", encoding="utf-8") as f:
        f.write(str(total_cost))


def rewrite_sentence_with_azure_openai(
    sentence_id: int,
    sentence: str,
    word_span: tuple,
    candidate_details: list[dict[str, Any]],
    metadata: dict[str, Any],
    candidates: list[str],
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Select best 5 BERT candidates via Azure OpenAI and derive predicted label from candidate scores."""
    user_prompt = create_user_prompt(
        sentence=sentence, word_span=word_span, candidates=candidates
    )
    messages = build_messages(user_prompt)

    # Request a structured JSON response from Azure OpenAI chat completions.
    response = client.chat.completions.create(
        model=deployment_name,
        messages=messages,
        response_format=response_format,
        max_completion_tokens=512,
        top_p=0.95,
    )

    # Estimate cost for this response (best-effort).
    try:
        cost_result = estimate_cost_typed(response)
        cost_info = cost_result.as_dict()  # Convert to dict for JSON serialization
    except Exception as _err:
        # Don't fail the rewrite on estimator errors; keep a surfacable error message.
        cost_info = {"error": str(_err)}

    message = response.choices[0].message
    refusal = getattr(message, "refusal", None)
    if refusal:
        raise RuntimeError(f"Model refused the request: {refusal}")

    # Parse the JSON response and enrich it with metadata for later analysis.
    parsed = parse_response_content(message.content or "{}")
    response_dict = response.to_dict()

    # Extract selected candidates and process BERT candidate details.
    selected_candidates = parsed.get("candidates", [])
    if not isinstance(selected_candidates, list):
        selected_candidates = []

    selected_candidate_details = [
        candidate
        for candidate in candidate_details
        if candidate.get("token") in selected_candidates
    ]

    # Normalise scores across selected candidates.
    selected_score_total = sum(
        candidate.get("score", 0.0) for candidate in selected_candidate_details
    )
    for candidate in selected_candidate_details:
        candidate_score = candidate.get("score", 0.0)
        candidate["normalised_score"] = (
            candidate_score / selected_score_total if selected_score_total > 0 else 0.0
        )

    # Derive morphological label predictions from selected candidate scores.
    predictions = {}
    for candidate in selected_candidate_details:
        resolved_form = candidate.get("resolved_form", [])
        if not resolved_form:
            continue
        label = resolved_form[0]
        predictions[label] = predictions.get(label, 0.0) + candidate["normalised_score"]

    predicted_label = max(predictions, key=predictions.get) if predictions else None

    # Enrich parsed response with metadata and analysis results.
    parsed["sentence_id"] = sentence_id
    parsed["candidate_details"] = selected_candidate_details
    parsed["predictions"] = predictions
    parsed["pred_label"] = predicted_label
    parsed["source_sentence"] = sentence
    parsed["target_word"] = metadata.get("target_word", "")

    if isinstance(word_span, list):
        parsed["word_span"] = word_span
    else:
        parsed["word_span"] = word_span.astype(
            int
        ).tolist()  # Convert numpy array to list for JSON serialization

    parsed["label"] = metadata.get("label", [])

    # Attach cost estimation metadata.
    response_dict["cost"] = cost_info

    return parsed, response_dict


# Backwards-compatible alias for any existing callers.
rewrite_sentence_with_genai = rewrite_sentence_with_azure_openai


def get_latest_processed_id(output_file):
    """Get the highest sentence ID that has already been processed and saved in the output file."""
    if output_file.exists() and output_file.stat().st_size > 0:
        with open(output_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            if isinstance(data, list) and len(data) > 0:
                return max(int(record["id"]) for record in data if "id" in record)
    return -1  # No valid records found, start from the beginning


def get_unprocessed_dataset(dataset, output_file):
    """Filter the dataset to include only records that have errors or have not been processed yet, based on the output file."""
    if output_file.exists() and output_file.stat().st_size > 0:
        unprocessed_records = []
        processed_records = []
        # First, get the list of sentences that have errors in the output file
        with open(output_file, "r", encoding="utf-8") as f:
            processed_data = json.load(f)
            for record in processed_data:
                if "error" in record:
                    unprocessed_records.append(record["source_sentence"])
                else:
                    processed_records.append(record["source_sentence"])
        # Now filter the original dataset to include only records that are either unprocessed or have errors
        filtered_dataset = dataset[
            dataset["sentence"].isin(unprocessed_records)
            | ~dataset["sentence"].isin(processed_records)
        ]
        return filtered_dataset
    return dataset  # If no output file exists, return the entire dataset for processing


def is_transient_error(exc: Exception) -> bool:
    """Heuristically detect retryable errors such as rate limit and network hiccups."""
    message = str(exc).lower()
    transient_markers = [
        "429",
        "rate",
        "quota",
        "too many requests",
        "timeout",
        "timed out",
        "connection",
        "temporar",
        "unavailable",
        "503",
        "502",
        "504",
        "internal",
    ]
    return any(marker in message for marker in transient_markers)


def rewrite_with_retry(
    sentence_id: int,
    sentence: str,
    word_span: tuple,
    candidate_details: list[dict[str, Any]],
    metadata: dict[str, Any],
    candidates: list[str],
    config: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Call rewrite function with exponential backoff on transient errors."""
    for attempt in range(1, config["max_attempts"] + 1):
        try:
            return rewrite_sentence_with_azure_openai(
                sentence_id=sentence_id,
                sentence=sentence,
                word_span=word_span,
                candidate_details=candidate_details,
                metadata=metadata,
                candidates=candidates,
            )
        except Exception as exc:
            should_retry = is_transient_error(exc) and attempt < config["max_attempts"]
            # should_retry = (
            #     attempt < config["max_attempts"]
            # )  # Retry on all exceptions for robustness, but still limit the number of attempts
            if not should_retry:
                raise
            backoff = min(
                config["max_backoff_seconds"],
                config["initial_backoff_seconds"] * (2 ** (attempt - 1)),
            )
            sleep_s = backoff + random.uniform(0.0, config["jitter_seconds"])
            print(
                f"Retry {attempt}/{config['max_attempts'] - 1} for sentence_id={sentence_id} "
                f"after transient error: {exc}. Sleeping {sleep_s:.2f}s..."
            )
            time.sleep(sleep_s)

In [5]:
bert_mlm_candidates_filepath = (
    HOMONYMS_DIRS["processed"] / "homonyms_bert_mlm_candidate_details_100.jsonl"
)
with open(bert_mlm_candidates_filepath, "r", encoding="utf-8") as f:
    bert_mlm_candidates_data = [json.loads(line) for line in f]

bert_mlm_candidates_df = pd.DataFrame(bert_mlm_candidates_data)

# Rename the "true_label" column to "label" to stay consistent with the rest of the code
bert_mlm_candidates_df.rename(columns={"true_label": "label"}, inplace=True)

display(bert_mlm_candidates_df.head(1))

   row_index  inflection_type  \
0          0                1

                                                                                                                                                                                                              sentence  \
0  Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.

     word word_span label predicted_best_label  predicted_best_label_score  \
0  võitja  [74, 80]  sg n                 sg n                     0.72215

                                                                                                                                                                                                                                      predicted_top_labels  \
0  [{'label': 'sg n', 'score': 0.7221502446191154}, {'label': 'sg g', 'score': 0.18655089150706772}, {'label': 'pl n', 'score': 0.031669486401369795}, {'label': 'nud', 'score': 0.03149387186567765}, {'label': 'sg tr', 'score': 0.0014702172484248877}]

                                                                                                                                                                                                    label_scores  \
0  {'sg n': 0.7221502446191154, 'sg g': 0.18655089150706772, 'nud': 0.03149387186567765, 'pl n': 0.031669486401369795, 'sg tr': 0.0014702172484248877, 'o': 0.00035745027707889676, 's': 0.00035488014691509306}


In [9]:
output_file = (
    OUTPUT_DIR / "gpt-4o-homonyms_BERT_MLM_to_LLM.json"
)  # Output file for results
output_file_log = (
    OUTPUT_DIR / "gpt-4o-homonyms_BERT_MLM_to_LLM_log.json"
)  # More detailed log file for debugging and analysis
total_cost_txt = (
    OUTPUT_DIR / "gpt-4o-homonyms_BERT_MLM_to_LLM_total_cost.txt"
)  # File to store the total cost information
sample_df = bert_mlm_candidates_df.iloc[:].copy()  # Use N for testing
sample_df["index"] = sample_df.index.astype(
    int
)  # Ensure index is an integer for ID purposes

# gpt-4o has following rate limits:
# - 180 000 tokens per minute (TPM)
# - 1080 requests per minute (RPM)
config = {
    # Pacing configuration to avoid hitting rate limits
    "base_delay_seconds": round(60 / 1080, 2),  # RPM is 1080 for gpt-4o
    "jitter_seconds": 0.1,  # Add a small random jitter to avoid thundering herd issues
    # Retry configuration for transient failures
    "max_attempts": 6,
    "initial_backoff_seconds": 2.0,
    "max_backoff_seconds": 60.0,
}

# Start from the next unprocessed sentence based on the output file contents
unprocessed_df = get_unprocessed_dataset(sample_df, output_file)
if len(unprocessed_df) == 0:
    print("No unprocessed sentences found. All done!")
else:
    print(f"Total unprocessed sentences to process: {len(unprocessed_df)}")
    print("Next sentence to process:")
    display(unprocessed_df.head(1))

# Find processed records that are in the sample_df
if output_file.exists() and output_file.stat().st_size > 0:
    with open(output_file, "r", encoding="utf-8") as f:
        processed_data = json.load(f)
        processed_ids = [
            int(record["sentence_id"])
            for record in processed_data
            if "sentence_id" in record
        ]
        processed_sentences = sample_df[sample_df["index"].isin(processed_ids)]
        print(
            f"Number of sentences in sample_df that have already been processed: {len(processed_sentences)}"
        )
        print("Sample of processed sentences:")
        display(sample_df[sample_df["index"].isin(processed_ids)].head(10))
else:
    processed_sentences = (
        pd.DataFrame()
    )  # Default to empty DataFrame if no output file exists
    print("No output file found, so no sentences have been processed yet.")

# Now remove all the already processed sentences from the output file that are not in the sample_df
# if output_file.exists() and output_file.stat().st_size > 0:
#     with open(output_file, "r", encoding="utf-8") as f:
#         processed_data = json.load(f)
#         processed_ids = [
#             int(record["sentence_id"])
#             for record in processed_data
#             if "sentence_id" in record
#         ]
#         filtered_data = [
#             record
#             for record in processed_data
#             if int(record.get("sentence_id", -1)) in sample_df["index"].values
#         ]
#     with open(output_file, "w", encoding="utf-8") as f:
#         json.dump(filtered_data, f, ensure_ascii=False, indent=2)

# Find cumulative total cost from the output file
total_cost = 0.0
if total_cost_txt.exists() and total_cost_txt.stat().st_size > 0:
    with open(total_cost_txt, "r", encoding="utf-8") as f:
        total_cost = float(f.read().strip())
        print(f"Cumulative total cost from log file: ${total_cost:.6f}")
else:
    print("No log file found, so cumulative cost is $0.00.")

Total unprocessed sentences to process: 2
Next sentence to process:

     row_index  inflection_type  \
296        296                1

                                                                                                                         sentence  \
296  (Algus lk. 5) "Võin teile vastata sõnaga, mida kasutan intervjuud andes väga harva : (teie poolt öeldu on) täielik nonsenss!

      word  word_span label predicted_best_label  predicted_best_label_score  \
296  öeldu  [97, 102]  sg n                 sg n                     0.30574

                                                                                                                                                                                                                                predicted_top_labels  \
296  [{'label': 'sg n', 'score': 0.3057395956129767}, {'label': 'pl n', 'score': 0.11585979379015043}, {'label': 'tud', 'score': 0.10208245331887156}, {'label': 'b', 'score': 0.04203795513603836}, {'label': 'vad', 'score': 0.03401518240571022}]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   label_scores  \
296  {'pl n': 0.11585979379015043, 'sg n': 0.3057395956129767, 'tud': 0.10208245331887156, 'b': 0.04203795513603836, 'vad': 0.03401518240571022, 'takse': 0.02752561680972576, 'des': 0.023742632009088993, 'sg es': 0.00836722832173109, 'ti': 0.007855487056076527, 'da': 0.009040222270414233, 'sg g': 0.0034738772083073854, 'sg tr': 0.0026254456024616957, 's': 0.004288185737095773, 'neg o': 0.0022131989244371653, 'neg': 0.0015161627670750022, 'n': 0.0013502751244232059, 'me': 0.0013301837025210261, 'sg p': 0.00211423949804157}


Number of sentences in sample_df that have already been processed: 7884
Sample of processed sentences:

   row_index  inflection_type  \
0          0                1
1          1                1
2          2                1
3          3                1
4          4                1
5          5                1
6          6                1
7          7                1
8          8                1
9          9                1

                                                                                                                                                                                                                                           sentence  \
0                               Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.
1                                                                                                            Normi-aktiveerimise teooria (Schwartz, 1970) on algselt mõeldud moraalse otsustamisprotsessi analüüsimiseks abistava käitumise näitel.
2                                                                                                                                             "Ehk oleks mõttekas ka mõni selleteemaline hoiatav kampaania korraldada," lisab punase autoga preili.
3                                                                                   "Minu otsus oli õige ning teeksin kõik sama moodi, kui saaksin uuesti teha," kommenteerib kolm aastat tagasi eriliste teenete eest Eesti passi saanud Primakov.
4                                                                               Itaalia president ütles Venemaa riigipea auks korraldatud suurejoonelisel banketil, et kahe riigi ühisavaldus Iraagi kohta oli kahe riigipea "suur tarkuseavaldus".
5                                                                                      Žüriis olid Ave Needo (Ruut FM), Aivo Tammela (Jüri noortemaja), Thea Tekkel (politsei esindaja), Margus Sõna (DJ School) ja Mario Liimann (OÜ Audiomeedia).
6                                                                                                              Samas teeb aga murelikuks asjaolu, et paljudes Araabia riikides kasvab rahva seas pahameel oma nn liiga Läänemeelse valitsuse vastu.
7                               Meri kinnitas eile Hamburgi linnapeale, et Eesti on valmis viisata suhtluseks kümmet Euroopa Liidu riiki ühendava Schengeni ühisviisaruumiga, sest Eesti piirikaitse on eeskujulik ja üks tänapäevasemaid Euroopas.
8  Siiditee John W. Orrison, endine CSX Transportationi presidendi abi, on rääkinud Wall Street Journalile, et kaupade eksportimine Hiinast ja Koreast Euroopa Liitu on piiramatu potentsiaaliga äri, kus liigub aastas kümneid miljardeid eurosid.
9                                                                                                                                                                                  Rahvusvaheline diplomaatia hoidis ära kahe naabri vahelise sõja.

          word   word_span label predicted_best_label  \
0       võitja    [74, 80]  sg n                 sg n
1      teooria    [20, 27]  sg n                 sg n
2    kampaania    [51, 60]  sg n                 sg n
3         õige    [16, 20]  sg n                 sg n
4      Itaalia      [0, 7]  sg g                 sg g
5        Mario  [125, 130]  sg n                 sg n
6      Araabia    [47, 54]  sg g                 sg g
7      Euroopa    [85, 92]  sg g                 sg g
8    piiramatu  [165, 174]  sg g                 sg g
9  diplomaatia    [15, 26]  sg n                 sg n

   predicted_best_label_score  \
0                    0.722150
1                    0.835027
2                    0.925145
3                    0.937690
4                    0.633394
5                    0.731673
6                    0.804141
7                    0.999933
8                    0.972653
9                    0.876886

                                                                                                                                                                                                                                              predicted_top_labels  \
0          [{'label': 'sg n', 'score': 0.7221502446191154}, {'label': 'sg g', 'score': 0.18655089150706772}, {'label': 'pl n', 'score': 0.031669486401369795}, {'label': 'nud', 'score': 0.03149387186567765}, {'label': 'sg tr', 'score': 0.0014702172484248877}]
1                                                          [{'label': 'sg n', 'score': 0.8350265937624499}, {'label': 'pl n', 'score': 0.03897170501295477}, {'label': 'sg g', 'score': 0.011666666658129543}, {'label': 'sg ad', 'score': 0.0036163415061309934}]
2                                                            [{'label': 'sg n', 'score': 0.9251450760057196}, {'label': 'sg g', 'score': 0.013393568340688944}, {'label': '?', 'score': 0.0015531816752627492}, {'label': 'sg p', 'score': 0.0008850809535942972}]
3           [{'label': 'sg n', 'score': 0.937689773486151}, {'label': 'pl n', 'score': 0.0059083469774729265}, {'label': 'tud', 'score': 0.004791804977382223}, {'label': 'sg p', 'score': 0.004379686346510425}, {'label': 'da', 'score': 0.0027839132235385478}]
4                                                              [{'label': 'sg g', 'score': 0.6333938237512484}, {'label': '?', 'score': 0.33930650624097325}, {'label': 'pl g', 'score': 0.014461975308222463}, {'label': 'sg n', 'score': 0.0003611558859120123}]
5                                                                                                                                                               [{'label': 'sg n', 'score': 0.7316727368161082}, {'label': 'sg g', 'score': 0.007352867629379034}]
6             [{'label': 'sg g', 'score': 0.8041406837801333}, {'label': '?', 'score': 0.11492913988877262}, {'label': 'pl in', 'score': 0.03877155072041205}, {'label': 'sg n', 'score': 0.009311669954210327}, {'label': 'pl n', 'score': 0.009071766457661095}]
7  [{'label': 'sg g', 'score': 0.9999333873498513}, {'label': '?', 'score': 2.4713935806275344e-05}, {'label': 'sg n', 'score': 1.5027668697283522e-05}, {'label': 'pl g', 'score': 1.4901468158967646e-05}, {'label': 'sg ill', 'score': 1.9783917650784133e-06}]
8    [{'label': 'sg g', 'score': 0.9726529849940562}, {'label': 'sg n', 'score': 0.022570988650841166}, {'label': 'pl n', 'score': 0.0002623763830342796}, {'label': 'pl g', 'score': 0.00020041059178765863}, {'label': 'sg p', 'score': 0.00017867725546238944}]
9                                                                                                              [{'label': 'sg n', 'score': 0.87688607966993}, {'label': 'pl n', 'score': 0.003051594365388155}, {'label': 'sg g', 'score': 0.0023830299032852054}]

                                                                                                                                                                                                                                                                                                                                                                                                                                            label_scores  \
0                                                                                                                                                                                                                                          {'sg n': 0.7221502446191154, 'sg g': 0.18655089150706772, 'nud': 0.03149387186567765, 'pl n': 0.031669486401369795, 'sg tr': 0.0014702172484248877, 'o': 0.00035745027707889676, 's': 0.00035488014691509306}
1                                                                                                                                                                                                                                                                                                                                {'sg n': 0.8350265937624499, 'pl n': 0.03897170501295477, 'sg g': 0.011666666658129543, 'sg ad': 0.0036163415061309934}
2                                                                                                                                                                                                                                                                                                                                  {'sg n': 0.9251450760057196, 'sg g': 0.013393568340688944, '?': 0.0015531816752627492, 'sg p': 0.0008850809535942972}
3                                                                                                                                                                                                                                       {'sg n': 0.937689773486151, 'pl n': 0.0059083469774729265, 'tud': 0.004791804977382223, 'sg p': 0.004379686346510425, 'da': 0.0027839132235385478, 'sg g': 0.0014248035149648786, 'nud': 0.00027981650782749057}
4                                                                                                                                                                                                                                                                                                                                    {'?': 0.33930650624097325, 'sg g': 0.6333938237512484, 'pl g': 0.014461975308222463, 'sg n': 0.0003611558859120123}
5                                                                                                                                                                                                                                                                                                                                                                                             {'sg n': 0.7316727368161082, 'sg g': 0.007352867629379034}
6                                                                                                                 {'sg g': 0.8041406837801333, '?': 0.11492913988877262, 'nud': 0.008400514348977596, 'pl n': 0.009071766457661095, 'sg n': 0.009311669954210327, 'pl in': 0.03877155072041205, 'tud': 0.0005694414236738037, 'pl g': 0.000530327179149026, 'pl el': 0.0006719314806105103, 'sg in': 0.0009488813775533345, 'adt': 0.000133970970637165}
7  {'sg g': 0.9999333873498513, 'pl g': 1.4901468158967646e-05, 'sg n': 1.5027668697283522e-05, '?': 2.4713935806275344e-05, 'sg ill': 1.9783917650784133e-06, 'sg in': 1.5135028661461547e-06, 'sg p': 1.1267234318879105e-06, 'sg el': 8.488981251275618e-08, 'sg all': 6.056696122413996e-08, 'pl n': 3.132157585146918e-08, 'neg': 3.771894796500419e-08, 'pl p': 2.7394914781098123e-08, 'tud': 5.21372041835851e-09, 'nud': 5.158209859246199e-09}
8                                                                                                                                                                                                                                 {'sg g': 0.9726529849940562, 'sg n': 0.022570988650841166, 'pl n': 0.0002623763830342796, 'tud': 0.00016885739872426106, 'pl g': 0.00020041059178765863, 'nud': 9.351898431001852e-05, 'sg p': 0.00017867725546238944}
9                                                                                                                                                                                                                                                                                                                                                                {'sg n': 0.87688607966993, 'pl n': 0.003051594365388155, 'sg g': 0.0023830299032852054}


Cumulative total cost from log file: $18.724012

In [7]:
create_user_prompt(
    sentence=unprocessed_df.iloc[0]["sentence"],
    word_span=unprocessed_df.iloc[0]["word_span"],
    candidates=[
        c.get("token")
        for c in unprocessed_df.iloc[0]["candidate_details"]
        if "token" in c
    ],
)

'Sentence: (Algus lk. 5) "Võin teile vastata sõnaga, mida kasutan intervjuud andes väga harva : (teie poolt <öeldu> on) täielik nonsenss!\nCandidates: [\'öeldud\', \'see\', \'on\', \'öeldakse\', \'nimetatud\', \'kirjutatud\', \'vastus\', \'öeldes\', \'mis\', \'kasutatud\', \'lause\', \'või\', \'kasutamine\', \'ja\', \'öel\', \'ütlemata\', \'valitud\', \'vaadatuna\', \'väidetud\', \'öeldi\', \'öelda\', \'antud\', \'tähendab\', \'sõna\', \'nimetamine\', \'mõeldud\', \'sõnad\', \'hääl\', \'vale\', \'mainitud\', \'valetamine\', \'esitatud\', \'õige\', \'ka\', \'olemine\', \'siis\', \'lisatud\', \'märgitud\', \'aga\', \'pöördumine\', \'väljendatud\', \'nagu\', \'kuidas\', \'lihtsalt\', \'vastuseks\', \'oli\', \'tehtud\', \'kasutades\', \'vastates\', \'pole\', \'kirjas\', \'et\', \'kirjutamine\', \'kirjutades\', \'avaldatud\', \'viisakas\', \'tsitaat\', \'siin\', \'ütles\', \'küsitud\', \'kas\', \'ei\', \'olev\', \'ta\', \'kes\', \'kasutatav\', \'kui\', \'alati\', \'ütlen\', \'vaadates\', \'ütlus\', \'toodud\', \'tegelikult\', \'ütleme\', \'suunatud\', \'kõik\', \'tõlge\', \'kasutatakse\', \'unustatud\', \'vist\', \'kommentaar\', \'kasutada\', \'tõlgitud\', \'loomulikult\', \'kustutatud\', \'midagi\', \'samuti\', \'ilmselt\', \'ütleb\', \'korrektne\', \'seda\']\n'

In [8]:
# Batch rewrite loop: call OpenAI and append each result to a JSON file
processed = len(processed_sentences)
max_cost = 20.0  # Set a maximum total cost threshold for the entire batch to avoid unexpected high costs during testing
with tqdm.tqdm(
    total=len(sample_df), desc="Processing sentences", initial=processed
) as pbar:
    for i, row in enumerate(
        zip(
            unprocessed_df["index"],
            unprocessed_df["sentence"],
            unprocessed_df["word_span"],
            unprocessed_df["word"],
            unprocessed_df["label"],
            unprocessed_df["candidate_details"],
        )
    ):
        sentence_id, sentence, word_span, word, label, candidate_details = row
        try:
            metadata = {"target_word": word, "label": label}
            candidates = [c.get("token") for c in candidate_details if "token" in c]
            result, response = rewrite_with_retry(
                sentence_id=sentence_id,
                sentence=sentence,
                word_span=word_span,
                candidate_details=candidate_details,
                metadata=metadata,
                candidates=candidates,
                config=config,
            )
            # Extract the parsed response (first element of tuple); ignore the response_dict for now
            parsed_result = result[0] if isinstance(result, tuple) else result
            append_result_to_json(output_file, parsed_result, id=sentence_id)
            append_result_to_json(
                output_file_log, response, id=sentence_id
            )  # Log the full response for debugging and analysis
            # Get the cost info from the result for logging
            cost_info = response.get("cost", {})
            if "error" in cost_info:
                tqdm.tqdm.write(
                    f"[{processed + 1}] Saved sentence_id={sentence_id} with cost estimation error: {cost_info['error']}"
                )
            else:
                total_cost_info = cost_info.get("total_cost", 0.0)
                total_cost += float(total_cost_info)
                write_total_cost(total_cost_txt, total_cost)
                # tqdm.tqdm.write(
                #     f"[{processed + 1}] Saved sentence_id={sentence_id} cost: {total_cost_info} total: {total_cost:.6f}"
                # )
        except Exception as exc:
            error_record = {
                "id": str(sentence_id),
                "source_sentence": sentence,
                "target_word": word,
                "word_span": word_span,
                "true_label": [label] if isinstance(label, str) else label.tolist(),
                "pred_label": None,
                "error": str(exc),
            }
            # append_result_to_json(output_file, error_record, id=sentence_id)
            # append_result_to_json(
            #     output_file_log, {"error": str(exc)}, id=sentence_id
            # )  # Log the error details in the log file as well
            tqdm.tqdm.write(
                f"[{processed + 1}] Error on sentence_id={sentence_id}: {exc}"
            )
            print("Error record:", error_record)
            print("Traceback:", exc.__traceback__)

        processed += 1
        # update postfix shown to the right of the bar
        pbar.set_postfix({"total_cost": f"${total_cost:.6f}", "processed": processed})
        pbar.update(1)

        if (
            total_cost > max_cost
        ):  # Stop the loop if total cost exceeds $20 to avoid unexpected high costs during testing
            print(
                f"Total cost exceeded ${max_cost}. Stopping the loop to avoid unexpected high costs during testing."
            )
            break

        # Additional pacing between successful/failed items to avoid bursty traffic.
        if i < len(unprocessed_df) - 1:  # Don't sleep after the last item
            sleep_s = config["base_delay_seconds"] + random.uniform(
                0.0, config["jitter_seconds"]
            )
            pbar.set_description_str(f"Sleeping {sleep_s:.2f}s")
            time.sleep(sleep_s)

print(f"Batch processing completed. Total cost: ${total_cost:.6f}")
print(f"Finished. Processed {processed} rows. Results appended to: {output_file}")

Sleeping 0.10s:  86%|████████▌ | 6762/7886 [00:01<21:32,  1.15s/it, total_cost=$16.007565, processed=6762]

[6762] Error on sentence_id=296: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400, 'innererror': {'code': 'ResponsibleAIPolicyViolation', 'content_filter_result': {'jailbreak': {'detected': True, 'filtered': True}}}}}
Error record: {'id': '296', 'source_sentence': '(Algus lk. 5) "Võin teile vastata sõnaga, mida kasutan intervjuud andes väga harva : (teie poolt öeldu on) täielik nonsenss!', 'target_word': 'öeldu', 'word_span': [97, 102], 'true_label': ['sg n'], 'pred_label': None, 'error': 'Error code: 400 - {\'error\': {\'message\': "The response was filtered due to the prompt triggering Azure OpenAI\'s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", \'type\': None, \'param\': \'prompt\', \'code\': \'content_filter\', \'status\': 400, \'innererror\': {\'code\': \'ResponsibleAIPolicyViolation\', \'content_filter_result\': {\'jailbreak\': {\'detected\': True, \'filtered\': True}}}}}'}
Traceback: <traceback object at 0x000001A20A109280>

Sleeping 0.06s:  86%|████████▌ | 6763/7886 [00:01<15:27,  1.21it/s, total_cost=$16.007565, processed=6763]

[6763] Error on sentence_id=668: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400, 'innererror': {'code': 'ResponsibleAIPolicyViolation', 'content_filter_result': {'jailbreak': {'detected': True, 'filtered': True}}}}}
Error record: {'id': '668', 'source_sentence': 'Sel juhul väldid olukorda, kus saad dünamo.', 'target_word': 'dünamo', 'word_span': [36, 42], 'true_label': ['sg g'], 'pred_label': None, 'error': 'Error code: 400 - {\'error\': {\'message\': "The response was filtered due to the prompt triggering Azure OpenAI\'s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", \'type\': None, \'param\': \'prompt\', \'code\': \'content_filter\', \'status\': 400, \'innererror\': {\'code\': \'ResponsibleAIPolicyViolation\', \'content_filter_result\': {\'jailbreak\': {\'detected\': True, \'filtered\': True}}}}}'}
Traceback: <traceback object at 0x000001A20A118B00>

Sleeping 0.12s: 100%|██████████| 7886/7886 [1:15:23<00:00,  4.02s/it, total_cost=$18.724012, processed=7886]

Batch processing completed. Total cost: $18.724012
Finished. Processed 7886 rows. Results appended to: C:\Users\sande\Git_projects\EstNLTK\EstNLTK_model_training\outputs\gpt-4o-homonyms_BERT_MLM_to_LLM.json

In [10]:
# Open LLM annotation data
llm_samples_df = pd.read_json(output_file, orient="records")

In [11]:
display(llm_samples_df.head(1))

,candidates,sentence_id,candidate_details,predictions,pred_label,source_sentence,target_word,word_span,label
0,"[võitnud, saaja, pälvinud, auhinna, tiitli]",0,"[{'rank': 3, 'token': 'auhinna', 'score': 0.056165203452110006, 'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri auhinna James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri auhinna James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_span': [74, 81], 'resolved_forms': ['sg g'], 'normalised_score': 0.43247800253933105}, {'rank': 4, 'token': 'võitnud', 'score': 0.05125705897808001, 'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitnud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitnud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_span': [74, 81], 'resolved_forms': ['nud', 'pl n', 'sg n'], 'normalised_score': 0.394684771359947}, {'rank': 7, 'token': 'pälvinud', 'score': 0.015388736501336, 'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri pälvinud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri pälvinud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_span': [74, 82], 'resolved_forms': ['nud', 'pl n', 'sg n'], 'normalised_score': 0.118494897456868}, {'rank': 9, 'token': 'saaja', 'score': 0.006725015118718001, 'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri saaja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri saaja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_span': [74, 79], 'resolved_forms': ['sg g'], 'normalised_score': 0.051783327163942}, {'rank': 58, 'token': 'tiitli', 'score': 0.000332333293044, 'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri tiitli James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri tiitli James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.', 'candidate_span': [74, 80], 'resolved_forms': ['sg g'], 'normalised_score': 0.002559001479909}]",{},NaN,"Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.",võitja,"[74, 80]",sg n

In [12]:
display(llm_samples_df.iloc[0]["candidate_details"])

[{'rank': 3,
  'token': 'auhinna',
  'score': 0.056165203452110006,
  'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri auhinna James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri auhinna James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_span': [74, 81],
  'resolved_forms': ['sg g'],
  'normalised_score': 0.43247800253933105},
 {'rank': 4,
  'token': 'võitnud',
  'score': 0.05125705897808001,
  'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitnud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri võitnud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_span': [74, 81],
  'resolved_forms': ['nud', 'pl n', 'sg n'],
  'normalised_score': 0.394684771359947},
 {'rank': 7,
  'token': 'pälvinud',
  'score': 0.015388736501336,
  'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri pälvinud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri pälvinud James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_span': [74, 82],
  'resolved_forms': ['nud', 'pl n', 'sg n'],
  'normalised_score': 0.118494897456868},
 {'rank': 9,
  'token': 'saaja',
  'score': 0.006725015118718001,
  'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri saaja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri saaja James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_span': [74, 79],
  'resolved_forms': ['sg g'],
  'normalised_score': 0.051783327163942},
 {'rank': 58,
  'token': 'tiitli',
  'score': 0.000332333293044,
  'sequence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri tiitli James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_sentence': 'Edinburghi agulite mehe Irvine Welshi ja Glasgow tööliskirjaniku, Bookeri tiitli James Kelmani puhul võib tõlketõrke tekitada keelekasutus - inglise inglise keelele demonstratiivselt vastanduv proletaarne Scots.',
  'candidate_span': [74, 80],
  'resolved_forms': ['sg g'],
  'normalised_score': 0.002559001479909}]

In [14]:
new_records = []

for index, row in tqdm.tqdm(llm_samples_df.iterrows(), total=llm_samples_df.shape[0]):
    id = row["sentence_id"]
    candidates = row.get("candidates", [])
    candidate_details = row.get("candidate_details", [])
    source_sentence = row["source_sentence"]
    target_word = row["target_word"]
    word_span = row["word_span"]
    label = row.get("label", [])[
        0
    ]  # Assuming label is a list and we take the first element as the form label
    # print(f"Source sentence: {source_sentence}")
    # print(f"Target word span: {word_span}")
    form_probabilities = {}
    for candidate in candidate_details:
        candidate_sentence = candidate.get("candidate_sentence")
        candidate_span = candidate.get("candidate_span", word_span)
        normalised_score = candidate.get("normalised_score", 0.0)
        # print(f"Candidate sentence: {candidate_sentence}")
        # Create EstNLTK Text object and perform morphological analysis
        estnltk_text = estnltk.Text(candidate_sentence)
        estnltk_text.tag_layer("morph_analysis")
        # Extract the morphological tags for the candidate word
        morph_layer = estnltk_text.morph_analysis
        # Find the token in the morph layer that corresponds to the candidate replacement
        candidate_token = None
        for token in morph_layer:
            if (
                token.start <= candidate_span[0] < token.end
            ):  # Check if the token covers the start of the original word span
                candidate_token = token
                break
        if candidate_token:
            # Count up the form labels for the candidate
            number_of_labels = len(candidate_token.form) if candidate_token.form else 0
            if number_of_labels > 0:
                # Distribute the normalised score equally among all form labels for this candidate
                weight_per_label = normalised_score / number_of_labels
                for candidate_label in candidate_token.form:
                    form_probabilities[candidate_label] = (
                        form_probabilities.get(candidate_label, 0) + weight_per_label
                    )
            else:
                form_probabilities["unknown"] = (
                    form_probabilities.get("unknown", 0) + normalised_score
                )

    best_form_label = (
        max(form_probabilities, key=form_probabilities.get)
        if form_probabilities
        else "unknown"
    )
    # Create a record for the chosen candidate and its features
    candidate_record = {
        "id": id,
        "candidates": candidates,
        "pred_label": best_form_label,
        "true_label": label,
        "predicted_form_distribution": form_probabilities,
        "source_sentence": source_sentence,
        "target_word": target_word,
        "word_span": word_span,
    }
    new_records.append(candidate_record)

100%|██████████| 7884/7884 [04:33<00:00, 28.79it/s]

In [15]:
# Create a new DataFrame from the predicted form labels and their distributions and save to JSON
homonym_results_df = pd.DataFrame(new_records)
homonym_results_df_path = (
    HOMONYMS_DIRS["processed"] / "homonyms_bert_mlm_llm_predictions_full.parquet"
)
homonym_results_df.to_parquet(homonym_results_df_path, index=False)

In [16]:
client.close()