In [1]:
"""
Smoke test: load a HF-format model and run a short prediction on a synthetic sentence.
"""
import pathlib
import torch
from transformers import AutoTokenizer, AutoModelForTokenClassification


def load_model(model_dir: str):
    tokenizer = AutoTokenizer.from_pretrained(model_dir, use_fast=True)
    model = AutoModelForTokenClassification.from_pretrained(model_dir)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    return model, tokenizer, device


def predict_words(model, tokenizer, device, words: list):
    enc = tokenizer(
        words, is_split_into_words=True, return_tensors="pt", truncation=True
    )
    enc = {k: v.to(device) for k, v in enc.items()}
    model.eval()
    with torch.no_grad():
        out = model(**enc)
        logits = out.logits.cpu().numpy()[0]

    word_ids = tokenizer(words, is_split_into_words=True)["input_ids"]
    # Use model.config.id2label when available
    cfg_id2label = getattr(model.config, "id2label", None)
    if cfg_id2label:
        id2label = {int(k): v for k, v in cfg_id2label.items()}
    else:
        id2label = None

    # Map per-token preds to first-subtoken-per-word labels
    tokens_word_ids = tokenizer(words, is_split_into_words=True).word_ids()
    preds = logits.argmax(axis=-1)
    word_preds = []
    previous_word = None
    for token_pred, widx in zip(preds, tokens_word_ids):
        if widx is None:
            previous_word = None
            continue
        if widx != previous_word:
            label = (
                id2label.get(int(token_pred), str(int(token_pred)))
                if id2label
                else str(int(token_pred))
            )
            word_preds.append(label)
        previous_word = widx

    return word_preds

In [ ]:
model_dir = pathlib.Path("../models/NER_mudel_v2/")
model, tokenizer, device = load_model(model_dir)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
sentence = "See on test lause"
words = sentence.split()
preds = predict_words(model, tokenizer, device, words)
print("Words:", words)
print("Predicted labels:", preds)

Words: ['See', 'on', 'test', 'lause']
Predicted labels: ['?', 'b_V', 'sg n_A', 'sg n_S']

## MorphHomonymsRetagger smoke test

In [1]:
import estnltk
from scripts.model.bert_morph_tagger import BertMorphTagger
from scripts.model.morph_homonyms_retagger import MorphHomonymsRetagger

bmt = BertMorphTagger("../models/NER_mudel_v2/")
mhr = MorphHomonymsRetagger("../models/NER_mudel_v2_homonym_full/")

e:\Git_projects\EstNLTK\simpletransformers\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
text = estnltk.Text(
    "Kas sa muna tahad? See muna on väga maitsev. Muna sees on kaks munakollast."
)
text.tag_layer("morph_analysis")
bmt.tag(text)
display(text.bert_morph_tagging)

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('Kas', [{'bert_tokens': ['▁Kas'], 'form': '', 'partofspeech': 'D', 'probability': 0.99996}]),
Span('sa', [{'bert_tokens': ['▁sa'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99992}]),
Span('muna', [{'bert_tokens': ['▁muna'], 'form': 'sg p', 'partofspeech': 'S', 'probability': 0.99981}]),
Span('tahad', [{'bert_tokens': ['▁tahad'], 'form': 'd', 'partofspeech': 'V', 'probability': 0.99865}]),
Span('?', [{'bert_tokens': ['?'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99992}]),
Span('See', [{'bert_tokens': ['▁See'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99991}]),
Span('muna', [{'bert_tokens': ['▁muna'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99985}]),
Span('on', [{'bert_tokens': ['▁on'], 'form': 'b', 'partofspeech': 'V', 'probability': 0.99996}]),
Span('väga', [{'bert_tokens': ['▁väga'], 'form': '', 'partofspeech': 'D', 'probability': 0.99996}]),
Span('maitsev', [{'bert_tokens': ['▁maitsev'], 'form': 'sg n', 'partofspeech': 'A', 'probability': 0.99991}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}]),
Span('Muna', [{'bert_tokens': ['▁Muna'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.9999}]),
Span('sees', [{'bert_tokens': ['▁sees'], 'form': '', 'partofspeech': 'K', 'probability': 0.99975}]),
Span('on', [{'bert_tokens': ['▁on'], 'form': 'b', 'partofspeech': 'V', 'probability': 0.99967}]),
Span('kaks', [{'bert_tokens': ['▁kaks'], 'form': 'sg n', 'partofspeech': 'N', 'probability': 0.99984}]),
Span('munakollast', [{'bert_tokens': ['▁muna', 'koll', 'ast'], 'form': 'sg p', 'partofspeech': 'S', 'probability': 0.99951}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}])])

In [10]:
mhr.retag(text)
display(text.bert_morph_tagging)

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('Kas', [{'bert_tokens': ['▁Kas'], 'form': '', 'partofspeech': 'D', 'probability': 0.99996}]),
Span('sa', [{'bert_tokens': ['▁sa'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99992}]),
Span('muna', [{'bert_tokens': ['▁muna'], 'form': 'sg p', 'partofspeech': 'S', 'probability': 0.99981}]),
Span('tahad', [{'bert_tokens': ['▁tahad'], 'form': 'd', 'partofspeech': 'V', 'probability': 0.99865}]),
Span('?', [{'bert_tokens': ['?'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99992}]),
Span('See', [{'bert_tokens': ['▁See'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99991}]),
Span('muna', [{'bert_tokens': ['▁muna'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.99985}]),
Span('on', [{'bert_tokens': ['▁on'], 'form': 'b', 'partofspeech': 'V', 'probability': 0.99996}]),
Span('väga', [{'bert_tokens': ['▁väga'], 'form': '', 'partofspeech': 'D', 'probability': 0.99996}]),
Span('maitsev', [{'bert_tokens': ['▁maitsev'], 'form': 'sg n', 'partofspeech': 'A', 'probability': 0.99991}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}]),
Span('Muna', [{'bert_tokens': ['▁Muna'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.9999}]),
Span('sees', [{'bert_tokens': ['▁sees'], 'form': '', 'partofspeech': 'K', 'probability': 0.99975}]),
Span('on', [{'bert_tokens': ['▁on'], 'form': 'b', 'partofspeech': 'V', 'probability': 0.99967}]),
Span('kaks', [{'bert_tokens': ['▁kaks'], 'form': 'sg n', 'partofspeech': 'N', 'probability': 0.99984}]),
Span('munakollast', [{'bert_tokens': ['▁muna', 'koll', 'ast'], 'form': 'sg p', 'partofspeech': 'S', 'probability': 0.99951}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}])])

In [11]:
display(text.bert_morph_tagging.meta)

{'morph_homonyms_retagger': {'inspected_words': 3,
  'corrected_words': 3,
  'homonym_list_size': 1296,
  'layer_to_change': 'bert_morph_tagging',
  'output_layer': 'bert_morph_tagging'}}