# Testing

In [ ]:
import os
import re
import csv
import typing
import itertools
import json
import logging
import warnings
import IPython.display
import torch
import evaluate
import pkg_resources
import types
import pandas as pd
import sklearn as sk
import numpy as np
import estnltk, estnltk.converters, estnltk.taggers
import math
import IPython

from tqdm import tqdm
from simpletransformers.ner import NERModel, NERArgs
from bert_morph_tagger import BertMorphTagger
from morph_eval_utils import (
    MorphDiffSummarizer,
    MorphDiffFinder,
    write_formatted_diff_str_to_file,
)
from est_ud_utils import (
    load_ud_file_texts_with_corrections,
    load_ud_file_with_corrections,
)
from est_ud_morph_conv import convert_ud_layer_to_reduced_morph_layer
from bert_morph_tagger_notebook_functions import NotebookFunctions

e:\Anaconda3\envs\gpulocal\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
from typing import MutableMapping, List

from estnltk import (
    Text,
    Layer,
    Tagger,
    ElementaryBaseSpan,
    EnvelopingBaseSpan,
    logger,
    Span,
)

# from estnltk_neural.taggers.embeddings.bert.bert_tokens_to_words_rewriter import BertTokens2WordsRewriter, map_words_to_bert_tokens, group_words_by_bert_tokens

from bert_tokens_to_words_rewriter import (
    BertTokens2WordsRewriter,
    map_words_to_bert_tokens,
)

In [ ]:
# Get locally imported modules from current notebook - https://stackoverflow.com/questions/40428931/package-for-listing-version-of-packages-used-in-a-jupyter-notebook - Alex P. Miller
def get_imports():

    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            # Split ensures you get root package,
            # not just imported function
            name = val.__name__.split(".")[0]

        elif isinstance(val, type):
            name = val.__module__.split(".")[0]

        # Some packages are weird and have different
        # imported names vs. system/pip names. Unfortunately,
        # there is no systematic way to get pip names from
        # a package's imported name. You'll have to add
        # exceptions to this list manually!
        poorly_named_packages = {"PIL": "Pillow", "sklearn": "scikit-learn"}
        if name in poorly_named_packages.keys():
            name = poorly_named_packages[name]

        yield name


imports = list(set(get_imports()))

# The only way I found to get the version of the root package
# from only the name of the package is to cross-check the names
# of installed packages vs. imported packages
requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name != "pip":
        requirements.append((m.project_name, m.version))

for r in requirements:
    print("{}=={}".format(*r))

# estnltk==1.7.3
# evaluate==0.4.2
# numpy==1.26.4
# pandas==2.2.2
# scikit-learn==1.5.1
# simpletransformers==0.70.1
# torch==2.5.0
# tqdm==4.66.5

estnltk==1.7.3
evaluate==0.4.2
numpy==1.26.4
pandas==2.2.2
scikit-learn==1.5.1
simpletransformers==0.70.1
torch==2.5.0
tqdm==4.66.5

In [ ]:
import pandas as pd
import typing
import itertools


def get_unique_labels(json_file: typing.Optional[str] = None):
    """Reads from JSON file or
    creates list of unique labels that the model must predict
    by creating all possible combinations of POS (Part Of Speech) and form.

    <i>Gathering unique labels from the enc2017 database proved to be insufficient for future model evaluation,
    because the database does not contain all possible combinations of POS and form.
    Evaluating model with UD Est-EDT test corpus proved that this problem existed.</i>

    Args:
        json_file (optional, str): Path to JSON file containing all unique labels

    Returns:
        list: List of unique labels
    """

    if json_file:
        try:
            with open(file=json_file, mode="r") as f:
                unique_labels = json.load(f)
            return unique_labels
        except:
            print("Could not read JSON file. Creating unique labels list.")

    # Separately, if one of two doesn't exist
    # pos_labels = [
    #     "A",
    #     "C",
    #     "D",
    #     "G",
    #     "H",
    #     "I",
    #     "J",
    #     "K",
    #     "N",
    #     "O",
    #     "P",
    #     "S",
    #     "U",
    #     "V",
    #     "X",
    #     "Y",
    #     "Z",
    # ]
    # form_labels = [
    #     "ab",
    #     "abl",
    #     "ad",
    #     "adt",
    #     "all",
    #     "el",
    #     "es",
    #     "g",
    #     "ill",
    #     "in",
    #     "kom",
    #     "n",
    #     "p",
    #     "pl",
    #     "sg",
    #     "ter",
    #     "tr",
    #     "b",
    #     "d",
    #     "da",
    #     "des",
    #     "ge",
    #     "gem",
    #     "gu",
    #     "ks",
    #     "ksid",
    #     "ksime",
    #     "ksin",
    #     "ksite",
    #     "ma",
    #     "maks",
    #     "mas",
    #     "mast",
    #     "mata",
    #     "me",
    #     "n",
    #     "neg",
    #     "neg ge",
    #     "neg gem",
    #     "neg gu",
    #     "neg ks",
    #     "neg me",
    #     "neg nud",
    #     "neg nuks",
    #     "neg o",
    #     "neg vat",
    #     "neg tud",
    #     "nud",
    #     "nuks",
    #     "nuksid",
    #     "nuksime",
    #     "nuksin",
    #     "nuksite",
    #     "nuvat",
    #     "o",
    #     "s",
    #     "sid",
    #     "sime",
    #     "sin",
    #     "site",
    #     "ta",
    #     "tagu",
    #     "taks",
    #     "takse",
    #     "tama",
    #     "tav",
    #     "tavat",
    #     "te",
    #     "ti",
    #     "tud",
    #     "tuks",
    #     "tuvat",
    #     "v",
    #     "vad",
    #     "vat",
    # ]

    pos_mutable = ["A", "C", "H", "N", "O", "P", "S", "U", "X", "Y"]
    pos_immutable = ["D", "G", "I", "J", "K", "X", "Z"]
    pos_verb = ["V"]
    form_mutable = [
        "ab",
        "abl",
        "ad",
        "adt",
        "all",
        "el",
        "es",
        "g",
        "ill",
        "in",
        "kom",
        "n",
        "p",
        "ter",
        "tr",
    ]
    form_mutable_count = ["pl", "sg"]
    form_verb = [
        "b",
        "d",
        "da",
        "des",
        "ge",
        "gem",
        "gu",
        "ks",
        "ksid",
        "ksime",
        "ksin",
        "ksite",
        "ma",
        "maks",
        "mas",
        "mast",
        "mata",
        "me",
        "n",
        "neg",
        "neg ge",
        "neg gem",
        "neg gu",
        "neg ks",
        "neg me",
        "neg nud",
        "neg nuks",
        "neg o",
        "neg vat",
        "neg tud",
        "nud",
        "nuks",
        "nuksid",
        "nuksime",
        "nuksin",
        "nuksite",
        "nuvat",
        "o",
        "s",
        "sid",
        "sime",
        "sin",
        "site",
        "ta",
        "tagu",
        "taks",
        "takse",
        "tama",
        "tav",
        "tavat",
        "te",
        "ti",
        "tud",
        "tuks",
        "tuvat",
        "v",
        "vad",
        "vat",
    ]

    # Combinations of only form
    only_form = (
        form_mutable
        + form_verb
        + list(itertools.product(form_mutable_count, form_mutable))
    )

    # Combinations of only pos
    only_pos = pos_mutable + pos_immutable + pos_verb

    # Combinations of mutable pos and their forms
    mutable_combinations = (
        list(
            itertools.product(
                pos_mutable, form_mutable
            )  # Non-verb combinations without count
        )
        + list(
            itertools.product(
                pos_mutable, itertools.product(form_mutable_count, form_mutable)
            )  # Non-verb combinations with count
        )
        + list(
            itertools.product(pos_verb, form_verb)  # Verb combinations
        )
    )

    # Combinations of verb pos and their forms
    verb_combinations = list(itertools.product(pos_verb, form_verb))

    # Labels
    # TODO: Check if all combinations of labels are represented
    mutable_labels = list()
    immutable_labels = [("", pos) for pos in pos_immutable]
    verb_labels = list(itertools.product(form_labels_verb, pos_label_verb))

    # Connect count and form in mutables
    for form, pos in noun_labels_nested:
        noun_labels.append((form[0] + " " + form[1], pos))

    pos_label_only = [("", pos) for pos in pos_labels]
    form_label_only = [(form, "") for form in form_labels]
    unknown_form_labels = [
        ("?", pos) for pos in pos_labels
    ]  # form '?' comes from enc2017 corpus after tagging

    unique_labels = (
        pos_label_only
        + form_label_only
        + noun_labels
        + verb_labels
        + unknown_form_labels
        + form_pos_labels
        + ["?"]
    )  # '?' for labels unknown to Vabamorf

    unique_labels_df = pd.DataFrame(unique_labels, columns=["form", "pos"])
    unique_labels_df["labels"] = unique_labels_df.apply(
        lambda row: (
            row["form"] + " " + row["pos"]
            if row["form"] and row["pos"]
            else row["form"] or row["pos"]
        ),
        axis=1,
    )
    # Drop form and pos columns and keep only labels column
    unique_labels_df.drop(labels=["form", "pos"], axis=1)
    print("List of unique labels created")
    return unique_labels_df["labels"].tolist()

Initializing the model<!-- Mudeli ülesehitamine -->

In [ ]:
def initialize_model(model_name, unique_labels, is_progress_bars=False):
    # Set up logging
    logger = logging.getLogger("simpletransformers.ner.ner_model")
    logger.setLevel(logging.ERROR)

    # Suppress specific warnings
    # warnings.filterwarnings("ignore", category=FutureWarning) # For warning message "FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated."
    warnings.filterwarnings(
        "ignore", category=UserWarning
    )  # For warnings like "UserWarning: <tag> seems not to be NE tag."

    # Configurations
    model_args = NERArgs()
    model_args.train_batch_size = 8
    model_args.evaluate_during_training = False
    model_args.learning_rate = 5e-5
    model_args.num_train_epochs = 10
    model_args.use_early_stopping = True
    model_args.use_cuda = torch.cuda.is_available()  # Use GPU if available
    model_args.save_eval_checkpoints = False
    model_args.save_model_every_epoch = False  # Takes a lot of storage space
    model_args.save_steps = -1
    model_args.overwrite_output_dir = True
    model_args.cache_dir = model_name + "/cache"
    model_args.best_model_dir = model_name + "/best_model"
    model_args.output_dir = model_name
    model_args.use_multiprocessing = False
    model_args.silent = is_progress_bars

    # Initialization
    model = NERModel("camembert", model_name, args=model_args, labels=unique_labels)
    return model

Function to predict tags to words

In [ ]:
def predict_tags(model, sentences):

    if isinstance(sentences, str):
        text = estnltk.Text(sentences)
        text.tag_layer("morph_analysis")
        text.morph_analysis
        sentences = [s.text for s in text.sentences]
        predictions, raw_outputs = model.predict(sentences, split_on_space=False)

    elif isinstance(sentences, list) and isinstance(sentences[0], list):
        predictions, raw_outputs = model.predict(sentences, split_on_space=False)

    else:
        raise TypeError(
            f"Input is in wrong format. Possible formats are str or list of lists. Your input is {type(sentences)}"
        )

    return predictions, raw_outputs

In [ ]:
with open("unique_labels.json", "r") as f:
    unique_labels = json.load(f)

model = initialize_model("NER_mudel", unique_labels)

In [7]:
model.tokenizer.vocab_file

'NER_mudel\\sentencepiece.bpe.model'

### Debugging

In [ ]:
in_dir = "_plain_texts_json"
comparison_data = pd.read_csv("comparison_data.csv", keep_default_na=False)
jsons = comparison_data["source"].unique().tolist()
morph_tagger = BertMorphTagger(
    "./NER_mudel_v2/", get_top_n_predictions=1, token_level=False
)

In [ ]:
morph_diff_finder = MorphDiffFinder(
    "morph_analysis",
    "bert_morph_tagging",
    diff_attribs=["partofspeech", "form"],
    focus_attribs=["partofspeech", "form"],
)
morph_diff_summarizer = MorphDiffSummarizer("morph_analysis", "bert_morph_tagging")

In [ ]:
# input_str = 'Aga muidugi, loodrid, kes soovivad stabiilset ja mugavat, 9.00-17.00 elu, on muidugi hea rääkida, et oi, kus ma siin nüüd rügan.'
# input_str = 'Ning laste kingitus: puust juuksehari (millist ma olin ammu endale soovinud), tulbid ja karp Rafaellot.'
input_str = "( nt kõrgenenud keskkõrge e puhul : � , � , î )"

In [8]:
text_obj = estnltk.Text(input_str)
# text_obj = estnltk.converters.json_to_text(file=os.path.join('./bert_morph_texts_json/', jsons[931]))
# text_obj = estnltk.converters.json_to_text(file=os.path.join('./_vabamorf_morph_texts_json/', jsons[10]))
# text_obj = estnltk.converters.json_to_text(file=os.path.join('./_bert_morph_texts_json/', jsons[27]))
# text_obj = estnltk.converters.json_to_text(file=os.path.join('./_vabamorf_morph_texts_json/', jsons[187]))
# text_obj = estnltk.converters.json_to_text(file=os.path.join('./_vabamorf_morph_texts_json/', jsons[186]))
# text_obj = estnltk.converters.json_to_text(file=os.path.join(in_dir, 'nc_17153_741265.json'))
text_obj.tag_layer("morph_analysis");

In [9]:
text_obj

Text(text='( nt kõrgenenud keskkõrge e puhul : � , � , î )')

In [10]:
# Apply the tagger to the text object
text_obj.add_layer(morph_tagger.make_layer(text_obj))

c:\Users\Admin\OneDrive\TU\Praktika\EstNLTK\morf_yhestaja\bert_tokens_to_words_rewriter.py:154: UserWarning: (!) No matching words span for bert token Span(' ', [{'bert_tokens': '▁', 'form': '?', 'partofspeech': '', 'probability': 0.80297}]).
  warnings.warn(f"(!) No matching {words_layer.name} span for bert token {bert_tokens_layer[i]}.")

In [11]:
text_obj.bert_morph_tagging

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('(', [{'bert_tokens': ['▁('], 'form': '', 'partofspeech': 'Z', 'probability': 0.99999}]),
Span('nt', [{'bert_tokens': ['▁nt'], 'form': '', 'partofspeech': 'Y', 'probability': 0.99042}]),
Span('kõrgenenud', [{'bert_tokens': ['▁kõr', 'genenud'], 'form': '', 'partofspeech': 'A', 'probability': 0.99978}]),
Span('keskkõrge', [{'bert_tokens': ['▁keskk', 'õr', 'ge'], 'form': 'sg g', 'partofspeech': 'S', 'probability': 0.99644}]),
Span('e', [{'bert_tokens': ['▁e'], 'form': '', 'partofspeech': 'Y', 'probability': 0.99819}]),
Span('puhul', [{'bert_tokens': ['▁puhul'], 'form': '', 'partofspeech': 'K', 'probability': 0.99939}]),
Span(':', [{'bert_tokens': ['▁:'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}]),
Span(',', [{'bert_tokens': ['▁,'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99999}]),
Span(',', [{'bert_tokens': ['▁,'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99999}]),
Span('î', [{'bert_tokens': ['î'], 'form': '?', 'partofspeech': '', 'probability': 0.86856}]),
Span(')', [{'bert_tokens': ['▁)'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99999}])])

In [12]:
text_obj.words

Layer(name='words', attributes=('normalized_form',), spans=SL[Span('(', [{'normalized_form': None}]),
Span('nt', [{'normalized_form': 'nt'}]),
Span('kõrgenenud', [{'normalized_form': None}]),
Span('keskkõrge', [{'normalized_form': None}]),
Span('e', [{'normalized_form': None}]),
Span('puhul', [{'normalized_form': None}]),
Span(':', [{'normalized_form': None}]),
Span('�', [{'normalized_form': None}]),
Span(',', [{'normalized_form': None}]),
Span('�', [{'normalized_form': None}]),
Span(',', [{'normalized_form': None}]),
Span('î', [{'normalized_form': None}]),
Span(')', [{'normalized_form': None}])])

In [57]:
# display(text_obj.bert_morph_tagging[50:55])
# display(text_obj.morph_analysis[50:55])

In [ ]:
morph_diff_layer, formatted_diffs_str, total_diff_gaps = (
    morph_diff_finder.find_difference(text_obj, fname=jsons[0], text_cat="wiki")
)  # text_obj.meta['texttype']

In [ ]:
fpath = os.path.join(
    "differences_test",
    f"_{jsons[0]}__ann_diffs_{datetime.now().strftime('%Y-%m-%dT%H%M%S')}.txt",
)
write_formatted_diff_str_to_file(fpath, formatted_diffs_str)

In [ ]:
morph_diff_summarizer.record_from_diff_layer(
    "morph_analysis", morph_diff_layer, "wiki"
)  # text_obj.meta['texttype'] <- None asemele tuleb hiljem tekstiliik võetud meta-andmetest

In [ ]:
morph_diff_summarizer.get_diffs_summary_output(show_doc_count=True)

'morph_analysis\n wiki  | #docs: 1 | modified spans: 2 / 20 (0.1000) | annotations ratio: 38 / 43 (0.8837) | only in morph_analysis: 4 (9.3023%) | only in bert_morph_tagging: 1 (2.3256%) \n\n'

In [ ]:
text_obj.meta["texttype"]

'blogs_and_forums'

In [13]:
# print(morph_diff_finder._bert_vabamorf_tags_layer)
# print(morph_diff_finder.new_layer)
# print(morph_diff_finder.old_layer)
# print(morph_diff_finder.old_layer + morph_diff_finder._redux_layer_suffix)
# print(morph_diff_finder.old_layer + morph_diff_finder._flat_layer_suffix)
# print(morph_diff_finder._bert_vabamorf_tags_layer + morph_diff_finder._redux_layer_suffix)
# print(morph_diff_finder._bert_vabamorf_tags_layer + morph_diff_finder._flat_layer_suffix)

In [ ]:
new_layer = Layer(
    name="bert_morph_tags",
    attributes=["bert_tokens", "form", "partofspeech"],
    text_object=text_obj,
    parent="words",
    ambiguous=True,
)
for sp in text_obj.bert_morph_tagging.spans:
    span = sp.base_span
    tokens = sp.bert_tokens[0]
    label = sp.morph_labels[0].split("_")
    pos = ""
    form = ""
    if len(label) == 1:  # Only one feature exissts (form or partofspeech)
        if label[0].isupper():  # partofspeech is uppercased
            pos = sp.morph_labels[0].split("_")[0]
        else:
            form = sp.morph_labels[0].split("_")[0]
    else:  # Both features exist
        form = sp.morph_labels[0].split("_")[0]
        pos = sp.morph_labels[0].split("_")[1]

    annotation = {"bert_tokens": tokens, "form": form, "partofspeech": pos}
    new_layer.add_annotation(span, annotation)
text_obj.add_layer(new_layer)

In [ ]:
def create_redux_morph_layer(text_obj, morph_layer, output_layer, add_layer=True):
    """Creates a reduced version of morph_analysis layer which only contains attributes 'partofspeech' and 'form'.
    The reduced morph layer is required for comparing Vabamorf's annotations against Bert annotations
    via DiffTagger (because DiffTagger assumes that comparable layers have common attributes).
    """
    assert isinstance(text_obj, Text)
    assert morph_layer in text_obj.layers, "(!) Layer {!r} missing from: {!r}".format(
        morph_layer, text_obj.layers.keys()
    )
    redux_layer = Layer(
        name=output_layer,
        attributes=("partofspeech", "form"),
        text_object=text_obj,
        ambiguous=True,
    )
    for morph_word in text_obj[morph_layer]:
        for ann in morph_word.annotations:
            assert "partofspeech" in ann.keys(), (
                "(!) Attribute {!r} missing from: {!r}".format("pos", ann)
            )
            assert "form" in ann.keys(), "(!) Attribute {!r} missing from: {!r}".format(
                "form", ann
            )
            postag = ann["partofspeech"]
            form = ann["form"]
            redux_layer.add_annotation(
                morph_word.base_span, {"partofspeech": postag, "form": form}
            )
    if add_layer:
        text_obj.add_layer(redux_layer)
    return redux_layer

In [ ]:
create_redux_morph_layer(
    text_obj, "morph_analysis", "morph_analysis_redux", add_layer=True
)
create_redux_morph_layer(
    text_obj, "bert_morph_tags", "bert_morph_tags_redux", add_layer=True
)
morph_diff_finder = MorphDiffFinder(
    "morph_analysis_redux",
    "bert_morph_tags_redux",
    diff_attribs=["partofspeech", "form"],
    focus_attribs=["partofspeech", "form"],
)

In [14]:
morph_diff_finder.find_difference(text_obj, fname=jsons[0])

(Layer(name='morph_diff_layer', attributes=('input_layer_name', 'span_status', 'partofspeech', 'form'), spans=SL[Span('Jüri', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'H', 'form': 'sg n'}, {'input_layer_name': 'bert_vabamorf_tags_flat', 'span_status': 'modified', 'partofspeech': 'H', 'form': 'sg g'}]),
 Span('küpsetatud', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'A', 'form': 'sg n'}, {'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'A', 'form': 'pl n'}, {'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'V', 'form': 'tud'}]),
 Span('soovinud', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'A', 'form': 'pl n'}, {'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'A', 'form': 'sg n'}, {'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'A', 'form': ''}]),
 Span('Rafaellot', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'H', 'form': 'sg n'}, {'input_layer_name': 'bert_vabamorf_tags_flat', 'span_status': 'modified', 'partofspeech': 'H', 'form': 'sg p'}]),
 Span('transada', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'S', 'form': 'sg n'}, {'input_layer_name': 'bert_vabamorf_tags_flat', 'span_status': 'modified', 'partofspeech': 'V', 'form': 'da'}]),
 Span('koos', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'D', 'form': ''}, {'input_layer_name': 'bert_vabamorf_tags_flat', 'span_status': 'modified', 'partofspeech': 'K', 'form': ''}]),
 Span('torti', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'S', 'form': 'adt'}, {'input_layer_name': 'bert_vabamorf_tags_flat', 'span_status': 'modified', 'partofspeech': 'S', 'form': 'sg p'}]),
 Span('ise', [{'input_layer_name': 'morph_analysis_flat', 'span_status': 'modified', 'partofspeech': 'P', 'form': 'pl n'}])]),
 "=====================================================================================\n\n  ::web13_274106_x.json::0\n\n...Koju jõudes ootas ees üllatus -  {Jüri}  küpsetatud imemaitsev shokolaadikook. Ning laste kingitus: ...\n --- MODIFIED -------------------------------------------------- \n morph_analysis_flat        ['H', 'sg n']\n bert_vabamorf_tags_flat    ['H', 'sg g']\n\n=====================================================================================\n\n  ::web13_274106_x.json::1\n\n...Koju jõudes ootas ees üllatus - Jüri  {küpsetatud}  imemaitsev shokolaadikook. Ning laste kingitus: puust juuks...\n --- COMMON   -------------------------------------------------- \n morph_analysis_flat        ['A', '']\n bert_vabamorf_tags_flat    ['A', '']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['A', 'sg n']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['A', 'pl n']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['V', 'tud']\n\n=====================================================================================\n\n  ::web13_274106_x.json::2\n\n...ste kingitus: puust juuksehari (millist ma olin ammu endale  {soovinud} ), tulbid ja karp Rafaellot.\\n\\nÕhtul käisin kiirkorras oma em...\n --- COMMON   -------------------------------------------------- \n morph_analysis_flat        ['V', 'nud']\n bert_vabamorf_tags_flat    ['V', 'nud']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['A', 'pl n']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['A', 'sg n']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['A', '']\n\n=====================================================================================\n\n  ::web13_274106_x.json::3\n\n...hari (millist ma olin ammu endale soovinud), tulbid ja karp  {Rafaellot} .\\n\\nÕhtul käisin kiirkorras oma emmet kallistamas. Kiirkorras...\n --- MODIFIED -------------------------------------------------- \n morph_analysis_flat        ['H', 'sg n']\n bert_vabamorf_tags_flat    ['H', 'sg p']\n\n=====================================================================================\n\n  ::web13_274106_x.json::4\n\n...le lennujaama vastu, et nad Barcelona-reisi lõpetuselt koju  {transada} . Ja siis sõime juba koos ema-isa juures torti.\\n\\nTõesti - ma...\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['S', 'sg n']\n --- EXTRA    -------------------------------------------------- \n bert_vabamorf_tags_flat    ['V', 'da']\n\n=====================================================================================\n\n  ::web13_274106_x.json::5\n\n...arcelona-reisi lõpetuselt koju transada. Ja siis sõime juba  {koos}  ema-isa juures torti.\\n\\nTõesti - ma ise olen emana väga õnne...\n --- MODIFIED -------------------------------------------------- \n morph_analysis_flat        ['D', '']\n bert_vabamorf_tags_flat    ['K', '']\n\n=====================================================================================\n\n  ::web13_274106_x.json::6\n\n...uselt koju transada. Ja siis sõime juba koos ema-isa juures  {torti} .\\n\\nTõesti - ma ise olen emana väga õnnelik ja olen väga õnne...\n --- MODIFIED -------------------------------------------------- \n morph_analysis_flat        ['S', 'adt']\n bert_vabamorf_tags_flat    ['S', 'sg p']\n\n=====================================================================================\n\n  ::web13_274106_x.json::7\n\n... Ja siis sõime juba koos ema-isa juures torti.\\n\\nTõesti - ma  {ise}  olen emana väga õnnelik ja olen väga õnnelik ka oma ema üle...\n --- COMMON   -------------------------------------------------- \n morph_analysis_flat        ['P', 'sg n']\n bert_vabamorf_tags_flat    ['P', 'sg n']\n --- MISSING  -------------------------------------------------- \n morph_analysis_flat        ['P', 'pl n']\n\n",
 8)

In [13]:
text_obj.words;

In [14]:
print(len(vm_spans), len(bert_spans))

35349 34331

In [39]:
text_obj.sentences[29]

EnvelopingSpan(['Varasemates', 'transkribeeritud', 'tekstides', 'võib', 'leida', 'nende', 'vokaalide', 'kolmesugust', 'märkimist', '(', 'nt', 'kõrgenenud', 'keskkõrge', 'e', 'puhul', ':', '�', ',', '�', ',', 'î', ')', '.'], [{}])

In [ ]:
bert_spans = text_obj.bert_morph_tagging.spans
vm_spans = text_obj.words.spans
shift = 0
print(len(vm_spans), len(bert_spans))
if len(vm_spans) < len(bert_spans):
    for i in range(len(vm_spans)):
        if vm_spans[i - shift].text != bert_spans[i].text:
            print(i, i + shift, vm_spans[i].text, bert_spans[i + shift].text)
            shift += 1
            for n in range(i - 10, i + 10 + 1):
                print(n, vm_spans[n].text, bert_spans[n].text)
            print()
        if shift > 10:
            break
else:
    for i in range(len(bert_spans)):
        if vm_spans[i].text != bert_spans[i - shift].text:
            print(i, i + shift, vm_spans[i].text, bert_spans[i + shift].text)
            shift += 1
            for n in range(i - 10, i + 10 + 1):
                print(n, vm_spans[n].text, bert_spans[n].text)
            print()
        if shift > 10:
            break

35349 34331
539 539 � ,
529 vokaalide vokaalide
530 kolmesugust kolmesugust
531 märkimist märkimist
532 ( (
533 nt nt
534 kõrgenenud kõrgenenud
535 keskkõrge keskkõrge
536 e e
537 puhul puhul
538 : :
539 � ,
540 , ,
541 � î
542 , )
543 î .
544 ) Transkribeerimine
545 . võib
546 Transkribeerimine ju
547 võib mingil
548 ju määral
549 mingil anda

541 542 � )
531 märkimist märkimist
532 ( (
533 nt nt
534 kõrgenenud kõrgenenud
535 keskkõrge keskkõrge
536 e e
537 puhul puhul
538 : :
539 � ,
540 , ,
541 � î
542 , )
543 î .
544 ) Transkribeerimine
545 . võib
546 Transkribeerimine ju
547 võib mingil
548 ju määral
549 mingil anda
550 määral edasi
551 anda nende

1452 1454 � ,
1442 i ü
1443 , ,
1444 ü e
1445 , ,
1446 e ö
1447 , ,
1448 ö ä
1449 , ,
1450 ä ,
1451 , u
1452 � ,
1453 , o
1454 u ,
1455 , a
1456 o ]
1457 , ning
1458 a kümme
1459 ] vokaali
1460 ning Võru
1461 kümme murdes
1462 vokaali [

1476 1479 � a
1466 i ,
1467 , e
1468 ü ,
1469 , ö
1470 e ,
1471 , ä
1472 ö ,
1473 , ,
1474 ä ,
1475 , u
1476 � ,
1477 , o
1478 � ,
1479 , a
1480 u ]
1481 , .
1482 o Merike
1483 , Parve
1484 a leiab
1485 ] Tiit-Rein
1486 . Viitsole

1478 1482 � Merike
1468 ü ,
1469 , ö
1470 e ,
1471 , ä
1472 ö ,
1473 , ,
1474 ä ,
1475 , u
1476 � ,
1477 , o
1478 � ,
1479 , a
1480 u ]
1481 , .
1482 o Merike
1483 , Parve
1484 a leiab
1485 ] Tiit-Rein
1486 . Viitsole
1487 Merike toetudes
1488 Parve ,

1498 1503 � keskvokaaliga
1488 Parve ,
1489 leiab et
1490 Tiit-Rein kõrge
1491 Viitsole keskvokaal
1492 toetudes [
1493 , ]
1494 et on
1495 kõrge iseseisev
1496 keskvokaal foneem
1497 [ ,
1498 � kuigi
1499 ] ei
1500 on leidu
1501 iseseisev minimaalpaare
1502 foneem keskkõrge
1503 , keskvokaaliga
1504 kuigi [
1505 ei õ
1506 leidu ]
1507 minimaalpaare ja
1508 keskkõrge kõrge

1517 1523 � laadi
1507 minimaalpaare ja
1508 keskkõrge kõrge
1509 keskvokaaliga keskvokaaliga
1510 [ [
1511 õ ]
1512 ] .
1513 ja Ometi
1514 kõrge on
1515 keskvokaaliga ilmne
1516 [ ,
1517 � et
1518 ] vokaalide
1519 . kvaliteedierinevus
1520 Ometi on
1521 on fonoloogiliselt
1522 ilmne distinktiivset
1523 , laadi
1524 et ning
1525 vokaalide [
1526 kvaliteedierinevus ]
1527 on asendamisel

1533 1540 � 1999b
1523 , laadi
1524 et ning
1525 vokaalide [
1526 kvaliteedierinevus ]
1527 on asendamisel
1528 fonoloogiliselt [
1529 distinktiivset ]
1530 laadi -
1531 ning ga
1532 [ kaotab
1533 � sõna
1534 ] näiteks
1535 asendamisel keelejuhtide
1536 [ arvates
1537 � tähenduse
1538 ] (
1539 - Parve
1540 ga 1999b
1541 kaotab :
1542 sõna 46
1543 näiteks -

1537 1545 � ;
1527 on asendamisel
1528 fonoloogiliselt [
1529 distinktiivset ]
1530 laadi -
1531 ning ga
1532 [ kaotab
1533 � sõna
1534 ] näiteks
1535 asendamisel keelejuhtide
1536 [ arvates
1537 � tähenduse
1538 ] (
1539 - Parve
1540 ga 1999b
1541 kaotab :
1542 sõna 46
1543 näiteks -
1544 keelejuhtide 51
1545 arvates ;
1546 tähenduse 2000a
1547 ( :

1606 1615 � ,
1596 ( :
1597 see ,
1598 tähendab ó
1599 kolmandavältelistes :
1600 sõnades ,
1601 ) :
1602 kõrgenenud ,
1603 : :
1604 é (
1605 : nt
1606 � k
1607 , '
1608 ó keel
1609 : '
1610 � :
1611 , kéle
1612 � '
1613 : keele
1614 � '
1615 , ,
1616 � k

1610 1620 � :
1600 sõnades ,
1601 ) :
1602 kõrgenenud ,
1603 : :
1604 é (
1605 : nt
1606 � k
1607 , '
1608 ó keel
1609 : '
1610 � :
1611 , kéle
1612 � '
1613 : keele
1614 � '
1615 , ,
1616 � k
1617 : '
1618 � kool
1619 ( '
1620 nt :

In [ ]:
morph_tagger.bert_tokenizer(input_str, return_tensors="pt")["input_ids"]

tensor([[    5,   156,  3487,   492, 27200,  7286,  2890,    78,    15,  1098,
           262,    36,    36, 39638, 39901,   300,     6]])

In [13]:
morph_tagger.bert_tokenizer(input_str)

{'input_ids': [5, 156, 3487, 492, 27200, 7286, 2890, 78, 15, 1098, 262, 36, 36, 39638, 39901, 300, 6], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [14]:
morph_tagger._tokenize_with_bert(input_str)

([(None, None, '<s>'),
  (0, 1, '▁('),
  (1, 4, '▁nt'),
  (4, 8, '▁kõr'),
  (8, 15, 'genenud'),
  (15, 21, '▁keskk'),
  (21, 23, 'õr'),
  (23, 25, 'ge'),
  (25, 27, '▁e'),
  (27, 33, '▁puhul'),
  (33, 35, '▁:'),
  (37, 39, '▁,'),
  (41, 43, '▁,'),
  (43, 44, '▁'),
  (44, 45, 'î'),
  (45, 47, '▁)'),
  (None, None, '</s>')],
 {'input_ids': [5, 156, 3487, 492, 27200, 7286, 2890, 78, 15, 1098, 262, 36, 36, 39638, 39901, 300, 6], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})

In [ ]:
for token_data in morph_tagger._get_bert_morph_tagging_label_predictions(input_str, 3):
    start, end = token_data["token"][0], token_data["token"][1]
    bert_tokens = token_data["token"][2]
    if start is None or end is None:
        continue  # Ignore sentence start and end tokens (<s>, </s>)
    all_labels = [pred["label"] for pred in token_data["predictions"]]
    all_probabilities = [pred["probability"] for pred in token_data["predictions"]]
    for label, prob in zip(all_labels, all_probabilities):
        print(label[0], label[1], prob)

 J 0.99991
o V 0.0
 D 0.0
pl g S 0.9996
sg g S 6e-05
pl g A 3e-05
sg n S 0.99978
sg in S 3e-05
sg p S 1e-05
 Z 0.99992
 J 2e-05
b V 0.0
sg el S 0.99941
sg p S 0.00012
sg el H 4e-05
sg n S 0.99975
sg in S 4e-05
sg p S 3e-05
sg n S 0.99975
sg in S 4e-05
sg p S 2e-05
 Z 0.99987
 J 5e-05
 A 0.0
sg p P 0.99783
sg el P 0.00098
sg p A 0.0001
sg p P 0.99854
sg el P 0.00043
sg p A 0.0001
sg n P 0.99983
pl n P 1e-05
sg g P 1e-05
sin V 0.99878
sime V 9e-05
n V 8e-05
 D 0.99989
 A 1e-05
sg g S 0.0
sg all P 0.9998
pl all P 2e-05
sg all H 1e-05
nud V 0.99973
pl n S 2e-05
 A 2e-05
 Z 0.99995
 J 0.0
 A 0.0
pl n S 0.99949
pl n A 0.00012
pl n H 5e-05
pl n S 0.99952
pl n A 0.00012
pl n H 4e-05
 J 0.99991
o V 0.0
 D 0.0
sg n S 0.99976
sg in S 2e-05
pl g S 2e-05
sg p H 0.78436
sg n H 0.1822
pl n H 0.00609
sg p H 0.88837
sg n H 0.08277
pl n H 0.00468
sg p H 0.9153
sg n H 0.05623
pl n H 0.00461
sg p H 0.91316
sg n H 0.05442
pl n H 0.00383
 Z 0.99996
 J 0.0
sg n H 0.0

In [ ]:
def _tokenize_with_bert(self, text, include_spanless=True):
    """
    Tokenizes input string with Bert's tokenizer and returns a list of token spans.
    Each token span is a triple (start, end, token).
    If include_spanless==True (default), then Bert's special "spanless" tokens
    (e.g. [CLS], [SEP]) will also be included with their respective start/end indexes
    set to None.
    """
    tokens = []
    batch_encoding = self.bert_tokenizer(text)

    # Iterate over tokens and their character spans
    for token_id, token in enumerate(batch_encoding.tokens()):
        char_span = batch_encoding.token_to_chars(token_id)

        # Skip any spanless tokens like [CLS], [SEP] unless include_spanless is set to True
        if char_span is None and include_spanless:
            tokens.append((None, None, token))
            continue
        elif char_span is None:
            continue

        # Initialize the current token list to collect non-punctuation parts
        start, end = char_span.start, char_span.end
        clean_token = []

        # Iterate over each character in the token to separate punctuation
        for i, char in enumerate(token):
            if (
                char.isalnum() or char == "▁"
            ):  # Alphanumeric or BERT's special start marker
                clean_token.append(char)
            else:
                # If clean_token has content, add it as a token with the current span
                if clean_token:
                    tokens.append(
                        (start, start + len(clean_token), "".join(clean_token))
                    )
                    clean_token = []

                # Add the punctuation as a separate token with its span
                tokens.append((char, start + i, start + i + 1))

        # Add any remaining non-punctuation part as a token
        if clean_token:
            tokens.append((start, start + len(clean_token), "".join(clean_token)))

    return tokens

In [ ]:
# Use the refactored _tokenize_with_bert method to get the correct tokens and their spans
tokens_with_spans = morph_tagger._tokenize_with_bert(input_str)

# Extract only the tokens for encoding
clean_tokens = [str(token) for _, _, token in tokens_with_spans]

# Tokenize the input string with BERT's tokenizer for obtaining token indices
token_indexes = morph_tagger.bert_tokenizer.convert_tokens_to_ids(clean_tokens)
print(token_indexes)
token_indexes = torch.tensor([token_indexes])  # Prepare for model input

# Check if input exceeds max sequence length
max_seq_length = morph_tagger.bert_tokenizer.model_max_length
if token_indexes.size(1) > max_seq_length:
    raise ValueError(
        f"Input length exceeds the model's max_seq_length of {max_seq_length} tokens"
    )

# Get model predictions (logits)
with torch.no_grad():
    output = morph_tagger.bert_morph_tagging(token_indexes)

logits = output.logits.squeeze(0)  # Shape: [sequence_length, num_labels]
probs = torch.softmax(logits, dim=-1)  # Convert logits to probabilities

# Assign predictions to tokens
top_n_predictions = []
for i, (start, end, token) in enumerate(tokens_with_spans):
    if start is None or end is None or token == "▁":
        continue  # Ignore sentence start and end tokens (<s>, </s>) and word start sign (▁)

    # Get probabilities for the current token
    token_probs = probs[i]
    top_n_indices = torch.topk(
        token_probs, morph_tagger.get_top_n_predictions
    ).indices  # Top N label indices
    top_n_labels = [
        morph_tagger.id2label[idx.item()] for idx in top_n_indices
    ]  # Convert indices to labels
    top_n_probs = [
        round(token_probs[idx].item(), 5) for idx in top_n_indices
    ]  # Get probabilities for top N labels

    # Add the predictions to the output
    top_n_predictions.append(
        {
            "token": (start, end, token),
            "predictions": [
                {"label": label, "probability": prob}
                for label, prob in zip(top_n_labels, top_n_probs)
            ],
        }
    )

NameError: name 'morph_tagger' is not defined

In [7]:
top_n_predictions

NameError: name 'top_n_predictions' is not defined

In [8]:
# len(_split_sentence_into_smaller_chunks(text_obj.text)[0][2])

In [9]:
text_obj.bert_morph_tagging.bert_tokens

NameError: name 'text_obj' is not defined

In [10]:
# predictions, raw_outputs = predict_tags(model, input_str)

In [11]:
# raw_outputs[0][0].keys()

In [31]:
text_obj.words[0].text

'Ning'

In [ ]:
sentences_layer = text_obj.sentences

morph_layer = Layer(
    name=morph_tagger.output_layer,
    attributes=morph_tagger.output_attributes,
    text_object=text_obj,
    parent="words",
    ambiguous=True,
)

In [ ]:
def rewriter_decorator(text_obj, word_index, span):
    """
    Decorator function for <code>BertTokens2WordsRewriter</code>. \n
    Aggregates the <code>morph_labels</code> and <code>probabilities</code> from <code>shared_bert_tokens</code>, finds the most
    common top-1 label, and retrieves the top N labels and their probabilities from the
    first token that contains this top-1 label.

    Args:
        text_obj: EstNLTK Text object.
        words_index: Index of the word in <code>words</code> layer.
        span: Span

    Returns:
        dict: Annotations with the top N labels and probabilities for the word/phrase.
    """

    # Step 1: Find the most frequent top-1 label across all tokens
    top_1_label_counts = collections.Counter()

    for sp in span:
        top_1_label = sp["morph_labels"][0]  # Get top-1 label
        # 'morph_labels': ['label', 'label', ...], first [0] to get the list of labels, second [0] to get the first element
        top_1_label_counts[top_1_label] += 1  # Count occurrences of each top-1 label

    # Identify the most frequent top-1 label
    most_frequent_label = top_1_label_counts.most_common(1)[0][0]
    annotations = list()

    # Step 2: Find the first token that has this most frequent top-1 label
    for sp in span:
        if most_frequent_label in sp["morph_labels"]:
            # Extract the top N labels and their probabilities starting from this label
            labels = sp["morph_labels"]
            probabilities = sp["probabilities"]

            assert len(labels) == len(probabilities)

            for label, prob in zip(labels, probabilities):
                annotation = {
                    "bert_tokens": [sp["bert_tokens"][0] for sp in span],
                    "morph_labels": label,
                    "probabilities": prob,
                }
                annotations.append(annotation)

            # Return the final annotation
            return annotations

    # Fallback if no label found (shouldn't happen)
    raise RuntimeError(f"Could not find a token with this label: {most_frequent_label}")

In [ ]:
for k, sentence in enumerate(sentences_layer):
    sent_start = sentence.start
    sent_text = sentence.enclosing_text
    # Apply batch processing: split larger input sentence into smaller chunks and
    # process chunk by chunk
    sent_chunks, sent_chunk_indexes = _split_sentence_into_smaller_chunks(sent_text)
    for sent_chunk, (chunk_start, chunk_end) in zip(sent_chunks, sent_chunk_indexes):
        print(f"<s>{sent_chunk}</s>")
        # Get predictions for the sentence
        top_n_predictions = morph_tagger._get_bert_morph_tagging_label_predictions(
            sent_chunk, morph_tagger.get_top_n_predictions
        )

        # Collect token level annotations (a label for each token)
        for token_data in top_n_predictions:
            start, end = token_data["token"][0], token_data["token"][1]
            bert_tokens = token_data["token"][2]
            if start is None or end is None or bert_tokens == "▁":
                continue  # Ignore sentence start and end tokens (<s>, </s>) and word start sign (▁)
            all_labels = [pred["label"] for pred in token_data["predictions"]]
            all_probabilities = [
                pred["probability"] for pred in token_data["predictions"]
            ]
            token_span = (
                sent_start + chunk_start + start,
                sent_start + chunk_start + end,
            )
            print(sent_start, chunk_start, start, end)
            print(token_data)
            print(token_span)
            for label, prob in zip(all_labels, all_probabilities):
                annotation = {
                    "bert_tokens": bert_tokens,
                    "morph_labels": label,
                    "probabilities": prob,
                }
                morph_layer.add_annotation(token_span, **annotation)
            # annotation = {'bert_tokens' : bert_tokens, 'morph_label' : predicted_label }
            # token_level_annotations.append([token_span, annotation, single_label])

# Add annotations
# if morph_tagger.token_level:
#     # Return token level annotations
#     morph_layer

# else:
#     # Aggregate tokens back into words/phrases
#     # Use BertTokens2WordsRewriter to convert BERT tokens to words
#     rewriter = BertTokens2WordsRewriter(
#         bert_tokens_layer=morph_tagger.output_layer,
#         input_words_layer=morph_tagger.words_layer,
#         output_attributes=morph_tagger.output_attributes,
#         output_layer=morph_tagger.output_layer,
#         decorator=rewriter_decorator)

# #     # Rewrite to align BERT tokens with words
#     morph_layer = rewriter.make_layer(text_obj, layers={morph_layer.name: morph_layer})

<s>Koju jõudes ootas ees üllatus - Jüri küpsetatud imemaitsev shokolaadikook.</s>
0 0 0 4
{'token': (0, 4, '▁Koju'), 'predictions': [{'label': 'adt_S', 'probability': 0.93019}]}
(0, 4)
0 0 4 11
{'token': (4, 11, '▁jõudes'), 'predictions': [{'label': 'des_V', 'probability': 0.99942}]}
(4, 11)
0 0 11 17
{'token': (11, 17, '▁ootas'), 'predictions': [{'label': 's_V', 'probability': 0.99991}]}
(11, 17)
0 0 17 21
{'token': (17, 21, '▁ees'), 'predictions': [{'label': 'D', 'probability': 0.99948}]}
(17, 21)
0 0 21 29
{'token': (21, 29, '▁üllatus'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99972}]}
(21, 29)
0 0 29 31
{'token': (29, 31, '▁-'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(29, 31)
0 0 31 36
{'token': (31, 36, '▁Jüri'), 'predictions': [{'label': 'sg g_H', 'probability': 0.80241}]}
(31, 36)
0 0 36 47
{'token': (36, 47, '▁küpsetatud'), 'predictions': [{'label': 'A', 'probability': 0.9985}]}
(36, 47)
0 0 47 51
{'token': (47, 51, '▁ime'), 'predictions': [{'label': 'sg n_A', 'probability': 0.99975}]}
(47, 51)
0 0 51 57
{'token': (51, 57, 'maitse'), 'predictions': [{'label': 'sg n_A', 'probability': 0.99974}]}
(51, 57)
0 0 57 58
{'token': (57, 58, 'v'), 'predictions': [{'label': 'sg n_A', 'probability': 0.99974}]}
(57, 58)
0 0 58 62
{'token': (58, 62, '▁sho'), 'predictions': [{'label': 'sg n_S', 'probability': 0.9996}]}
(58, 62)
0 0 62 67
{'token': (62, 67, 'kolaa'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99951}]}
(62, 67)
0 0 67 70
{'token': (67, 70, 'dik'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99947}]}
(67, 70)
0 0 70 73
{'token': (70, 73, 'ook'), 'predictions': [{'label': 'sg n_S', 'probability': 0.9996}]}
(70, 73)
0 0 73 74
{'token': (73, 74, '.'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(73, 74)
<s>Ning laste kingitus: puust juuksehari (millist ma olin ammu endale soovinud), tulbid ja karp Rafaellot.</s>
75 0 0 4
{'token': (0, 4, '▁Ning'), 'predictions': [{'label': 'J', 'probability': 0.99991}]}
(75, 79)
75 0 4 10
{'token': (4, 10, '▁laste'), 'predictions': [{'label': 'pl g_S', 'probability': 0.9996}]}
(79, 85)
75 0 10 19
{'token': (10, 19, '▁kingitus'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99978}]}
(85, 94)
75 0 19 20
{'token': (19, 20, ':'), 'predictions': [{'label': 'Z', 'probability': 0.99992}]}
(94, 95)
75 0 20 26
{'token': (20, 26, '▁puust'), 'predictions': [{'label': 'sg el_S', 'probability': 0.99941}]}
(95, 101)
75 0 26 33
{'token': (26, 33, '▁juukse'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99975}]}
(101, 108)
75 0 33 37
{'token': (33, 37, 'hari'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99975}]}
(108, 112)
75 0 37 39
{'token': (37, 39, '▁('), 'predictions': [{'label': 'Z', 'probability': 0.99987}]}
(112, 114)
75 0 39 42
{'token': (39, 42, 'mil'), 'predictions': [{'label': 'sg p_P', 'probability': 0.99783}]}
(114, 117)
75 0 42 46
{'token': (42, 46, 'list'), 'predictions': [{'label': 'sg p_P', 'probability': 0.99854}]}
(117, 121)
75 0 46 49
{'token': (46, 49, '▁ma'), 'predictions': [{'label': 'sg n_P', 'probability': 0.99983}]}
(121, 124)
75 0 49 54
{'token': (49, 54, '▁olin'), 'predictions': [{'label': 'sin_V', 'probability': 0.99878}]}
(124, 129)
75 0 54 59
{'token': (54, 59, '▁ammu'), 'predictions': [{'label': 'D', 'probability': 0.99989}]}
(129, 134)
75 0 59 66
{'token': (59, 66, '▁endale'), 'predictions': [{'label': 'sg all_P', 'probability': 0.9998}]}
(134, 141)
75 0 66 75
{'token': (66, 75, '▁soovinud'), 'predictions': [{'label': 'nud_V', 'probability': 0.99973}]}
(141, 150)
75 0 75 77
{'token': (75, 77, '),'), 'predictions': [{'label': 'Z', 'probability': 0.99995}]}
(150, 152)
75 0 77 81
{'token': (77, 81, '▁tul'), 'predictions': [{'label': 'pl n_S', 'probability': 0.99949}]}
(152, 156)
75 0 81 84
{'token': (81, 84, 'bid'), 'predictions': [{'label': 'pl n_S', 'probability': 0.99952}]}
(156, 159)
75 0 84 87
{'token': (84, 87, '▁ja'), 'predictions': [{'label': 'J', 'probability': 0.99991}]}
(159, 162)
75 0 87 92
{'token': (87, 92, '▁karp'), 'predictions': [{'label': 'sg n_S', 'probability': 0.99976}]}
(162, 167)
75 0 92 95
{'token': (92, 95, '▁Ra'), 'predictions': [{'label': 'sg p_H', 'probability': 0.78436}]}
(167, 170)
75 0 95 97
{'token': (95, 97, 'fa'), 'predictions': [{'label': 'sg p_H', 'probability': 0.88837}]}
(170, 172)
75 0 97 100
{'token': (97, 100, 'ell'), 'predictions': [{'label': 'sg p_H', 'probability': 0.9153}]}
(172, 175)
75 0 100 102
{'token': (100, 102, 'ot'), 'predictions': [{'label': 'sg p_H', 'probability': 0.91316}]}
(175, 177)
75 0 102 103
{'token': (102, 103, '.'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(177, 178)
<s>Õhtul käisin kiirkorras oma emmet kallistamas.</s>
180 0 0 5
{'token': (0, 5, '▁Õhtul'), 'predictions': [{'label': 'sg ad_S', 'probability': 0.99602}]}
(180, 185)
180 0 5 12
{'token': (5, 12, '▁käisin'), 'predictions': [{'label': 'sin_V', 'probability': 0.99886}]}
(185, 192)
180 0 12 17
{'token': (12, 17, '▁kiir'), 'predictions': [{'label': 'D', 'probability': 0.99948}]}
(192, 197)
180 0 17 23
{'token': (17, 23, 'korras'), 'predictions': [{'label': 'D', 'probability': 0.99846}]}
(197, 203)
180 0 23 27
{'token': (23, 27, '▁oma'), 'predictions': [{'label': 'sg g_P', 'probability': 0.99967}]}
(203, 207)
180 0 27 29
{'token': (27, 29, '▁e'), 'predictions': [{'label': 'sg p_S', 'probability': 0.99955}]}
(207, 209)
180 0 29 33
{'token': (29, 33, 'mmet'), 'predictions': [{'label': 'sg p_S', 'probability': 0.99954}]}
(209, 213)
180 0 33 38
{'token': (33, 38, '▁kall'), 'predictions': [{'label': 'mas_V', 'probability': 0.99913}]}
(213, 218)
180 0 38 42
{'token': (38, 42, 'ista'), 'predictions': [{'label': 'mas_V', 'probability': 0.99914}]}
(218, 222)
180 0 42 45
{'token': (42, 45, 'mas'), 'predictions': [{'label': 'mas_V', 'probability': 0.99912}]}
(222, 225)
180 0 45 46
{'token': (45, 46, '.'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(225, 226)
<s>Kiirkorras sellepärast, et läksin kohe Karinile-Toomasele lennujaama vastu, et nad Barcelona-reisi lõpetuselt koju transada.</s>
227 0 0 4
{'token': (0, 4, '▁Kiir'), 'predictions': [{'label': 'D', 'probability': 0.99979}]}
(227, 231)
227 0 4 10
{'token': (4, 10, 'korras'), 'predictions': [{'label': 'D', 'probability': 0.9997}]}
(231, 237)
227 0 10 22
{'token': (10, 22, '▁sellepärast'), 'predictions': [{'label': 'D', 'probability': 0.99988}]}
(237, 249)
227 0 22 23
{'token': (22, 23, ','), 'predictions': [{'label': 'Z', 'probability': 0.99997}]}
(249, 250)
227 0 23 26
{'token': (23, 26, '▁et'), 'predictions': [{'label': 'J', 'probability': 0.99991}]}
(250, 253)
227 0 26 33
{'token': (26, 33, '▁läksin'), 'predictions': [{'label': 'sin_V', 'probability': 0.99886}]}
(253, 260)
227 0 33 38
{'token': (33, 38, '▁kohe'), 'predictions': [{'label': 'D', 'probability': 0.99989}]}
(260, 265)
227 0 38 42
{'token': (38, 42, '▁Kar'), 'predictions': [{'label': 'sg all_H', 'probability': 0.95678}]}
(265, 269)
227 0 42 47
{'token': (42, 47, 'inile'), 'predictions': [{'label': 'sg all_H', 'probability': 0.94859}]}
(269, 274)
227 0 47 48
{'token': (47, 48, '-'), 'predictions': [{'label': 'sg all_H', 'probability': 0.7179}]}
(274, 275)
227 0 48 49
{'token': (48, 49, 'T'), 'predictions': [{'label': 'sg all_H', 'probability': 0.94553}]}
(275, 276)
227 0 49 53
{'token': (49, 53, 'ooma'), 'predictions': [{'label': 'sg all_H', 'probability': 0.9597}]}
(276, 280)
227 0 53 57
{'token': (53, 57, 'sele'), 'predictions': [{'label': 'sg all_H', 'probability': 0.97346}]}
(280, 284)
227 0 57 68
{'token': (57, 68, '▁lennujaama'), 'predictions': [{'label': 'sg g_S', 'probability': 0.99971}]}
(284, 295)
227 0 68 74
{'token': (68, 74, '▁vastu'), 'predictions': [{'label': 'K', 'probability': 0.9993}]}
(295, 301)
227 0 74 75
{'token': (74, 75, ','), 'predictions': [{'label': 'Z', 'probability': 0.99997}]}
(301, 302)
227 0 75 78
{'token': (75, 78, '▁et'), 'predictions': [{'label': 'J', 'probability': 0.99991}]}
(302, 305)
227 0 78 82
{'token': (78, 82, '▁nad'), 'predictions': [{'label': 'pl n_P', 'probability': 0.9998}]}
(305, 309)
227 0 82 92
{'token': (82, 92, '▁Barcelona'), 'predictions': [{'label': 'sg g_S', 'probability': 0.9993}]}
(309, 319)
227 0 92 93
{'token': (92, 93, '-'), 'predictions': [{'label': 'sg g_S', 'probability': 0.99961}]}
(319, 320)
227 0 93 98
{'token': (93, 98, 'reisi'), 'predictions': [{'label': 'sg g_S', 'probability': 0.99958}]}
(320, 325)
227 0 98 102
{'token': (98, 102, '▁lõp'), 'predictions': [{'label': 'sg abl_S', 'probability': 0.9948}]}
(325, 329)
227 0 102 104
{'token': (102, 104, 'et'), 'predictions': [{'label': 'sg abl_S', 'probability': 0.99502}]}
(329, 331)
227 0 104 109
{'token': (104, 109, 'uselt'), 'predictions': [{'label': 'sg abl_S', 'probability': 0.99187}]}
(331, 336)
227 0 109 114
{'token': (109, 114, '▁koju'), 'predictions': [{'label': 'adt_S', 'probability': 0.99876}]}
(336, 341)
227 0 114 119
{'token': (114, 119, '▁tran'), 'predictions': [{'label': 'da_V', 'probability': 0.99977}]}
(341, 346)
227 0 119 123
{'token': (119, 123, 'sada'), 'predictions': [{'label': 'da_V', 'probability': 0.99983}]}
(346, 350)
227 0 123 124
{'token': (123, 124, '.'), 'predictions': [{'label': 'Z', 'probability': 0.99997}]}
(350, 351)
<s>Ja siis sõime juba koos ema-isa juures torti.</s>
352 0 0 2
{'token': (0, 2, '▁Ja'), 'predictions': [{'label': 'J', 'probability': 0.99991}]}
(352, 354)
352 0 2 7
{'token': (2, 7, '▁siis'), 'predictions': [{'label': 'D', 'probability': 0.9999}]}
(354, 359)
352 0 7 13
{'token': (7, 13, '▁sõime'), 'predictions': [{'label': 'sime_V', 'probability': 0.99407}]}
(359, 365)
352 0 13 18
{'token': (13, 18, '▁juba'), 'predictions': [{'label': 'D', 'probability': 0.9999}]}
(365, 370)
352 0 18 23
{'token': (18, 23, '▁koos'), 'predictions': [{'label': 'K', 'probability': 0.9997}]}
(370, 375)
352 0 23 27
{'token': (23, 27, '▁ema'), 'predictions': [{'label': 'sg g_S', 'probability': 0.99962}]}
(375, 379)
352 0 27 28
{'token': (27, 28, '-'), 'predictions': [{'label': 'sg g_S', 'probability': 0.99956}]}
(379, 380)
352 0 28 31
{'token': (28, 31, 'isa'), 'predictions': [{'label': 'sg g_S', 'probability': 0.99965}]}
(380, 383)
352 0 31 38
{'token': (31, 38, '▁juures'), 'predictions': [{'label': 'K', 'probability': 0.99972}]}
(383, 390)
352 0 38 42
{'token': (38, 42, '▁tor'), 'predictions': [{'label': 'sg p_S', 'probability': 0.99946}]}
(390, 394)
352 0 42 44
{'token': (42, 44, 'ti'), 'predictions': [{'label': 'sg p_S', 'probability': 0.99941}]}
(394, 396)
352 0 44 45
{'token': (44, 45, '.'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(396, 397)
<s>Tõesti - ma ise olen emana väga õnnelik ja olen väga õnnelik ka oma ema üle.</s>
399 0 0 6
{'token': (0, 6, '▁Tõesti'), 'predictions': [{'label': 'D', 'probability': 0.99989}]}
(399, 405)
399 0 6 8
{'token': (6, 8, '▁-'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(405, 407)
399 0 8 11
{'token': (8, 11, '▁ma'), 'predictions': [{'label': 'sg n_P', 'probability': 0.99983}]}
(407, 410)
399 0 11 15
{'token': (11, 15, '▁ise'), 'predictions': [{'label': 'sg n_P', 'probability': 0.99733}]}
(410, 414)
399 0 15 20
{'token': (15, 20, '▁olen'), 'predictions': [{'label': 'n_V', 'probability': 0.9996}]}
(414, 419)
399 0 20 24
{'token': (20, 24, '▁ema'), 'predictions': [{'label': 'sg es_S', 'probability': 0.99738}]}
(419, 423)
399 0 24 26
{'token': (24, 26, 'na'), 'predictions': [{'label': 'sg es_S', 'probability': 0.99711}]}
(423, 425)
399 0 26 31
{'token': (26, 31, '▁väga'), 'predictions': [{'label': 'D', 'probability': 0.9999}]}
(425, 430)
399 0 31 39
{'token': (31, 39, '▁õnnelik'), 'predictions': [{'label': 'sg n_A', 'probability': 0.99977}]}
(430, 438)
399 0 39 42
{'token': (39, 42, '▁ja'), 'predictions': [{'label': 'J', 'probability': 0.99991}]}
(438, 441)
399 0 42 47
{'token': (42, 47, '▁olen'), 'predictions': [{'label': 'n_V', 'probability': 0.99961}]}
(441, 446)
399 0 47 52
{'token': (47, 52, '▁väga'), 'predictions': [{'label': 'D', 'probability': 0.9999}]}
(446, 451)
399 0 52 60
{'token': (52, 60, '▁õnnelik'), 'predictions': [{'label': 'sg n_A', 'probability': 0.99976}]}
(451, 459)
399 0 60 63
{'token': (60, 63, '▁ka'), 'predictions': [{'label': 'D', 'probability': 0.99989}]}
(459, 462)
399 0 63 67
{'token': (63, 67, '▁oma'), 'predictions': [{'label': 'sg g_P', 'probability': 0.99966}]}
(462, 466)
399 0 67 71
{'token': (67, 71, '▁ema'), 'predictions': [{'label': 'sg g_S', 'probability': 0.9997}]}
(466, 470)
399 0 71 75
{'token': (71, 75, '▁üle'), 'predictions': [{'label': 'K', 'probability': 0.99966}]}
(470, 474)
399 0 75 76
{'token': (75, 76, '.'), 'predictions': [{'label': 'Z', 'probability': 0.99996}]}
(474, 475)

In [21]:
map_words_to_bert_tokens(text_obj.words, morph_layer)

{0: [Span('(', [{'bert_tokens': '▁(', 'morph_labels': 'Z', 'probabilities': 0.99991}])],
 1: [Span('Ameerika', [{'bert_tokens': 'Ameerika', 'morph_labels': 'sg g_H', 'probabilities': 0.99858}])],
 2: [Span(' teadlased', [{'bert_tokens': '▁teadlased', 'morph_labels': 'pl n_S', 'probabilities': 0.99957}])],
 3: [Span(' on', [{'bert_tokens': '▁on', 'morph_labels': 'b_V', 'probabilities': 0.99992}])],
 4: [Span(' kindlaks', [{'bert_tokens': '▁kindlaks', 'morph_labels': 'sg tr_A', 'probabilities': 0.99904}])],
 5: [Span(' teinud', [{'bert_tokens': '▁teinud', 'morph_labels': 'nud_V', 'probabilities': 0.99971}])],
 6: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 7: [Span(' et', [{'bert_tokens': '▁et', 'morph_labels': 'J', 'probabilities': 0.99989}])],
 8: [Span(' 99%', [{'bert_tokens': '▁99%', 'morph_labels': '?_N', 'probabilities': 0.99934}])],
 9: [Span(' blog', [{'bert_tokens': '▁blog', 'morph_labels': 'pl in_S', 'probabilities': 0.99847}]),
  Span('ides', [{'bert_tokens': 'ides', 'morph_labels': 'pl in_S', 'probabilities': 0.99861}])],
 10: [Span(' kirja', [{'bert_tokens': '▁kirja', 'morph_labels': 'adt_S', 'probabilities': 0.60903}])],
 11: [Span(' pandud', [{'bert_tokens': '▁pandud', 'morph_labels': 'tud_V', 'probabilities': 0.99875}])],
 12: [Span(' inf', [{'bert_tokens': '▁inf', 'morph_labels': 'sg el_S', 'probabilities': 0.99922}]),
  Span('ost', [{'bert_tokens': 'ost', 'morph_labels': 'sg el_S', 'probabilities': 0.99914}])],
 13: [Span(' huvitab', [{'bert_tokens': '▁huvitab', 'morph_labels': 'b_V', 'probabilities': 0.99992}])],
 14: [Span(' vaid', [{'bert_tokens': '▁vaid', 'morph_labels': 'D', 'probabilities': 0.99988}])],
 15: [Span(' autorit', [{'bert_tokens': '▁autorit', 'morph_labels': 'sg p_S', 'probabilities': 0.99962}])],
 16: [Span(' v', [{'bert_tokens': '▁v', 'morph_labels': '?_Y', 'probabilities': 0.99501}])],
 17: [Span('�i', [{'bert_tokens': '▁i', 'morph_labels': '?_Y', 'probabilities': 0.99706}])],
 18: [Span('�i', [{'bert_tokens': '▁i', 'morph_labels': '?_Y', 'probabilities': 0.99706}])],
 19: [Span(' selle', [{'bert_tokens': '▁selle', 'morph_labels': 'sg g_P', 'probabilities': 0.99971}])],
 20: [Span(' l', [{'bert_tokens': '▁l', 'morph_labels': '?_Y', 'probabilities': 0.99881}])],
 21: [Span('�h', [{'bert_tokens': '▁h', 'morph_labels': 'pl p_S', 'probabilities': 0.99945}])],
 22: [Span('�h', [{'bert_tokens': '▁h', 'morph_labels': 'pl p_S', 'probabilities': 0.99945}]),
  Span('iko', [{'bert_tokens': 'iko', 'morph_labels': 'pl p_S', 'probabilities': 0.99947}]),
  Span('nd', [{'bert_tokens': 'nd', 'morph_labels': 'pl p_S', 'probabilities': 0.99945}]),
  Span('lasi', [{'bert_tokens': 'lasi', 'morph_labels': 'pl p_S', 'probabilities': 0.99954}])],
 23: [Span('.)', [{'bert_tokens': '.)', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 24: [Span('.)', [{'bert_tokens': '.)', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 25: [Span('Tallinn', [{'bert_tokens': '▁Tallinn', 'morph_labels': 'sg g_H', 'probabilities': 0.99896}]),
  Span('-', [{'bert_tokens': '-', 'morph_labels': 'sg g_H', 'probabilities': 0.99825}]),
  Span('Tartu', [{'bert_tokens': 'Tartu', 'morph_labels': 'sg g_H', 'probabilities': 0.99897}]),
  Span('-', [{'bert_tokens': '-', 'morph_labels': 'sg g_H', 'probabilities': 0.99853}]),
  Span('Tallinna', [{'bert_tokens': 'Tallinna', 'morph_labels': 'sg g_H', 'probabilities': 0.99899}])],
 26: [Span(' p', [{'bert_tokens': '▁p', 'morph_labels': '?_Y', 'probabilities': 0.9973}])],
 27: [Span('�e', [{'bert_tokens': '▁e', 'morph_labels': 'sg n_S', 'probabilities': 0.98374}])],
 28: [Span('�e', [{'bert_tokens': '▁e', 'morph_labels': 'sg n_S', 'probabilities': 0.98374}]),
  Span('v', [{'bert_tokens': 'v', 'morph_labels': 'sg n_S', 'probabilities': 0.99865}])],
 29: [Span(' --', [{'bert_tokens': '▁--', 'morph_labels': 'Z', 'probabilities': 0.99994}])],
 30: [Span(' Tartus', [{'bert_tokens': '▁Tartus', 'morph_labels': 'sg in_H', 'probabilities': 0.99563}])],
 31: [Span(' l', [{'bert_tokens': '▁l', 'morph_labels': '?_Y', 'probabilities': 0.99865}])],
 32: [Span('�pu', [{'bert_tokens': '▁pu', 'morph_labels': 'sg p_S', 'probabilities': 0.51468}])],
 33: [Span('�pu', [{'bert_tokens': '▁pu', 'morph_labels': 'sg p_S', 'probabilities': 0.51468}]),
  Span('pidu', [{'bert_tokens': 'pidu', 'morph_labels': 'sg p_S', 'probabilities': 0.73874}])],
 34: [Span(' ja', [{'bert_tokens': '▁ja', 'morph_labels': 'J', 'probabilities': 0.9999}])],
 35: [Span(' diplomi', [{'bert_tokens': '▁diplomi', 'morph_labels': 'sg g_S', 'probabilities': 0.99968}])],
 36: [Span(' k', [{'bert_tokens': '▁k', 'morph_labels': '?_Y', 'probabilities': 0.9985}])],
 37: [Span('�t', [{'bert_tokens': '▁t', 'morph_labels': 'sg g_S', 'probabilities': 0.996}])],
 38: [Span('�t', [{'bert_tokens': '▁t', 'morph_labels': 'sg g_S', 'probabilities': 0.996}]),
  Span('te', [{'bert_tokens': 'te', 'morph_labels': 'sg g_S', 'probabilities': 0.9989}])],
 39: [Span(' saamine', [{'bert_tokens': '▁saamine', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}])],
 40: [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99995}])],
 41: [Span('8', [{'bert_tokens': '▁8', 'morph_labels': '?_N', 'probabilities': 0.99942}])],
 42: [Span(' aastat', [{'bert_tokens': '▁aastat', 'morph_labels': 'sg p_S', 'probabilities': 0.99961}])],
 43: [Span(' T', [{'bert_tokens': '▁T', 'morph_labels': 'sg in_Y', 'probabilities': 0.38007}])],
 44: [Span('�-', [{'bert_tokens': '▁-', 'morph_labels': 'sg in_Y', 'probabilities': 0.45885}])],
 45: [Span('s', [{'bert_tokens': 's', 'morph_labels': '?_Y', 'probabilities': 0.26216}])],
 46: [Span(' k', [{'bert_tokens': '▁k', 'morph_labels': '?_Y', 'probabilities': 0.99859}])],
 47: [Span('�id', [{'bert_tokens': '▁id', 'morph_labels': 'pl n_S', 'probabilities': 0.99938}])],
 48: [Span('�id', [{'bert_tokens': '▁id', 'morph_labels': 'pl n_S', 'probabilities': 0.99938}]),
  Span('ud', [{'bert_tokens': 'ud', 'morph_labels': 'pl n_S', 'probabilities': 0.99946}])],
 49: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99995}])],
 50: [Span(' k', [{'bert_tokens': '▁k', 'morph_labels': '?_Y', 'probabilities': 0.99868}])],
 51: [Span('�ik', [{'bert_tokens': '▁ik', 'morph_labels': 'sg n_S', 'probabilities': 0.99602}])],
 52: [Span('�ik', [{'bert_tokens': '▁ik', 'morph_labels': 'sg n_S', 'probabilities': 0.99602}])],
 53: [Span(' kur', [{'bert_tokens': '▁kur', 'morph_labels': 'pl n_S', 'probabilities': 0.99896}]),
  Span('sa', [{'bert_tokens': 'sa', 'morph_labels': 'pl n_S', 'probabilities': 0.99925}]),
  Span('kaaslased', [{'bert_tokens': 'kaaslased', 'morph_labels': 'pl n_S', 'probabilities': 0.99944}])],
 54: [Span(' ammu', [{'bert_tokens': '▁ammu', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 55: [Span(' juba', [{'bert_tokens': '▁juba', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 56: [Span(' l', [{'bert_tokens': '▁l', 'morph_labels': '?_Y', 'probabilities': 0.9988}])],
 57: [Span('�pe', [{'bert_tokens': '▁pe', 'morph_labels': 'nud_V', 'probabilities': 0.99939}])],
 58: [Span('�pe', [{'bert_tokens': '▁pe', 'morph_labels': 'nud_V', 'probabilities': 0.99939}]),
  Span('tanud', [{'bert_tokens': 'tanud', 'morph_labels': 'nud_V', 'probabilities': 0.99969}])],
 59: [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 60: [Span('Seega', [{'bert_tokens': '▁Seega', 'morph_labels': 'D', 'probabilities': 0.99991}])],
 61: [Span(' eriti', [{'bert_tokens': '▁eriti', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 62: [Span(' vanu', [{'bert_tokens': '▁vanu', 'morph_labels': 'pl p_A', 'probabilities': 0.99922}])],
 63: [Span(' tuttavaid', [{'bert_tokens': '▁tuttavaid', 'morph_labels': 'pl p_S', 'probabilities': 0.99967}])],
 64: [Span(' kohata', [{'bert_tokens': '▁kohata', 'morph_labels': 'da_V', 'probabilities': 0.99988}])],
 65: [Span(' ei', [{'bert_tokens': '▁ei', 'morph_labels': 'neg_V', 'probabilities': 0.99987}])],
 66: [Span(' loo', [{'bert_tokens': '▁loo', 'morph_labels': 'nud_V', 'probabilities': 0.99977}]),
  Span('tnud', [{'bert_tokens': 'tnud', 'morph_labels': 'nud_V', 'probabilities': 0.99977}])],
 67: [Span(' --', [{'bert_tokens': '▁--', 'morph_labels': 'Z', 'probabilities': 0.99997}])],
 68: [Span(' kes', [{'bert_tokens': '▁kes', 'morph_labels': 'sg n_P', 'probabilities': 0.99986}])],
 69: [Span(' see', [{'bert_tokens': '▁see', 'morph_labels': 'sg n_P', 'probabilities': 0.99986}])],
 70: [Span(' ikka', [{'bert_tokens': '▁ikka', 'morph_labels': 'D', 'probabilities': 0.99991}])],
 71: [Span(' peale', [{'bert_tokens': '▁peale', 'morph_labels': 'K', 'probabilities': 0.97435}])],
 72: [Span(' perekonna', [{'bert_tokens': '▁perekonna', 'morph_labels': 'sg g_S', 'probabilities': 0.99972}])],
 73: [Span(' teab', [{'bert_tokens': '▁teab', 'morph_labels': 'b_V', 'probabilities': 0.99993}])],
 74: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99997}])],
 75: [Span(' et', [{'bert_tokens': '▁et', 'morph_labels': 'J', 'probabilities': 0.99991}])],
 76: [Span(' t', [{'bert_tokens': '▁t', 'morph_labels': '?_Y', 'probabilities': 0.99844}])],
 77: [Span('�na', [{'bert_tokens': '▁na', 'morph_labels': '?_Y', 'probabilities': 0.99786}])],
 78: [Span('�na', [{'bert_tokens': '▁na', 'morph_labels': '?_Y', 'probabilities': 0.99786}])],
 79: [Span(' l', [{'bert_tokens': '▁l', 'morph_labels': '?_Y', 'probabilities': 0.99872}])],
 80: [Span('�pe', [{'bert_tokens': '▁pe', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}])],
 81: [Span('�pe', [{'bert_tokens': '▁pe', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}]),
  Span('tamine', [{'bert_tokens': 'tamine', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}])],
 82: [Span(' on', [{'bert_tokens': '▁on', 'morph_labels': 'b_V', 'probabilities': 0.99993}])],
 83: [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99997}])],
 84: [Span('Mind', [{'bert_tokens': '▁Mind', 'morph_labels': 'sg p_P', 'probabilities': 0.99976}])],
 85: [Span('�l', [{'bert_tokens': '▁l', 'morph_labels': 'sid_V', 'probabilities': 0.99981}])],
 86: [Span('�l', [{'bert_tokens': '▁l', 'morph_labels': 'sid_V', 'probabilities': 0.99981}]),
  Span('la', [{'bert_tokens': 'la', 'morph_labels': 'sid_V', 'probabilities': 0.99981}]),
  Span('tasid', [{'bert_tokens': 'tasid', 'morph_labels': 'sid_V', 'probabilities': 0.99981}])],
 87: [Span(' aga', [{'bert_tokens': '▁aga', 'morph_labels': 'J', 'probabilities': 0.99991}])],
 88: [Span(' vanad', [{'bert_tokens': '▁vanad', 'morph_labels': 'pl n_A', 'probabilities': 0.99932}])],
 89: [Span(' s', [{'bert_tokens': '▁s', 'morph_labels': '?_Y', 'probabilities': 0.99893}])],
 90: [Span('�b', [{'bert_tokens': '▁b', 'morph_labels': 'pl n_S', 'probabilities': 0.99941}])],
 91: [Span('�b', [{'bert_tokens': '▁b', 'morph_labels': 'pl n_S', 'probabilities': 0.99941}]),
  Span('rad', [{'bert_tokens': 'rad', 'morph_labels': 'pl n_S', 'probabilities': 0.99945}])],
 92: [Span(' -', [{'bert_tokens': '▁-', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 93: [Span(' Lea', [{'bert_tokens': '▁Lea', 'morph_labels': 'sg n_H', 'probabilities': 0.99949}])],
 94: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99995}])],
 95: [Span(' Pille', [{'bert_tokens': '▁Pille', 'morph_labels': 'sg n_H', 'probabilities': 0.99951}])],
 96: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99995}])],
 97: [Span(' Len', [{'bert_tokens': '▁Len', 'morph_labels': 'sg n_H', 'probabilities': 0.99951}]),
  Span('ar', [{'bert_tokens': 'ar', 'morph_labels': 'sg n_H', 'probabilities': 0.99951}])],
 98: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99995}])],
 99: [Span(' Marge', [{'bert_tokens': '▁Marge', 'morph_labels': 'sg n_H', 'probabilities': 0.99952}])],
 100: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 101: [Span(' Liis', [{'bert_tokens': '▁Liis', 'morph_labels': 'sg n_H', 'probabilities': 0.99952}])],
 102: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 103: [Span(' Tarmo', [{'bert_tokens': '▁Tarmo', 'morph_labels': 'sg n_H', 'probabilities': 0.99956}])],
 104: [Span(' -', [{'bert_tokens': '▁-', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 105: [Span(' kes', [{'bert_tokens': '▁kes', 'morph_labels': 'sg n_P', 'probabilities': 0.99986}])],
 106: [Span(' isegi', [{'bert_tokens': '▁isegi', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 107: [Span(' lille', [{'bert_tokens': '▁lille', 'morph_labels': 'pl n_S', 'probabilities': 0.9996}]),
  Span('k', [{'bert_tokens': 'k', 'morph_labels': 'pl n_S', 'probabilities': 0.99962}]),
  Span('imb', [{'bert_tokens': 'imb', 'morph_labels': 'pl n_S', 'probabilities': 0.99963}]),
  Span('ud', [{'bert_tokens': 'ud', 'morph_labels': 'pl n_S', 'probabilities': 0.99965}])],
 108: [Span(' kaasa', [{'bert_tokens': '▁kaasa', 'morph_labels': 'D', 'probabilities': 0.99989}])],
 109: [Span(' olid', [{'bert_tokens': '▁olid', 'morph_labels': 'sid_V', 'probabilities': 0.99982}])],
 110: [Span(' v', [{'bert_tokens': '▁v', 'morph_labels': '?_Y', 'probabilities': 0.99883}])],
 111: [Span('�t', [{'bert_tokens': '▁t', 'morph_labels': 'nud_V', 'probabilities': 0.98187}])],
 112: [Span('�t', [{'bert_tokens': '▁t', 'morph_labels': 'nud_V', 'probabilities': 0.98187}]),
  Span('nud', [{'bert_tokens': 'nud', 'morph_labels': 'nud_V', 'probabilities': 0.99888}])],
 113: [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 114: [Span('Suured', [{'bert_tokens': '▁Suured', 'morph_labels': 'pl n_A', 'probabilities': 0.99924}])],
 115: [Span(' t', [{'bert_tokens': '▁t', 'morph_labels': 'pl n_S', 'probabilities': 0.57077}])],
 116: [Span('�n', [{'bert_tokens': '▁n', 'morph_labels': 'pl n_S', 'probabilities': 0.99807}])],
 117: [Span('�n', [{'bert_tokens': '▁n', 'morph_labels': 'pl n_S', 'probabilities': 0.99807}]),
  Span('ud', [{'bert_tokens': 'ud', 'morph_labels': 'pl n_S', 'probabilities': 0.99892}])],
 118: [Span(' teile', [{'bert_tokens': '▁teile', 'morph_labels': 'pl all_P', 'probabilities': 0.99914}])],
 119: [Span(' sooja', [{'bert_tokens': '▁sooja', 'morph_labels': 'pl g_A', 'probabilities': 0.99861}]),
  Span('de', [{'bert_tokens': 'de', 'morph_labels': 'pl g_A', 'probabilities': 0.99848}])],
 120: [Span(' s', [{'bert_tokens': '▁s', 'morph_labels': '?_Y', 'probabilities': 0.99132}])],
 121: [Span('�nad', [{'bert_tokens': '▁nad', 'morph_labels': 'pl g_S', 'probabilities': 0.91637}])],
 122: [Span('�nad', [{'bert_tokens': '▁nad', 'morph_labels': 'pl g_S', 'probabilities': 0.91637}]),
  Span('e', [{'bert_tokens': 'e', 'morph_labels': 'pl g_S', 'probabilities': 0.83475}])],
 123: [Span(' eest', [{'bert_tokens': '▁eest', 'morph_labels': 'K', 'probabilities': 0.99961}])],
 124: [Span(' veelkord', [{'bert_tokens': '▁veelkord', 'morph_labels': 'D', 'probabilities': 0.99989}])],
 125: [Span('!', [{'bert_tokens': '!', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 126: [Span('Kirjutasin', [{'bert_tokens': '▁Kirjutasin', 'morph_labels': 'sin_V', 'probabilities': 0.99884}])],
 127: [Span(' eelmisel', [{'bert_tokens': '▁eelmisel', 'morph_labels': 'sg ad_A', 'probabilities': 0.9986}])],
 128: [Span(' kuul', [{'bert_tokens': '▁kuul', 'morph_labels': 'sg ad_S', 'probabilities': 0.99953}])],
 129: [Span(' blog', [{'bert_tokens': '▁blog', 'morph_labels': 'sg ill_S', 'probabilities': 0.99858}]),
  Span('isse', [{'bert_tokens': 'isse', 'morph_labels': 'sg ill_S', 'probabilities': 0.99835}])],
 130: [Span(' ka', [{'bert_tokens': '▁ka', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 131: [Span(' k', [{'bert_tokens': '▁k', 'morph_labels': '?_Y', 'probabilities': 0.99565}])],
 132: [Span('�sim', [{'bert_tokens': '▁sim', 'morph_labels': 'sg g_S', 'probabilities': 0.99844}])],
 133: [Span('�sim', [{'bert_tokens': '▁sim', 'morph_labels': 'sg g_S', 'probabilities': 0.99844}]),
  Span('use', [{'bert_tokens': 'use', 'morph_labels': 'sg g_S', 'probabilities': 0.9982}])],
 134: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99997}])],
 135: [Span(' et', [{'bert_tokens': '▁et', 'morph_labels': 'J', 'probabilities': 0.9999}])],
 136: [Span(' mida', [{'bert_tokens': '▁mida', 'morph_labels': 'sg p_P', 'probabilities': 0.99979}])],
 137: [Span(' (', [{'bert_tokens': '▁(', 'morph_labels': 'Z', 'probabilities': 0.99993}])],
 138: [Span('hea', [{'bert_tokens': 'hea', 'morph_labels': 'sg n_A', 'probabilities': 0.9995}])],
 139: [Span(' lugeja', [{'bert_tokens': '▁lugeja', 'morph_labels': 'sg n_S', 'probabilities': 0.99965}])],
 140: [Span(')', [{'bert_tokens': ')', 'morph_labels': 'Z', 'probabilities': 0.99994}])],
 141: [Span(' edasi', [{'bert_tokens': '▁edasi', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 142: [Span(' soovita', [{'bert_tokens': '▁soovita', 'morph_labels': 'd_V', 'probabilities': 0.9993}]),
  Span('d', [{'bert_tokens': 'd', 'morph_labels': 'd_V', 'probabilities': 0.99934}])],
 143: [Span('�p', [{'bert_tokens': '▁p', 'morph_labels': 'da_V', 'probabilities': 0.9977}])],
 144: [Span('�p', [{'bert_tokens': '▁p', 'morph_labels': 'da_V', 'probabilities': 0.9977}]),
  Span('pida', [{'bert_tokens': 'pida', 'morph_labels': 'da_V', 'probabilities': 0.99919}])],
 145: [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 146: [Span('T', [{'bert_tokens': '▁T', 'morph_labels': '?_Y', 'probabilities': 0.75227}])],
 147: [Span('�n', [{'bert_tokens': '▁n', 'morph_labels': 'pl n_S', 'probabilities': 0.98616}])],
 148: [Span('�n', [{'bert_tokens': '▁n', 'morph_labels': 'pl n_S', 'probabilities': 0.98616}]),
  Span('ud', [{'bert_tokens': 'ud', 'morph_labels': 'pl n_S', 'probabilities': 0.99315}])],
 149: [Span(' blogis', [{'bert_tokens': '▁blogis', 'morph_labels': 'sg kom_S', 'probabilities': 0.99783}])],
 150: [Span('/', [{'bert_tokens': '/', 'morph_labels': 'sg kom_S', 'probabilities': 0.99703}])],
 151: [Span('e', [{'bert_tokens': 'e', 'morph_labels': 'sg kom_S', 'probabilities': 0.99958}]),
  Span('-', [{'bert_tokens': '-', 'morph_labels': 'sg kom_S', 'probabilities': 0.99958}]),
  Span('meil', [{'bert_tokens': 'meil', 'morph_labels': 'sg kom_S', 'probabilities': 0.99958}]),
  Span('iga', [{'bert_tokens': 'iga', 'morph_labels': 'sg kom_S', 'probabilities': 0.99955}])],
 152: [Span(' vasta', [{'bert_tokens': '▁vasta', 'morph_labels': 'pl all_S', 'probabilities': 0.9991}]),
  Span('jatele', [{'bert_tokens': 'jatele', 'morph_labels': 'pl all_S', 'probabilities': 0.99906}])],
 153: [Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99996}])],
 154: [Span(' kuid', [{'bert_tokens': '▁kuid', 'morph_labels': 'J', 'probabilities': 0.99989}])],
 155: [Span(' otsust', [{'bert_tokens': '▁otsust', 'morph_labels': 'sg p_S', 'probabilities': 0.99965}])],
 156: [Span(' pole', [{'bert_tokens': '▁pole', 'morph_labels': 'neg o_V', 'probabilities': 0.99946}])],
 157: [Span(' ma', [{'bert_tokens': '▁ma', 'morph_labels': 'sg n_P', 'probabilities': 0.99987}])],
 158: [Span(' ikka', [{'bert_tokens': '▁ikka', 'morph_labels': 'D', 'probabilities': 0.99991}])],
 159: [Span(' veel', [{'bert_tokens': '▁veel', 'morph_labels': 'D', 'probabilities': 0.9999}])],
 160: [Span(' teinud', [{'bert_tokens': '▁teinud', 'morph_labels': 'nud_V', 'probabilities': 0.9998}])],
 161: [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99997}])],
 162: [Span('Ehk', [{'bert_tokens': '▁Ehk', 'morph_labels': 'D', 'probabilities': 0.99989}])],
 163: [Span(' tuleb', [{'bert_tokens': '▁tuleb', 'morph_labels': 'b_V', 'probabilities': 0.99992}])],
 164: [Span(' j', [{'bert_tokens': '▁j', 'morph_labels': '?_Y', 'probabilities': 0.99812}])],
 165: [Span('�ni', [{'bert_tokens': '▁ni', 'morph_labels': '?_Y', 'probabilities': 0.99683}])],
 166: [Span('�ni', [{'bert_tokens': '▁ni', 'morph_labels': '?_Y', 'probabilities': 0.99683}])],
 167: [Span('�sel', [{'bert_tokens': '▁sel', 'morph_labels': 'sg ad_P', 'probabilities': 0.99965}])],

In [ ]:
mapping = map_words_to_bert_tokens(text_obj.words, morph_layer)
for k, v in mapping.items():
    # print([sp['bert_tokens'][0] for sp in v])
    print(
        k,
        text_obj.words[k].text,
        text_obj.words[k].base_span,
        [sp.annotations[0].bert_tokens for sp in v],
    )
    # rewriter_decorator(text_obj, k, v)
print(len(mapping), len(text_obj.words))

0 ( ElementaryBaseSpan(0, 1) ['▁(']
1 Ameerika ElementaryBaseSpan(1, 9) ['Ameerika']
2 teadlased ElementaryBaseSpan(10, 19) ['▁teadlased']
3 on ElementaryBaseSpan(20, 22) ['▁on']
4 kindlaks ElementaryBaseSpan(23, 31) ['▁kindlaks']
5 teinud ElementaryBaseSpan(32, 38) ['▁teinud']
6 , ElementaryBaseSpan(38, 39) [',']
7 et ElementaryBaseSpan(40, 42) ['▁et']
8 99% ElementaryBaseSpan(43, 46) ['▁99%']
9 blogides ElementaryBaseSpan(47, 55) ['▁blog', 'ides']
10 kirja ElementaryBaseSpan(56, 61) ['▁kirja']
11 pandud ElementaryBaseSpan(62, 68) ['▁pandud']
12 infost ElementaryBaseSpan(69, 75) ['▁inf', 'ost']
13 huvitab ElementaryBaseSpan(76, 83) ['▁huvitab']
14 vaid ElementaryBaseSpan(84, 88) ['▁vaid']
15 autorit ElementaryBaseSpan(89, 96) ['▁autorit']
16 v ElementaryBaseSpan(97, 98) ['▁v']
17 � ElementaryBaseSpan(98, 99) ['▁i']
18 i ElementaryBaseSpan(99, 100) ['▁i']
19 selle ElementaryBaseSpan(101, 106) ['▁selle']
20 l ElementaryBaseSpan(107, 108) ['▁l']
21 � ElementaryBaseSpan(108, 109) ['▁h']
22 hikondlasi ElementaryBaseSpan(109, 119) ['▁h', 'iko', 'nd', 'lasi']
23 . ElementaryBaseSpan(119, 120) ['.)']
24 ) ElementaryBaseSpan(120, 121) ['.)']
25 Tallinn-Tartu-Tallinna ElementaryBaseSpan(123, 145) ['▁Tallinn', '-', 'Tartu', '-', 'Tallinna']
26 p ElementaryBaseSpan(146, 147) ['▁p']
27 � ElementaryBaseSpan(147, 148) ['▁e']
28 ev ElementaryBaseSpan(148, 150) ['▁e', 'v']
29 -- ElementaryBaseSpan(151, 153) ['▁--']
30 Tartus ElementaryBaseSpan(154, 160) ['▁Tartus']
31 l ElementaryBaseSpan(161, 162) ['▁l']
32 � ElementaryBaseSpan(162, 163) ['▁pu']
33 pupidu ElementaryBaseSpan(163, 169) ['▁pu', 'pidu']
34 ja ElementaryBaseSpan(170, 172) ['▁ja']
35 diplomi ElementaryBaseSpan(173, 180) ['▁diplomi']
36 k ElementaryBaseSpan(181, 182) ['▁k']
37 � ElementaryBaseSpan(182, 183) ['▁t']
38 tte ElementaryBaseSpan(183, 186) ['▁t', 'te']
39 saamine ElementaryBaseSpan(187, 194) ['▁saamine']
40 . ElementaryBaseSpan(194, 195) ['.']
41 8 ElementaryBaseSpan(196, 197) ['▁8']
42 aastat ElementaryBaseSpan(198, 204) ['▁aastat']
43 T ElementaryBaseSpan(205, 206) ['▁T']
44 �- ElementaryBaseSpan(206, 208) ['▁-']
45 s ElementaryBaseSpan(208, 209) ['s']
46 k ElementaryBaseSpan(210, 211) ['▁k']
47 � ElementaryBaseSpan(211, 212) ['▁id']
48 idud ElementaryBaseSpan(212, 216) ['▁id', 'ud']
49 , ElementaryBaseSpan(216, 217) [',']
50 k ElementaryBaseSpan(218, 219) ['▁k']
51 � ElementaryBaseSpan(219, 220) ['▁ik']
52 ik ElementaryBaseSpan(220, 222) ['▁ik']
53 kursakaaslased ElementaryBaseSpan(223, 237) ['▁kur', 'sa', 'kaaslased']
54 ammu ElementaryBaseSpan(238, 242) ['▁ammu']
55 juba ElementaryBaseSpan(243, 247) ['▁juba']
56 l ElementaryBaseSpan(248, 249) ['▁l']
57 � ElementaryBaseSpan(249, 250) ['▁pe']
58 petanud ElementaryBaseSpan(250, 257) ['▁pe', 'tanud']
59 . ElementaryBaseSpan(257, 258) ['.']
60 Seega ElementaryBaseSpan(259, 264) ['▁Seega']
61 eriti ElementaryBaseSpan(265, 270) ['▁eriti']
62 vanu ElementaryBaseSpan(271, 275) ['▁vanu']
63 tuttavaid ElementaryBaseSpan(276, 285) ['▁tuttavaid']
64 kohata ElementaryBaseSpan(286, 292) ['▁kohata']
65 ei ElementaryBaseSpan(293, 295) ['▁ei']
66 lootnud ElementaryBaseSpan(296, 303) ['▁loo', 'tnud']
67 -- ElementaryBaseSpan(304, 306) ['▁--']
68 kes ElementaryBaseSpan(307, 310) ['▁kes']
69 see ElementaryBaseSpan(311, 314) ['▁see']
70 ikka ElementaryBaseSpan(315, 319) ['▁ikka']
71 peale ElementaryBaseSpan(320, 325) ['▁peale']
72 perekonna ElementaryBaseSpan(326, 335) ['▁perekonna']
73 teab ElementaryBaseSpan(336, 340) ['▁teab']
74 , ElementaryBaseSpan(340, 341) [',']
75 et ElementaryBaseSpan(342, 344) ['▁et']
76 t ElementaryBaseSpan(345, 346) ['▁t']
77 � ElementaryBaseSpan(346, 347) ['▁na']
78 na ElementaryBaseSpan(347, 349) ['▁na']
79 l ElementaryBaseSpan(350, 351) ['▁l']
80 � ElementaryBaseSpan(351, 352) ['▁pe']
81 petamine ElementaryBaseSpan(352, 360) ['▁pe', 'tamine']
82 on ElementaryBaseSpan(361, 363) ['▁on']
83 . ElementaryBaseSpan(363, 364) ['.']
84 Mind ElementaryBaseSpan(365, 369) ['▁Mind']
85 � ElementaryBaseSpan(370, 371) ['▁l']
86 llatasid ElementaryBaseSpan(371, 379) ['▁l', 'la', 'tasid']
87 aga ElementaryBaseSpan(380, 383) ['▁aga']
88 vanad ElementaryBaseSpan(384, 389) ['▁vanad']
89 s ElementaryBaseSpan(390, 391) ['▁s']
90 � ElementaryBaseSpan(391, 392) ['▁b']
91 brad ElementaryBaseSpan(392, 396) ['▁b', 'rad']
92 - ElementaryBaseSpan(397, 398) ['▁-']
93 Lea ElementaryBaseSpan(399, 402) ['▁Lea']
94 , ElementaryBaseSpan(402, 403) [',']
95 Pille ElementaryBaseSpan(404, 409) ['▁Pille']
96 , ElementaryBaseSpan(409, 410) [',']
97 Lenar ElementaryBaseSpan(411, 416) ['▁Len', 'ar']
98 , ElementaryBaseSpan(416, 417) [',']
99 Marge ElementaryBaseSpan(418, 423) ['▁Marge']
100 , ElementaryBaseSpan(423, 424) [',']
101 Liis ElementaryBaseSpan(425, 429) ['▁Liis']
102 , ElementaryBaseSpan(429, 430) [',']
103 Tarmo ElementaryBaseSpan(431, 436) ['▁Tarmo']
104 - ElementaryBaseSpan(437, 438) ['▁-']
105 kes ElementaryBaseSpan(439, 442) ['▁kes']
106 isegi ElementaryBaseSpan(443, 448) ['▁isegi']
107 lillekimbud ElementaryBaseSpan(449, 460) ['▁lille', 'k', 'imb', 'ud']
108 kaasa ElementaryBaseSpan(461, 466) ['▁kaasa']
109 olid ElementaryBaseSpan(467, 471) ['▁olid']
110 v ElementaryBaseSpan(472, 473) ['▁v']
111 � ElementaryBaseSpan(473, 474) ['▁t']
112 tnud ElementaryBaseSpan(474, 478) ['▁t', 'nud']
113 . ElementaryBaseSpan(478, 479) ['.']
114 Suured ElementaryBaseSpan(480, 486) ['▁Suured']
115 t ElementaryBaseSpan(487, 488) ['▁t']
116 � ElementaryBaseSpan(488, 489) ['▁n']
117 nud ElementaryBaseSpan(489, 492) ['▁n', 'ud']
118 teile ElementaryBaseSpan(493, 498) ['▁teile']
119 soojade ElementaryBaseSpan(499, 506) ['▁sooja', 'de']
120 s ElementaryBaseSpan(507, 508) ['▁s']
121 � ElementaryBaseSpan(508, 509) ['▁nad']
122 nade ElementaryBaseSpan(509, 513) ['▁nad', 'e']
123 eest ElementaryBaseSpan(514, 518) ['▁eest']
124 veelkord ElementaryBaseSpan(519, 527) ['▁veelkord']
125 ! ElementaryBaseSpan(527, 528) ['!']
126 Kirjutasin ElementaryBaseSpan(530, 540) ['▁Kirjutasin']
127 eelmisel ElementaryBaseSpan(541, 549) ['▁eelmisel']
128 kuul ElementaryBaseSpan(550, 554) ['▁kuul']
129 blogisse ElementaryBaseSpan(555, 563) ['▁blog', 'isse']
130 ka ElementaryBaseSpan(564, 566) ['▁ka']
131 k ElementaryBaseSpan(567, 568) ['▁k']
132 � ElementaryBaseSpan(568, 569) ['▁sim']
133 simuse ElementaryBaseSpan(569, 575) ['▁sim', 'use']
134 , ElementaryBaseSpan(575, 576) [',']
135 et ElementaryBaseSpan(577, 579) ['▁et']
136 mida ElementaryBaseSpan(580, 584) ['▁mida']
137 ( ElementaryBaseSpan(585, 586) ['▁(']
138 hea ElementaryBaseSpan(586, 589) ['hea']
139 lugeja ElementaryBaseSpan(590, 596) ['▁lugeja']
140 ) ElementaryBaseSpan(596, 597) [')']
141 edasi ElementaryBaseSpan(598, 603) ['▁edasi']
142 soovitad ElementaryBaseSpan(604, 612) ['▁soovita', 'd']
143 � ElementaryBaseSpan(613, 614) ['▁p']
144 ppida ElementaryBaseSpan(614, 619) ['▁p', 'pida']
145 . ElementaryBaseSpan(619, 620) ['.']
146 T ElementaryBaseSpan(621, 622) ['▁T']
147 � ElementaryBaseSpan(622, 623) ['▁n']
148 nud ElementaryBaseSpan(623, 626) ['▁n', 'ud']
149 blogis ElementaryBaseSpan(627, 633) ['▁blogis']
150 / ElementaryBaseSpan(633, 634) ['/']
151 e-meiliga ElementaryBaseSpan(634, 643) ['e', '-', 'meil', 'iga']
152 vastajatele ElementaryBaseSpan(644, 655) ['▁vasta', 'jatele']
153 , ElementaryBaseSpan(655, 656) [',']
154 kuid ElementaryBaseSpan(657, 661) ['▁kuid']
155 otsust ElementaryBaseSpan(662, 668) ['▁otsust']
156 pole ElementaryBaseSpan(669, 673) ['▁pole']
157 ma ElementaryBaseSpan(674, 676) ['▁ma']
158 ikka ElementaryBaseSpan(677, 681) ['▁ikka']
159 veel ElementaryBaseSpan(682, 686) ['▁veel']
160 teinud ElementaryBaseSpan(687, 693) ['▁teinud']
161 . ElementaryBaseSpan(693, 694) ['.']
162 Ehk ElementaryBaseSpan(695, 698) ['▁Ehk']
163 tuleb ElementaryBaseSpan(699, 704) ['▁tuleb']
164 j ElementaryBaseSpan(705, 706) ['▁j']
165 �� ElementaryBaseSpan(706, 708) ['▁ni']
166 ni ElementaryBaseSpan(708, 710) ['▁ni']
167 �� ElementaryBaseSpan(710, 712) ['▁sel']
168 sel ElementaryBaseSpan(712, 715) ['▁sel']
169 s ElementaryBaseSpan(716, 717) ['▁s']
170 � ElementaryBaseSpan(717, 718) ['▁na']
171 najala ElementaryBaseSpan(718, 724) ['▁na', 'jala']
172 � ElementaryBaseSpan(724, 725) ['▁it']
173 it ElementaryBaseSpan(725, 727) ['▁it']
174 otsides ElementaryBaseSpan(728, 735) ['▁otsides']
175 m ElementaryBaseSpan(736, 737) ['▁m']
176 � ElementaryBaseSpan(737, 738) ['▁ni']
177 ni ElementaryBaseSpan(738, 740) ['▁ni']
178 hea ElementaryBaseSpan(741, 744) ['▁hea']
179 m ElementaryBaseSpan(745, 746) ['▁m']
180 � ElementaryBaseSpan(746, 747) ['▁te']
181 te ElementaryBaseSpan(747, 749) ['▁te']
182 . ElementaryBaseSpan(749, 750) ['.']
183 V ElementaryBaseSpan(751, 752) ['▁V']
184 � ElementaryBaseSpan(752, 753) ['▁i']
185 i ElementaryBaseSpan(753, 754) ['▁i']
186 on ElementaryBaseSpan(755, 757) ['▁on']
187 Sul ElementaryBaseSpan(758, 761) ['▁Sul']
188 m ElementaryBaseSpan(762, 763) ['▁m']
189 � ElementaryBaseSpan(763, 764) ['▁ni']
190 ni ElementaryBaseSpan(764, 766) ['▁ni']
191 ettepanek ElementaryBaseSpan(767, 776) ['▁ettepanek']
192 ? ElementaryBaseSpan(776, 777) ['?']
193 ---- ElementaryBaseSpan(779, 783) ['▁-', '---']
194 P ElementaryBaseSpan(784, 785) ['▁P']
195 � ElementaryBaseSpan(785, 786) ['▁ra']
196 rast ElementaryBaseSpan(786, 790) ['▁ra', 'st']
197 l ElementaryBaseSpan(791, 792) ['▁l']
198 � ElementaryBaseSpan(792, 793) ['▁pu']
199 puaktust ElementaryBaseSpan(793, 801) ['▁pu', 'akt', 'ust']
200 perekonnaga ElementaryBaseSpan(802, 813) ['▁perekonna', 'ga']
201 l ElementaryBaseSpan(814, 815) ['▁l']
202 � ElementaryBaseSpan(815, 816) ['▁u']
203 unas ElementaryBaseSpan(816, 820) ['▁u', 'nas']
204 �� ElementaryBaseSpan(820, 822) ['▁ki']
205 ki ElementaryBaseSpan(822, 824) ['▁ki']
206 s ElementaryBaseSpan(825, 826) ['▁s']
207 �� ElementaryBaseSpan(826, 828) ['▁es']
208 es ElementaryBaseSpan(828, 830) ['▁es']
209 avastasin ElementaryBaseSpan(831, 840) ['▁avastasin']
210 end ElementaryBaseSpan(841, 844) ['▁end']
211 taaskord ElementaryBaseSpan(845, 853) ['▁taaskord']
212 m ElementaryBaseSpan(854, 855) ['▁m']
213 � ElementaryBaseSpan(855, 856) ['▁t']
214 ttel ElementaryBaseSpan(856, 860) ['▁t', 'tel']
215 , ElementaryBaseSpan(860, 861) [',']
216 et ElementaryBaseSpan(862, 864) ['▁et']
217 kui ElementaryBaseSpan(865, 868) ['▁kui']
218 v ElementaryBaseSpan(869, 870) ['▁v']
219 � ElementaryBaseSpan(870, 871) ['▁he']
220 he ElementaryBaseSpan(871, 873) ['▁he']
221 me ElementaryBaseSpan(874, 876) ['▁me']
222 oma ElementaryBaseSpan(877, 880) ['▁oma']
223 vanematest ElementaryBaseSpan(881, 891) ['▁vanematest']
224 tegelikult ElementaryBaseSpan(892, 902) ['▁tegelikult']
225 teavad ElementaryBaseSpan(903, 909) ['▁teavad']
226 . ElementaryBaseSpan(909, 910) ['.']
227 Selliseid ElementaryBaseSpan(911, 920) ['▁Selliseid']
228 isklikke ElementaryBaseSpan(921, 929) ['▁is', 'k', 'likke']
229 asju ElementaryBaseSpan(930, 934) ['▁asju']
230 , ElementaryBaseSpan(934, 935) [',']
231 ma ElementaryBaseSpan(936, 938) ['▁ma']
232 m ElementaryBaseSpan(939, 940) ['▁m']
233 � ElementaryBaseSpan(940, 941) ['▁t']
234 tlen ElementaryBaseSpan(941, 945) ['▁t', 'len']
235 -- ElementaryBaseSpan(946, 948) ['▁--']
236 suhted ElementaryBaseSpan(949, 955) ['▁suhted']
237 , ElementaryBaseSpan(955, 956) [',']
238 lemmik ElementaryBaseSpan(957, 963) ['▁lemmik']
239 � ElementaryBaseSpan(964, 965) ['▁p']
240 ppeaine ElementaryBaseSpan(965, 972) ['▁p', 'pea', 'ine']
241 , ElementaryBaseSpan(972, 973) [',']
242 suurim ElementaryBaseSpan(974, 980) ['▁suurim']
243 p ElementaryBaseSpan(981, 982) ['▁p']
244 � ElementaryBaseSpan(982, 983) ['▁tite']
245 titemp ElementaryBaseSpan(983, 989) ['▁tite', 'mp']
246 jne ElementaryBaseSpan(990, 993) ['▁jne']
247 . ElementaryBaseSpan(993, 994) ['.']
248 Oleks ElementaryBaseSpan(995, 1000) ['▁Oleks']
249 neil ElementaryBaseSpan(1001, 1005) ['▁neil']
250 oma ElementaryBaseSpan(1006, 1009) ['▁oma']
251 nooruses ElementaryBaseSpan(1010, 1018) ['▁nooruses']
252 blogitamis-harjumus ElementaryBaseSpan(1019, 1038) ['▁blogi', 'tamis', '-', 'harju', 'mus']
253 / ElementaryBaseSpan(1038, 1039) ['/']
254 v ElementaryBaseSpan(1039, 1040) ['v']
255 � ElementaryBaseSpan(1040, 1041) ['▁im']
256 imalus ElementaryBaseSpan(1041, 1047) ['▁im', 'alus']
257 olnud ElementaryBaseSpan(1048, 1053) ['▁olnud']
258 .... ElementaryBaseSpan(1053, 1057) ['....']
259 p ElementaryBaseSpan(1058, 1059) ['▁p']
260 � ElementaryBaseSpan(1059, 1060) ['▁ris']
261 ris ElementaryBaseSpan(1060, 1063) ['▁ris']
262 p ElementaryBaseSpan(1064, 1065) ['▁p']
263 � ElementaryBaseSpan(1065, 1066) ['▁ne']
264 neveks ElementaryBaseSpan(1066, 1072) ['▁ne', 've', 'ks']
265 oleks ElementaryBaseSpan(1073, 1078) ['▁oleks']
266 lugeda ElementaryBaseSpan(1079, 1085) ['▁lugeda']
267 . ElementaryBaseSpan(1085, 1086) ['.']
268 N ElementaryBaseSpan(1088, 1089) ['▁N']
270 iteks ElementaryBaseSpan(1090, 1095) ['iteks']
271 t ElementaryBaseSpan(1096, 1097) ['▁t']
272 � ElementaryBaseSpan(1097, 1098) ['▁na']
273 na ElementaryBaseSpan(1098, 1100) ['▁na']
274 r ElementaryBaseSpan(1101, 1102) ['▁r']
275 �� ElementaryBaseSpan(1102, 1104) ['▁kis']
276 kis ElementaryBaseSpan(1104, 1107) ['▁kis']
277 mulle ElementaryBaseSpan(1108, 1113) ['▁mulle']
278 isa ElementaryBaseSpan(1114, 1117) ['▁isa']
279 loo ElementaryBaseSpan(1118, 1121) ['▁loo']
280 , ElementaryBaseSpan(1121, 1122) [',']
281 kuidas ElementaryBaseSpan(1123, 1129) ['▁kuidas']
282 ta ElementaryBaseSpan(1130, 1132) ['▁ta']
283 69ndal ElementaryBaseSpan(1133, 1139) ['▁69', 'ndal']
284 aastal ElementaryBaseSpan(1140, 1146) ['▁aastal']
285 � ElementaryBaseSpan(1147, 1148) ['▁lik']
286 likooli ElementaryBaseSpan(1148, 1155) ['▁lik', 'ooli']
287 ilma ElementaryBaseSpan(1156, 1160) ['▁ilma']
288 komsomooli ElementaryBaseSpan(1161, 1171) ['▁koms', 'om', 'ooli']
289 kuulumata ElementaryBaseSpan(1172, 1181) ['▁kuulu', 'mata']
290 vastuv ElementaryBaseSpan(1182, 1188) ['▁vastu', 'v']
291 � ElementaryBaseSpan(1188, 1189) ['▁et']
292 eti ElementaryBaseSpan(1189, 1192) ['▁et', 'i']
293 ( ElementaryBaseSpan(1193, 1194) ['▁(']
294 p ElementaryBaseSpan(1194, 1195) ['p']
295 � ElementaryBaseSpan(1195, 1196) ['▁ra']
296 rast ElementaryBaseSpan(1196, 1200) ['▁ra', 'st']
297 Praha ElementaryBaseSpan(1201, 1206) ['▁Pra', 'ha']
298 s ElementaryBaseSpan(1207, 1208) ['▁s']
299 � ElementaryBaseSpan(1208, 1209) ['▁n']
300 ndmusi ElementaryBaseSpan(1209, 1215) ['▁n', 'd', 'musi']
301 l ElementaryBaseSpan(1216, 1217) ['▁l']
302 � ElementaryBaseSpan(1217, 1218) ['▁ks']
303 ks ElementaryBaseSpan(1218, 1220) ['▁ks']
304 sinna ElementaryBaseSpan(1221, 1226) ['▁sinna']
305 kuulumine ElementaryBaseSpan(1227, 1236) ['▁kuul', 'umine']
306 v ElementaryBaseSpan(1237, 1238) ['▁v']
307 � ElementaryBaseSpan(1238, 1239) ['▁ga']
308 ga ElementaryBaseSpan(1239, 1241) ['▁ga']
309 kohustuslikuks ElementaryBaseSpan(1242, 1256) ['▁kohustuslikuks']
310 ) ElementaryBaseSpan(1256, 1257) [').']
311 . ElementaryBaseSpan(1257, 1258) [').']
312 Lugu ElementaryBaseSpan(1259, 1263) ['▁Lugu']
313 sellest ElementaryBaseSpan(1264, 1271) ['▁sellest']
314 , ElementaryBaseSpan(1271, 1272) [',']
315 kuidas ElementaryBaseSpan(1273, 1279) ['▁kuidas']
316 teda ElementaryBaseSpan(1280, 1284) ['▁teda']
317 lendlehtede ElementaryBaseSpan(1285, 1296) ['▁lend', 'lehtede']
318 ( ElementaryBaseSpan(1297, 1298) ['▁("']
319 " ElementaryBaseSpan(1298, 1299) ['▁("']
320 V ElementaryBaseSpan(1299, 1300) ['V']
321 � ElementaryBaseSpan(1300, 1301) ['▁im']
322 im ElementaryBaseSpan(1301, 1303) ['▁im']
323 valetab ElementaryBaseSpan(1304, 1311) ['▁valetab']
324 ... ElementaryBaseSpan(1311, 1314) ['...']
325 Kuulake ElementaryBaseSpan(1315, 1322) ['▁Kuula', 'ke']
326 Ameerika ElementaryBaseSpan(1323, 1331) ['▁Ameerika']
327 H ElementaryBaseSpan(1332, 1333) ['▁H']
328 �� ElementaryBaseSpan(1333, 1335) ['▁lt']
329 lt ElementaryBaseSpan(1335, 1337) ['▁lt']
330 " ElementaryBaseSpan(1337, 1338) ['"...']
331 . ElementaryBaseSpan(1338, 1339) ['"...']
332 . ElementaryBaseSpan(1339, 1340) ['"...']
333 . ElementaryBaseSpan(1340, 1341) ['"...']
334 ) ElementaryBaseSpan(1341, 1342) ['▁)']
335 pioneeriorganisatsioonist ElementaryBaseSpan(1343, 1368) ['▁pi', 'oneeri', 'organisatsioon', 'ist']
336 ja ElementaryBaseSpan(1369, 1371) ['▁ja']
337 peaagu ElementaryBaseSpan(1372, 1378) ['▁peaa', 'gu']
338 ka ElementaryBaseSpan(1379, 1381) ['▁ka']
339 koolist ElementaryBaseSpan(1382, 1389) ['▁koolist']
340 v ElementaryBaseSpan(1390, 1391) ['▁v']
341 � ElementaryBaseSpan(1391, 1392) ['▁l']
342 lja ElementaryBaseSpan(1392, 1395) ['▁l', 'ja']
343 visati ElementaryBaseSpan(1396, 1402) ['▁visati']
344 , ElementaryBaseSpan(1402, 1403) [',']
345 olin ElementaryBaseSpan(1404, 1408) ['▁olin']
346 ma ElementaryBaseSpan(1409, 1411) ['▁ma']
347 juba ElementaryBaseSpan(1412, 1416) ['▁juba']
348 varem ElementaryBaseSpan(1417, 1422) ['▁varem']
349 kuulnud ElementaryBaseSpan(1423, 1430) ['▁kuulnud']
350 aga ElementaryBaseSpan(1431, 1434) ['▁aga']
351 ikka ElementaryBaseSpan(1435, 1439) ['▁ikka']
352 oli ElementaryBaseSpan(1440, 1443) ['▁oli']
353 huvitav ElementaryBaseSpan(1444, 1451) ['▁huvitav']
354 veelkord ElementaryBaseSpan(1452, 1460) ['▁veelkord']
355 kuulata ElementaryBaseSpan(1461, 1468) ['▁kuulata']
356 . ElementaryBaseSpan(1468, 1469) ['.']
357 Proovige ElementaryBaseSpan(1471, 1479) ['▁Proovi', 'ge']
358 ... ElementaryBaseSpan(1479, 1482) ['...']
359 K ElementaryBaseSpan(1483, 1484) ['▁K']
360 � ElementaryBaseSpan(1484, 1485) ['▁s']
361 sige ElementaryBaseSpan(1485, 1489) ['▁s', 'ige']
362 oma ElementaryBaseSpan(1490, 1493) ['▁oma']
363 vanematelt ElementaryBaseSpan(1494, 1504) ['▁vanematelt']
364 esimese ElementaryBaseSpan(1505, 1512) ['▁esimese']
365 armastuse ElementaryBaseSpan(1513, 1522) ['▁armastuse']
366 , ElementaryBaseSpan(1522, 1523) [',']
367 miilitsaga ElementaryBaseSpan(1524, 1534) ['▁miilitsa', 'ga']
368 v ElementaryBaseSpan(1535, 1536) ['▁v']
369 � ElementaryBaseSpan(1536, 1537) ['▁im']
370 imaliku ElementaryBaseSpan(1537, 1544) ['▁im', 'al', 'iku']
371 kokkupuutumise ElementaryBaseSpan(1545, 1559) ['▁kokkupuu', 'tu', 'mise']
372 , ElementaryBaseSpan(1559, 1560) [',']
373 ( ElementaryBaseSpan(1561, 1562) ['▁(']
374 mitte-) ElementaryBaseSpan(1562, 1569) ['mitte', '-)']
375 lemmik ElementaryBaseSpan(1569, 1575) ['le', 'mmik']
376 � ElementaryBaseSpan(1575, 1576) ['▁pe']
377 petajaga ElementaryBaseSpan(1576, 1584) ['▁pe', 'tajaga']
378 seonduva ElementaryBaseSpan(1585, 1593) ['▁seondu', 'va']
379 , ElementaryBaseSpan(1593, 1594) [',']
380 pioneerilaagri ElementaryBaseSpan(1595, 1609) ['▁pi', 'oneeri', 'laagri']
381 , ElementaryBaseSpan(1609, 1610) [',']
382 s ElementaryBaseSpan(1611, 1612) ['▁s']
383 � ElementaryBaseSpan(1612, 1613) ['▁ja']
384 jav ElementaryBaseSpan(1613, 1616) ['▁ja', 'v']
385 � ElementaryBaseSpan(1616, 1617) ['▁e']
386 e ElementaryBaseSpan(1617, 1618) ['▁e']
387 v ElementaryBaseSpan(1619, 1620) ['▁v']
388 � ElementaryBaseSpan(1620, 1621) ['▁i']
389 i ElementaryBaseSpan(1621, 1622) ['▁i']
390 mis ElementaryBaseSpan(1623, 1626) ['▁mis']
391 iganes ElementaryBaseSpan(1627, 1633) ['▁iganes']
392 kohta ElementaryBaseSpan(1634, 1639) ['▁kohta']
393 . ElementaryBaseSpan(1639, 1640) ['.']
394 Usun ElementaryBaseSpan(1641, 1645) ['▁Usun']
395 , ElementaryBaseSpan(1645, 1646) [',']
396 et ElementaryBaseSpan(1647, 1649) ['▁et']
397 v ElementaryBaseSpan(1650, 1651) ['▁v']
399 ite ElementaryBaseSpan(1652, 1655) ['ite']
400 midagi ElementaryBaseSpan(1656, 1662) ['▁midagi']
401 � ElementaryBaseSpan(1663, 1664) ['▁l']
402 llatavat ElementaryBaseSpan(1664, 1672) ['▁l', 'la', 'tavat']
403 / ElementaryBaseSpan(1672, 1673) ['/']
404 huvitavat ElementaryBaseSpan(1673, 1682) ['hu', 'vita', 'vat']
405 / ElementaryBaseSpan(1682, 1683) ['/']
406 lahedat ElementaryBaseSpan(1683, 1690) ['la', 'heda', 't']
407 teada ElementaryBaseSpan(1691, 1696) ['▁teada']
408 saada ElementaryBaseSpan(1697, 1702) ['▁saada']
409 . ElementaryBaseSpan(1702, 1703) ['.']
410 Ja ElementaryBaseSpan(1704, 1706) ['▁Ja']
411 kui ElementaryBaseSpan(1707, 1710) ['▁kui']
412 see ElementaryBaseSpan(1711, 1714) ['▁see']
413 on ElementaryBaseSpan(1715, 1717) ['▁on']

In [41]:
morph_tagger._tokenize_with_bert(text_obj.text)

([(None, None, '<s>'),
  (0, 1, '▁('),
  (1, 9, 'Ameerika'),
  (9, 19, '▁teadlased'),
  (19, 22, '▁on'),
  (22, 31, '▁kindlaks'),
  (31, 38, '▁teinud'),
  (38, 39, ','),
  (39, 42, '▁et'),
  (42, 46, '▁99%'),
  (46, 51, '▁blog'),
  (51, 55, 'ides'),
  (55, 61, '▁kirja'),
  (61, 68, '▁pandud'),
  (68, 72, '▁inf'),
  (72, 75, 'ost'),
  (75, 83, '▁huvitab'),
  (83, 88, '▁vaid'),
  (88, 96, '▁autorit'),
  (96, 98, '▁v'),
  (98, 100, '▁i'),
  (100, 106, '▁selle'),
  (106, 108, '▁l'),
  (108, 110, '▁h'),
  (110, 113, 'iko'),
  (113, 115, 'nd'),
  (115, 119, 'lasi'),
  (119, 121, '.)'),
  (122, 130, '▁Tallinn'),
  (130, 131, '-'),
  (131, 136, 'Tartu'),
  (136, 137, '-'),
  (137, 145, 'Tallinna'),
  (145, 147, '▁p'),
  (147, 149, '▁e'),
  (149, 150, 'v'),
  (150, 153, '▁--'),
  (153, 160, '▁Tartus'),
  (160, 162, '▁l'),
  (162, 165, '▁pu'),
  (165, 169, 'pidu'),
  (169, 172, '▁ja'),
  (172, 180, '▁diplomi'),
  (180, 182, '▁k'),
  (182, 184, '▁t'),
  (184, 186, 'te'),
  (186, 194, '▁saamine'),
  (194, 195, '.'),
  (195, 197, '▁8'),
  (197, 204, '▁aastat'),
  (204, 206, '▁T'),
  (206, 208, '▁-'),
  (208, 209, 's'),
  (209, 211, '▁k'),
  (211, 214, '▁id'),
  (214, 216, 'ud'),
  (216, 217, ','),
  (217, 219, '▁k'),
  (219, 222, '▁ik'),
  (222, 226, '▁kur'),
  (226, 228, 'sa'),
  (228, 237, 'kaaslased'),
  (237, 242, '▁ammu'),
  (242, 247, '▁juba'),
  (247, 249, '▁l'),
  (249, 252, '▁pe'),
  (252, 257, 'tanud'),
  (257, 258, '.'),
  (258, 264, '▁Seega'),
  (264, 270, '▁eriti'),
  (270, 275, '▁vanu'),
  (275, 285, '▁tuttavaid'),
  (285, 292, '▁kohata'),
  (292, 295, '▁ei'),
  (295, 299, '▁loo'),
  (299, 303, 'tnud'),
  (303, 306, '▁--'),
  (306, 310, '▁kes'),
  (310, 314, '▁see'),
  (314, 319, '▁ikka'),
  (319, 325, '▁peale'),
  (325, 335, '▁perekonna'),
  (335, 340, '▁teab'),
  (340, 341, ','),
  (341, 344, '▁et'),
  (344, 346, '▁t'),
  (346, 349, '▁na'),
  (349, 351, '▁l'),
  (351, 354, '▁pe'),
  (354, 360, 'tamine'),
  (360, 363, '▁on'),
  (363, 364, '.'),
  (364, 369, '▁Mind'),
  (370, 372, '▁l'),
  (372, 374, 'la'),
  (374, 379, 'tasid'),
  (379, 383, '▁aga'),
  (383, 389, '▁vanad'),
  (389, 391, '▁s'),
  (391, 393, '▁b'),
  (393, 396, 'rad'),
  (396, 398, '▁-'),
  (398, 402, '▁Lea'),
  (402, 403, ','),
  (403, 409, '▁Pille'),
  (409, 410, ','),
  (410, 414, '▁Len'),
  (414, 416, 'ar'),
  (416, 417, ','),
  (417, 423, '▁Marge'),
  (423, 424, ','),
  (424, 429, '▁Liis'),
  (429, 430, ','),
  (430, 436, '▁Tarmo'),
  (436, 438, '▁-'),
  (438, 442, '▁kes'),
  (442, 448, '▁isegi'),
  (448, 454, '▁lille'),
  (454, 455, 'k'),
  (455, 458, 'imb'),
  (458, 460, 'ud'),
  (460, 466, '▁kaasa'),
  (466, 471, '▁olid'),
  (471, 473, '▁v'),
  (473, 475, '▁t'),
  (475, 478, 'nud'),
  (478, 479, '.'),
  (479, 486, '▁Suured'),
  (486, 488, '▁t'),
  (488, 490, '▁n'),
  (490, 492, 'ud'),
  (492, 498, '▁teile'),
  (498, 504, '▁sooja'),
  (504, 506, 'de'),
  (506, 508, '▁s'),
  (508, 512, '▁nad'),
  (512, 513, 'e'),
  (513, 518, '▁eest'),
  (518, 527, '▁veelkord'),
  (527, 528, '!'),
  (529, 540, '▁Kirjutasin'),
  (540, 549, '▁eelmisel'),
  (549, 554, '▁kuul'),
  (554, 559, '▁blog'),
  (559, 563, 'isse'),
  (563, 566, '▁ka'),
  (566, 568, '▁k'),
  (568, 572, '▁sim'),
  (572, 575, 'use'),
  (575, 576, ','),
  (576, 579, '▁et'),
  (579, 584, '▁mida'),
  (584, 586, '▁('),
  (586, 589, 'hea'),
  (589, 596, '▁lugeja'),
  (596, 597, ')'),
  (597, 603, '▁edasi'),
  (603, 611, '▁soovita'),
  (611, 612, 'd'),
  (613, 615, '▁p'),
  (615, 619, 'pida'),
  (619, 620, '.'),
  (620, 622, '▁T'),
  (622, 624, '▁n'),
  (624, 626, 'ud'),
  (626, 633, '▁blogis'),
  (633, 634, '/'),
  (634, 635, 'e'),
  (635, 636, '-'),
  (636, 640, 'meil'),
  (640, 643, 'iga'),
  (643, 649, '▁vasta'),
  (649, 655, 'jatele'),
  (655, 656, ','),
  (656, 661, '▁kuid'),
  (661, 668, '▁otsust'),
  (668, 673, '▁pole'),
  (673, 676, '▁ma'),
  (676, 681, '▁ikka'),
  (681, 686, '▁veel'),
  (686, 693, '▁teinud'),
  (693, 694, '.'),
  (694, 698, '▁Ehk'),
  (698, 704, '▁tuleb'),
  (704, 706, '▁j'),
  (707, 710, '▁ni'),
  (711, 715, '▁sel'),
  (715, 717, '▁s'),
  (717, 720, '▁na'),
  (720, 724, 'jala'),
  (724, 727, '▁it'),
  (727, 735, '▁otsides'),
  (735, 737, '▁m'),
  (737, 740, '▁ni'),
  (740, 744, '▁hea'),
  (744, 746, '▁m'),
  (746, 749, '▁te'),
  (749, 750, '.'),
  (750, 752, '▁V'),
  (752, 754, '▁i'),
  (754, 757, '▁on'),
  (757, 761, '▁Sul'),
  (761, 763, '▁m'),
  (763, 766, '▁ni'),
  (766, 776, '▁ettepanek'),
  (776, 777, '?'),
  (778, 780, '▁-'),
  (780, 783, '---'),
  (783, 785, '▁P'),
  (785, 788, '▁ra'),
  (788, 790, 'st'),
  (790, 792, '▁l'),
  (792, 795, '▁pu'),
  (795, 798, 'akt'),
  (798, 801, 'ust'),
  (801, 811, '▁perekonna'),
  (811, 813, 'ga'),
  (813, 815, '▁l'),
  (815, 817, '▁u'),
  (817, 820, 'nas'),
  (821, 824, '▁ki'),
  (824, 826, '▁s'),
  (827, 830, '▁es'),
  (830, 840, '▁avastasin'),
  (840, 844, '▁end'),
  (844, 853, '▁taaskord'),
  (853, 855, '▁m'),
  (855, 857, '▁t'),
  (857, 860, 'tel'),
  (860, 861, ','),
  (861, 864, '▁et'),
  (864, 868, '▁kui'),
  (868, 870, '▁v'),
  (870, 873, '▁he'),
  (873, 876, '▁me'),
  (876, 880, '▁oma'),
  (880, 891, '▁vanematest'),
  (891, 902, '▁tegelikult'),
  (902, 909, '▁teavad'),
  (909, 910, '.'),
  (910, 920, '▁Selliseid'),
  (920, 923, '▁is'),
  (923, 924, 'k'),
  (924, 929, 'likke'),
  (929, 934, '▁asju'),
  (934, 935, ','),
  (935, 938, '▁ma'),
  (938, 940, '▁m'),
  (940, 942, '▁t'),
  (942, 945, 'len'),
  (945, 948, '▁--'),
  (948, 955, '▁suhted'),
  (955, 956, ','),
  (956, 963, '▁lemmik'),
  (964, 966, '▁p'),
  (966, 969, 'pea'),
  (969, 972, 'ine'),
  (972, 973, ','),
  (973, 980, '▁suurim'),
  (980, 982, '▁p'),
  (982, 987, '▁tite'),
  (987, 989, 'mp'),
  (989, 993, '▁jne'),
  (993, 994, '.'),
  (994, 1000, '▁Oleks'),
  (1000, 1005, '▁neil'),
  (1005, 1009, '▁oma'),
  (1009, 1018, '▁nooruses'),
  (1018, 1024, '▁blogi'),
  (1024, 1029, 'tamis'),
  (1029, 1030, '-'),
  (1030, 1035, 'harju'),
  (1035, 1038, 'mus'),
  (1038, 1039, '/'),
  (1039, 1040, 'v'),
  (1040, 1043, '▁im'),
  (1043, 1047, 'alus'),
  (1047, 1053, '▁olnud'),
  (1053, 1057, '....'),
  (1057, 1059, '▁p'),
  (1059, 1063, '▁ris'),
  (1063, 1065, '▁p'),
  (1065, 1068, '▁ne'),
  (1068, 1070, 've'),
  (1070, 1072, 'ks'),
  (1072, 1078, '▁oleks'),
  (1078, 1085, '▁lugeda'),
  (1085, 1086, '.'),
  (1087, 1089, '▁N'),
  (1089, 1090, '▁'),
  (1090, 1095, 'iteks'),
  (1095, 1097, '▁t'),
  (1097, 1100, '▁na'),
  (1100, 1102, '▁r'),
  (1103, 1107, '▁kis'),
  (1107, 1113, '▁mulle'),
  (1113, 1117, '▁isa'),
  (1117, 1121, '▁loo'),
  (1121, 1122, ','),
  (1122, 1129, '▁kuidas'),
  (1129, 1132, '▁ta'),
  (1132, 1135, '▁69'),
  (1135, 1139, 'ndal'),
  (1139, 1146, '▁aastal'),
  (1147, 1151, '▁lik'),
  (1151, 1155, 'ooli'),
  (1155, 1160, '▁ilma'),
  (1160, 1165, '▁koms'),
  (1165, 1167, 'om'),
  (1167, 1171, 'ooli'),
  (1171, 1177, '▁kuulu'),
  (1177, 1181, 'mata'),
  (1181, 1187, '▁vastu'),
  (1187, 1188, 'v'),
  (1188, 1191, '▁et'),
  (1191, 1192, 'i'),
  (1192, 1194, '▁('),
  (1194, 1195, 'p'),
  (1195, 1198, '▁ra'),
  (1198, 1200, 'st'),
  (1200, 1204, '▁Pra'),
  (1204, 1206, 'ha'),
  (1206, 1208, '▁s'),
  (1208, 1210, '▁n'),
  (1210, 1211, 'd'),
  (1211, 1215, 'musi'),
  (1215, 1217, '▁l'),
  (1217, 1220, '▁ks'),
  (1220, 1226, '▁sinna'),
  (1226, 1231, '▁kuul'),
  (1231, 1236, 'umine'),
  (1236, 1238, '▁v'),
  (1238, 1241, '▁ga'),
  (1241, 1256, '▁kohustuslikuks'),
  (1256, 1258, ').'),
  (1258, 1263, '▁Lugu'),
  (1263, 1271, '▁sellest'),
  (1271, 1272, ','),
  (1272, 1279, '▁kuidas'),
  (1279, 1284, '▁teda'),
  (1284, 1289, '▁lend'),
  (1289, 1296, 'lehtede'),
  (1296, 1299, '▁("'),
  (1299, 1300, 'V'),
  (1300, 1303, '▁im'),
  (1303, 1311, '▁valetab'),
  (1311, 1314, '...'),
  (1314, 1320, '▁Kuula'),
  (1320, 1322, 'ke'),
  (1322, 1331, '▁Ameerika'),
  (1331, 1333, '▁H'),
  (1334, 1337, '▁lt'),
  (1337, 1341, '"...'),
  (1341, 1342, ')'),
  (1342, 1345, '▁pi'),
  (1345, 1351, 'oneeri'),
  (1351, 1365, 'organisatsioon'),
  (1365, 1368, 'ist'),
  (1368, 1371, '▁ja'),
  (1371, 1376, '▁peaa'),
  (1376, 1378, 'gu'),
  (1378, 1381, '▁ka'),
  (1381, 1389, '▁koolist'),
  (1389, 1391, '▁v'),
  (1391, 1393, '▁l'),
  (1393, 1395, 'ja'),
  (1395, 1402, '▁visati'),
  (1402, 1403, ','),
  (1403, 1408, '▁olin'),
  (1408, 1411, '▁ma'),
  (1411, 1416, '▁juba'),
  (1416, 1422, '▁varem'),
  (1422, 1430, '▁kuulnud'),
  (1430, 1434, '▁aga'),
  (1434, 1439, '▁ikka'),
  (1439, 1443, '▁oli'),
  (1443, 1451, '▁huvitav'),
  (1451, 1460, '▁veelkord'),
  (1460, 1468, '▁kuulata'),
  (1468, 1469, '.'),
  (1470, 1477, '▁Proovi'),
  (1477, 1479, 'ge'),
  (1479, 1482, '...'),
  (1482, 1484, '▁K'),
  (1484, 1486, '▁s'),
  (1486, 1489, 'ige'),
  (1489, 1493, '▁oma'),
  (1493, 1504, '▁vanematelt'),
  (1504, 1512, '▁esimese'),
  (1512, 1522, '▁armastuse'),
  (1522, 1523, ','),
  (1523, 1532, '▁miilitsa'),
  (1532, 1534, 'ga'),
  (1534, 1536, '▁v'),
  (1536, 1539, '▁im'),
  (1539, 1541, 'al'),
  (1541, 1544, 'iku'),
  (1544, 1553, '▁kokkupuu'),
  (1553, 1555, 'tu'),
  (1555, 1559, 'mise'),
  (1559, 1560, ','),
  (1560, 1562, '▁('),
  (1562, 1567, 'mitte'),
  (1567, 1569, '-)'),
  (1569, 1571, 'le'),
  (1571, 1575, 'mmik'),
  (1575, 1578, '▁pe'),
  (1578, 1584, 'tajaga'),
  (1584, 1591, '▁seondu'),
  (1591, 1593, 'va'),
  (1593, 1594, ','),
  (1594, 1597, '▁pi'),
  (1597, 1603, 'oneeri'),
  (1603, 1609, 'laagri'),
  (1609, 1610, ','),
  (1610, 1612, '▁s'),
  (1612, 1615, '▁ja'),
  (1615, 1616, 'v'),
  (1616, 1618, '▁e'),
  (1618, 1620, '▁v'),
  (1620, 1622, '▁i'),
  (1622, 1626, '▁mis'),
  (1626, 1633, '▁iganes'),
  (1633, 1639, '▁kohta'),
  (1639, 1640, '.'),
  (1640, 1645, '▁Usun'),
  (1645, 1646, ','),
  (1646, 1649, '▁et'),
  (1649, 1651, '▁v'),
  (1651, 1652, '▁'),
  (1652, 1655, 'ite'),
  (1655, 1662, '▁midagi'),
  (1663, 1665, '▁l'),
  (1665, 1667, 'la'),
  (1667, 1672, 'tavat'),
  (1672, 1673, '/'),
  (1673, 1675, 'hu'),
  (1675, 1679, 'vita'),
  (1679, 1682, 'vat'),
  (1682, 1683, '/'),
  (1683, 1685, 'la'),
  (1685, 1689, 'heda'),
  (1689, 1690, 't'),
  (1690, 1696, '▁teada'),
  (1696, 1702, '▁saada'),
  (1702, 1703, '.'),
  (1703, 1706, '▁Ja'),
  (1706, 1710, '▁kui'),
  (1710, 1714, '▁see'),
  (1714, 1717, '▁on'),
  (1717, 1719, '▁t'),
  (1719, 1722, '▁el'),
  (1722, 1727, 'iselt'),
  (1727, 1732, '▁lahe'),
  (1732, 1736, '▁asi'),
  (1736, 1737, ','),
  (1737, 1742, '▁siis'),
  (1742, 1748, '▁pange'),
  (1748, 1752, '▁oma'),
  (1752, 1757, '▁blog'),
  (1757, 1761, 'isse'),
  (1761, 1766, '▁jutt'),
  (1766, 1774, '▁kenasti'),
  (1774, 1780, '▁kirja'),
  (1780, 1781, ','),
  (1781, 1784, '▁et'),
  (1784, 1789, '▁teie'),
  (1789, 1796, '▁lapsed'),
  (1796, 1804, '▁saaksid'),
  (1804, 1811, '▁lugeda'),
  (1811, 1817, '▁mitte'),
  (1817, 1824, '▁ainult'),
  (1824, 1830, '▁isade'),
  (1830, 1831, '/'),
  (1831, 1834, 'ema'),
  (1834, 1836, 'de'),
  (1836, 1841, '▁vaid'),
  (1841, 1844, '▁ka'),
  (1844, 1849, '▁vana'),
  (1849, 1854, 'isade'),
  (1854, 1855, '/'),
  (1855, 1856, '-'),
  (1856, 1859, 'ema'),
  (1859, 1861, 'de'),
  (1861, 1867, '▁kohta'),
  (1867, 1868, '.'),
  (1868, 1870, '▁('),
  (1870, 1872, 'vt'),
  (1872, 1873, '.'),
  (1873, 1879, '▁blogi'),
  (1879, 1887, '▁alguses'),
  (1887, 1893, '▁olnud'),
  (1893, 1895, '▁m'),
  (1895, 1897, '▁t'),
  (1897, 1899, 'te'),
  (1899, 1903, 'tera'),
  (1903, 1904, ')'),
  (1904, 1905, '!'),
  (None, None, '</s>')],
 {'input_ids': [5, 156, 14862, 9606, 45, 3944, 1555, 39659, 68, 37453, 19130, 585, 1849, 3242, 1413, 1301, 8768, 406, 37742, 16, 1378, 157, 38, 61, 668, 86, 2077, 10380, 2565, 39669, 13384, 39669, 11429, 19, 15, 39652, 5242, 3536, 38, 282, 14907, 39, 39347, 8, 11, 29, 11065, 39657, 754, 876, 89, 263, 39642, 8, 2000, 26, 39659, 8, 11637, 1468, 200, 20529, 2666, 385, 38, 115, 818, 39657, 1497, 1243, 8680, 22035, 21930, 75, 310, 2688, 5242, 203, 149, 423, 540, 4836, 2340, 39659, 68, 11, 226, 38, 115, 1515, 45, 39657, 7831, 38, 102, 1703, 217, 6532, 21, 475, 1310, 263, 14781, 39659, 15173, 39659, 3729, 108, 39659, 31646, 39659, 7615, 39659, 7601, 263, 203, 869, 7170, 39647, 12762, 26, 1047, 736, 16, 11, 99, 39657, 17787, 11, 32, 26, 3781, 4768, 116, 21, 549, 39640, 328, 12573, 39696, 38731, 4224, 470, 19130, 446, 46, 8, 14995, 53, 39659, 68, 261, 156, 12550, 6409, 39680, 984, 2841, 39649, 19, 1418, 39657, 89, 32, 26, 18717, 39708, 39640, 39669, 30926, 239, 787, 1998, 39659, 304, 4098, 255, 127, 423, 354, 1555, 39657, 2919, 430, 57, 1834, 104, 21, 226, 7955, 13479, 21223, 18, 1834, 635, 18, 50, 39657, 118, 1378, 45, 4442, 18, 1834, 7991, 39689, 263, 14644, 113, 128, 9, 38, 282, 25285, 60, 4836, 28, 38, 448, 5619, 832, 21, 284, 16800, 691, 15739, 18, 11, 379, 39659, 68, 126, 16, 906, 138, 142, 29225, 1335, 5681, 39657, 12928, 531, 39647, 4020, 2232, 39659, 127, 18, 11, 4194, 5242, 7312, 39659, 5339, 19, 1614, 84, 39659, 4858, 19, 28217, 559, 1337, 39657, 5552, 1606, 142, 28601, 10120, 10797, 39669, 16857, 928, 39708, 39652, 1176, 10319, 550, 1531, 19, 8060, 19, 298, 256, 34, 390, 2079, 39657, 166, 39638, 744, 11, 226, 154, 9910, 1306, 1889, 310, 39659, 711, 90, 8650, 15551, 682, 4964, 1028, 1031, 28795, 1276, 1028, 2128, 421, 387, 39652, 68, 39641, 156, 39655, 128, 9, 1936, 111, 21, 32, 39649, 8997, 38, 32934, 1412, 470, 1102, 16, 1827, 30207, 883, 8383, 717, 39659, 711, 1250, 9875, 21900, 8108, 39676, 1176, 19539, 523, 20914, 171, 4238, 204, 22949, 19710, 39680, 1891, 28083, 16555, 51, 39, 25922, 85, 46, 13706, 16, 38, 17, 24545, 39659, 2903, 127, 385, 1559, 4617, 217, 423, 185, 3750, 12573, 6053, 39657, 18248, 78, 523, 65, 21, 291, 142, 35731, 1965, 12122, 39659, 25357, 28, 16, 1176, 12, 187, 18527, 170, 88, 39659, 156, 8668, 23536, 10, 11216, 115, 28607, 8186, 35, 39659, 1891, 28083, 36697, 39659, 21, 39, 39652, 15, 16, 1378, 201, 6961, 582, 39657, 10475, 39659, 68, 16, 39638, 308, 514, 38, 102, 3749, 39708, 604, 629, 469, 39708, 102, 3488, 39643, 1155, 774, 39657, 484, 126, 149, 45, 11, 313, 342, 6163, 1149, 39659, 160, 12789, 142, 19130, 446, 2770, 6614, 1849, 39659, 68, 1930, 2047, 5525, 2079, 361, 628, 31671, 39708, 3995, 116, 406, 46, 911, 32883, 39708, 39669, 3995, 116, 582, 39657, 156, 8321, 39657, 10120, 2714, 550, 18, 11, 29, 9105, 39680, 39696, 6], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})

In [ ]:
group_words_by_bert_tokens(
    text_obj.words, map_words_to_bert_tokens(text_obj.words, morph_layer)
)

[([Span('Ning', [{'normalized_form': None}])],
  [Span('Ning', [{'bert_tokens': '▁Ning', 'morph_labels': 'J', 'probabilities': 0.99991}])]),
 ([Span('laste', [{'normalized_form': None}])],
  [Span(' laste', [{'bert_tokens': '▁laste', 'morph_labels': 'pl g_S', 'probabilities': 0.9996}])]),
 ([Span('kingitus', [{'normalized_form': None}])],
  [Span(' kingitus', [{'bert_tokens': '▁kingitus', 'morph_labels': 'sg n_S', 'probabilities': 0.99978}])]),
 ([Span(':', [{'normalized_form': None}])],
  [Span(':', [{'bert_tokens': ':', 'morph_labels': 'Z', 'probabilities': 0.99992}])]),
 ([Span('puust', [{'normalized_form': None}])],
  [Span(' puust', [{'bert_tokens': '▁puust', 'morph_labels': 'sg el_S', 'probabilities': 0.99941}])]),
 ([Span('juuksehari', [{'normalized_form': None}])],
  [Span(' juukse', [{'bert_tokens': '▁juukse', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}]),
   Span('hari', [{'bert_tokens': 'hari', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}])]),
 ([Span('(', [{'normalized_form': None}])],
  [Span(' (', [{'bert_tokens': '▁(', 'morph_labels': 'Z', 'probabilities': 0.99987}])]),
 ([Span('millist', [{'normalized_form': None}])],
  [Span('mil', [{'bert_tokens': 'mil', 'morph_labels': 'sg p_P', 'probabilities': 0.99783}]),
   Span('list', [{'bert_tokens': 'list', 'morph_labels': 'sg p_P', 'probabilities': 0.99854}])]),
 ([Span('ma', [{'normalized_form': None}])],
  [Span(' ma', [{'bert_tokens': '▁ma', 'morph_labels': 'sg n_P', 'probabilities': 0.99983}])]),
 ([Span('olin', [{'normalized_form': None}])],
  [Span(' olin', [{'bert_tokens': '▁olin', 'morph_labels': 'sin_V', 'probabilities': 0.99878}])]),
 ([Span('ammu', [{'normalized_form': None}])],
  [Span(' ammu', [{'bert_tokens': '▁ammu', 'morph_labels': 'D', 'probabilities': 0.99989}])]),
 ([Span('endale', [{'normalized_form': None}])],
  [Span(' endale', [{'bert_tokens': '▁endale', 'morph_labels': 'sg all_P', 'probabilities': 0.9998}])]),
 ([Span('soovinud', [{'normalized_form': None}])],
  [Span(' soovinud', [{'bert_tokens': '▁soovinud', 'morph_labels': 'nud_V', 'probabilities': 0.99973}])]),
 ([Span(')', [{'normalized_form': None}]),
   Span(',', [{'normalized_form': None}])],
  [Span('),', [{'bert_tokens': '),', 'morph_labels': 'Z', 'probabilities': 0.99995}])]),
 ([Span('tulbid', [{'normalized_form': None}])],
  [Span(' tul', [{'bert_tokens': '▁tul', 'morph_labels': 'pl n_S', 'probabilities': 0.99949}]),
   Span('bid', [{'bert_tokens': 'bid', 'morph_labels': 'pl n_S', 'probabilities': 0.99952}])]),
 ([Span('ja', [{'normalized_form': None}])],
  [Span(' ja', [{'bert_tokens': '▁ja', 'morph_labels': 'J', 'probabilities': 0.99991}])]),
 ([Span('karp', [{'normalized_form': None}])],
  [Span(' karp', [{'bert_tokens': '▁karp', 'morph_labels': 'sg n_S', 'probabilities': 0.99976}])]),
 ([Span('Rafaellot', [{'normalized_form': None}])],
  [Span(' Ra', [{'bert_tokens': '▁Ra', 'morph_labels': 'sg p_H', 'probabilities': 0.78436}]),
   Span('fa', [{'bert_tokens': 'fa', 'morph_labels': 'sg p_H', 'probabilities': 0.88837}]),
   Span('ell', [{'bert_tokens': 'ell', 'morph_labels': 'sg p_H', 'probabilities': 0.9153}]),
   Span('ot', [{'bert_tokens': 'ot', 'morph_labels': 'sg p_H', 'probabilities': 0.91316}])]),
 ([Span('.', [{'normalized_form': None}])],
  [Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99996}])])]

In [ ]:
grouped_words = group_words_by_bert_tokens(
    text_obj.words, morph_layer, map_words_to_bert_tokens(text_obj.words, morph_layer)
)

In [ ]:
test_layer = Layer(
    name=morph_tagger.output_layer,
    attributes=morph_tagger.output_attributes,
    text_object=text_obj,
    ambiguous=True,
)
for sharing_words, shared_bert_tokens in grouped_words:
    if len(sharing_words) > 1:  # TODO: Add comment
        assert len(sharing_words) == len(shared_bert_tokens), (
            f"Sharing words and shared bert tokens aren't the same length\nsharing_words={len(sharing_words)}\nshared_bert_tokens={len(shared_bert_tokens)}"
        )
        for sharing_word_part, shared_bert_tokens_part in zip(
            sharing_words, shared_bert_tokens
        ):
            new_span = sharing_word_part.base_span
            annotation = rewriter_decorator(
                text_obj, [sharing_word_part], [shared_bert_tokens_part]
            )
            if annotation is not None:
                test_layer.add_annotation(new_span, annotation)
    else:
        new_span = [sp.base_span for sp in sharing_words][0]
        annotation = rewriter_decorator(text_obj, sharing_words, shared_bert_tokens)
        if annotation is not None:
            test_layer.add_annotation(new_span, annotation)

TypeError: 'float' object is not iterable

In [111]:
test_layer

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'morph_labels', 'probabilities'), spans=SL[Span('Ning', [{'bert_tokens': ['▁Ning'], 'morph_labels': ['J', 'o_V', 'D'], 'probabilities': [0.99991, 0.0, 0.0]}]),
Span('laste', [{'bert_tokens': ['▁laste'], 'morph_labels': ['pl g_S', 'sg g_S', 'pl g_A'], 'probabilities': [0.9996, 6e-05, 3e-05]}]),
Span('kingitus', [{'bert_tokens': ['▁kingitus'], 'morph_labels': ['sg n_S', 'sg in_S', 'sg p_S'], 'probabilities': [0.99978, 3e-05, 1e-05]}]),
Span(':', [{'bert_tokens': [':'], 'morph_labels': ['Z', 'J', 'b_V'], 'probabilities': [0.99992, 2e-05, 0.0]}]),
Span('puust', [{'bert_tokens': ['▁puust'], 'morph_labels': ['sg el_S', 'sg p_S', 'sg el_H'], 'probabilities': [0.99941, 0.00012, 4e-05]}]),
Span('juuksehari', [{'bert_tokens': ['▁juukse', 'hari'], 'morph_labels': ['sg n_S', 'sg in_S', 'sg p_S'], 'probabilities': [0.99975, 4e-05, 3e-05]}]),
Span('(', [{'bert_tokens': ['▁('], 'morph_labels': ['Z', 'J', 'A'], 'probabilities': [0.99987, 5e-05, 0.0]}]),
Span('millist', [{'bert_tokens': ['mil', 'list'], 'morph_labels': ['sg p_P', 'sg el_P', 'sg p_A'], 'probabilities': [0.99783, 0.00098, 0.0001]}]),
Span('ma', [{'bert_tokens': ['▁ma'], 'morph_labels': ['sg n_P', 'pl n_P', 'sg g_P'], 'probabilities': [0.99983, 1e-05, 1e-05]}]),
Span('olin', [{'bert_tokens': ['▁olin'], 'morph_labels': ['sin_V', 'sime_V', 'n_V'], 'probabilities': [0.99878, 9e-05, 8e-05]}]),
Span('ammu', [{'bert_tokens': ['▁ammu'], 'morph_labels': ['D', 'A', 'sg g_S'], 'probabilities': [0.99989, 1e-05, 0.0]}]),
Span('endale', [{'bert_tokens': ['▁endale'], 'morph_labels': ['sg all_P', 'pl all_P', 'sg all_H'], 'probabilities': [0.9998, 2e-05, 1e-05]}]),
Span('soovinud', [{'bert_tokens': ['▁soovinud'], 'morph_labels': ['nud_V', 'pl n_S', 'A'], 'probabilities': [0.99973, 2e-05, 2e-05]}]),
Span(')', [{'bert_tokens': [')'], 'morph_labels': ['Z', 'J', 'A'], 'probabilities': [0.99995, 0.0, 0.0]}]),
Span(',', [{'bert_tokens': [','], 'morph_labels': ['Z', 'J', 'A'], 'probabilities': [0.99995, 0.0, 0.0]}]),
Span('tulbid', [{'bert_tokens': ['▁tul', 'bid'], 'morph_labels': ['pl n_S', 'pl n_A', 'pl n_H'], 'probabilities': [0.99949, 0.00012, 5e-05]}]),
Span('ja', [{'bert_tokens': ['▁ja'], 'morph_labels': ['J', 'o_V', 'D'], 'probabilities': [0.99991, 0.0, 0.0]}]),
Span('karp', [{'bert_tokens': ['▁karp'], 'morph_labels': ['sg n_S', 'sg in_S', 'pl g_S'], 'probabilities': [0.99976, 2e-05, 2e-05]}]),
Span('Rafaellot', [{'bert_tokens': ['▁Ra', 'fa', 'ell', 'ot'], 'morph_labels': ['sg p_H', 'sg n_H', 'pl n_H'], 'probabilities': [0.78436, 0.1822, 0.00609]}]),
Span('.', [{'bert_tokens': ['.'], 'morph_labels': ['Z', 'J', 'sg n_H'], 'probabilities': [0.99996, 0.0, 0.0]}])])

In [ ]:
bert_tokens = group_words_by_bert_tokens(
    text_obj.words, map_words_to_bert_tokens(text_obj.words, morph_layer)
)[13][1]
words = group_words_by_bert_tokens(
    text_obj.words, map_words_to_bert_tokens(text_obj.words, morph_layer)
)[13][0]
new_bert_tokens = []
token_index = 0

for word in words:
    # Ensure there is a corresponding BERT token
    if token_index < len(bert_tokens):
        bert_token = bert_tokens[token_index]
        print(bert_token)
        remaining_token = bert_token["bert_tokens"][0]  # Start with the full BERT token
        current_start = bert_token.start

        # While there is still part of the BERT token remaining to split
        while remaining_token:
            # Calculate the overlap between the word and the remaining BERT token
            word_length = word.end - word.start
            sub_token = remaining_token[
                :word_length
            ]  # Take the part that fits the current word
            remaining_token = remaining_token[
                word_length:
            ]  # The rest of the BERT token
            annotation_count = len(bert_token["morph_labels"])

            # Create a new sub-token with the same labels and probabilities and wrap it in Span
            new_sub_token_span = estnltk.Span(
                estnltk.ElementaryBaseSpan(
                    word.start, min(word.end, current_start + len(sub_token))
                ),
                morph_layer,
            )
            for i in range(annotation_count):
                new_sub_token_span.add_annotation(
                    {
                        "bert_tokens": sub_token,
                        "morph_labels": bert_token["morph_labels"][
                            i
                        ],  # Keep the original labels
                        "probabilities": bert_token["probabilities"][
                            i
                        ],  # Keep the original probabilities
                    }
                )
            new_bert_tokens.append(new_sub_token_span)
            current_start += len(sub_token)

            # If there is no remaining part of the token, move to the next word
            if not remaining_token:
                token_index += 1
                break

            # Move to the next word span
            word = next((w for w in words if w.start >= new_sub_token_span.end), None)
            if word is None:
                break  # No more words left

Span('),', [{'bert_tokens': '),', 'morph_labels': 'Z', 'probabilities': 0.99995}, {'bert_tokens': '),', 'morph_labels': 'J', 'probabilities': 0.0}, {'bert_tokens': '),', 'morph_labels': 'A', 'probabilities': 0.0}])

In [36]:
new_bert_tokens

[Span(')', [{'bert_tokens': ')', 'morph_labels': 'Z', 'probabilities': 0.99995}, {'bert_tokens': ')', 'morph_labels': 'J', 'probabilities': 0.0}, {'bert_tokens': ')', 'morph_labels': 'A', 'probabilities': 0.0}]),
 Span(',', [{'bert_tokens': ',', 'morph_labels': 'Z', 'probabilities': 0.99995}, {'bert_tokens': ',', 'morph_labels': 'J', 'probabilities': 0.0}, {'bert_tokens': ',', 'morph_labels': 'A', 'probabilities': 0.0}])]

In [40]:
for span in text_obj.words.spans:
    if span.normalized_form[0]:
        print(span.normalized_form[0])
    else:
        print(span.text)

Ennustaja
,
ma
pean
tarvilikuks
teid
informeerida
selles
,
et
sellest
"
lugejatrombsmaarikapiitertupolev
brittnolooginoff
"
esinen
ma
ainult
ühe
korra
,
s.t.
.
Maarikana
.
Teised
pole
kunagi
minu
aliased
olnud
.
Rahu
sulle
,
ära
üle
pinguta
.

In [ ]:
def rewrite_layer(self, text_obj, bert_tokens_layer, words_layer):
    """
    Combines tokens progressively to match the length and structure of the provided words list.
    Handles cases where tokens need to be recombined or split to match the words.
    """
    tokens = [token[0] for token in bert_tokens_layer.bert_tokens]
    words = [
        span.normalized_form[0] if span.normalized_form[0] is not None else span.text
        for span in words_layer.spans
    ]

    new_morph_layer = Layer(
        name=self.output_layer,
        attributes=self.output_attributes,
        text_object=text_obj,
        ambiguous=True,
    )

    token_buffer = ""
    collected_tokens = []
    word_index = 0
    token_index = 0
    token_start_index = 0
    next_token = True

    while token_index < len(tokens) and word_index < len(words):
        span = bert_tokens_layer.spans[token_index]

        # Clean the token by removing the leading '▁' if present
        clean_token = tokens[token_index].strip("▁")

        # If this is the first token in the word, capture the span start
        if token_buffer == "":
            span_start = span.start
            token_start_index = token_index

        # Accumulate token to the buffer
        if next_token:
            token_buffer += clean_token
            collected_tokens.append(tokens[token_index])

        # Case 1: Exact match with the current word
        if token_buffer == words[word_index]:
            span_end = span.end
            span_tuple = (span_start, span_end)

            for label, prob in zip(list(span.morph_labels), list(span.probabilities)):
                annotation = {
                    "bert_tokens": collected_tokens,
                    "morph_labels": label,
                    "probabilities": prob,
                }
                new_morph_layer.add_annotation(span_tuple, annotation)

            # Reset the buffer and collected tokens for the next word
            token_buffer = ""
            collected_tokens = []
            word_index += 1  # Move to the next word
            token_index += 1  # Move to the next token
            next_token = True

        # Case 2: Token buffer length exceeds the current word length, try splitting
        elif len(token_buffer) > len(words[word_index]):
            split_length = len(words[word_index])  # Get the length of the current word
            if token_buffer[:split_length] == words[word_index]:
                span_end = words_layer.spans[word_index].end
                span_tuple = (span_start, span_end)

                for label, prob in zip(
                    list(span.morph_labels), list(span.probabilities)
                ):
                    annotation = {
                        "bert_tokens": collected_tokens,
                        "morph_labels": label,
                        "probabilities": prob,
                    }
                    new_morph_layer.add_annotation(span_tuple, annotation)

                token_buffer = token_buffer[
                    split_length:
                ]  # Keep the remainder for the next word
                span_start = span_end
                word_index += 1  # Move to the next word
                next_token = False
            else:
                # Case 3: No match, move to the next token and continue combining
                token_index += 1
                next_token = True

        # Case 4: Buffer is still less than the current word, move to the next token to keep accumulating
        else:
            token_index += 1
            next_token = True

    # If there are any remaining tokens after the loop, add them as the final word
    if token_buffer and word_index < len(words):
        for label, prob in zip(list(span.morph_labels), list(span.probabilities)):
            annotation = {
                "bert_tokens": collected_tokens,
                "morph_labels": label,
                "probabilities": prob,
            }
            new_morph_layer.add_annotation(span_tuple, annotation)

    return new_morph_layer


rewrite_layer(morph_tagger, text_obj, morph_layer, text_obj.words)

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'morph_labels', 'probabilities'), spans=SL[Span('Ennustaja', [{'bert_tokens': ['▁Enn', 'ustaja'], 'morph_labels': 'sg n_S', 'probabilities': 0.99958}]),
Span(',', [{'bert_tokens': [','], 'morph_labels': 'Z', 'probabilities': 0.99996}]),
Span(' ma', [{'bert_tokens': ['▁ma'], 'morph_labels': 'sg n_P', 'probabilities': 0.99986}]),
Span(' pean', [{'bert_tokens': ['▁pean'], 'morph_labels': 'n_V', 'probabilities': 0.99952}]),
Span(' tarvilikuks', [{'bert_tokens': ['▁tarv', 'il', 'ikuks'], 'morph_labels': 'sg tr_A', 'probabilities': 0.99894}]),
Span(' teid', [{'bert_tokens': ['▁teid'], 'morph_labels': 'pl p_P', 'probabilities': 0.99611}]),
Span(' informeerida', [{'bert_tokens': ['▁informeer', 'ida'], 'morph_labels': 'da_V', 'probabilities': 0.99987}]),
Span(' selles', [{'bert_tokens': ['▁selles'], 'morph_labels': 'sg in_P', 'probabilities': 0.99934}]),
Span(',', [{'bert_tokens': [','], 'morph_labels': 'Z', 'probabilities': 0.99997}]),
Span(' et', [{'bert_tokens': ['▁et'], 'morph_labels': 'J', 'probabilities': 0.99991}]),
Span(' sellest', [{'bert_tokens': ['▁sellest'], 'morph_labels': 'sg el_P', 'probabilities': 0.99917}]),
Span(' "', [{'bert_tokens': ['▁"'], 'morph_labels': 'Z', 'probabilities': 0.99995}]),
Span('lugejatrombsmaarikapiitertupolev', [{'bert_tokens': ['lu', 'geja', 't', 'ro', 'mb', 's', 'maar', 'ika', 'pii', 'ter', 'tu', 'pole', 'v'], 'morph_labels': 'sg n_A', 'probabilities': 0.99668}]),
Span(' brittnolooginoff', [{'bert_tokens': ['▁britt', 'n', 'oloo', 'gin', 'off'], 'morph_labels': 'sg n_S', 'probabilities': 0.99961}]),
Span('"', [{'bert_tokens': ['"'], 'morph_labels': 'Z', 'probabilities': 0.99994}]),
Span(' esinen', [{'bert_tokens': ['▁esin', 'en'], 'morph_labels': 'n_V', 'probabilities': 0.99936}]),
Span(' ma', [{'bert_tokens': ['▁ma'], 'morph_labels': 'sg n_P', 'probabilities': 0.99986}]),
Span(' ainult', [{'bert_tokens': ['▁ainult'], 'morph_labels': 'D', 'probabilities': 0.9999}]),
Span(' ühe', [{'bert_tokens': ['▁ühe'], 'morph_labels': 'sg g_P', 'probabilities': 0.99935}]),
Span(' korra', [{'bert_tokens': ['▁korra'], 'morph_labels': 'sg g_S', 'probabilities': 0.99968}]),
Span(',', [{'bert_tokens': [','], 'morph_labels': 'Z', 'probabilities': 0.99997}]),
Span(' s.t.', [{'bert_tokens': ['▁s', '.', 't', '.'], 'morph_labels': 'Z', 'probabilities': 0.99956}]),
Span(' .', [{'bert_tokens': ['▁.'], 'morph_labels': 'Z', 'probabilities': 0.99996}, {'bert_tokens': ['▁Maar', 'ika', '-', 'na', '.', '▁Teised', '▁pole', '▁kunagi', '▁minu', '▁al', 'ia', 'sed', '▁olnud', '.', '▁Rahu', '▁sulle', ',', '▁ära', '▁üle', '▁pingu', 'ta', '.'], 'morph_labels': 'Z', 'probabilities': 0.99997}])])

In [30]:
top_n_predictions, tokens_with_spans

NameError: name 'tokens_with_spans' is not defined

In [31]:
morph_layer

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'morph_labels', 'probabilities'), spans=SL[Span('Ning', [{'bert_tokens': '▁Ning', 'morph_labels': 'J', 'probabilities': 0.99991}, {'bert_tokens': '▁Ning', 'morph_labels': 'o_V', 'probabilities': 0.0}, {'bert_tokens': '▁Ning', 'morph_labels': 'D', 'probabilities': 0.0}]),
Span(' laste', [{'bert_tokens': '▁laste', 'morph_labels': 'pl g_S', 'probabilities': 0.9996}, {'bert_tokens': '▁laste', 'morph_labels': 'sg g_S', 'probabilities': 6e-05}, {'bert_tokens': '▁laste', 'morph_labels': 'pl g_A', 'probabilities': 3e-05}]),
Span(' kingitus', [{'bert_tokens': '▁kingitus', 'morph_labels': 'sg n_S', 'probabilities': 0.99978}, {'bert_tokens': '▁kingitus', 'morph_labels': 'sg in_S', 'probabilities': 3e-05}, {'bert_tokens': '▁kingitus', 'morph_labels': 'sg p_S', 'probabilities': 1e-05}]),
Span(':', [{'bert_tokens': ':', 'morph_labels': 'Z', 'probabilities': 0.99992}, {'bert_tokens': ':', 'morph_labels': 'J', 'probabilities': 2e-05}, {'bert_tokens': ':', 'morph_labels': 'b_V', 'probabilities': 0.0}]),
Span(' puust', [{'bert_tokens': '▁puust', 'morph_labels': 'sg el_S', 'probabilities': 0.99941}, {'bert_tokens': '▁puust', 'morph_labels': 'sg p_S', 'probabilities': 0.00012}, {'bert_tokens': '▁puust', 'morph_labels': 'sg el_H', 'probabilities': 4e-05}]),
Span(' juukse', [{'bert_tokens': '▁juukse', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}, {'bert_tokens': '▁juukse', 'morph_labels': 'sg in_S', 'probabilities': 4e-05}, {'bert_tokens': '▁juukse', 'morph_labels': 'sg p_S', 'probabilities': 3e-05}]),
Span('hari', [{'bert_tokens': 'hari', 'morph_labels': 'sg n_S', 'probabilities': 0.99975}, {'bert_tokens': 'hari', 'morph_labels': 'sg in_S', 'probabilities': 4e-05}, {'bert_tokens': 'hari', 'morph_labels': 'sg p_S', 'probabilities': 2e-05}]),
Span(' (', [{'bert_tokens': '▁(', 'morph_labels': 'Z', 'probabilities': 0.99987}, {'bert_tokens': '▁(', 'morph_labels': 'J', 'probabilities': 5e-05}, {'bert_tokens': '▁(', 'morph_labels': 'A', 'probabilities': 0.0}]),
Span('mil', [{'bert_tokens': 'mil', 'morph_labels': 'sg p_P', 'probabilities': 0.99783}, {'bert_tokens': 'mil', 'morph_labels': 'sg el_P', 'probabilities': 0.00098}, {'bert_tokens': 'mil', 'morph_labels': 'sg p_A', 'probabilities': 0.0001}]),
Span('list', [{'bert_tokens': 'list', 'morph_labels': 'sg p_P', 'probabilities': 0.99854}, {'bert_tokens': 'list', 'morph_labels': 'sg el_P', 'probabilities': 0.00043}, {'bert_tokens': 'list', 'morph_labels': 'sg p_A', 'probabilities': 0.0001}]),
Span(' ma', [{'bert_tokens': '▁ma', 'morph_labels': 'sg n_P', 'probabilities': 0.99983}, {'bert_tokens': '▁ma', 'morph_labels': 'pl n_P', 'probabilities': 1e-05}, {'bert_tokens': '▁ma', 'morph_labels': 'sg g_P', 'probabilities': 1e-05}]),
Span(' olin', [{'bert_tokens': '▁olin', 'morph_labels': 'sin_V', 'probabilities': 0.99878}, {'bert_tokens': '▁olin', 'morph_labels': 'sime_V', 'probabilities': 9e-05}, {'bert_tokens': '▁olin', 'morph_labels': 'n_V', 'probabilities': 8e-05}]),
Span(' ammu', [{'bert_tokens': '▁ammu', 'morph_labels': 'D', 'probabilities': 0.99989}, {'bert_tokens': '▁ammu', 'morph_labels': 'A', 'probabilities': 1e-05}, {'bert_tokens': '▁ammu', 'morph_labels': 'sg g_S', 'probabilities': 0.0}]),
Span(' endale', [{'bert_tokens': '▁endale', 'morph_labels': 'sg all_P', 'probabilities': 0.9998}, {'bert_tokens': '▁endale', 'morph_labels': 'pl all_P', 'probabilities': 2e-05}, {'bert_tokens': '▁endale', 'morph_labels': 'sg all_H', 'probabilities': 1e-05}]),
Span(' soovinud', [{'bert_tokens': '▁soovinud', 'morph_labels': 'nud_V', 'probabilities': 0.99973}, {'bert_tokens': '▁soovinud', 'morph_labels': 'pl n_S', 'probabilities': 2e-05}, {'bert_tokens': '▁soovinud', 'morph_labels': 'A', 'probabilities': 2e-05}]),
Span('),', [{'bert_tokens': '),', 'morph_labels': 'Z', 'probabilities': 0.99995}, {'bert_tokens': '),', 'morph_labels': 'J', 'probabilities': 0.0}, {'bert_tokens': '),', 'morph_labels': 'A', 'probabilities': 0.0}]),
Span(' tul', [{'bert_tokens': '▁tul', 'morph_labels': 'pl n_S', 'probabilities': 0.99949}, {'bert_tokens': '▁tul', 'morph_labels': 'pl n_A', 'probabilities': 0.00012}, {'bert_tokens': '▁tul', 'morph_labels': 'pl n_H', 'probabilities': 5e-05}]),
Span('bid', [{'bert_tokens': 'bid', 'morph_labels': 'pl n_S', 'probabilities': 0.99952}, {'bert_tokens': 'bid', 'morph_labels': 'pl n_A', 'probabilities': 0.00012}, {'bert_tokens': 'bid', 'morph_labels': 'pl n_H', 'probabilities': 4e-05}]),
Span(' ja', [{'bert_tokens': '▁ja', 'morph_labels': 'J', 'probabilities': 0.99991}, {'bert_tokens': '▁ja', 'morph_labels': 'o_V', 'probabilities': 0.0}, {'bert_tokens': '▁ja', 'morph_labels': 'D', 'probabilities': 0.0}]),
Span(' karp', [{'bert_tokens': '▁karp', 'morph_labels': 'sg n_S', 'probabilities': 0.99976}, {'bert_tokens': '▁karp', 'morph_labels': 'sg in_S', 'probabilities': 2e-05}, {'bert_tokens': '▁karp', 'morph_labels': 'pl g_S', 'probabilities': 2e-05}]),
Span(' Ra', [{'bert_tokens': '▁Ra', 'morph_labels': 'sg p_H', 'probabilities': 0.78436}, {'bert_tokens': '▁Ra', 'morph_labels': 'sg n_H', 'probabilities': 0.1822}, {'bert_tokens': '▁Ra', 'morph_labels': 'pl n_H', 'probabilities': 0.00609}]),
Span('fa', [{'bert_tokens': 'fa', 'morph_labels': 'sg p_H', 'probabilities': 0.88837}, {'bert_tokens': 'fa', 'morph_labels': 'sg n_H', 'probabilities': 0.08277}, {'bert_tokens': 'fa', 'morph_labels': 'pl n_H', 'probabilities': 0.00468}]),
Span('ell', [{'bert_tokens': 'ell', 'morph_labels': 'sg p_H', 'probabilities': 0.9153}, {'bert_tokens': 'ell', 'morph_labels': 'sg n_H', 'probabilities': 0.05623}, {'bert_tokens': 'ell', 'morph_labels': 'pl n_H', 'probabilities': 0.00461}]),
Span('ot', [{'bert_tokens': 'ot', 'morph_labels': 'sg p_H', 'probabilities': 0.91316}, {'bert_tokens': 'ot', 'morph_labels': 'sg n_H', 'probabilities': 0.05442}, {'bert_tokens': 'ot', 'morph_labels': 'pl n_H', 'probabilities': 0.00383}]),
Span('.', [{'bert_tokens': '.', 'morph_labels': 'Z', 'probabilities': 0.99996}, {'bert_tokens': '.', 'morph_labels': 'J', 'probabilities': 0.0}, {'bert_tokens': '.', 'morph_labels': 'sg n_H', 'probabilities': 0.0}])])

In [94]:
# Apply the tagger to the text object
morph_tagger.make_layer(text_obj)

Layer(name='bert_morph_tagging', attributes=('bert_tokens', 'morph_labels', 'probabilities'), spans=SL[EnvelopingSpan(['Ning'], [{'bert_tokens': ['▁Ning'], 'morph_labels': 'J', 'probabilities': 0.99991}]),
EnvelopingSpan(['laste'], [{'bert_tokens': ['▁laste'], 'morph_labels': 'pl g_S', 'probabilities': 0.9996}]),
EnvelopingSpan(['kingitus'], [{'bert_tokens': ['▁kingitus'], 'morph_labels': 'sg n_S', 'probabilities': 0.99978}]),
EnvelopingSpan([':'], [{'bert_tokens': [':'], 'morph_labels': 'Z', 'probabilities': 0.99992}]),
EnvelopingSpan(['puust'], [{'bert_tokens': ['▁puust'], 'morph_labels': 'sg el_S', 'probabilities': 0.99941}]),
EnvelopingSpan(['juuksehari'], [{'bert_tokens': ['▁juukse', 'hari'], 'morph_labels': 'sg n_S', 'probabilities': 0.99975}]),
EnvelopingSpan(['('], [{'bert_tokens': ['▁('], 'morph_labels': 'Z', 'probabilities': 0.99987}]),
EnvelopingSpan(['millist'], [{'bert_tokens': ['mil', 'list'], 'morph_labels': 'sg p_P', 'probabilities': 0.99783}]),
EnvelopingSpan(['ma'], [{'bert_tokens': ['▁ma'], 'morph_labels': 'sg n_P', 'probabilities': 0.99983}]),
EnvelopingSpan(['olin'], [{'bert_tokens': ['▁olin'], 'morph_labels': 'sin_V', 'probabilities': 0.99878}]),
EnvelopingSpan(['ammu'], [{'bert_tokens': ['▁ammu'], 'morph_labels': 'D', 'probabilities': 0.99989}]),
EnvelopingSpan(['endale'], [{'bert_tokens': ['▁endale'], 'morph_labels': 'sg all_P', 'probabilities': 0.9998}]),
EnvelopingSpan(['soovinud'], [{'bert_tokens': ['▁soovinud'], 'morph_labels': 'nud_V', 'probabilities': 0.99973}]),
EnvelopingSpan([')', ','], [{'bert_tokens': ['),'], 'morph_labels': 'Z', 'probabilities': 0.99995}]),
EnvelopingSpan(['tulbid'], [{'bert_tokens': ['▁tul', 'bid'], 'morph_labels': 'pl n_S', 'probabilities': 0.99949}]),
EnvelopingSpan(['ja'], [{'bert_tokens': ['▁ja'], 'morph_labels': 'J', 'probabilities': 0.99991}]),
EnvelopingSpan(['karp'], [{'bert_tokens': ['▁karp'], 'morph_labels': 'sg n_S', 'probabilities': 0.99976}]),
EnvelopingSpan(['Rafaellot'], [{'bert_tokens': ['▁Ra', 'fa', 'ell', 'ot'], 'morph_labels': 'sg p_H', 'probabilities': 0.78436}]),
EnvelopingSpan(['.'], [{'bert_tokens': ['.'], 'morph_labels': 'Z', 'probabilities': 0.99996}])])

### Testing _(will be removed afterwards)_

In [ ]:
test_text = estnltk.Text(
    "A. H. Tammsaare oli eesti kirjanik, esseist, kultuurifilosoof ja tõlkija. Üksnes autorihüvitis oli 12 431 krooni."
)
test_text.tag_layer("morph_analysis")
test_text.morph_analysis;

In [ ]:
sentences = [s.text for s in test_text.sentences]

In [ ]:
# Predict tags
predictions, raw_outputs = model.predict(sentences, split_on_space=False)

# Output of predictions
print(predictions)

INFO:ner_model.py:1884:  Converting to features started.
[[{'A. H. Tammsaare': 'sg n_H'}, {'oli': 's_V'}, {'eesti': 'G'}, {'kirjanik': 'sg n_S'}, {',': 'Z'}, {'esseist': 'sg n_S'}, {',': 'Z'}, {'kultuurifilosoof': 'sg n_S'}, {'ja': 'J'}, {'tõlkija': 'sg n_S'}, {'.': 'Z'}], [{'Üksnes': 'D'}, {'autorihüvitis': 'sg n_S'}, {'oli': 's_V'}, {'12 431': '?_N'}, {'krooni': 'sg p_S'}, {'.': 'Z'}]]

In [ ]:
display(test_text.morph_analysis)

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('A. H. Tammsaare', [{'normalized_text': 'A. H. Tammsaare', 'lemma': 'A. H. Tammsaare', 'root': 'A. _H. _Tamm_saare', 'root_tokens': ['A. ', 'H. ', 'Tamm', 'saare'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'H'}]),
Span('oli', [{'normalized_text': 'oli', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('eesti', [{'normalized_text': 'eesti', 'lemma': 'eesti', 'root': 'eesti', 'root_tokens': ['eesti'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'G'}]),
Span('kirjanik', [{'normalized_text': 'kirjanik', 'lemma': 'kirjanik', 'root': 'kirjanik', 'root_tokens': ['kirjanik'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span(',', [{'normalized_text': ',', 'lemma': ',', 'root': ',', 'root_tokens': [','], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('esseist', [{'normalized_text': 'esseist', 'lemma': 'essee', 'root': 'essee', 'root_tokens': ['essee'], 'ending': 'ist', 'clitic': '', 'form': 'pl el', 'partofspeech': 'S'}]),
Span(',', [{'normalized_text': ',', 'lemma': ',', 'root': ',', 'root_tokens': [','], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('kultuurifilosoof', [{'normalized_text': 'kultuurifilosoof', 'lemma': 'kultuurifilosoof', 'root': 'kultuuri_filosoof', 'root_tokens': ['kultuuri', 'filosoof'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('ja', [{'normalized_text': 'ja', 'lemma': 'ja', 'root': 'ja', 'root_tokens': ['ja'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'J'}]),
Span('tõlkija', [{'normalized_text': 'tõlkija', 'lemma': 'tõlkija', 'root': 'tõlkija', 'root_tokens': ['tõlkija'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('Üksnes', [{'normalized_text': 'Üksnes', 'lemma': 'üksnes', 'root': 'üksnes', 'root_tokens': ['üksnes'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('autorihüvitis', [{'normalized_text': 'autorihüvitis', 'lemma': 'autorihüvitis', 'root': 'autori_hüvitis', 'root_tokens': ['autori', 'hüvitis'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('oli', [{'normalized_text': 'oli', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('12 431', [{'normalized_text': '12431', 'lemma': '12431', 'root': '12431', 'root_tokens': ['12431'], 'ending': '0', 'clitic': '', 'form': '?', 'partofspeech': 'N'}]),
Span('krooni', [{'normalized_text': 'krooni', 'lemma': 'kroon', 'root': 'kroon', 'root_tokens': ['kroon'], 'ending': '0', 'clitic': '', 'form': 'sg p', 'partofspeech': 'S'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

In [ ]:
predictions, raw_outputs = model.predict(
    [
        "Uuringutulemuste interpretatsioon jätab mitmed küsimused vastuseta.",
        "Kas tuba on soe või külm?",
    ]
)

# Output of predictions
print(predictions)

INFO:ner_model.py:1884:  Converting to features started.
[[{'Uuringutulemuste': 'pl g_S'}, {'interpretatsioon': 'sg n_S'}, {'jätab': 'b_V'}, {'mitmed': 'pl n_P'}, {'küsimused': 'pl n_S'}, {'vastuseta.': 'sg ab_S'}], [{'Kas': 'D'}, {'tuba': 'sg n_S'}, {'on': 'b_V'}, {'soe': 'sg n_A'}, {'või': 'J'}, {'külm?': 'sg n_A'}]]

In [ ]:
test_data = comparison_data[
    (comparison_data["source"] == "nc_8303_518571.json")
    & (comparison_data["sentence_id"] == 797)
]

In [ ]:
text_list = test_data.words.tolist()

In [ ]:
test_data

,sentence_id,words,form,pos,type,source,labels
1467181,797,Tegevusalad,pl n,S,periodicals,nc_8303_518571.json,pl n_S
1467182,797,:,,Z,periodicals,nc_8303_518571.json,Z
1467183,797,puit-,sg n,S,periodicals,nc_8303_518571.json,sg n_S
1467184,797,",",,Z,periodicals,nc_8303_518571.json,Z
1467185,797,plast-,sg n,S,periodicals,nc_8303_518571.json,sg n_S
...,...,...,...,...,...,...,...
1467249,797,",",,Z,periodicals,nc_8303_518571.json,Z
1467250,797,paljundustööd,pl n,S,periodicals,nc_8303_518571.json,pl n_S
1467251,797,",",,Z,periodicals,nc_8303_518571.json,Z
1467252,797,infoteenused,pl n,S,periodicals,nc_8303_518571.json,pl n_S
1467253,797,.,,Z,periodicals,nc_8303_518571.json,Z

In [ ]:
inputs = model.tokenizer(" ".join(text_list), return_tensors="pt")

In [ ]:
len(inputs["input_ids"][0])

128

In [ ]:
for token_idx in range(len(inputs["input_ids"][0])):
    token = model.tokenizer.decode([inputs["input_ids"][0][token_idx]])
    print(f"Token: {token}")

Token: <s>
Token: Tegevus
Token: alad
Token: :
Token: puit
Token: -
Token: ,
Token: plast
Token: -
Token: ,
Token: klaas
Token: -
Token: ,
Token: kummi
Token: -
Token: ja
Token: metall
Token: it
Token: oodete
Token: tootmine
Token: ,
Token: toidu
Token: kaupade
Token: tootmine
Token: ,
Token: toidu
Token: kaupade
Token: jae
Token: -
Token: ja
Token: hul
Token: gika
Token: ub
Token: andus
Token: (
Token: v
Token: .
Token: a
Token: .
Token: litse
Token: ntse
Token: eri
Token: tavad
Token: kaubad
Token: )
Token: ,
Token: tööstus
Token: kaupade
Token: jae
Token: -
Token: ,
Token: hulgi
Token: -
Token: ja
Token: komisjon
Token: ika
Token: ub
Token: andus
Token: ,
Token: arvuti
Token: -
Token: ,
Token: video
Token: -
Token: ja
Token: hel
Token: isal
Token: vest
Token: iste
Token: palju
Token: ndamine
Token: ja
Token: laen
Token: utamine
Token: ,
Token: interj
Token: öör
Token: iku
Token: ju
Token: ndus
Token: ,
Token: kuju
Token: ndust
Token: ööd
Token: ,
Token: demonst
Token: ratsioonide
Token: ,
Token: näit
Token: uste
Token: ,
Token: nõupida
Token: miste
Token: ,
Token: konverents
Token: ide
Token: ja
Token: spordi
Token: võistluste
Token: organiseeri
Token: mine
Token: ,
Token: är
Token: ikon
Token: ta
Token: ktide
Token: vahenda
Token: mine
Token: ,
Token: transpordi
Token: teenused
Token: (
Token: Eesti
Token: Vabariigi
Token: piires
Token: )
Token: ,
Token: teenindus
Token: punktid
Token: ,
Token: palju
Token: ndust
Token: ööd
Token: ,
Token: info
Token: teenused
Token: .
Token: </s>

In [ ]:
text = estnltk.Text("  ".join(text_list))
text.tag_layer("clauses")
display(text)
clauses = [clause.text for clause in text.clauses]
for clause in clauses:
    print(len(clause))
print("Sum:", sum(len(clause) for clause in clauses))

Text(text='Tegevusalad  :  puit-  ,  plast-  ,  klaas-  ,  kummi-  ja  metallitoodete  tootmine  ,  toidukaupade  tootmine  ,  toidukaupade  jae-  ja  hulgikaubandus  (  v . a .  litsentseeritavad  kaubad  )  ,  tööstuskaupade  jae-  ,  hulgi-  ja  komisjonikaubandus  ,  arvuti-  ,  video-  ja  helisalvestiste  paljundamine  ja  laenutamine  ,  interjöörikujundus  ,  kujundustööd  ,  demonstratsioonide  ,  näituste  ,  nõupidamiste  ,  konverentside  ja  spordivõistluste  organiseerimine  ,  ärikontaktide  vahendamine  ,  transporditeenused  (  Eesti  Vabariigi  piires  )  ,  teeninduspunktid  ,  paljundustööd  ,  infoteenused  .')

2
61
5
5
Sum: 73

In [ ]:
for i in range(len(text_list)):
    print(text_list[i], text.words[i].text)

Tegevusalad Tegevusalad
: :
puit- puit-
, ,
plast- plast-
, ,
klaas- klaas-
, ,
kummi- kummi-
ja ja
metallitoodete metallitoodete
tootmine tootmine
, ,
toidukaupade toidukaupade
tootmine tootmine
, ,
toidukaupade toidukaupade
jae- jae-
ja ja
hulgikaubandus hulgikaubandus
( (
v . a . v . a .
litsentseeritavad litsentseeritavad
kaubad kaubad
) )
, ,
tööstuskaupade tööstuskaupade
jae- jae-
, ,
hulgi- hulgi-
ja ja
komisjonikaubandus komisjonikaubandus
, ,
arvuti- arvuti-
, ,
video- video-
ja ja
helisalvestiste helisalvestiste
paljundamine paljundamine
ja ja
laenutamine laenutamine
, ,
interjöörikujundus interjöörikujundus
, ,
kujundustööd kujundustööd
, ,
demonstratsioonide demonstratsioonide
, ,
näituste näituste
, ,
nõupidamiste nõupidamiste
, ,
konverentside konverentside
ja ja
spordivõistluste spordivõistluste
organiseerimine organiseerimine
, ,
ärikontaktide ärikontaktide
vahendamine vahendamine
, ,
transporditeenused transporditeenused
( (
Eesti Eesti
Vabariigi Vabariigi
piires piires
) )
, ,
teeninduspunktid teeninduspunktid
, ,
paljundustööd paljundustööd
, ,
infoteenused infoteenused
. .

In [ ]:
predictions, raw_outputs = model.predict(clauses, split_on_space=False)
ner_labels_parts = list()
for prediction_part in predictions:
    ner_labels_part = [list(p.values())[0] for p in prediction_part]
    print(len(ner_labels_part), ner_labels_part)
    ner_labels_parts.append(ner_labels_part)

ner_labels = list(itertools.chain.from_iterable(ner_labels_parts))

2 ['pl n_S', 'Z']
61 ['sg n_S', 'Z', 'sg n_S', 'Z', 'sg n_S', 'Z', 'sg g_S', 'J', 'pl g_S', 'sg n_S', 'Z', 'pl g_S', 'sg n_S', 'Z', 'pl g_S', 'sg g_S', 'J', 'sg n_S', 'Z', 'pl g_S', 'sg g_S', 'Z', 'sg n_S', 'J', 'sg n_S', 'Z', 'sg g_S', 'Z', 'sg g_S', 'J', 'pl g_S', 'sg n_S', 'J', 'sg n_S', 'Z', 'sg n_S', 'Z', 'sg n_S', 'Z', 'pl g_S', 'Z', 'pl g_S', 'Z', 'pl g_S', 'Z', 'pl g_S', 'J', 'pl g_S', 'sg n_S', 'Z', 'pl g_S', 'sg n_S', 'Z', 'pl n_S', 'Z', 'pl n_S', 'Z', 'sg p_S', 'Z', 'pl n_S', 'Z']
5 ['Z', '?_Y', 'pl n_A', 'pl n_S', 'Z']
5 ['Z', 'sg g_H', 'sg g_S', 'K', 'Z']

In [ ]:
predictions, raw_outputs = model.predict([text.words.text], split_on_space=False)

# ner_words = [list(p.keys())[0] for p in predictions[0]]
ner_labels = [list(p.values())[0] for p in predictions[0]]

In [ ]:
len(ner_labels)

72

In [ ]:
predictions

[[{'Sisaldab': 'b_V'}, {':': 'Z'}],
 [{'dementsus': 'sg n_S'}, {':': 'Z'}],
 [{'-': 'Z'},
  {'CO-mürgistusest': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'tserebraalsest': 'sg el_A'},
  {'lipidoosist': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'epilepsiast': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'hepatolentikulaarsest': 'sg el_A'},
  {'degeneratsioonist': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'hüperkaltseemiast': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'kilpnäärmehaigustest': 'pl el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'intoksikatsioonidest': 'pl el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'sclerosis': 'sg n_S'},
  {"multiplex ' ist": 'sg n_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'neurosüüfilisest': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'niatsiinivaegusest': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'polyarteritis': 'sg in_S'},
  {"nodosa ' st": 'sg n_S'},
  {'-': 'Z'},
  {'süsteemsest': 'sg el_A'},
  {'lupus': 'sg n_S'},
  {'erythematosus': 'sg n_S'},
  {"'": 'Z'},
  {'est': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'trüpanosomiaasist': 'sg el_S'},
  {';': 'Z'},
  {'-': 'Z'},
  {'vitamiin': 'sg n_S'},
  {'B12': '?_Y'},
  {'vaegusest': 'sg el_S'},
  {'.': 'Z'}],
 [{'(': 'Z'}, {'T58': '?_Y'}, {')': 'Z'}],
 [{'(': 'Z'}, {'E75': '?_Y'}, {'.': 'Z'}, {'-': 'Z'}, {')': 'Z'}],
 [{'(': 'Z'}, {'G40': '?_Y'}, {'.': 'Z'}, {'-': 'Z'}, {')': 'Z'}],
 [{'(': 'Z'}, {'Wilsoni': 'sg g_H'}, {'tõbi': 'sg n_S'}, {')': 'Z'}],
 [{'(': 'Z'}, {'E83': '?_Y'}, {'.': 'Z'}, {'0': '?_N'}, {')': 'Z'}],
 [{'(': 'Z'}, {'E83': '?_Y'}, {'.': 'Z'}, {'5': '?_N'}, {')': 'Z'}],
 [{'(': 'Z'},
  {'E00': '?_Y'},
  {'.': 'Z'},
  {'-': 'Z'},
  {',': 'Z'},
  {'E02': '?_Y'},
  {')': 'Z'}],
 [{'(': 'Z'}, {'T36-T65': '?_Y'}, {')': 'Z'}],
 [{'(': 'Z'}, {'G35': '?_Y'}, {')': 'Z'}],
 [{'(': 'Z'}, {'A52': '?_Y'}, {'.': 'Z'}, {'1': '?_N'}, {')': 'Z'}],
 [{'(': 'Z'}, {'pellagra': 'sg n_S'}, {')': 'Z'}],
 [{'(': 'Z'}, {'E52': '?_Y'}, {')': 'Z'}],
 [{'(': 'Z'}, {'M30': '?_Y'}, {'.': 'Z'}, {'0': '?_N'}, {')': 'Z'}],
 [{'(': 'Z'}, {'M32': '?_Y'}, {'.': 'Z'}, {'-': 'Z'}, {')': 'Z'}],
 [{'(': 'Z'},
  {'Aafrika': 'sg n_H'},
  {'B56': '?_Y'},
  {'.': 'Z'},
  {'-': 'Z'},
  {',': 'Z'},
  {'Ameerika': 'sg n_H'},
  {'B57': '?_Y'},
  {'.': 'Z'},
  {'-': 'Z'},
  {')': 'Z'}],
 [{'(': 'Z'}, {'E53': '?_Y'}, {'.': 'Z'}, {'8': '?_N'}, {')': 'Z'}]]

In [ ]:
len(ner_labels)

132

In [ ]:
text = estnltk.Text(
    'Paki tagaküljele - " Suitsetamine lühendab eluiga , " " Suitsetamine ummistab veresooni ning põhjustab südameinfarkte ja rabandusi , " " Suitsetamine tekitab surmavat kopsuvähki , " " Raseduse ajal suitsetamine kahjustab sinu last , " " Kaitse lapsi : ära sunni neid hingama tubakasuitsu , " " Arstilt või apteekrilt saad abi suitsetamisest loobumiseks , " " Suitsetamine tekitab kergesti sõltuvust , ära alusta , " " Suitsetamisest loobumine vähendab ohtu haigestuda surmavatesse südame- ja kopsuhaigustesse , " " Otsi abi suitsetamisest loobumiseks : küsi nõu oma perearstilt või lähimast apteegist . "'
)
# text = estnltk.Text("Mul on taskus kolm asja: telefon, rahakott ja võtmed.")
# text = estnltk.Text("Ta ei söö herneid, sest need ei maitse talle.")
text.tag_layer("clauses")
clauses = [clause.text for clause in text.clauses]

In [ ]:
text.clauses

Layer(name='clauses', attributes=('clause_type',), spans=SL[EnvelopingSpan(['231', 'Kirikuseadus', 'jaguneb', 'kahekümne', 'kaheksaks', 'peatükiks', ':'], [{'clause_type': 'regular'}]),
EnvelopingSpan(['1', ')', 'Õigest', 'kristlikust', 'õpetusest', ',', '2', ')', 'Jutlustest', 'ja', 'korrakohasest', 'jumalateenistusest', ',', '3', ')', 'Ristimisest', ',', '4', ')', 'Hädaristimisest', ',', '5', ')', 'Lapsevoodi-naiste', 'kirikuskäimisest', ',', '232', '6', ')', 'Pihtimisest', 'ja', 'pattude', 'andeksandmisest', ',', '7', ')', 'Salajasest', 'pihtimisest', ',', '8', ')', 'Üldisest', 'pihtimisest', ',', '9', ')', 'Avalikust', 'pihtimisest', 'ja', 'kiriklikust', 'patukahetsusest', ',', '10', ')', 'Kirikuvandest', ',', '11', ')', 'Armulauast', ',', '12', ')', 'Üldisest', 'palvest', 'ja', 'litaaniast', ',', '13', ')', 'Kirikulauludest', ',', '14', ')', 'Tähtsatest', 'pühadest', ',', '15', ')', 'Kihlusest', 'ja', 'abielust', ',', '16', ')', 'Kihluse', 'ja', 'abielu', 'lahutamisest', ',', '17', ')', 'Haigete', 'ja', 'vangide', 'külastamisest', ',', '18', ')', 'Kristlikust', 'matusest', ',', '19', ')', 'Pastoriametist', ',', '20', ')', 'Piiskoppide', 'valimisest', ',', '21', ')', 'Kuidas', 'valitud', 'piiskoppi', 'ordineerida', ',', '22', ')', 'Kuidas', 'pastorit', 'ordineerida', ',', '23', ')', 'Kuidas', 'korrakohaselt', 'ametissekutsutud', 'pastorit', 'koguduses', 'ametisse', 'panna', ',', '24', ')', 'Piiskoppidest', ',', 'superintendentidest', ',', 'praostidest', ',', 'pastoritest', ',', 'kaplanitest', 'ja', 'teistest', 'kirikuteenijatest', ',', '25', ')', 'Sinoditest', 'ehk', 'pastorite', 'kokkutulekutest', ',', '26', ')', 'Kirikutest', ',', 'nende', 'sisseseadest', 'ja', 'omandist', ',', '27', ')', 'Kuidas', 'peab', 'algama', 'ja', 'toimuma', 'jumalateenistus', 'vastvalminud', 'kirikus', ',', '28', ')', 'Hospidalidest', '.'], [{'clause_type': 'regular'}]),
EnvelopingSpan(['(', 'Kuuenädalaste', ')'], [{'clause_type': 'embedded'}])])

In [ ]:
clauses_text = [" ".join(clause) for clause in clauses]
full_text = " ".join(clauses_text)
diff_text = estnltk.Text(full_text)
diff_text.tag_layer("clauses")
diff_clauses = [clause.text for clause in diff_text.clauses]

NameError: name 'clauses' is not defined

In [ ]:
diff_text.clauses

Layer(name='clauses', attributes=('clause_type',), spans=SL[EnvelopingSpan(['Paki', 'tagaküljele', '-', '"', 'Suitsetamine', 'lühendab', 'eluiga', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Suitsetamine', 'ummistab', 'veresooni', 'ning'], [{'clause_type': 'regular'}]),
EnvelopingSpan(['põhjustab', 'südameinfarkte', 'ja', 'rabandusi', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Suitsetamine', 'tekitab', 'surmavat', 'kopsuvähki', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Raseduse', 'ajal', 'suitsetamine', 'kahjustab', 'sinu', 'last', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Kaitse', 'lapsi', ':'], [{'clause_type': 'regular'}]),
EnvelopingSpan(['ära', 'sunni', 'neid', 'hingama', 'tubakasuitsu', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Arstilt', 'või', 'apteekrilt', 'saad', 'abi', 'suitsetamisest', 'loobumiseks', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Suitsetamine', 'tekitab', 'kergesti', 'sõltuvust', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['ära', 'alusta', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Suitsetamisest', 'loobumine', 'vähendab', 'ohtu', 'haigestuda', 'surmavatesse', 'südame-', 'ja', 'kopsuhaigustesse', ','], [{'clause_type': 'regular'}]),
EnvelopingSpan(['"', '"', 'Otsi', 'abi', 'suitsetamisest', 'loobumiseks', ':'], [{'clause_type': 'regular'}]),
EnvelopingSpan(['küsi', 'nõu', 'oma', 'perearstilt', 'või', 'lähimast', 'apteegist', '.', '"'], [{'clause_type': 'regular'}])])

In [ ]:
for clause in text.clauses:
    display(clause.morph_analysis)

In [ ]:
with open(
    file="./differences/_nc_255_27987.json__ann_diffs.txt", mode="r", encoding="UTF-8"
) as in_f:
    for i, line in enumerate(in_f):
        if i > 20:
            break
        line = line.strip()
        print(line)

=====================================================================================

::nc_255_27987.json::202969

... {Kahtlused}  Ühendriikide majanduse kiire kasvutempo jätkumise suhtes ho...
--- MODIFIED --------------------------------------------------
morph_analysis_flat        ['H', 'pl n']
bert_vabamorf_tags_flat    ['S', 'pl n']

=====================================================================================

::nc_255_27987.json::202970

...ad dollarit surve all , Euroopa ühisraha murdis esmaspäeval  {läbi}  0,900 dollari piiri viimase nelja kuu kõrgeima tasemeni , v...
--- MODIFIED --------------------------------------------------
morph_analysis_flat        ['K', '']
bert_vabamorf_tags_flat    ['D', '']

=====================================================================================

::nc_255_27987.json::202971

In [ ]:
!python pick_randomly_from_diffs.py differences__ann_diffs_.txt 100 -e

INFO:pick_randomly_from_diffs.py:66: Collecting difference indexes ...
ERROR:pick_randomly_from_diffs.py:77: (!) No differences found from the given ann_diffs_file. Invalid file, perhaps?

### Testing v2

In [ ]:
in_dir = "_plain_texts_json"
jsons = os.listdir(in_dir)
train_data = pd.read_csv("./model_data.csv", keep_default_na=False)
morph_tagger_v2 = BertMorphTagger("./NER_mudel_v2/")
warnings.filterwarnings("ignore", module="bert_tokens_to_words_rewriter")

In [ ]:
used_sources = set(train_data["source"].unique())
unused_jsons = [json_file for json_file in jsons if json_file not in used_sources]

In [ ]:
print(len(jsons))
print(len(used_sources))
print(
    f"{len(jsons)} - {len(used_sources)} = {len(jsons) - len(used_sources)}, actual: {len(unused_jsons)}"
)

18486
1116
18486 - 1116 = 17370, actual: 17370

In [ ]:
# TODO: lahendada Vabamorfi ja BERT taggeri span'ide erinevused
# ['nc_17153_741265.json', 'nc_17164_741348.json']

In [ ]:
unused_jsons.remove("nc_17153_741265.json")
unused_jsons.remove("nc_17164_741348.json")

In [ ]:
counter = 0
failed_jsons = ["nc_17153_741265.json", "nc_17164_741348.json"]
for j in tqdm(unused_jsons):
    with open(os.path.join("_diff_morph_texts_json_v2_complete", j), "r") as f:
        t = json.load(f)
        if t["layers"][1]["name"] != "bert_morph_tagging":
            counter += 1
            failed_jsons.append(j)

print(counter)
print(failed_jsons)

  0%|          | 0/17368 [00:00<?, ?it/s]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5181: character maps to <undefined>

In [ ]:
NotebookFunctions.create_json_file_by_file_enc2017(
    unused_jsons,
    in_dir,
    "_diff_morph_texts_json_v2_complete",
    "enc2017",
    True,
    bert_morph_tagger=morph_tagger_v2,
    ignore_errors=False,
    replace_files=False,
)

Beginning to morphologically tag file by file

100%|██████████| 17368/17368 [00:03<00:00, 4919.72it/s]

Morphological tagging completed successfully

##### Splitting data to sets<!-- #### Andmete jagamine hulkadesse -->

In [ ]:
# Reading CSV file
data = pd.read_csv("model_data.csv", keep_default_na=False)

Grouping data by filename to preserve the integrity of texts<!-- Andmete grupeerimine failinimede kaupa, et säilitada tekstide terviklikkus -->

In [ ]:
grouped = data.groupby("source")

groups = list(grouped.groups.keys())
train_groups, test_groups = sk.model_selection.train_test_split(
    groups, test_size=0.2, random_state=42
)


def filter_by_group(df, groups):
    return df[df["source"].isin(groups)]


# Splitting dataframe
train_df = filter_by_group(data, train_groups)
test_df = filter_by_group(data, test_groups)

Removing unnecessary columns for the model<!-- Mudelile ebavajalike veergude eemaldamine -->

In [ ]:
train_df = train_df.drop(labels=["type", "source"], axis=1)
test_df = test_df.drop(labels=["type", "source"], axis=1)
# display(train_df)
# display(test_df)

In [ ]:
with open("unique_labels.json", "r") as f:
    unique_labels = json.load(f)

In [ ]:
from bert_morph_tagger_notebook_functions import NotebookFunctions

with open("unique_labels.json", "r") as f:
    unique_labels = json.load(f)

model = NotebookFunctions.initialize_model("NER_mudel_v2", unique_labels, False)
result, model_outputs, preds_list = model.eval_model(test_df)
print(f"Evaluation Loss:{result['eval_loss']:.4f}")
print(f"Precision: \t{result['precision']:.4f}")
print(f"Recall: \t{result['recall']:.4f}")
print(f"F1 Score: \t{result['f1_score']:.4f}")

100%|██████████| 1/1 [00:09<00:00,  9.44s/it]
Running Evaluation:   0%|          | 0/4 [00:00<?, ?it/s]e:\Anaconda3\envs\gpulocal\Lib\site-packages\simpletransformers\ner\ner_model.py:1303: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast():
Running Evaluation: 100%|██████████| 4/4 [00:03<00:00,  1.30it/s]

Evaluation Loss:1.1393
Precision: 	0.8878
Recall: 	0.8134
F1 Score: 	0.8489

| Metric          | Bert_morph_v2 | Bert_morph_v1 |
| --------------- | ------------- | ------------- |
| Evaluation Loss | 1.1393        | 0.2393        |
| Precision       | 0.8878        | 0.9545        |
| Recall          | 0.8134        | 0.9534        |
| F1 Score        | 0.8489        | 0.9540        |